CHATS_SIT/force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>County_Lookup__c</fullName>
        <label>County Lookup</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adams</fullName>
                </value>
                <value>
                    <fullName>Alamosa</fullName>
                </value>
                <value>
                    <fullName>Arapahoe</fullName>
                </value>
                <value>
                    <fullName>Archuleta</fullName>
                </value>
                <value>
                    <fullName>Baca</fullName>
                </value>
                <value>
                    <fullName>Bent</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Broomfield</fullName>
                </value>
                <value>
                    <fullName>Chaffee</fullName>
                </value>
                <value>
                    <fullName>Cheyenne</fullName>
                </value>
                <value>
                    <fullName>Clear Creek</fullName>
                </value>
                <value>
                    <fullName>Conejos</fullName>
                </value>
                <value>
                    <fullName>Costilla</fullName>
                </value>
                <value>
                    <fullName>Crowley</fullName>
                </value>
                <value>
                    <fullName>Custer</fullName>
                </value>
                <value>
                    <fullName>Delta</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Dolores</fullName>
                </value>
                <value>
                    <fullName>Douglas</fullName>
                </value>
                <value>
                    <fullName>Eagle</fullName>
                </value>
                <value>
                    <fullName>Elbert</fullName>
                </value>
                <value>
                    <fullName>El Paso</fullName>
                </value>
                <value>
                    <fullName>Fremont</fullName>
                </value>
                <value>
                    <fullName>Garfield</fullName>
                </value>
                <value>
                    <fullName>Gilpin</fullName>
                </value>
                <value>
                    <fullName>Grand</fullName>
                </value>
                <value>
                    <fullName>Gunnison</fullName>
                </value>
                <value>
                    <fullName>Hinsdale</fullName>
                </value>
                <value>
                    <fullName>Huerfano</fullName>
                </value>
                <value>
                    <fullName>Jackson</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Certification_Date__c</fullName>
        <label>License Certification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Expiration_Date__c</fullName>
        <label>License Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <label>License Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licensing_Status__c</fullName>
        <label>Licensing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone_Program_Site_Phone__c</fullName>
        <label>Phone (Program Site Phone)`</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Email__c</fullName>
        <description>Primary Email - Data transferred from OEC Org ( Provider)</description>
        <label>Primary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>QRIS_Rating__c</fullName>
        <label>QRIS Rating</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Level 1</fullName>
                </value>
                <value>
                    <fullName>Level 2</fullName>
                </value>
                <value>
                    <fullName>Level 3</fullName>
                </value>
                <value>
                    <fullName>Level 4</fullName>
                </value>
                <value>
                    <fullName>Level 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CNTY_DEPT_NAME__c</fullName>
        <description>County Department Name</description>
        <label>County Department Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/AccountServicesTest.cls
@isTest
public class AccountServicesTest {
    
static testmethod void testAccount(){
        
        T_COUNTY__c cnty = new T_COUNTY__c (    CDE_COUNTY__c = 03, CNTY_DEPT_NAME__c = 'Arapahoe County');
        
        Account acc = new Account(  Name = 'Acc', License_Number__c = '12345', License_Expiration_Date__c = date.today() + 1,
                                    License_Certification_Date__c = date.today(), Licensing_Status__c = 'Closed',
                                    Phone_Program_Site_Phone__c = '1234567891', QRIS_Rating__c = 'Level 3',
                                    Primary_Email__c = 'testacc@acc.com', County_Lookup__c = 'Arapahoe' ); 
        
        Account acc1 = new Account(  Name = 'Act', License_Number__c = '123456', License_Expiration_Date__c = date.today() + 2,
                                    License_Certification_Date__c = date.today(), Licensing_Status__c = 'Closed',
                                    Phone_Program_Site_Phone__c = '9988998899', QRIS_Rating__c = 'Level 2',
                                    Primary_Email__c = 'testacc@acc.com', County_Lookup__c = 'Arapahoe' ); 
        
        T_CHATS_PROVR_STATUS__c provr = new T_CHATS_PROVR_STATUS__c (Name = '12345');
        
        test.startTest();
        insert cnty;
        insert provr;
        insert acc;
        
        system.assertEquals('Acc', acc.Name,'Account Name Mismatch');
        system.assertEquals('12345', acc.License_Number__c,'License Numer Mismatch');
        system.assertEquals('Closed', acc.Licensing_Status__c,'License Status Mismatch');
        system.assertEquals('1234567891', acc.Phone_Program_Site_Phone__c,'Phone program Site Phone Mismatch');
        system.assertEquals('Level 3', acc.QRIS_Rating__c,'QRIS Rating Mismatch');
        system.assertEquals('testacc@acc.com', acc.Primary_Email__c,'Primary Email Mismatch');
        
        insert acc1;

        test.stopTest();
    }
}