CHATS_SIT/force-app/main/default/objects/batchsit_t_sbsd_indiv_care_level__x.object
<CustomObject>
    <description>batchsit$t_sbsd_indiv_care_level</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_sbsd_indiv_care_level</externalName>
    <fields>
        <fullName>idn_client__c</fullName>
        <description>idn_client</description>
        <externalDeveloperName>idn_client</externalDeveloperName>
        <label>Client ID</label>
        <length>50</length>
        <referenceTargetField>T_SBSD_INDIV__c.IDN_EXTNL__c</referenceTargetField>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Care Level</relationshipLabel>
        <relationshipName>batchsit_t_sbsd_indiv_care_level</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <label>Care Level</label>
    <pluralLabel>Care Level</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_INDIV_CAT_RQ__c.object
<CustomObject>
    <description>Individual is requesting care indicators.</description>
    <fields>
        <fullName>IDN_CASE_INDIV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Individual ID</label>
        <referenceTo>T_SBSD_CASE_INDIV__c</referenceTo>
        <relationshipLabel>Child Care Requests</relationshipLabel>
        <relationshipName>Child_Care_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case Individual External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Child Care Request</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Child Care Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Child Care Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>CDE_ATTENDING_SCHOOL1__c</fullName>
        <label>Child attending kindergarten or above?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_ATTENDING_SCHOOL_BEGINDATE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Child Kindergarten Begin/Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_DOB__c</fullName>
        <description>DOB</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/classes/IndividulCareLevelServices.cls
public with sharing class IndividulCareLevelServices {
    
    public static void doMethod(List<T_INDIV_CAT_RQ__c> childCareRequest){
        Map<ID,T_INDIV_CAT_RQ__c> mapInvIdChildCare = new Map<ID,T_INDIV_CAT_RQ__c>();
        Map<ID,integer> mapInvIdCareLevelLength = new Map<ID,integer>();
        Map<ID,ID> mapCaseInvIdIndvId = new Map<ID,ID>();
        Map<ID,ID> mapInvIdCaseIndvId = new Map<ID,ID>();
        Id loggedUserId = UserInfo.getUserId();
        DateTime nowDate = System.now();
        // iterate over this list and collect Individual Id
        try{
            for(T_INDIV_CAT_RQ__c objChildCare:childCareRequest){
                mapInvIdChildCare.put(objChildCare.IDN_CASE_INDIV__c, objChildCare);
            }
            List<T_SBSD_CASE_INDIV__c> listCaseIndv =[select id,IDN_CLIENT__c from T_SBSD_CASE_INDIV__c where id in: mapInvIdChildCare.keySet()];
            for (T_SBSD_CASE_INDIV__c objCaseIndiv:listCaseIndv){
                mapCaseInvIdIndvId.put(objCaseIndiv.Id, objCaseIndiv.IDN_CLIENT__c);
                mapInvIdCaseIndvId.put(objCaseIndiv.IDN_CLIENT__c, objCaseIndiv.Id);
            }
            
            List<T_SBSD_INDIV__c> lstIndv = [select id,DTE_DOB__c,CDE_ATTENDING_SCHOOL1__c,CDE_ATTENDING_SCHOOL_BEGINDATE__c,IDN_EXTNL__c,(select id from batchsit_t_sbsd_indiv_care_level__r) from T_SBSD_INDIV__c where id in: mapInvIdCaseIndvId.keySet()];
            map<id,T_SBSD_INDIV__c>  mapIdIndv= new map<id,T_SBSD_INDIV__c>();
            for(T_SBSD_INDIV__c objIndv:lstIndv){
                mapIdIndv.put(objIndv.id, objIndv);
                if(objIndv.batchsit_t_sbsd_indiv_care_level__r != null){
                    mapInvIdCareLevelLength.put(objIndv.id, objIndv.batchsit_t_sbsd_indiv_care_level__r.size());
                    
                }
                else{
                    mapInvIdCareLevelLength.put(objIndv.id, 0);
                }
                
            }
            list<SObject> listCareLevel = new List<SObject>();
            String bodyText = '[';
            String body='';
            for(T_INDIV_CAT_RQ__c objChildCare:childCareRequest){
                system.debug('mapCaseInvIdIndvId.get(objChildCare.IDN_CASE_INDIV__c)--'+mapCaseInvIdIndvId.get(objChildCare.IDN_CASE_INDIV__c));
                if(mapInvIdCareLevelLength.get(mapCaseInvIdIndvId.get(objChildCare.IDN_CASE_INDIV__c)) ==0){
                    body +=  getBodyForCreateCareLevelWS(objChildCare,mapCaseInvIdIndvId,mapIdIndv);
                }
            }
            if(String.isNotBlank(body) && body.length() >1){
                body = body.substring(0, body.length()-1);
                bodyText ='[' + body +']';
                if(!Test.isRunningTest()) {
                    HerokuService.createCareLevelRecords(bodyText);
                }
            }
        } catch (Exception ex) {
            ExceptionLoggingServices.captureExceptionLog(ex, new Map<String,Object>{'Class__c'=>'IndividulCareLevelServices','Method__c'=>'doMethod'}); 
        }      
    }
    
    public static String getBodyForCreateCareLevelWS(T_INDIV_CAT_RQ__c objChildCare, Map<ID,ID> mapCaseInvIdIndvId,map<id,T_SBSD_INDIV__c>  mapIdIndv  ){
        Id loggedUserId = UserInfo.getUserId();
        DateTime nowDate = System.now();
        Integer beginDateInt =0;
        Integer endDateInt =6;
        String bodyText='';
        Id individualId = mapCaseInvIdIndvId.get(objChildCare.IDN_CASE_INDIV__c);
        T_SBSD_INDIV__c individualRecord = mapIdIndv.get(individualId);
        Integer Age = Date.Today().year() - individualRecord.DTE_DOB__c.year();
        Integer months = Date.Today().Month() - individualRecord.DTE_DOB__c.Month();
        if (months < 0 || (months == 0 && Date.Today().Day() < individualRecord.DTE_DOB__c.Day())) {
            Age--;
        }
        Date SABeginDate = getSABeginDate(individualRecord,Age);
        for(Integer i=1;i<=8;i++){
            bodyText+='{';
            bodyText+='"cde_level_care":"'+i+'",';
            bodyText+='"createdbyid":"'+UserInfo.getUserId()+'",';
            bodyText+='"nbr_seq_hist":"1",';
            bodyText+='"lastmodifiedbyid":"'+UserInfo.getUserId()+'",';
            bodyText+='"idn_client":"'+individualRecord.IDN_EXTNL__c+'",';
            if(i == 1){
                bodyText+='"dte_begin_effv":"'+individualRecord.DTE_DOB__c+'",';
                bodyText+='"dte_end_effv":"'+(individualRecord.DTE_DOB__c.addmonths(6)).adddays(-1)+'"';
            }
            else if(i==7){
                bodyText+='"dte_begin_effv":"'+individualRecord.DTE_DOB__c.addmonths(36)+'",';
                bodyText+='"dte_end_effv":"'+SABeginDate.adddays(-1)+'"';
            }else if(i==8){
                bodyText+='"dte_begin_effv":"'+SABeginDate+'"';
            }
            else{
                bodyText+='"dte_begin_effv":"'+individualRecord.DTE_DOB__c.addmonths(beginDateInt)+'",';
                bodyText+='"dte_end_effv":"'+(individualRecord.DTE_DOB__c.addmonths(endDateInt)).adddays(-1)+'"';
            }
            bodyText+='},';
            beginDateInt = beginDateInt+6;
            endDateInt = endDateInt+6;
        }
        return bodyText;
    }
    public static date getSABeginDate(T_SBSD_INDIV__c individualRecord,Integer Age){
        Date SABeginDate = individualRecord.DTE_DOB__c.addmonths(60);
        if(Age<18 && Age >=5){
            if((individualRecord.CDE_ATTENDING_SCHOOL1__c == 'N'|| individualRecord.CDE_ATTENDING_SCHOOL1__c == 'Unknown')
               && individualRecord.CDE_ATTENDING_SCHOOL_BEGINDATE__c!=null){
                   SABeginDate = individualRecord.CDE_ATTENDING_SCHOOL_BEGINDATE__c;
               }
        }else if(Age<5){
            if((individualRecord.CDE_ATTENDING_SCHOOL1__c == 'N' ||  individualRecord.CDE_ATTENDING_SCHOOL1__c == 'Y')
               &&  individualRecord.CDE_ATTENDING_SCHOOL_BEGINDATE__c!=null){
                   SABeginDate = individualRecord.CDE_ATTENDING_SCHOOL_BEGINDATE__c;
               }
        }
        return SABeginDate;
    }
}