CHATS_SIT/force-app/main/default/objects/batchsit_t_sbsd_indiv_care_level__x.object
<CustomObject>
    <description>batchsit$t_sbsd_indiv_care_level</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_sbsd_indiv_care_level</externalName>
    <fields>
        <fullName>cde_level_care__c</fullName>
        <description>cde_level_care</description>
        <externalDeveloperName>cde_level_care</externalDeveloperName>
        <label>Care Level</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>createdbyid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>createdbyid</description>
        <externalDeveloperName>createdbyid</externalDeveloperName>
        <label>Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>batchsit_t_sbsd_indiv_care_level</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dte_begin_effv__c</fullName>
        <description>dte_begin_effv</description>
        <externalDeveloperName>dte_begin_effv</externalDeveloperName>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>idn_client__c</fullName>
        <description>idn_client</description>
        <externalDeveloperName>idn_client</externalDeveloperName>
        <label>Client ID</label>
        <length>50</length>
        <referenceTargetField>T_SBSD_INDIV__c.IDN_EXTNL__c</referenceTargetField>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Care Level</relationshipLabel>
        <relationshipName>batchsit_t_sbsd_indiv_care_level</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <fields>
        <fullName>idn_sbsd_indiv_care_level__c</fullName>
        <description>idn_sbsd_indiv_care_level</description>
        <externalDeveloperName>idn_sbsd_indiv_care_level</externalDeveloperName>
        <label>Care Level ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lastmodifiedbyid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lastmodifiedbyid</description>
        <externalDeveloperName>lastmodifiedbyid</externalDeveloperName>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>batchsit_t_sbsd_indiv_care_level1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care Level</label>
    <pluralLabel>Care Level</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_IMM__c</fullName>
        <label>Immunized</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00389</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_SOURCE_VRFYD_IMMU__c</fullName>
        <description>Immunization How Verified</description>
        <label>Immunization How Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00709</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Immunization Verified</description>
        <label>Immunization Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <label>License Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00367.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Available</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <label>Verbal Verification</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Written Verification</label>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
        <isActive>false</isActive>
        <label>CV</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
        <isActive>false</isActive>
        <label>N/A-adult caretaker</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <isActive>false</isActive>
        <label>SV</label>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
        <isActive>false</isActive>
        <label>N/A-not requesting child</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>R00367</description>
    <masterLabel>R00367</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00389.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NMD</fullName>
        <label>No. Medical reason</label>
    </customValue>
    <customValue>
        <fullName>NNW</fullName>
        <label>No. Not immunized</label>
    </customValue>
    <customValue>
        <fullName>NRL</fullName>
        <label>No. Religious Reasons</label>
    </customValue>
    <customValue>
        <fullName>NW</fullName>
        <label>No. In Process</label>
    </customValue>
    <customValue>
        <fullName>YES</fullName>
        <label>Yes. Immunized</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <description>R00389</description>
    <masterLabel>R00389</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00709.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NUR</fullName>
        <label>Dr/Nurse Statement</label>
    </customValue>
    <customValue>
        <fullName>PRO</fullName>
        <label>Provider</label>
    </customValue>
    <customValue>
        <fullName>SAG</fullName>
        <label>School Age</label>
    </customValue>
    <customValue>
        <fullName>SRD</fullName>
        <label>Shot Record</label>
    </customValue>
    <description>R00709</description>
    <masterLabel>R00709</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/IndividualCareLvlApexCtrl_Test.cls
@isTest(seeAllData=false)
public class IndividualCareLvlApexCtrl_Test {
    static T_SBSD_INDIV__c obj = new T_SBSD_INDIV__c();
    static T_AUTH__c authObj = new T_AUTH__c();
    public static T_SBSD_INDIV__c sbsdIndiv = new T_SBSD_INDIV__c();
    public static void testDataSetup(){
        List<SObject> sobjects = new List<SObject> ();
        List<batchsit_t_sbsd_indiv_care_level__x> indivList = new  List<batchsit_t_sbsd_indiv_care_level__x>();
        batchsit_t_sbsd_indiv_care_level__x x = new batchsit_t_sbsd_indiv_care_level__x();
         batchsit_t_sbsd_indiv_care_level__x z = new batchsit_t_sbsd_indiv_care_level__x();
        x.idn_sbsd_indiv_care_level__c = 12;
        x.cde_level_care__c = '8';
        x.dte_begin_effv__c= System.today();
        x.createdbyid__c = UserInfo.getUserId();
        x.ExternalId ='test';
        
         z.idn_sbsd_indiv_care_level__c = 12;
        z.cde_level_care__c = '8';
        z.dte_begin_effv__c= System.today().addYears(-11);
        z.createdbyid__c = UserInfo.getUserId();
        z.ExternalId ='test';
        
                
         batchsit_t_sbsd_indiv_care_level__x y = new batchsit_t_sbsd_indiv_care_level__x();
        y.idn_sbsd_indiv_care_level__c = 13;
        y.cde_level_care__c = '7';
        y.createdbyid__c = UserInfo.getUserId();
        y.dte_begin_effv__c= System.today();
        y.ExternalId ='test';

        indivList.add(x);
         indivList.add(y);
        
        obj =TestClassUtility.createIndividual(true,System.today(),'first','1','last','123','CC');
        T_COUNTY__c  countyObj =TestClassUtility.createCounty('Test','PEN',1,true);
        T_CHATS_PROVR_STATUS__c provObj = TestClassUtility.createProvider(true,'Test');
        authObj =TestClassUtility.createAuthorization(true,System.today(),System.today(),countyObj.Id,provObj.Id);
        x.idn_client__c =  obj.Id;
        x.lastmodifiedbyid__c =UserInfo.getUserId();
        sobjects.add(x);
        //BG Temp Fix
        Date datetoday=System.Today();
        
        
        T_SBSD_INDIV__c individual = TestClassUtility.createIndividual(true,system.today().addYears(-15),'first','1','last','123','CC');
         sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstNameA','1','lastNameA','1','CC');
        T_SBSD_CASE__c sbsdcase=TestClassUtility.createCase(false,countyObj.Id);
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today().addYears(4);
        sbsdcase.IDN_EXTNL__c='12345';
        upsert sbsdcase;
        Date begindate = date.newInstance(datetoday.year(),datetoday.month(),1);
        begindate = begindate.addDays(25);
        //Removed unused variable on 5/13/2018 BG        
        Date enddate = begindate.addDays(20);
        T_AUTH__c authorization=TestClassUtility.createAuthorization(false,enddate,begindate,countyObj.Id,provObj.Id);
        authorization.IDN_CASE__c=sbsdcase.Id;
        authorization.IDN_CLIENT__c=sbsdIndiv.Id;
        authorization.CDE_TYPE_VERIF__c = 'NA';
        authorization.CDE_SOURCE_VRFYD_IMMU__c ='PRO';
        authorization.CDE_IMM__c ='NRL';
        insert authorization;
        IndividualCareLvlApexCtrl.encumbranceUpdate('TEST',null);
        IndividualCareLvlApexCtrl.fetchAuthEncumbrance('TEST');
        IndividualCareLvlApexCtrl.authEncumbranceUpdate('TEST');
        
            
    }
    static testmethod  void testgetIndividualCareLvls(){
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock()); 
        testDataSetup();
        Boolean isError;
        List<batchsit_t_sbsd_indiv_care_level__x> indCareLvl;
        Id indivId;
        String message;
        Test.startTest();
        IndividualCareLvlApexCtrl.getIndividualCareLvls(obj.Id);
        IndividualCareLvlApexCtrl.indivCareLevelWrapper wrap = new IndividualCareLvlApexCtrl.indivCareLevelWrapper( isError, indCareLvl, message, indivId);
        system.assertEquals(null,wrap.message,'Message should be null');
         Test.stopTest();
    }
    static testmethod  void testgetIndividualCareLvls_Scneriao2(){
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock()); 
        Boolean isError;
        List<batchsit_t_sbsd_indiv_care_level__x> indCareLvl;
        Id indivId;
        String message;
        Test.startTest();
        IndividualCareLvlApexCtrl.fetchAuthEncumbrance('test');
        IndividualCareLvlApexCtrl.authEncumbranceUpdate('test');
        Test.stopTest();
    }
    static testmethod  void testgetIndividualCareLvls_Scneriao7(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator()); 
        Boolean isError;
        List<batchsit_t_sbsd_indiv_care_level__x> indCareLvl;
        Id indivId;
        String message;
        Test.startTest();
        IndividualCareLvlApexCtrl.authEncumbranceUpdate('test');
        IndividualCareLvlApexCtrl.fetchAuthEncumbrance('test');
        Test.stopTest();
    }
    static testmethod  void testgetIndividualCareLvls_Scneriao1(){
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock()); 
        Test.startTest();
        IndividualCareLvlApexCtrl.encumbranceUpdate('TEST',null);
        Test.stopTest();
    }
    static testmethod  void testgetIndividualCareLvls_Scneriao3(){
        testDataSetup();
        Test.startTest();
        IndividualCareLvlApexCtrl.insertATSRecord(sbsdIndiv.Id);
        Test.stopTest();
    }
    static testmethod  void testgetIndividualCareLvls_Scneriao4(){
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock());
        List<batchsit_t_sbsd_indiv_care_level__x> indivList = new  List<batchsit_t_sbsd_indiv_care_level__x>();
         batchsit_t_sbsd_indiv_care_level__x x = new batchsit_t_sbsd_indiv_care_level__x();
         batchsit_t_sbsd_indiv_care_level__x z = new batchsit_t_sbsd_indiv_care_level__x();
        x.idn_sbsd_indiv_care_level__c = 12;
        x.cde_level_care__c = '8';
        x.dte_begin_effv__c= System.today();
        x.createdbyid__c = UserInfo.getUserId();
        x.ExternalId ='test';
        
         z.idn_sbsd_indiv_care_level__c = 12;
        z.cde_level_care__c = '8';
        z.dte_begin_effv__c= System.today().addYears(-11);
        z.createdbyid__c = UserInfo.getUserId();
        z.ExternalId ='test';
        
                
         batchsit_t_sbsd_indiv_care_level__x y = new batchsit_t_sbsd_indiv_care_level__x();
        y.idn_sbsd_indiv_care_level__c = 13;
        y.cde_level_care__c = '7';
        y.createdbyid__c = UserInfo.getUserId();
        y.dte_begin_effv__c= System.today();
        y.ExternalId ='test';
		Id indivId = 'a2Am0000001VeqY';
        indivList.add(x);
         indivList.add(y);
        Test.startTest();
        IndividualCareLvlApexCtrl.validateIndCareLst(indivId,indivList);
        Test.stopTest();
    }
     static testmethod  void testgetIndividualCareLvls_Scneriao5(){
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock());
        List<batchsit_t_sbsd_indiv_care_level__x> indivList = new  List<batchsit_t_sbsd_indiv_care_level__x>();
         batchsit_t_sbsd_indiv_care_level__x x = new batchsit_t_sbsd_indiv_care_level__x();
         batchsit_t_sbsd_indiv_care_level__x z = new batchsit_t_sbsd_indiv_care_level__x();
        x.idn_sbsd_indiv_care_level__c = 12;
        x.cde_level_care__c = '7';
        x.dte_begin_effv__c= System.today();
        x.createdbyid__c = UserInfo.getUserId();
        x.ExternalId ='test';
        
         z.idn_sbsd_indiv_care_level__c = 12;
        z.cde_level_care__c = '8';
        z.dte_begin_effv__c= System.today().addDays(-10);
        z.createdbyid__c = UserInfo.getUserId();
        z.ExternalId ='test';
        
                
         batchsit_t_sbsd_indiv_care_level__x y = new batchsit_t_sbsd_indiv_care_level__x();
        y.idn_sbsd_indiv_care_level__c = 13;
        y.cde_level_care__c = '7';
        y.createdbyid__c = UserInfo.getUserId();
        y.dte_begin_effv__c= System.today();
        y.ExternalId ='test';
		Id indivId = 'a2Am0000001VeqY';
        indivList.add(x);
         indivList.add(y);
         indivList.add(z);
        Test.startTest();
        IndividualCareLvlApexCtrl.validateIndCareLst(indivId,indivList);
        Test.stopTest();
    }
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json;charset=UTF-8');
            //res.setBody('{"example":"test"}');
            res.setBody('[{"cde_Level_Care":"1892","cde_Type_Unit_Care":"8",errMessage":"Test","successInd":"Y"},{"authCopayId":"1893","errMessage":"Test","successInd":"Y"}]');
            res.setStatusCode(200);
            res.setStatus('OK');
            return res;
        }
    }
}