CHATS_SIT/force-app/main/default/objects/batchsit_t_sbsd_case_cmt__x.object
<CustomObject>
    <description>batchsit$t_sbsd_case_cmt</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_sbsd_case_cmt</externalName>
    <fields>
        <fullName>idn_case__c</fullName>
        <description>idn_case</description>
        <externalDeveloperName>idn_case</externalDeveloperName>
        <label>Case ID</label>
        <length>50</length>
        <referenceTargetField>T_SBSD_CASE__c.IDN_EXTNL__c</referenceTargetField>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Comment</relationshipLabel>
        <relationshipName>batchsit_t_sbsd_case_cmt</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <label>Case Comment</label>
    <pluralLabel>Case Comment</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>AMT_ACTV_AUTH__c</fullName>
        <description>Authorization Activity Amount</description>
        <label>Authorization Activity Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AMT_TRANSP_AUTH__c</fullName>
        <description>Authorization Transportation Amount</description>
        <label>Authorization Transportation Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>T_AUTH</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <label>License Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_SCH__c.object
<CustomObject>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_AGRMT_FISCAL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement</description>
        <label>Fiscal Agreement</label>
        <referenceTo>T_PROVR_FISCAL_AGREMENT__c</referenceTo>
        <relationshipLabel>Rate Schedules</relationshipLabel>
        <relationshipName>Rate_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Rate Schedule ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Rate Schedule Quality Rating</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Rate Schedules</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_AGRMT__c</fullName>
        <description>Renewal Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_RCV_AGRMT_FISCAL__c</fullName>
        <description>Date Received</description>
        <label>Date Fiscal Agreement Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_REDET_CASE__c</fullName>
        <description>Case Redetermination Date</description>
        <label>Case Redetermination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>CDE_STATUS_CASE__c</fullName>
        <description>Case Status</description>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00357</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00357.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>REO</fullName>
        <label>Reopen</label>
    </customValue>
    <description>R00357</description>
    <masterLabel>R00357</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CHATSAuraUtility_Test.cls
@isTest
public class CHATSAuraUtility_Test {
    
    static testmethod  void testfetchLoggedInUserId(){
        Test.startTest();
        system.assertEquals(UserInfo.getUserId(),CHATSAuraUtility.fetchLoggedInUserId(),'Should return logged in User Id');
        Test.stopTest();
    }

    public static testmethod  void testGetDataFromWebService(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        LightningServerResponse lsr = CHATSAuraUtility.getDataFromWebService(System.Label.AUTH_ENCUMBR_FETCH_COUNTY, 'POST', '', new List<String>{'count'});
        system.assertEquals(true,lsr.isSuccessful);
    }
    
    public static testmethod  void testGetSobjectName(){
        T_COUNTY__c county = TestClassUtility.createCounty('Test', 'Dept', 1, true);
        String sObjectName = CHATSAuraUtility.getSObjectName(county.Id);
        system.assertEquals(sObjectName ,'T_COUNTY__c', 'sObject Name should be T_COUNTY__c');
    }
    
    public static testmethod  void fetchLoggedInProfileId_Test(){
        T_COUNTY__c county = TestClassUtility.createCounty('Test', 'Dept', 1, true);
        T_SBSD_CASE__c sbsdcase = TestClassUtility.createCase(false,county.Id);
        sbsdcase.IDN_EXTNL__c ='12345'; // Dont Change the value
        upsert sbsdcase;
        batchsit_t_sbsd_case_cmt__x caseComm = new batchsit_t_sbsd_case_cmt__x();
        caseComm.idn_case__c = sbsdcase.IDN_EXTNL__c;
        Profile userProfile=[Select id from Profile where Name ='System Administrator'];
        User user = TestClassUtility.createUser(userProfile.Id , 'test','test','test@example.com','test@example.com.'+string.valueof(math.random()*3),'ttes');
        
        System.runAs(user){
            LightningServerResponse res = CHATSAuraUtility.fetchLoggedInProfileId(caseComm.Id);
            System.assertEquals(res.objectData.get('profileName') ,'System Administrator');
        }        
    }
    
    public static testmethod  void getCaseOrCaseCommentObjectAPI_Test(){
        T_COUNTY__c county = TestClassUtility.createCounty('Test', 'Dept', 1, true);
        T_SBSD_CASE__c sbsdcase = TestClassUtility.createCase(false,county.Id);
        sbsdcase.IDN_EXTNL__c ='12345'; // Dont Change the value
        upsert sbsdcase;
        batchsit_t_sbsd_case_cmt__x caseComm = new batchsit_t_sbsd_case_cmt__x();
        caseComm.idn_case__c = sbsdcase.IDN_EXTNL__c;
        
        LightningServerResponse res = CHATSAuraUtility.getCaseOrCaseCommentObjectAPI(caseComm.Id, 'true');
        LightningServerResponse res2 = CHATSAuraUtility.getCaseOrCaseCommentObjectAPI(caseComm.Id, 'false');
        LightningServerResponse res3 = CHATSAuraUtility.getCaseOrCaseCommentObjectAPI(sbsdcase.Id, 'true');
        LightningServerResponse res4 = CHATSAuraUtility.getCaseOrCaseCommentObjectAPI(sbsdcase.Id, 'false');
        
        System.assertEquals(res.isSuccessful, true);
        System.assertEquals(res2.isSuccessful, true);
        System.assertEquals(res3.isSuccessful, true);
        System.assertEquals(res4.isSuccessful, true);
    }
    
    public static testmethod  void checkOwnerCountyMatch_Test(){
        Date nullDate;
        Date datetoday=System.Today();
        Date begindate = date.newInstance(datetoday.year(),datetoday.month(),datetoday.day());
        begindate = begindate.addDays(-5);
        String begDate = String.valueOf(begindate);
        Date enddate = begindate.addDays(20);
        
        T_COUNTY__c county= TestClassUtility.createCounty('Test Name','Department',2,true);
        
        T_SBSD_CASE__c sbsdcase=TestClassUtility.createCase(false, county.Id);
        sbsdcase.IDN_EXTNL__c='12345';
        sbsdcase.DTE_REDET_CASE__c = begindate;
        upsert sbsdcase;
        
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1');
        insert provider;
        
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstName','1','lastName','1','CC');
        
        T_AUTH__c authorization=TestClassUtility.createAuthorization(false,nullDate,begindate,county.Id,provider.Id);
        authorization.IDN_CASE__c=sbsdcase.Id;
        authorization.IDN_CLIENT__c=sbsdIndiv.Id;
        authorization.IDN_EXTNL__c='123';
        authorization.AMT_ACTV_AUTH__c =1;
        authorization.AMT_TRANSP_AUTH__c =11;
        insert authorization;
        
        T_SBSD_CASE_STATUS_MODE__c caseStatus = new T_SBSD_CASE_STATUS_MODE__c();
        caseStatus.CDE_STATUS_CASE__c = 'CLS';
        caseStatus.IDN_CASE__c = sbsdcase.Id;
        insert caseStatus;
        
        String openRecordTypeId = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Open').getRecordTypeId();
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement = TestClassUtility.createFiscaAgreement(false, 'FA1', begindate, county.Id);
        fiscalAgreement.RecordtypeId = openRecordTypeId;
        fiscalAgreement.CDE_TYPE_STATUS__c = 'OPN';
        fiscalAgreement.ID_SERVICE__c = provider.Id;
        fiscalAgreement.DTE_RCV_AGRMT_FISCAL__c = begindate;
        fiscalAgreement.DTE_END_AGRMT__c = nullDate;
        insert fiscalAgreement;
        
        T_FISCAL_SCH__c fiscalRateSch = TestClassUtility.createRateSchedule(false, begindate, null, fiscalAgreement.Id, '1');
        fiscalRateSch.DTE_END_EFFV__c = nullDate;
        fiscalRateSch.IDN_AGRMT_FISCAL__c = fiscalAgreement.Id;
        insert fiscalRateSch;
        
        CHATSAuraUtility.checkOwnerCountyMatch(authorization.Id,'CDE_COUNTY__c');
        CHATSAuraUtility.checkOwnerCountyMatch(sbsdcase.Id,'CDE_COUNTY__c');
        String hoursPerWeekDay = '[{"CDE_TYPE_UNIT_CARE__c":"1","CNT_HOUR_CARE__c":"0"},{"CDE_TYPE_UNIT_CARE__c":"1","CNT_HOUR_CARE__c":"8"},{"CDE_TYPE_UNIT_CARE__c":"1","CNT_HOUR_CARE__c":"8"},{"CDE_TYPE_UNIT_CARE__c":"1","CNT_HOUR_CARE__c":"8"},{"CDE_TYPE_UNIT_CARE__c":"1","CNT_HOUR_CARE__c":"8"},{"CDE_TYPE_UNIT_CARE__c":"1","CNT_HOUR_CARE__c":"8"},{"CDE_TYPE_UNIT_CARE__c":"1","CNT_HOUR_CARE__c":"0"}]';
        CHATSAuraUtility.careLevelOfferedByProvider(authorization.Id, authorization.Id, begDate, provider.Id, sbsdIndiv.Id, hoursPerWeekDay);
        CHATSAuraUtility.careLevelOfferedByProvider(sbsdcase.Id, sbsdcase.Id, begDate, provider.Id, sbsdIndiv.Id, hoursPerWeekDay);
    }
}