CHATS_SIT/force-app/main/default/objects/batchsit_t_auth_status__x.object
<CustomObject>
    
    <description>batchsit$t_auth_status</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_auth_status</externalName>
    <label>Authorization Status</label>
    <pluralLabel>Authorization Status</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/batchsit_t_fiscal_rate__x.object-meta.xml
<CustomObject>
    <description>batchsit$t_fiscal_rate</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_fiscal_rate</externalName>
    <label>batchsit$t_fiscal_rate</label>
    <pluralLabel>batchsit$t_fiscal_rate</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/fields/amt_fa__c.field-meta.xml
<CustomField>
    <fullName>amt_fa__c</fullName>
    <description>amt_fa</description>
    <externalDeveloperName>amt_fa</externalDeveloperName>
    <label>Fiscal Agreement Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/fields/amt_provr__c.field-meta.xml
<CustomField>
    <fullName>amt_provr__c</fullName>
    <description>amt_provr</description>
    <externalDeveloperName>amt_provr</externalDeveloperName>
    <label>Provider Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/fields/cde_age_group__c.field-meta.xml
<CustomField>
    <fullName>cde_age_group__c</fullName>
    <description>cde_age_group</description>
    <externalDeveloperName>cde_age_group</externalDeveloperName>
    <label>Age Group</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/fields/cde_care_unit__c.field-meta.xml
<CustomField>
    <fullName>cde_care_unit__c</fullName>
    <description>cde_care_unit</description>
    <externalDeveloperName>cde_care_unit</externalDeveloperName>
    <label>Care Unit</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/fields/cde_rate_type__c.field-meta.xml
<CustomField>
    <fullName>cde_rate_type__c</fullName>
    <description>cde_rate_type</description>
    <externalDeveloperName>cde_rate_type</externalDeveloperName>
    <label>Rate Type</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/fields/idn_fiscal_sch__c.field-meta.xml
<CustomField>
    <fullName>idn_fiscal_sch__c</fullName>
    <description>idn_fiscal_sch</description>
    <externalDeveloperName>idn_fiscal_sch</externalDeveloperName>
    <label>idn_fiscal_sch</label>
    <length>18</length>
    <referenceTargetField>T_FISCAL_SCH__c.IDN_EXTNL__c</referenceTargetField>
    <referenceTo>T_FISCAL_SCH__c</referenceTo>
    <relationshipLabel>batchsit$t_fiscal_rate</relationshipLabel>
    <relationshipName>batchsit_t_fiscal_rate</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>DTE_END_EFFV_AUTH__c</fullName>
        <label>Authorization End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_SCH__c.object
<CustomObject>
    <fields>
        <fullName>CDE_RATE_TYPE__c</fullName>
        <description>Rate Type</description>
        <label>Rate Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00751</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Rate Schedule ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rate Schedules</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <description>Provider ID</description>
        <label>Provider ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/classes/HerokuServiceTest.cls
@isTest
public class HerokuServiceTest {
    
    public static testmethod void testHerokuCallout() {
        Set<String> subPaymentDetailIdList = new Set<String>();
        subPaymentDetailIdList.add('test');
        Test.setMock(HttpCalloutMock.class, new HerokuServiceHttpCalloutMock());
        HerokuService.authEncubUpdateCareLevel();
        HerokuService.authStatusCreate();
        HerokuService.authCopayCreate();
        HerokuService.authCopayFetch();
        HerokuService.authCopayUpdate(); 
        HerokuService.subPaymentService(subPaymentDetailIdList, 'Claim');
        system.assertEquals(0,[select Id from batchsit_t_auth_status__x Limit 10].size(),'Zero rows should return');
        //HerokuService.authEncumbranceUpdate('[{"cde_Status_Encmbr":"8","idn_Auth":"a1fg0000001kMgQAAU","idn_Encmbr_Auth":"33","lastmodifieddate":"2012-12-12 10:10:10","lastmodifiedbyid":"Salesforce"}]');
        //HerokuService.authCopayUpdate();
        //HerokuService.authCopayUpdate();
    }
    
    public static testmethod void testHerokuCallout1() {
        Date datetoday=System.Today();
        Date begindate = date.newInstance(datetoday.year(),datetoday.month(),1);
        Date dob = date.newInstance(datetoday.year()-20, datetoday.month(), 1);
        Date enddate = begindate.addDays(25);
        begindate = begindate.addDays(21);
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_INDIV__c individual = TestClassUtility.createIndividual(true, dob, 'firstName', '1', 'lastName', '123', 'CC');
        T_SBSD_CASE__c case1 = TestClassUtility.createCase(true, county.Id);
        T_SBSD_CASE__c case2 = TestClassUtility.createCase(true, county.Id);
        T_CHATS_PROVR_STATUS__c provider = TestClassUtility.createProvider(true, 'Level 3');
        T_AUTH__c authorization=TestClassUtility.createAuthorization(false,enddate,begindate,county.Id,null);
        authorization.IDN_CASE__c= case1.Id;
        authorization.IDN_CLIENT__c= individual.Id;
        authorization.IDN_PROVR__c= provider.Id;
        insert authorization;
        List<EncumberenceWrapper> encumList = new List<EncumberenceWrapper>();
        List<EncumbranceEnrollWrapper> encumEnrollList = new List<EncumbranceEnrollWrapper>();
        
        EncumberenceWrapper  encumberence= new EncumberenceWrapper();
        encumberence.cde_Level_Care = '5';
        encumberence.cde_Status_Encmbr = '4';
        //encumberence.cde_Type_Unit_Care = encumberenceRec.cde_Type_Unit_Care__c;
        encumberence.cnt_Hour_Attnd_Actual = '0';
        encumberence.cnt_Hour_Care = '0';
        encumberence.idn_Auth = authorization.Id;
        encumberence.dte_Care = '2012-12-12';
        encumberence.createdbyid = 'test';
        encumberence.createddate = '2012-12-12 10:10:10';
        encumberence.nbr_Seq_Hist =  '1';
        encumberence.lastmodifieddate = '2012-12-12 10:10:10';
        encumberence.lastmodifiedbyid = 'test';
        encumberence.ind_0_36_months = 'N';
        encumList.add(encumberence);
        
        EncumbranceEnrollWrapper encumbEnroll = new EncumbranceEnrollWrapper();
        encumbEnroll.ind_0_36_months = 'Y';
        encumbEnroll.authId = authorization.Id;
        encumbEnroll.careDate = '2012-12-12';
        encumbEnroll.createdbyid = 'test';
        encumbEnroll.createddate = '2012-12-12 10:10:10';
        encumbEnroll.nbrSeqHist =  '1';
        encumbEnroll.lastmodifieddate = '2012-12-12 10:10:10';
        encumbEnroll.lastmodifiedbyid = 'test';
        encumEnrollList.add(encumbEnroll);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HerokuServiceHttpCalloutMock());
        HerokuService.authEncumbranceUpdate('[{"cde_Status_Encmbr":"8","idn_Auth":'+authorization.Id+',"idn_Encmbr_Auth":"33","lastmodifieddate":"2012-12-12 10:10:10","lastmodifiedbyid":"Salesforce"}]');
        HerokuService.authEncumbrancefetch('{"authId":'+authorization.Id+'}');
        //HerokuService.authEncumbranceEnrollfetch(authorization.Id);
        HerokuService.authEncumbranceCreate(encumList);
        //HerokuService.authEncumbranceEnrollCreate(encumEnrollList);
        HerokuService.caseCopyCreate('1','1','1','R','R','2012-12-12','2012-12-12','621003857','1','1','4','Y',true);
        HerokuService.caseCopyUpdate('1','1','1','R','R','2012-12-12','2012-12-12','621003857','1','1','4','Y','ExternalId');
        system.assertEquals(true,HerokuService.updateCaseParentFee('providerId').isSuccess);
        Test.stopTest();
    }
    
    public static testmethod void testHerokuCallout2() {
        Date datetoday=System.Today();
        Date begindate = date.newInstance(datetoday.year(),datetoday.month(),1);
        Date dob = date.newInstance(datetoday.year()-20, datetoday.month(), 1);
        Date enddate = begindate.addDays(25);
        begindate = begindate.addDays(21);
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_INDIV__c individual = TestClassUtility.createIndividual(true, dob, 'firstName', '1', 'lastName', '007', 'CC');
        T_SBSD_CASE__c case1 = TestClassUtility.createCase(true, county.Id);
        T_SBSD_CASE__c case2 = TestClassUtility.createCase(true, county.Id);
        T_CHATS_PROVR_STATUS__c provider = TestClassUtility.createProvider(true, 'Level 3');
        T_AUTH__c authorization=TestClassUtility.createAuthorization(false,enddate,begindate,county.Id,null);
        authorization.IDN_CASE__c= case1.Id;
        authorization.IDN_CLIENT__c= individual.Id;
        authorization.IDN_PROVR__c= provider.Id;
        insert authorization; 
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HerokuServiceHttpCalloutMock());
        HerokuService.authCopayDelete(authorization.IDN_EXTNL__c, authorization.DTE_END_EFFV_AUTH__c,authorization.LastModifiedById);
        HerokuService.authEncumbranceDelete(authorization.IDN_EXTNL__c, authorization.DTE_END_EFFV_AUTH__c);
        //HerokuService.authEncumbranceEnrollDelete(authorization.IDN_EXTNL__c, authorization.DTE_END_EFFV_AUTH__c);
        HerokuService.getAmountPaidService(case1.Id, '1', '2022');
        Test.stopTest();
    }
    
    public static testmethod void testFiscalRateCallouts() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_CHATS_PROVR_STATUS__c provider = TestClassUtility.createProvider(true, 'Level 3');
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement = TestClassUtility.createFiscaAgreement(false, '1234', system.today(), county.Id);
        fiscalAgreement.ID_SERVICE__c = provider.Id;
        insert fiscalAgreement;
        T_FISCAL_SCH__c fiscalSchedule = TestClassUtility.createRateSchedule(true, system.today(), null, fiscalAgreement.Id, '1');
        List<Id>fiscalScheduleIdLst = new List<Id>();
        fiscalScheduleIdLst.add(fiscalSchedule.Id);
        batchsit_t_fiscal_rate__x fiscalRate = new batchsit_t_fiscal_rate__x();
        fiscalRate.amt_fa__c= 10;
        fiscalRate.amt_provr__c= 15;
        fiscalRate.cde_age_group__c= '1';
        fiscalRate.cde_care_unit__c= '2';
        fiscalRate.cde_rate_type__c= '1';
        fiscalRate.idn_fiscal_sch__c = fiscalSchedule.Id;
        List<batchsit_t_fiscal_rate__x> lstFiscalRates = new List<batchsit_t_fiscal_rate__x>();
        lstFiscalRates.add(fiscalRate);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HerokuServiceHttpCalloutMock());
        system.assertEquals(true,HerokuService.fiscalRatefetch(fiscalScheduleIdLst).size()>0);
        system.assertEquals(true,HerokuService.createFiscalRateRecords(lstFiscalRates).isSuccess);
        system.assertEquals(true, HerokuService.deleteFiscalRateRecords(fiscalScheduleIdLst).isSuccess);
        Test.setMock(HttpCalloutMock.class, new HerokuServiceUnSuccessfullCalloutMock());
        system.assertEquals(false,HerokuService.fiscalRatefetch(fiscalScheduleIdLst).size()>0);
        system.assertEquals(false,HerokuService.createFiscalRateRecords(lstFiscalRates).isSuccess);
        system.assertEquals(false, HerokuService.deleteFiscalRateRecords(fiscalScheduleIdLst).isSuccess);
        Test.stopTest();
    }
    
    public static testmethod void testExceptionCallouts() {
        HerokuService.authEncubUpdateCareLevel();  
        HerokuService.authStatusCreate();
        HerokuService.authCopayCreate();
        HerokuService.authCopayFetch();
        HerokuService.authCopayUpdate();
        HerokuService.authEncumbranceCreate(new List<EncumberenceWrapper>());
        //HerokuService.authEncumbranceEnrollCreate(new List<EncumbranceEnrollWrapper>());
        HerokuService.authEncumbrancefetch('test');
        HerokuService.authEncumbranceUpdate('test');
        HerokuService.createFiscalRateRecords(new List<batchsit_t_fiscal_rate__x>());
        Test.setMock(HttpCalloutMock.class, new HerokuServiceHttpCalloutMock2());
        HerokuService.authEncubUpdateCareLevel();
        HerokuService.authStatusCreate();
        HerokuService.authCopayCreate();
        HerokuService.authCopayFetch();
        HerokuService.authCopayUpdate();
        HerokuService.convertDateJSONToDate('/');
        HerokuService.authEncumbranceCreate(new List<EncumberenceWrapper>());
        //HerokuService.authEncumbranceEnrollCreate(new List<EncumbranceEnrollWrapper>());
        HerokuService.authEncumbrancefetch('test');
        //HerokuService.authEncumbranceEnrollfetch('test');
        Map<String, String> testMap=HerokuService.authEncumbranceUpdate('test');
        system.assertEquals(true, testMap.size()>0);
        HerokuService.createFiscalRateRecords(new List<batchsit_t_fiscal_rate__x>());
        HerokuService.subPaymentService(new set<string>(), 'Claim');
        HerokuService.getAmountPaidService('', null, null);
    }
    
    public class HerokuServiceHttpCalloutMock2 implements HttpCalloutMock {
        // Implement this interface method authEncumbrancefetch
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            if(request.getEndpoint().contains('AuthEncumbr/UpdateRecordsForCareLevel')){
                response.setStatusCode(100);
            }else if(request.getEndpoint().contains('AuthStatus/CreateRecord')){
                response.setStatusCode(100);
            }else if(request.getEndpoint().contains('AuthCopay/FetchRecords')){
                response.setStatusCode(100);
            }else if(request.getEndpoint().contains('AuthCopay/UpdateRecords')){
                response.setStatusCode(100);
            }else if(request.getEndpoint().contains('AuthEncumbr/CreateRecord')){
                response.setStatusCode(100);
            }else if(request.getEndpoint().contains('AuthEncumbr/FetchRecords')){
                response.setStatusCode(100);
            }else if(request.getEndpoint().contains('AuthEncumbr/UpdateRecord')){
                response.setStatusCode(100);
            }else if(request.getEndpoint().contains('SubpaymentDetail/UpdateExistingAdjustment')){
                response.setStatusCode(100);
            }else if(request.getEndpoint().contains('farates/create')){
                response.setStatusCode(100);
            }else if(request.getEndpoint().contains('CaseReview/GetSubsidyAmount')){
                response.setStatusCode(100);
            }
            return response; 
        }
    }
}