CHATS_SIT/force-app/main/default/objects/batchsit_t_sbsd_case_copay__x.object
<CustomObject>
    <description>batchsit$t_sbsd_case_copay</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_sbsd_case_copay</externalName>
    <fields>
        <fullName>amt_copay_case_assesd__c</fullName>
        <description>amt_copay_case_assesd</description>
        <externalDeveloperName>amt_copay_case_assesd</externalDeveloperName>
        <label>Parent Fee</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>amt_copay_case_ft__c</fullName>
        <description>amt_copay_case_ft</description>
        <externalDeveloperName>amt_copay_case_ft</externalDeveloperName>
        <label>Full Time Fee</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>amt_copay_case_ft_qlty__c</fullName>
        <description>amt_copay_case_ft_qlty</description>
        <externalDeveloperName>amt_copay_case_ft_qlty</externalDeveloperName>
        <label>Quality Rating Discounted Full Time</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>amt_copay_case_pt__c</fullName>
        <description>amt_copay_case_pt</description>
        <externalDeveloperName>amt_copay_case_pt</externalDeveloperName>
        <label>Part Time Fee</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cde_reason_ovrd__c</fullName>
        <description>cde_reason_ovrd</description>
        <externalDeveloperName>cde_reason_ovrd</externalDeveloperName>
        <label>Override Reason</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cde_rec_copay__c</fullName>
        <description>cde_rec_copay</description>
        <externalDeveloperName>cde_rec_copay</externalDeveloperName>
        <label>Recommended Parent Fee Unit</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dte_begin_effv__c</fullName>
        <description>dte_begin_effv</description>
        <externalDeveloperName>dte_begin_effv</externalDeveloperName>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>idn_case__c</fullName>
        <description>idn_case</description>
        <externalDeveloperName>idn_case</externalDeveloperName>
        <label>Case ID</label>
        <length>50</length>
        <referenceTargetField>T_SBSD_CASE__c.IDN_EXTNL__c</referenceTargetField>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Parent Fee</relationshipLabel>
        <relationshipName>batchsit_t_sbsd_case_copay</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <fields>
        <fullName>nbr_seq_hist__c</fullName>
        <description>nbr_seq_hist</description>
        <externalDeveloperName>nbr_seq_hist</externalDeveloperName>
        <label>Number Sequence history</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case Parent Fee</label>
    <pluralLabel>Case Parent Fee</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>T_AUTH</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_IMM__c</fullName>
        <label>Immunized</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00389</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_SOURCE_VRFYD_IMMU__c</fullName>
        <description>Immunization How Verified</description>
        <label>Immunization How Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00709</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Immunization Verified</description>
        <label>Immunization Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <label>License Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_SCH__c.object
<CustomObject>
    <fields>
        <fullName>CDE_RATE_TYPE__c</fullName>
        <description>Rate Type</description>
        <label>Rate Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00751</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_AGRMT_FISCAL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement</description>
        <label>Fiscal Agreement</label>
        <referenceTo>T_PROVR_FISCAL_AGREMENT__c</referenceTo>
        <relationshipLabel>Rate Schedules</relationshipLabel>
        <relationshipName>Rate_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Rate Schedule ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Rate Schedule Quality Rating</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Rate Schedules</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_RCV_AGRMT_FISCAL__c</fullName>
        <description>Date Received</description>
        <label>Date Fiscal Agreement Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00367.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Available</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <label>Verbal Verification</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Written Verification</label>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
        <isActive>false</isActive>
        <label>CV</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
        <isActive>false</isActive>
        <label>N/A-adult caretaker</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <isActive>false</isActive>
        <label>SV</label>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
        <isActive>false</isActive>
        <label>N/A-not requesting child</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>R00367</description>
    <masterLabel>R00367</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00389.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NMD</fullName>
        <label>No. Medical reason</label>
    </customValue>
    <customValue>
        <fullName>NNW</fullName>
        <label>No. Not immunized</label>
    </customValue>
    <customValue>
        <fullName>NRL</fullName>
        <label>No. Religious Reasons</label>
    </customValue>
    <customValue>
        <fullName>NW</fullName>
        <label>No. In Process</label>
    </customValue>
    <customValue>
        <fullName>YES</fullName>
        <label>Yes. Immunized</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <description>R00389</description>
    <masterLabel>R00389</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00709.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NUR</fullName>
        <label>Dr/Nurse Statement</label>
    </customValue>
    <customValue>
        <fullName>PRO</fullName>
        <label>Provider</label>
    </customValue>
    <customValue>
        <fullName>SAG</fullName>
        <label>School Age</label>
    </customValue>
    <customValue>
        <fullName>SRD</fullName>
        <label>Shot Record</label>
    </customValue>
    <description>R00709</description>
    <masterLabel>R00709</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/UpdateParentFeeApxCtrl_Test.cls
@isTest
global class UpdateParentFeeApxCtrl_Test {
    public static final String OPEN = 'OPN';
    public static final String openRecordTypeId = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Open').getRecordTypeId();
    testMethod static void testSaveAuthCopay() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();   
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x();
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        T_County__c countyRec = TestClassUtility.createCounty('Denver', 'Test', 1, true);
        T_SBSD_Case__c caseRec = new T_SBSD_Case__c(CDE_COUNTY__c=countyRec.Id);  
        insert caseRec;
        Date effective = System.today();
        String wrapLst = '[{"AMT_COPAY_AUTH":"10","authCopayId":"1891","CDE_STATUS_AUTH":"2","childName":"Hegde,Ganesh","DTE_DOB":"2001-12-19","IDN_AUTH":"4444","IDN_PROVR":"a1jg00000028GDgAAM","ProviderName":"Govinda Trust and company","errMsg":null},{"AMT_COPAY_AUTH":"10","authCopayId":"1889","CDE_STATUS_AUTH":"2","childName":"Hegde,Ganesh","DTE_DOB":"2001-12-19","IDN_AUTH":"4444","IDN_PROVR":"a1jg00000028GDgAAM","ProviderName":"Govinda Trust and company","errMsg":null}]';
        ParentFeeAllocationWrapper wrapper = new ParentFeeAllocationWrapper('Hegde,Ganesh','4444',effective, '123', 'Govinda Trust and company', effective,effective,  10,  'authExternalId', effective, '12345',false,effective,10,'','' ); 
        List<ParentFeeAllocationWrapper> listWrapper = new List<ParentFeeAllocationWrapper>();
        listWrapper.add(wrapper);
        String authCopayWrap = JSON.serialize(listWrapper);
        
        String wrapLst2 = '[{"AMT_COPAY_AUTH":"10","authCopayId":"1891","CDE_STATUS_AUTH":"2","childName":"Hegde,Ganesh","DTE_DOB":"2001-12-19","IDN_AUTH":"4444","IDN_PROVR":"a1jg00000028GDgAAM","ProviderName":"Govinda Trust and company","errMsg":null},{"AMT_COPAY_AUTH":"10","authCopayId":"1889","CDE_STATUS_AUTH":"2","childName":"Hegde,Ganesh","DTE_DOB":"2001-12-19","IDN_AUTH":"4444","IDN_PROVR":"a1jg00000028GDgAAM","ProviderName":"Govinda Trust and company","errMsg":null}]';
        ParentFeeAllocationWrapper wrapper2 = new ParentFeeAllocationWrapper('Hegde,Ganesh','4444',effective, '123', 'Govinda Trust and company', effective,effective,  10,  'authExternalId', effective, '',false,effective ,10,'','');
        List<ParentFeeAllocationWrapper> listWrapper2 = new List<ParentFeeAllocationWrapper>();
        listWrapper2.add(wrapper2);
        String authCopayWrap2 = JSON.serialize(listWrapper2);

        String uniqueUserName = 'testuser' + DateTime.now().getTime() + '@test.com';
        Profile pro = [SELECT Id FROM Profile WHERE Name='Read Only User'];
        User testUser = TestClassUtility.createUser(pro.Id, 'lastNameT', 'firstNameT', 'testUser@test.com', 'testing_testuser@test.com', 'testT');
        System.runAs(testUser) {
            UpdateParentFeeApxCtrl.getInitData(caseRec.Id);
        }
        UpdateParentFeeApxCtrl.getActiveAuthorizationForCase(caseRec.Id,effDt);
        UpdateParentFeeApxCtrl.getActiveAuthorizationForCase(caseRec.Id,'2018-01');
        UpdateParentFeeApxCtrl.deleteParentFeeData('12345');
        UpdateParentFeeApxCtrl.saveAuthCopay(effDt,authCopayWrap);
        UpdateParentFeeApxCtrl.saveAuthCopay('2018-01',authCopayWrap);
        UpdateParentFeeApxCtrl.updateAuthCopay(effDt,authCopayWrap,false);
        UpdateParentFeeApxCtrl.updateAuthCopay('2018-01',authCopayWrap2,false);
        Test.stopTest();
    }
    testMethod static void testgetActiveAuthorizationForCase() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1');
        insert provider;
        
        T_SBSD_CASE__c sbsdcase=TestClassUtility.createCase(false,county.Id);
        
        Date datetoday=System.Today();
        //Date begindate = date.newInstance(datetoday.year(),datetoday.month()+1,1);
        //Date enddate = begindate.addDays(20);
        
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today().addYears(4);
        sbsdcase.IDN_EXTNL__c='12345';
        upsert sbsdcase;
        Date begindate = date.newInstance(datetoday.year(),datetoday.month(),1);
        begindate = begindate.addDays(25);
        String parentFeeDate =String.valueOf(begindate);
        //Removed unused variable on 5/13/2018 BG        
        Date enddate = begindate.addDays(20);
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstName','1','lastName','1','CC');
        T_AUTH__c authorization=TestClassUtility.createAuthorization(false,enddate,begindate,county.Id,provider.Id);
        authorization.IDN_CASE__c=sbsdcase.Id;
        authorization.IDN_CLIENT__c=sbsdIndiv.Id;
        authorization.CDE_TYPE_VERIF__c = 'NA';
        authorization.CDE_SOURCE_VRFYD_IMMU__c ='PRO';
        authorization.CDE_IMM__c ='NRL';
        insert authorization;
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement=TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county.Id);
        fiscalAgreement.RecordtypeId=openRecordTypeId;
        fiscalAgreement.CDE_TYPE_STATUS__c=OPEN;
        fiscalAgreement.ID_SERVICE__c=provider.Id;
        fiscalAgreement.DTE_RCV_AGRMT_FISCAL__c=begindateOpn;
        insert fiscalAgreement;
        T_FISCAL_SCH__c fiscalRateSch1 = new T_FISCAL_SCH__c(IDN_AGRMT_FISCAL__c = fiscalAgreement.Id, CDE_RATE_TYPE__c = '1', TXT_CHATS_RATING__c='Level 3', DTE_BEGIN_EFFV__c= (Date.today()).addDays(-7));
        insert fiscalRateSch1;
        Test.startTest();
        UpdateParentFeeApxCtrl.getActiveAuthorizationForCase(sbsdcase.Id,parentFeeDate);
        Test.stopTest();
    } 
    
    global class MockHttpResponseGenerator implements HttpCalloutMock {
        // Implement this interface method
        global HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint
            // and method.
            //System.assertEquals(Label.AuthCopayFetch, req.getEndpoint());
            //System.assertEquals('POST', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json;charset=UTF-8');
            //res.setBody('{"example":"test"}');
            res.setBody('[{"authCopayId":"1892","errMessage":"Test","successInd":"N"},{"authCopayId":"1893","errMessage":"Test","successInd":"Y"}]');
            res.setStatusCode(300);
            res.setStatus('OK');
            return res;
        }
    }
     global class MockHttpResponseGenerator1 implements HttpCalloutMock {
        // Implement this interface method
        global HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint
            // and method.
            //System.assertEquals(Label.AuthCopayFetch, req.getEndpoint());
            //System.assertEquals('POST', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json;charset=UTF-8');
            //res.setBody('{"example":"test"}');
            res.setBody('{"caseCopayid":"860985","successInd":"Y","errMessage":""}');
            res.setStatusCode(200);
            res.setStatus('OK');
            return res;
        }
    }
    global class MockHttpResponseGenerator2 implements HttpCalloutMock {
        // Implement this interface method
        global HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint
            // and method.
            //System.assertEquals(Label.AuthCopayFetch, req.getEndpoint());
            //System.assertEquals('POST', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json;charset=UTF-8');
            //res.setBody('{"example":"test"}');
            res.setBody('{"caseCopayid":"860985","successInd":"N","errMessage":"tEST"}');
            res.setStatusCode(300);
            res.setStatus('OK');
            return res;
        }
    }
    @isTest static void testPostCallout() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_ft__c=123,amt_copay_case_assesd__c=10,dte_begin_effv__c= System.today(),cde_rec_copay__c ='TES',cde_reason_ovrd__c='Test',idn_case__c='12345',nbr_seq_hist__c=1234,amt_copay_case_ft_qlty__c=123,amt_copay_case_pt_qlty__c=123,ind_qlty__c='Y',idn_sbsd_case_copay__c=123456);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
       // HerokuService.caseCopyCreate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','',true);
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',false,newCaseCopayRec);
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',TRUE,newCaseCopayRec);
        Test.stopTest();
        
    }
    @isTest static void testPostCallout_Scneraio3() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_ft__c=123,amt_copay_case_assesd__c=10,dte_begin_effv__c= System.today(),cde_rec_copay__c ='TES',cde_reason_ovrd__c='Test',idn_case__c='12345',nbr_seq_hist__c=1234,amt_copay_case_ft_qlty__c=123,amt_copay_case_pt_qlty__c=123,ind_qlty__c='Y',idn_sbsd_case_copay__c=123456);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
        HerokuService.caseCopyUpdate('12','123','effDt', '12','Y','2018-12-12','','1233','111','11','12','12','12345');
        HerokuService.caseCopyCreate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','',true);
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',false,newCaseCopayRec);
        Test.stopTest();
        
    }
    @isTest static void testPostCallout_Scneraio6() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_ft__c=123,amt_copay_case_assesd__c=10,dte_begin_effv__c= System.today(),cde_rec_copay__c ='TES',cde_reason_ovrd__c='Test',idn_case__c='12345',nbr_seq_hist__c=1234,amt_copay_case_ft_qlty__c=123,amt_copay_case_pt_qlty__c=123,ind_qlty__c='Y',idn_sbsd_case_copay__c=123456);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
        HerokuService.caseCopyCreate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','',true);
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',TRUE,newCaseCopayRec);
        Test.stopTest();
        
    }
     @isTest static void testPostCallout_Scneraio10() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator1()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_ft__c=123,amt_copay_case_assesd__c=10,dte_begin_effv__c= System.today(),cde_rec_copay__c ='TES',cde_reason_ovrd__c='Test',idn_case__c='12345',nbr_seq_hist__c=1234,amt_copay_case_ft_qlty__c=123,amt_copay_case_pt_qlty__c=123,ind_qlty__c='Y',idn_sbsd_case_copay__c=123456);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
        HerokuService.caseCopyCreate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','',true);
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',TRUE,newCaseCopayRec);
        Test.stopTest();
        
    }
    @isTest static void testPostCallout_Scneraio11() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator1()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_ft__c=123,amt_copay_case_assesd__c=10,dte_begin_effv__c= System.today(),cde_rec_copay__c ='TES',cde_reason_ovrd__c='Test',idn_case__c='12345',nbr_seq_hist__c=1234,amt_copay_case_ft_qlty__c=123,amt_copay_case_pt_qlty__c=123,ind_qlty__c='Y',idn_sbsd_case_copay__c=123456);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
        HerokuService.caseCopyCreate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','',true);
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',FALSE,newCaseCopayRec);
        Test.stopTest();
        
    }
    @isTest static void testPostCallout_Scneraio12() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_ft__c=123,amt_copay_case_assesd__c=10,dte_begin_effv__c= System.today(),cde_rec_copay__c ='TES',cde_reason_ovrd__c='Test',idn_case__c='12345',nbr_seq_hist__c=1234,amt_copay_case_ft_qlty__c=123,amt_copay_case_pt_qlty__c=123,ind_qlty__c='Y',idn_sbsd_case_copay__c=123456);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
        HerokuService.caseCopyUpdate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','','12345');
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',FALSE,newCaseCopayRec);
        Test.stopTest();
        
    }
    @isTest static void testPostCallout_Scneraio13() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
        Date effectiveDate = Date.newInstance(2018, 04, 01); 
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_ft__c=123,amt_copay_case_assesd__c=10,dte_begin_effv__c= effectiveDate,cde_rec_copay__c ='TES',cde_reason_ovrd__c='Test',idn_case__c='12345',nbr_seq_hist__c=1234,amt_copay_case_ft_qlty__c=123,amt_copay_case_pt_qlty__c=123,ind_qlty__c='Y',idn_sbsd_case_copay__c=123456);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
        HerokuService.caseCopyUpdate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','','12345');
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',FALSE,newCaseCopayRec);
        Test.stopTest();
        
    }
    @isTest static void testPostUpdateCallout() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
       batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_ft__c=123,amt_copay_case_assesd__c=10,dte_begin_effv__c= System.today(),cde_rec_copay__c ='TES',cde_reason_ovrd__c='Test',idn_case__c='12345',nbr_seq_hist__c=1234,amt_copay_case_ft_qlty__c=123,amt_copay_case_pt_qlty__c=123,ind_qlty__c='Y',idn_sbsd_case_copay__c=123456);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x(); Test.startTest();
        HerokuService.caseCopyUpdate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','','12345');
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',false,newCaseCopayRec);
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',TRUE,newCaseCopayRec);
        Test.stopTest();
        
    }
    @isTest static void testPostUpdateCallout_Scneraio4() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
       batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_ft__c=123,amt_copay_case_assesd__c=10,dte_begin_effv__c= System.today(),cde_rec_copay__c ='TES',cde_reason_ovrd__c='Test',idn_case__c='12345',nbr_seq_hist__c=1234,amt_copay_case_ft_qlty__c=123,amt_copay_case_pt_qlty__c=123,ind_qlty__c='Y',idn_sbsd_case_copay__c=123456);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
        HerokuService.caseCopyUpdate('12','123','effDt', '12','Y','2018-12-12','','1233','111','11','12','12','12345');
        HerokuService.caseCopyCreate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','',true);
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',false,newCaseCopayRec);
        Test.stopTest();
        
    }
     @isTest static void testPostUpdateCallout_Scneraio5() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseCaseCopayGenerator()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
       batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_ft__c=123,amt_copay_case_assesd__c=10,dte_begin_effv__c= System.today(),cde_rec_copay__c ='TES',cde_reason_ovrd__c='Test',idn_case__c='12345',nbr_seq_hist__c=1234,amt_copay_case_ft_qlty__c=123,amt_copay_case_pt_qlty__c=123,ind_qlty__c='Y',idn_sbsd_case_copay__c=123456);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
        HerokuService.caseCopyUpdate('12','123','effDt', '12','Y','2018-12-12','','1233','111','11','12','12','12345');
        HerokuService.caseCopyCreate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','',true);
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',false,newCaseCopayRec);
         UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',true,newCaseCopayRec);
        Test.stopTest();
        
    }
    global class MockHttpResponseCaseCopayGenerator implements HttpCalloutMock {
        // Implement this interface method
        global HTTPResponse respond(HTTPRequest request) {
            // Create a fake response
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"caseCopayid":"860983","successInd":"N","errMessage":"Custom"}');
            response.setStatusCode(200);
            return response; 
        }
    }

    @isTest static void testPostUpdateCallout_Scneraio1() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_assesd__c=10);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
        HerokuService.caseCopyUpdate('12','1234','effDt', 'wrapLst','false','newCaseCopayRec','123','123','111','11','','','12345');
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',false,newCaseCopayRec);
        
        Test.stopTest();
        
    }
    @isTest static void testPostUpdateCallout_Scneraio2() {
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator()); 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x(ExternalId ='12345',amt_copay_case_pt__c =10,amt_copay_case_assesd__c=10);
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        Test.startTest();
        UpdateParentFeeApxCtrl.saveCaseCopayRecord(caseCopayRec,'1234',effDt, 'wrapLst',false,newCaseCopayRec);
        Test.stopTest();
        
    }
    testMethod static void testAuthWeight() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x();
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        T_County__c countyRec = TestClassUtility.createCounty('Denver', 'Test', 1, true);
        T_SBSD_Case__c caseRec = TestClassUtility.createCase(false, countyRec.Id);
        T_SBSD_Case__c caseR= new T_SBSD_Case__c(CDE_COUNTY__c=countyRec.Id);  
        insert caseR;
        system.debug('caseR---'+caseR.id);
        UpdateParentFeeApxCtrl.getInitData(caseR.Id);
        UpdateParentFeeApxCtrl.getAuthWeight(caseR.Id,'2022-11-01');
        Test.stopTest();
    }
     testMethod static void testgetAuthCopayRecords() {
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock()); 
        Test.startTest();
         Date effective = System.today();
         ParentFeeAllocationWrapper wrapper2 = new ParentFeeAllocationWrapper('Hegde,Ganesh','4444',effective, '123', 'Govinda Trust and company', effective,effective,  10,  'authExternalId', effective, '',false,effective,10,'','' );
        List<ParentFeeAllocationWrapper> listWrapper2 = new List<ParentFeeAllocationWrapper>();
        listWrapper2.add(wrapper2);
        String authCopayWrap2 = JSON.serialize(listWrapper2);
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x();
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        T_County__c countyRec = TestClassUtility.createCounty('Denver', 'Test', 1, true);
        T_SBSD_Case__c caseRec = TestClassUtility.createCase(false, countyRec.Id);
        T_SBSD_Case__c caseR= new T_SBSD_Case__c(CDE_COUNTY__c=countyRec.Id);  
        insert caseR;
        system.debug('caseR---'+caseR.id);
         ParentFeeFlowWSCaller.callSearchParentFeeWS(caseR.IDN_EXTNL__c,'10',2019,effDt,null);
         //UpdateParentFeeApxCtrl.getAuthCopayRecords(caseRec.Id,effDt);
         UpdateParentFeeApxCtrl.upsertParentFeeData(authCopayWrap2,system.today(),true,true);
         UpdateParentFeeApxCtrl.getCaseParentFeeRecord(caseR.IDN_EXTNL__c,effDt,null);
         UpdateParentFeeApxCtrl.getCaseParentFeeRecord(caseR.IDN_EXTNL__c,'2018-01',null);
        Test.stopTest();
    }
     testMethod static void testgetAuthCopayRecords_Scneraio1() {
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock()); 
        
         Date effective = System.today();
         ParentFeeAllocationWrapper wrapper2 = new ParentFeeAllocationWrapper('Hegde,Ganesh','4444',effective, '123', 'Govinda Trust and company', effective,effective,  10,  'authExternalId', effective, '',false,effective ,10,'','');
        List<ParentFeeAllocationWrapper> listWrapper2 = new List<ParentFeeAllocationWrapper>();
        listWrapper2.add(wrapper2);
        String authCopayWrap2 = JSON.serialize(listWrapper2);
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x();
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        T_County__c countyRec = TestClassUtility.createCounty('Denver', 'Test', 1, true);
        T_SBSD_Case__c caseRec = TestClassUtility.createCase(false, countyRec.Id);
        T_SBSD_Case__c caseR= new T_SBSD_Case__c(CDE_COUNTY__c=countyRec.Id);  
        insert caseR;
        system.debug('caseR---'+caseR.id);
        Test.startTest();
        UpdateParentFeeApxCtrl.getAuthCopayRecords(caseRec.Id,effDt,null,'');
        UpdateParentFeeApxCtrl.getAuthCopayRecords(caseRec.Id,'2018-01',null,'');
        Test.stopTest();
    }
     testMethod static void testgetAuthCopayRecords_Scneraio2() {
        Test.setMock(HttpCalloutMock.class, new UpdateParentFeeApxCtrlMock()); 
        
         Date effective = System.today();
         ParentFeeAllocationWrapper wrapper2 = new ParentFeeAllocationWrapper('Hegde,Ganesh','4444',effective, '123', 'Govinda Trust and company', effective,effective,  10,  'authExternalId', effective, '',false,effective ,10,'','');
        List<ParentFeeAllocationWrapper> listWrapper2 = new List<ParentFeeAllocationWrapper>();
        listWrapper2.add(wrapper2);
        String authCopayWrap2 = JSON.serialize(listWrapper2);
        String effDt = '2018-04-01';
        batchsit_t_sbsd_case_copay__x caseCopayRec = new batchsit_t_sbsd_case_copay__x();
        batchsit_t_sbsd_case_copay__x newCaseCopayRec = new batchsit_t_sbsd_case_copay__x();
        T_County__c countyRec = TestClassUtility.createCounty('Denver', 'Test', 1, true);
        T_SBSD_Case__c caseRec = TestClassUtility.createCase(false, countyRec.Id);
        T_SBSD_Case__c caseR= new T_SBSD_Case__c(CDE_COUNTY__c=countyRec.Id);  
        insert caseR;
         Test.startTest();
         ParentFeeFlowWSCaller.callSearchParentFeeWS(caseR.IDN_EXTNL__c,'10',2019,effDt,null);
         UpdateParentFeeApxCtrl.upsertParentFeeData(authCopayWrap2,system.today(),true,true);
         UpdateParentFeeApxCtrl.getPrivateRates(listWrapper2, system.today(), 'PT', caseR.IDN_EXTNL__c, null);
        Test.stopTest();
    }    
}