CHATS_SIT/force-app/main/default/objects/batchsit_t_sbsd_case_cmt__x.object
<CustomObject>
    <description>batchsit$t_sbsd_case_cmt</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_sbsd_case_cmt</externalName>
    <fields>
        <fullName>cde_type_cmt__c</fullName>
        <description>cde_type_cmt</description>
        <externalDeveloperName>cde_type_cmt</externalDeveloperName>
        <label>Note Generation Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cde_type_note_cmt__c</fullName>
        <description>cde_type_note_cmt</description>
        <externalDeveloperName>cde_type_note_cmt</externalDeveloperName>
        <label>Note Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>createdbyid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>createdbyid</description>
        <externalDeveloperName>createdbyid</externalDeveloperName>
        <label>Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>batchsit_t_sbsd_case_cmt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>createddate__c</fullName>
        <description>createddate</description>
        <externalDeveloperName>createddate</externalDeveloperName>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>idn_case__c</fullName>
        <description>idn_case</description>
        <externalDeveloperName>idn_case</externalDeveloperName>
        <label>Case ID</label>
        <length>50</length>
        <referenceTargetField>T_SBSD_CASE__c.IDN_EXTNL__c</referenceTargetField>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Comment</relationshipLabel>
        <relationshipName>batchsit_t_sbsd_case_cmt</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <fields>
        <fullName>lastmodifiedbyid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lastmodifiedbyid</description>
        <externalDeveloperName>lastmodifiedbyid</externalDeveloperName>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>batchsit_t_sbsd_case_cmt1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lastmodifieddate__c</fullName>
        <description>lastmodifieddate</description>
        <externalDeveloperName>lastmodifieddate</externalDeveloperName>
        <label>Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>nbr_seq_hist__c</fullName>
        <description>nbr_seq_hist</description>
        <externalDeveloperName>nbr_seq_hist</externalDeveloperName>
        <label>Number Sequence history</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>txt_cmt__c</fullName>
        <description>txt_cmt</description>
        <externalDeveloperName>txt_cmt</externalDeveloperName>
        <label>Note Text</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>txt_subj__c</fullName>
        <description>txt_subj</description>
        <externalDeveloperName>txt_subj</externalDeveloperName>
        <label>Subject</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Case Comment</label>
    <pluralLabel>Case Comment</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Exception_Log__c.object
<CustomObject>
    <description>The object stores all the exceptions that were catched through out the applications for debugging and reporting purpose.</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Stores the message that was returned from the exception generated.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_INDIV_VERIF__c.object
<CustomObject>
    <description>Individual verification tracking</description>
    <fields>
        <fullName>CDE_TYPE_INFO_INDIV__c</fullName>
        <description>Type of Individual Information</description>
        <label>Type of Individual Information</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00366</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Verified</description>
        <label>Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual Information ID</label>
        <referenceTo>T_SBSD_INDIV_INFO__c</referenceTo>
        <relationshipLabel>Individual Verification</relationshipLabel>
        <relationshipName>Individual_Verification</relationshipName>
        <type>Lookup</type> 
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Individual Verification</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Individual Verification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Date Person Entered Home</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <fields>
        <fullName>NAM_FIRST__c</fullName>
        <description>First Name</description>
        <label>First Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_LAST__c</fullName>
        <description>Last Name</description>
        <label>Last Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_INFO__c.object
<CustomObject>
    <description>Information codes about individual</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>Parent_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Legacy Individual Citizenship Information</description>
        <label>Legacy Individual Citizenship Info</label>
        <referenceTo>T_SBSD_INDIV_INFO__c</referenceTo>
        <relationshipLabel>Individual_Information</relationshipLabel>
        <relationshipName>Individual_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_INFO_INDIV__c</fullName>
        <description>Type of Individual Information</description>
        <label>Individual Information Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00366</valueSetName>
        </valueSet>
    </fields> 
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Individual_Information</relationshipLabel>
        <relationshipName>Individual_Information</relationshipName>
        <type>Lookup</type>
    </fields>    
    <fields>
        <fullName>CDE_VALUE_INFO_INDIV__c</fullName>
        <label>Individual Information Value</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CDE_TYPE_INFO_INDIV__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>R00847</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Individual Information (Individual)</relationshipLabel>
        <relationshipName>Individual_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Individual Information</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Individual Information ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00366.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CS</fullName>
        <label>citizenship status</label>
    </customValue>
    <customValue>
        <fullName>HDS</fullName>
        <label>head start</label>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
        <label>marital status</label>
    </customValue>
    <customValue>
        <fullName>FST</fullName>
        <label>foster care</label>
    </customValue>
    <customValue>
        <fullName>IMM</fullName>
        <isActive>false</isActive>
        <label>age appropriate immunization</label>
    </customValue>
    <description>R00366</description>
    <masterLabel>R00366</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00367.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Available</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <label>Verbal Verification</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Written Verification</label>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
        <isActive>false</isActive>
        <label>CV</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
        <isActive>false</isActive>
        <label>N/A-adult caretaker</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <isActive>false</isActive>
        <label>SV</label>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
        <isActive>false</isActive>
        <label>N/A-not requesting child</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>R00367</description>
    <masterLabel>R00367</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00847.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3</fullName>
        <label>Common Law Relationship</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Divorced</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Married - Living w/ Spouse</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Married - Not living with Spouse (Involuntarily)</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Married - Not living with Spouse (Voluntarily)</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Significant Other</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Single - Never Married</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Widow/Widower</label>
    </customValue>
    <customValue>
        <fullName>CZN</fullName>
        <label>Citizen</label>
    </customValue>
    <customValue>
        <fullName>NCZ</fullName>
        <label>Non-Citizen</label>
    </customValue>
    <customValue>
        <fullName>LFR</fullName>
        <label>Qualified Alien</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <masterLabel>R00847</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CitizenshipDatafixBatch.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           5/24/2022                                                         
*  @description    Adjustment batch class for datafix                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 24-Jan-2024                                                            
*  * Author: Diya Chaudhary                                                      
*  * Description: Initial version                   
*********************************************************************************************/
global with sharing class CitizenshipDatafixBatch implements 
Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    public Set<Id> caseIds = new Set<Id>();
    public Set<String> providerCountySet = new Set<String>();
    public Exception_Log__c[] errors = new Exception_Log__c[0];
    public List<batchsit_t_sbsd_case_cmt__x> caseCommentList = new List<batchsit_t_sbsd_case_cmt__x>();
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Date todayDate = system.today(); // this is referred in below dynamic query
        List<String> clientIds = new List<String>();
        clientIds = system.Label.CitizenshipIndivIds.split(';');
        String status ='CS';
        String queryStr ;
        if(Test.isRunningTest()){
            queryStr ='select id,createdDate,IDN_CASE__c,IDN_CLIENT__r.name,IDN_CLIENT__r.NAM_FIRST__c,IDN_CLIENT__r.NAM_LAST__c,IDN_CLIENT__c,DTE_BEGIN_EFFV__c,DTE_END_EFFV__c,CDE_TYPE_INFO_INDIV__c,CDE_VALUE_INFO_INDIV__c from T_SBSD_INDIV_INFO__c where CDE_TYPE_INFO_INDIV__c=:status';
            
        }else{
            queryStr ='select id,createdDate,IDN_CASE__c,IDN_CLIENT__r.name,IDN_CLIENT__r.NAM_FIRST__c,IDN_CLIENT__r.NAM_LAST__c,IDN_CLIENT__c,DTE_BEGIN_EFFV__c,DTE_END_EFFV__c,CDE_TYPE_INFO_INDIV__c,CDE_VALUE_INFO_INDIV__c from T_SBSD_INDIV_INFO__c where CDE_TYPE_INFO_INDIV__c=:status and IDN_CLIENT__r.name=:clientIds and IDN_CASE__c!= null';
            
        }        system.debug('queryStr--'+queryStr);
        return Database.getQueryLocator(queryStr);
    }
    global void execute(Database.BatchableContext bc, List<T_SBSD_INDIV_INFO__c> indivInfoList){
        try{
            Map<String,T_SBSD_INDIV_INFO__c> indivInfoMap = new Map<String,T_SBSD_INDIV_INFO__c>();
            Map<String,List<String>> indivCaseMap = new Map<String,List<String>>();
            Set<String> indivIds = new Set<String>();
            Map<String,String> caseMap= new Map<String,String>();
            Map<String,String> caseExternalIdMap= new Map<String,String>();
            List<T_SBSD_INDIV_INFO__c> indivInfoToBeInserted= new List<T_SBSD_INDIV_INFO__c>();
            List<T_INDIV_VERIF__c> indivInfoVerifToBeInserted= new List<T_INDIV_VERIF__c>();
            Map<string,T_INDIV_VERIF__c> indivInfoVerif = new Map<string,T_INDIV_VERIF__c>();
            List<T_SBSD_INDIV_INFO__c> indivInfoToBeDatafixed= new List<T_SBSD_INDIV_INFO__c>();
            Set<String> infoInfoIds = new Set<String>();
            for(T_SBSD_INDIV_INFO__c indivInfo :indivInfoList){
                indivIds.add(indivInfo.IDN_CLIENT__c);
                indivInfoMap.put(indivInfo.IDN_CLIENT__c,indivInfo);
                
            }
            system.debug('indivIds--'+indivIds);
            system.debug('indivInfoMap--'+indivInfoMap);
            
            for(T_SBSD_CASE_INDIV__c caseIndiv :[Select id,IDN_CASE__c,IDN_CASE__r.name,IDN_CASE__r.IDN_EXTNL__c,IDN_CLIENT__c from T_SBSD_CASE_INDIV__c where IDN_CLIENT__c in :indivIds ]){
               caseMap.put(caseIndiv.IDN_CASE__c,caseIndiv.IDN_CASE__r.name);
                caseExternalIdMap.put(caseIndiv.IDN_CASE__c,caseIndiv.IDN_CASE__r.IDN_EXTNL__c);
                if(indivCaseMap.containskey(caseIndiv.IDN_CLIENT__c)){
                    List<String> caseids = indivCaseMap.get(caseIndiv.IDN_CLIENT__c);
                    caseids.add(caseIndiv.IDN_CASE__c);
                    indivCaseMap.put(caseIndiv.IDN_CLIENT__c,caseids);
                }else{
                    indivCaseMap.put(caseIndiv.IDN_CLIENT__c,new List<String>{caseIndiv.IDN_CASE__c});
                }
                
            }
            system.debug('indivCaseMap--'+indivCaseMap);
            for(String indiv:indivCaseMap.keySet()){
                for(String caseId:indivCaseMap.get(indiv)){
                    if(indivInfoMap.get(indiv) != null){
                        T_SBSD_INDIV_INFO__c indivInfo = indivInfoMap.get(indiv);
                        if(indivInfo.IDN_CASE__c !=caseId){
                            T_SBSD_INDIV_INFO__c indivInfoCloneCopy  = indivInfo.clone(false, false, false, false);
                            indivInfoCloneCopy.Parent_Record__c =indivInfo.Id;
                            indivInfoCloneCopy.IDN_CASE__c =caseId;
                            caseIds.add(caseId);
                            indivInfoToBeInserted.add(indivInfoCloneCopy);
                            batchsit_t_sbsd_case_cmt__x cmtObj = new batchsit_t_sbsd_case_cmt__x();
                            cmtObj.createdbyid__c =UserInfo.getUserId();
                            cmtObj.cde_type_cmt__c='System-Generated';
                            cmtObj.cde_type_note_cmt__c ='General';
                            cmtObj.createddate__c = System.now();
                            cmtObj.idn_case__c=caseExternalIdMap.get(caseId);
                            cmtObj.lastmodifiedbyid__c=UserInfo.getUserId();
                            cmtObj.lastmodifieddate__c= System.now();
                            cmtObj.txt_cmt__c='A data fix was performed on this case and individual '+ caseMap.get(caseId) +' AND '+ indivInfo.IDN_CLIENT__r.name+' on 02/01/2024 to properly associate the case and county with their Citizenship Verification Record. As needed, view the history record associated with Individual Information Record '+'('+ URL.getOrgDomainUrl().toExternalForm() +'/lightning/r/T_SBSD_INDIV_INFO__c/'+indivInfo.Id +'/view )'+' to view all of the citizenship verification associated with this individual.';
                            cmtObj.txt_subj__c='Citizenship Datafix';
                           // cmtObj.nbr_seq_hist__c=0;
                            caseCommentList.add(cmtObj);
                        }
                        
                    }
                    
                }
            }
            
            /*  for(T_SBSD_INDIV_INFO__c indivInfo :[select id,Parent_Record__c,createdDate,IDN_CASE__c,IDN_CLIENT__c,DTE_BEGIN_EFFV__c,DTE_END_EFFV__c,CDE_TYPE_INFO_INDIV__c,CDE_VALUE_INFO_INDIV__c from T_SBSD_INDIV_INFO__c
where CDE_TYPE_INFO_INDIV__c='CS' and createdDate = today and createdById='0052M00000AqYDJQA3']){

infoInfoIds.add(indivInfo.id);
indivInfoToBeDatafixed.add(indivInfo);
}*/
            system.debug('indivInfoToBeInserted--'+indivInfoToBeInserted.size());
            system.debug('indivInfoToBeInserted--'+indivInfoToBeInserted);
            List<Database.SaveResult> lstSaveResult = new List<Database.SaveResult>();
            lstSaveResult.addAll(Database.insert(indivInfoToBeInserted, false));
            for(T_INDIV_VERIF__c verif :[Select id,CDE_TYPE_VERIF__c,IDN_CLIENT__c,CDE_TYPE_INFO_INDIV__c from T_INDIV_VERIF__c where IDN_CLIENT__c in:indivInfoList  ]){
                indivInfoVerif.put(verif.IDN_CLIENT__c,verif);
            }
            for(T_SBSD_INDIV_INFO__c indivInfo:indivInfoToBeInserted){
                system.debug('indivInfo---'+indivInfo);
                
                if(indivInfoVerif.get(indivInfo.Parent_Record__c) != null){
                    T_INDIV_VERIF__c indivInfoVerifObj = indivInfoVerif.get(indivInfo.Parent_Record__c);
                    T_INDIV_VERIF__c indivInfoCloneCopy  = indivInfoVerifObj.clone(false, false, false, false);
                    indivInfoCloneCopy.IDN_CLIENT__c =indivInfo.id;
                    indivInfoVerifToBeInserted.add(indivInfoCloneCopy);
                }
                
            }
            if(indivInfoVerifToBeInserted != null && indivInfoVerifToBeInserted.size()>0){
                database.insert(indivInfoVerifToBeInserted);
            }
            
        }
        catch(Exception e) {
            Exception_Log__c xLog = new Exception_Log__c();
            xLog.Class__c = 'CitizenshipDatafixBatch';
            xLog.Method__c = 'executeMethod';
            xLog.Exception_Message__c = 'CitizenshipDatafixBatch  for citizenship'+e.getMessage();
            xLog.Exception_Type__c = 'Error';
            errors.add(xLog);
        }
    }    
    global void finish(Database.BatchableContext bc){
        
        if(caseCommentList!= null && caseCommentList.size()>0){
            system.debug('caseCommentList--'+caseCommentList);
            //GenericDataSaverApxCtrl.insertExternalObjRecords(caseCommentList, TRUE);
            Database.insertAsync(caseCommentList);
        }
        
    }   
}