CHATS_SIT/force-app/main/default/objects/batchsit_t_auth_status__x.object
<CustomObject>
    
    <description>batchsit$t_auth_status</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_auth_status</externalName>
    <label>Authorization Status</label>
    <pluralLabel>Authorization Status</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>DTE_APPLN__c</fullName>
        <description>Date Application Received</description>
        <label>Date Application Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/classes/AssessParentFeeControllerTest.cls
@isTest
global class AssessParentFeeControllerTest {
    
    testMethod static void testGetAuthCopayRecords() {
        
        T_COUNTY__c countyObj = TestClassUtility.createCounty('countyName', 'countyDepartmentName',10,true);
        T_CHATS_PROVR_STATUS__c providerObj = TestClassUtility.createProvider(true, 'Test');
        batchsit_t_auth_status__x authStatus ;
        //Removed unused variable on 5/13/2018 BG         
        T_SBSD_CASE__c caseRec = TestClassUtility.createCase(false, countyObj.Id);
        caseRec.DTE_APPLN__c = System.today().addDays(-10);
        caseRec.IDN_EXTNL__c = '4444';
        insert caseRec;
        T_AUTH__c authObj = TestClassUtility.createAuthorization(false, null, System.today().addDays(-8), countyObj.Id, providerObj.Id);
        authObj.IDN_CASE__c = caseRec.Id;
        authObj.IDN_EXTNL__c='123';
        insert authObj;
        T_AUTH__c authObj2 = TestClassUtility.createAuthorization(false, null, System.today().addDays(-8), countyObj.Id, providerObj.Id);
        authObj2.IDN_CASE__c = caseRec.Id;
        authObj.IDN_EXTNL__c='456';
        insert authObj2;
        
        //Removed unused variable on 5/13/2018 BG  
        AuthorizationStatusController.upsertAuthStatus(authStatus,true,false,authObj.Id,true);
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        //Removed unused variable on 5/13/2018 BG         
        Test.startTest();
        List<ParentFeeAssessmentWrapper> wrapList = AssessParentFeeController.getAuthCopayRecords('4444');
        System.assertEquals(wrapList[0].IDN_AUTH, '123');
        Test.stopTest();
    }
    
    global class MockHttpResponseGenerator implements HttpCalloutMock {
        // Implement this interface method
        global HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint
            // and method.
            System.assertEquals(Label.AuthCopayFetch, req.getEndpoint());
            System.assertEquals('POST', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json;charset=UTF-8');
            //res.setBody('{"example":"test"}');
            res.setBody('[{"authCopayId":"1891","authCopayDteBeginEffectv":"null","indivNamFirst":"Ganesh","indivNamLast":"Hegde","authCopayAuthId":"123","cdeAuthStatus":"2","authProvrId":"a1jg00000028GDgAAM","namFacility":"Govinda Trust and company","provrNamLast":null,"provrNamFirst":null,"indivDOB":"2001-12-19","amtCopayAuth":"40.0","errorMsg":null},{"authCopayId":"1891","authCopayDteBeginEffectv":"9-9-1999","indivNamFirst":"Ganesh","indivNamLast":"Hegde","authCopayAuthId":"4444","cdeAuthStatus":"2","authProvrId":"a1jg00000028GDgAAM","namFacility":null,"provrNamLast":"Some","provrNamFirst":"Name","indivDOB":"2001-12-19","amtCopayAuth":"40.0","errorMsg":null},{"authCopayId":"40","authCopayDteBeginEffectv":"null","indivNamFirst":"Sachin","indivNamLast":"Tendukar","authCopayAuthId":"8888","cdeAuthStatus":"4","authProvrId":"a1jg00000028GjrAAE","namFacility":"Being Human Trust","provrNamLast":null,"provrNamFirst":null,"indivDOB":"2001-12-19","amtCopayAuth":"122.89","errorMsg":null}]');
            res.setStatusCode(202);
            res.setStatus('Accepted');
            return res;
        }
    }
}