CHATS_SIT/force-app/main/default/objects/Batch_Log__c.object
<CustomObject>
    <description>Object to maintain batch Logs</description>
    <fields>
        <fullName>Batch_Name__c</fullName>
        <label>Batch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Error Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Records_Failed__c</fullName>
        <label>Records_Failed</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_Processed__c</fullName>
        <label>Records Processed</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>end_time__c</fullName>
        <label>end time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>start_time__c</fullName>
        <label>start time</label>
        <type>DateTime</type>
    </fields>
    <label>Batch Log</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Batch Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Exception_Log__c.object
<CustomObject>
    <description>The object stores all the exceptions that were catched through out the applications for debugging and reporting purpose.</description>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Stores the message that was returned from the exception generated.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/FailLogBatch.cls
global with sharing class FailLogBatch implements Database.Batchable<sObject> {
    global List<SObject> start(Database.BatchableContext bc) {
        //List<Batch_Log__c> salesforceBatchLogList = new List<Batch_Log__c>();
        List<SObject> herokuLogList = new List<SObject>();
        DateTime utTime = System.now();
        TimeZone tz = UserInfo.getTimeZone();
        DateTime currTime = utTime.addSeconds((tz.getOffset(utTime)/1000));
        DateTime last24Hrs = currTime.addHours(-12);
        String tableName = Label.herokuBatchLogTableName; 
        //String externalObjectName = Label.
        try{

            
            String failedBatchLogQuery = 'SELECT Id, idn_batch_log__c, createdDate__c, Batch_Name__c, Records_Processed__c , Records_Failed__c,Status__c, Error_Message__c, batch_run_date__c, start_time__c, end_time__c ';
            failedBatchLogQuery += 'FROM ' + tableName;
            failedBatchLogQuery += ' WHERE createdDate__c >= :last24Hrs AND Status__c = \'FAILED\' Order by createdDate__c DESC';

            herokuLogList = Database.query(failedBatchLogQuery);
            // for(sObject extObj : herokuLogList){
            //     Batch_Log__c singleObj = new Batch_Log__c();
            //     singleObj.IDN_EXTNL__c = (String)extObj.get('idn_extnl__c');
            //     singleObj.Batch_Name__c = (String)extObj.get('batch_name__c');
            //     singleObj.Status__c = (String)extObj.get('status__c');
            //     singleObj.Records_Processed__c = (Decimal)extObj.get('records_processed__c');
            //     singleObj.Error_Message__c = (String)extObj.get('error_message__c');
            //     Datetime batchRunDatetime = (Datetime)extObj.get('batch_run_date__c');
            //     singleObj.Date__c = Date.newinstance(batchRunDatetime.year(), batchRunDatetime.month(), batchRunDatetime.day());
            //     singleObj.start_time__c = (DateTime)extObj.get('start_time__c');
            //     singleObj.end_time__c = (DateTime)extObj.get('end_time__c');
            //     salesforceBatchLogList.add(singleObj);
                
            // }
        }catch(Exception e){
            Exception_Log__c errorLog = new Exception_Log__c();
            errorLog.Exception_Message__c = 'ERROR IN FailLogBatch:' + e.getMessage();
            List<Exception_Log__c> errorList = new List<Exception_Log__c>();
            errorList.add(errorLog);
            GenericDMLHandler.insertRecords(errorList, null);
        }
        return herokuLogList;
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope){
        Map<String, List<SObject>> failedBatchLogMapByName = new Map<String, List<SObject>>();
        for(SObject blObj : scope){
            if(failedBatchLogMapByName.get((String)blObj.get('batch_name__c')) == null ){
                List<SObject> logList = new List<SObject>();
                logList.add(blObj);
                failedBatchLogMapByName.put((String)blObj.get('batch_name__c'), logList);
            }
            else{
                List<SObject> existingLogList = failedBatchLogMapByName.get((String)blObj.get('batch_name__c'));
                existingLogList.add(blObj);
                failedBatchLogMapByName.put((String)blObj.get('batch_name__c'), existingLogList);
            }
        }

        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        for(String keyString : failedBatchLogMapByName.keyset()){
            List<SObject> logsByName = failedBatchLogMapByName.get(keyString);

            FailLogEmailHelper helperObject = new FailLogEmailHelper(logsByName,keyString);
            emailList.add(helperObject.createEmails(Label.chats24hrSupportEmail));
        }
        Messaging.sendEmail(emailList);

    }

    global void finish(Database.BatchableContext BC){
    }

}