CHATS_SIT/force-app/main/default/objects/batchsit_t_eligty_run__x.object
<CustomObject>
    <description>batchsit$t_eligty_run</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_eligty_run</externalName>
    <label>Eligibility Run</label>
    <pluralLabel>Eligibility Run</pluralLabel> 
</CustomObject>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fcompsn_eligty__x.object
<CustomObject>
    <description>batchsit$t_fcompsn_eligty</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_fcompsn_eligty</externalName>
    <label>Household Eligibility</label>
    <pluralLabel>Household Eligibility</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fcompsn_indiv_eligty__x.object
<CustomObject>
    <description>batchsit$t_fcompsn_indiv_eligty</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_fcompsn_indiv_eligty</externalName>
    <label>Individual Eligibility</label>
    <pluralLabel>Individual Eligibility</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/classes/CaseHeaderApxCtrl_Test.cls
/*
*/
@isTest
public class CaseHeaderApxCtrl_Test {
    
     public static testMethod void testGetInitData(){
        List<T_SBSD_CASE__c> caseRecords = [SELECT id FROM T_SBSD_CASE__c limit 100];
        System.assertEquals(false, caseRecords.isEmpty(),'caseRecords should not be empty');
        LightningServerResponse lsr = CaseHeaderApxCtrl.getInitData(caseRecords.get(0).Id);
        System.assertEquals(true, lsr.isSuccessful, 'lsr.isSucessful should be true');
        System.assertEquals(true, lsr.objectData.containsKey('caseRecord'), 'lsr.objectData should contain caseRecord as key');
         
        CaseHeaderApxCtrl.getInitData('Junk');
    }
    
    public static testMethod void testGetCaseId(){
        LightningServerResponse  lr=  CaseHeaderApxCtrl.getCaseId(null, null);
        System.assertEquals(null, lr, 'r.caseExtId should be null');
       // T_SBSD_CASE__c cases= new T_SBSD_CASE__c(idn_extnl__c='12345');
         LightningServerResponse  lr1=  CaseHeaderApxCtrl.getCaseId('2', 'batchsit_t_fcompsn_eligty__x');
         LightningServerResponse  lr2=  CaseHeaderApxCtrl.getCaseId('2', 'batchsit_t_eligty_run__x');
         LightningServerResponse  lr3=  CaseHeaderApxCtrl.getCaseId('2', 'batchsit_t_fcompsn_indiv_eligty__x');
         
        
            
            }    
    
    @testSetup
    public static void setUpData(){
        User user;
        Profile userProfile=[Select id from Profile where Name ='System Administrator'];
        user = TestClassUtility.createUser(userProfile.Id , 'test','test','test@example.com','test@example.com.'+string.valueof(math.random()*3),'ttes');
        
        if(user!=null){
            insert user; 
        }
            
        System.runAs(user){
            T_COUNTY__c countyRec = TestClassUtility.createCounty('Denver','Denver',1,true);
            TestClassUtility.createCase(true,countyRec.Id);
            TestClassUtility.createIndividual(false,System.today().addYears(-15), 'firstName','1', 'lastName','123456789','CI');

        }
    }
}