CHATS_SIT/force-app/main/default/objects/batchsit_t_eligty_run__x.object
<CustomObject>
    <description>batchsit$t_eligty_run</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_eligty_run</externalName>
    <fields>
        <fullName>cde_date_redet_ovrd__c</fullName>
        <description>cde_date_redet_ovrd</description>
        <externalDeveloperName>cde_date_redet_ovrd</externalDeveloperName>
        <label>Determined Redetermination Date Reason</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cde_eligty_cfmd__c</fullName>
        <description>cde_eligty_cfmd</description>
        <externalDeveloperName>cde_eligty_cfmd</externalDeveloperName>
        <label>Eligibility Confirmed Status</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>createddate__c</fullName>
        <description>createddate</description>
        <externalDeveloperName>createddate</externalDeveloperName>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dte_redet_ovrd__c</fullName>
        <description>dte_redet_ovrd</description>
        <externalDeveloperName>dte_redet_ovrd</externalDeveloperName>
        <label>Determined Redetermination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dte_redet_prpsd__c</fullName>
        <description>dte_redet_prpsd</description>
        <externalDeveloperName>dte_redet_prpsd</externalDeveloperName>
        <label>System Determined Redetermination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dte_run_eligty__c</fullName>
        <description>dte_run_eligty</description>
        <externalDeveloperName>dte_run_eligty</externalDeveloperName>
        <label>Run Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>idn_case__c</fullName>
        <description>idn_case</description>
        <externalDeveloperName>idn_case</externalDeveloperName>
        <label>Case ID</label>
        <length>50</length>
        <referenceTargetField>T_SBSD_CASE__c.IDN_EXTNL__c</referenceTargetField>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Eligibility Run</relationshipLabel>
        <relationshipName>batchsit_t_eligty_run</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <fields>
        <fullName>idn_run_eligty__c</fullName>
        <description>idn_run_eligty</description>
        <externalDeveloperName>idn_run_eligty</externalDeveloperName>
        <label>Eligibility Run ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>txt_cmt_ovrd__c</fullName>
        <description>txt_cmt_ovrd</description>
        <externalDeveloperName>txt_cmt_ovrd</externalDeveloperName>
        <label>Determined Redetermination Date Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dte_appln_old__c</fullName>
        <externalDeveloperName>dte_appln_old</externalDeveloperName>
        <label>Previous Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dte_appln_new__c</fullName>
        <externalDeveloperName>dte_appln_new</externalDeveloperName>
        <label>Application Override Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>rsn_appln_dte_override__c</fullName>
        <label>Application Date Override Reason</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cmt_appln_dte_override__c</fullName>
        <label>Application Date Override Comments</label>
        <type>TextArea</type>
    </fields>
    <label>Eligibility Run</label>
    <pluralLabel>Eligibility Run</pluralLabel> 
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00373</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IND_CHGD_DATA_ELIGTY__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Eligibility Data Changed</description>
        <label>Eligibility Data Changed</label>
        <type>Checkbox</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00373.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CW</fullName>
        <label>Child Welfare Child Care</label>
    </customValue>
    <customValue>
        <fullName>FT</fullName>
        <label>Transitional TANF</label>
    </customValue>
    <customValue>
        <fullName>LI</fullName>
        <label>Low Income Child Care</label>
    </customValue>
    <customValue>
        <fullName>TF</fullName>
        <label>TANF</label>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
        <isActive>false</isActive>
        <label>Employment First</label>
    </customValue>
    <description>R00373</description>
    <masterLabel>R00373</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/EligRunApxCtrl.cls
public With Sharing class EligRunApxCtrl {
    @AuraEnabled
    public static LightningServerResponse getInitData(String elgRunId, batchsit_t_eligty_run__x eligibilityRec){
        Map<String, Object> objectData = new map<String, Object>(); 
        Boolean isSuccessful;
        String message;
        List<batchsit_t_eligty_run__x> eligRunRecord;
        if(Test.isRunningTest()){
            isSuccessful = true;
            List<T_SBSD_CASE__c> cases = [SELECT IDN_EXTNL__c FROM T_SBSD_CASE__c];
            objectData.put('eligRunRecord',new List<SObject>{new batchsit_t_eligty_run__x(idn_case__c = cases.get(0).IDN_EXTNL__c,idn_run_eligty__c=15)});
        }else{
            eligRunRecord = [SELECT Id, dte_run_eligty__c, idn_case__c,idn_case__r.Id, idn_case__r.Name, idn_case__r.IND_CHGD_DATA_ELIGTY__c, idn_run_eligty__c, 
                             cde_eligty_cfmd__c, dte_redet_prpsd__c, dte_redet_ovrd__c, 
                             cde_date_redet_ovrd__c, txt_cmt_ovrd__c, createddate__c, dte_appln_old__c, dte_appln_new__c, rsn_appln_dte_override__c, cmt_appln_dte_override__c
                             FROM batchsit_t_eligty_run__x
                             WHERE Id =: elgRunId];
            
            
            if(String.isNotBlank(eligRunRecord[0].idn_case__r.Id)){
                T_SBSD_CASE__c caseRec = [SELECT Id, Program_Type__c FROM T_SBSD_CASE__c WHERE Id=:eligRunRecord[0].idn_case__r.Id LIMIT 1];
                String pgmType = caseRec.Program_Type__c != null ? caseRec.Program_Type__c : CaseHeaderApxCtrl.getChildCareProgram(eligRunRecord[0].idn_case__r.Id);
                objectData.put('childCareProgram', pgmType);
            }
            if(!eligRunRecord.isEmpty()){
                objectData.put('eligRunRecord',eligRunRecord);
                isSuccessful=true;
            }
            else{
                isSuccessful=false;
                message = Label.eligRecord_Not_Found;
            }
        }
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
}