CHATS_SIT/force-app/main/default/objects/batchsit_t_auth_encmbr__x.object
<CustomObject>
    <description>batchsit$t_auth_encmbr</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_auth_encmbr</externalName>
    <fields>
        <fullName>cde_status_encmbr__c</fullName>
        <description>cde_status_encmbr</description>
        <externalDeveloperName>cde_status_encmbr</externalDeveloperName>
        <label>Encumbrance Status</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cde_type_unit_care__c</fullName>
        <description>cde_type_unit_care</description>
        <externalDeveloperName>cde_type_unit_care</externalDeveloperName>
        <label>Rate Type</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cnt_hour_attnd_actual__c</fullName>
        <description>cnt_hour_attnd_actual</description>
        <externalDeveloperName>cnt_hour_attnd_actual</externalDeveloperName>
        <label>Actual Attended Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cnt_hour_care__c</fullName>
        <description>cnt_hour_care</description>
        <externalDeveloperName>cnt_hour_care</externalDeveloperName>
        <label>Authorized Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dte_care__c</fullName>
        <description>dte_care</description>
        <externalDeveloperName>dte_care</externalDeveloperName>
        <label>Date of Care</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>idn_auth__c</fullName>
        <description>idn_auth</description>
        <externalDeveloperName>idn_auth</externalDeveloperName>
        <label>Authorization ID</label>
        <length>50</length>
        <referenceTargetField>T_AUTH__c.IDN_EXTNL__c</referenceTargetField>
        <referenceTo>T_AUTH__c</referenceTo>
        <relationshipLabel>Authorization Encumbrance</relationshipLabel>
        <relationshipName>batchsit_t_auth_encmbr</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <fields>
        <fullName>ind_0_36_months__c</fullName>
        <description>ind_0_36_months</description>
        <externalDeveloperName>ind_0_36_months</externalDeveloperName>
        <label>0-36 Months</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Authorization Encumbrance</label>
    <pluralLabel>Authorization Encumbrance</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/batchsit_t_sbsd_indiv_care_level__x.object
<CustomObject>
    <description>batchsit$t_sbsd_indiv_care_level</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_sbsd_indiv_care_level</externalName>
    <fields>
        <fullName>idn_client__c</fullName>
        <description>idn_client</description>
        <externalDeveloperName>idn_client</externalDeveloperName>
        <label>Client ID</label>
        <length>50</length>
        <referenceTargetField>T_SBSD_INDIV__c.IDN_EXTNL__c</referenceTargetField>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Care Level</relationshipLabel>
        <relationshipName>batchsit_t_sbsd_indiv_care_level</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <label>Care Level</label>
    <pluralLabel>Care Level</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Field_Utility__c.object
<CustomObject>

    <fields>
        <fullName>R00690__c</fullName>
        <label>R00690</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00690</valueSetName>
        </valueSet>
    </fields>
    <label>Field Utility</label>
    <nameField>
        <label>Picklist Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>Protective_Services_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Protective Services Indicator</label>
        <type>Checkbox</type>
    </fields> 
    <fields>
        <fullName>DTE_BEGIN_EFFV_AUTH__c</fullName>
        <description>Authorization Begin Date</description>
        <label>Authorization Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_AUTH__c</fullName>
        <label>Authorization End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_TYPE_PROVR__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00691</valueSetName>
        </valueSet>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_SCH__c.object
<CustomObject>
    <fields>
        <fullName>CDE_RATE_TYPE__c</fullName>
        <description>Rate Type</description>
        <label>Rate Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00751</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Rate Schedule ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rate Schedules</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>DTE_DOB__c</fullName>
        <description>DOB</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00690.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Authorized</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Attended</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Paid</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Care Not Offered</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <isActive>false</isActive>
        <label>6</label>
    </customValue>
    <description>R00690</description>
    <masterLabel>R00690</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/AuthEncumbRelatedListController.cls
public with sharing class AuthEncumbRelatedListController implements IRequest{

    public static String EXEMPT = System.Label.Exempt_Provider_Type;
    public String jsonParam;
    private static Map<String, Object> requestObj;

    public Object processRequest(String methodName, String jsonParam) {
        Object response = null;
        this.jsonParam = jsonParam;
        if(this.jsonParam != null){
            requestObj = (Map<String, Object>)JSON.deserializeUntyped(jsonParam);  
        }

        if (methodName == 'fetchRelatedObjectdata') {
            response = fetchRelatedObjectdata(getMapValue('recordId'));
        } else if (methodName == 'fetchRelatedArchivedObjectdata') {
            response = fetchRelatedArchivedObjectdata(getMapValue('recordId'), getMapValue('monthStr'), getMapValue('yearStr'));
        } else if (methodName == 'getAuthEncumbRecordId') {
            String recordId = getAuthEncumbRecordId(getMapValue('externalId'));
            response = new LightningServerResponse(true, 'Success', new Map<String, object>{'recordId' => recordId});
        } 
        return response;
    }

    private static String getMapValue(String fieldName){
        return (String)requestObj.get(fieldName);
    }

    @AuraEnabled
    public static String getAuthEncumbRecordId(String externalId){
        String recordId;
       if(String.isNotBlank(externalId)){
            List<batchsit_t_auth_encmbr__x> encumbList = [Select id ,ExternalId from batchsit_t_auth_encmbr__x where ExternalId =:externalId WITH SECURITY_ENFORCED];
            if(encumbList != null && encumbList.size()>0){
                recordId =encumbList[0].id;
            }
        }
        return recordId;
    }

    @AuraEnabled
    public static LightningServerResponse fetchRelatedObjectdata(String recordId){
        Map<String, Object> objectData = new map<String, Object>();
        Map<String, String> rateTypeMap = new Map<String, String>();
        Map<String, String> statusMap = new Map<String, String>();
        Boolean isSuccessful = true;
        String message;
        String isErrorWebservice = '';
        Boolean attendedFlg;
        List<batchsit_t_auth_encmbr__x> fetchedEncumberence = new List<batchsit_t_auth_encmbr__x>();
        List<authEncumbranceRelatedListWrap> authEncumbranceRelatedList = new List<authEncumbranceRelatedListWrap>();
        List<batchsit_t_sbsd_indiv_care_level__x> careLevels = new List<batchsit_t_sbsd_indiv_care_level__x>();
        Map<String, batchsit_t_auth_encmbr__x> careDateToAuthEncmbr2 = new Map<String, batchsit_t_auth_encmbr__x>();
        try {
            T_AUTH__c authRec = [SELECT IDN_EXTNL__c,DTE_BEGIN_EFFV_AUTH__c, DTE_END_EFFV_AUTH__c, IDN_CLIENT__c, IDN_CLIENT__r.DTE_DOB__c,
                                 IDN_PROVR__r.CDE_TYPE_PROVR__c, IDN_CASE__c, Protective_Services_Indicator__c
                                 FROM T_AUTH__c where id =:recordId WITH SECURITY_ENFORCED];
            Schema.DescribeFieldResult fieldResult = T_FISCAL_SCH__c.CDE_RATE_TYPE__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for(Schema.PicklistEntry f : ple){
                rateTypeMap.put(f.getValue(), f.getLabel());
            }  
            Schema.DescribeFieldResult fieldResult1 = Field_Utility__c.R00690__c.getDescribe();
            List<Schema.PicklistEntry> ple1 = fieldResult1.getPicklistValues();
            for(Schema.PicklistEntry f : ple1){
                statusMap.put(f.getValue(), f.getLabel());
            }
            if(authRec != null){
                if(!Test.isRunningTest()){
                    fetchedEncumberence = HerokuService.authEncumbrancefetch(authRec.IDN_EXTNL__c);
                } else {
                    fetchedEncumberence.add(new batchsit_t_auth_encmbr__x(dte_care__c =(system.today()).addDays(1),idn_auth__c ='Test123',cde_status_encmbr__c='2',cnt_hour_care__c=12,cde_type_unit_care__c='Reg',ExternalId='Test123',ind_0_36_months__c='Y'));
                    fetchedEncumberence.add(new batchsit_t_auth_encmbr__x(dte_care__c =(system.today()).addDays(1),idn_auth__c ='Test123',cde_status_encmbr__c='2',cnt_hour_care__c=12,cde_type_unit_care__c='Reg',ExternalId='Test234',ind_0_36_months__c='N'));
                }
                for(batchsit_t_auth_encmbr__x anAuthEncmbr: fetchedEncumberence){
                    authEncumbranceRelatedListWrap encumb = new authEncumbranceRelatedListWrap();
                    encumb.ExternalId = anAuthEncmbr.ExternalId;
                    encumb.encumbId = anAuthEncmbr.ExternalId;
                    encumb.status = statusMap.get(String.valueOf(anAuthEncmbr.cde_status_encmbr__c));
                    encumb.rateType = rateTypeMap.get(String.valueOf(anAuthEncmbr.cde_type_unit_care__c)) ;
                    encumb.dateOfCare = anAuthEncmbr.dte_care__c;
                    encumb.actualAttendedHours = anAuthEncmbr.cnt_hour_attnd_actual__c;
                    encumb.authorizedHours = anAuthEncmbr.cnt_Hour_Care__c;
                    encumb.attendedFlag = HerokuService.globalAttended.get(encumb.ExternalId);
                    encumb.ind0to36months = anAuthEncmbr.ind_0_36_months__c == 'Y' ? true : false; //added for CCCAP-14174
                    authEncumbranceRelatedList.add(encumb);
                }
                // objectData.put('fetchedEncumberence',fetchedEncumberence);
            }
        } catch(Exception ex) {
            String message1 = ex.getMessage();
            if(fetchedEncumberence == null || fetchedEncumberence.size() <=0){
                message1 = 'Problem in connecting with external system.';
            }
            return new LightningServerResponse(false, message1, null);
        }
        return new LightningServerResponse(isSuccessful,'Validation check',new Map<String, object>{'authEncumbranceRelatedList' => authEncumbranceRelatedList});
    }
    @AuraEnabled
    public static LightningServerResponse fetchRelatedArchivedObjectdata(String recordId, String monthStr, string yearStr){
        Map<String, Object> objectData = new map<String, Object>();
        Map<String, String> rateTypeMap = new Map<String, String>();
        Map<String, String> statusMap = new Map<String, String>();
        Boolean isSuccessful = true;
        String message;
        String isErrorWebservice = '';
        Boolean attendedFlg;
        List<batchsit_t_auth_encmbr__x> fetchedEncumberence = new List<batchsit_t_auth_encmbr__x>();
        List<authEncumbranceRelatedListWrap> authEncumbranceRelatedList = new List<authEncumbranceRelatedListWrap>();
        List<batchsit_t_sbsd_indiv_care_level__x> careLevels = new List<batchsit_t_sbsd_indiv_care_level__x>();
        Map<String, batchsit_t_auth_encmbr__x> careDateToAuthEncmbr2 = new Map<String, batchsit_t_auth_encmbr__x>();
        try {
            T_AUTH__c authRec = [SELECT IDN_EXTNL__c,DTE_BEGIN_EFFV_AUTH__c, DTE_END_EFFV_AUTH__c, IDN_CLIENT__c, IDN_CLIENT__r.DTE_DOB__c,
                                 IDN_PROVR__r.CDE_TYPE_PROVR__c, IDN_CASE__c, Protective_Services_Indicator__c
                                 FROM T_AUTH__c where id =:recordId WITH SECURITY_ENFORCED];
            Schema.DescribeFieldResult fieldResult = T_FISCAL_SCH__c.CDE_RATE_TYPE__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for(Schema.PicklistEntry f : ple){
                rateTypeMap.put(f.getValue(), f.getLabel());
            }  
            Schema.DescribeFieldResult fieldResult1 = Field_Utility__c.R00690__c.getDescribe();
            List<Schema.PicklistEntry> ple1 = fieldResult1.getPicklistValues();
            for(Schema.PicklistEntry f : ple1){
                statusMap.put(f.getValue(), f.getLabel());
            }
            if(authRec != null){
                if(!Test.isRunningTest()){
                    fetchedEncumberence = HerokuService.authEncumbrancefetchArchived(authRec.IDN_EXTNL__c,monthStr,yearStr);
                } else {
                    fetchedEncumberence.add(new batchsit_t_auth_encmbr__x(dte_care__c =(system.today()).addDays(1),idn_auth__c ='Test123',cde_status_encmbr__c='2',cnt_hour_care__c=12,cde_type_unit_care__c='Reg',ExternalId='Test123',ind_0_36_months__c='Y'));
                    fetchedEncumberence.add(new batchsit_t_auth_encmbr__x(dte_care__c =(system.today()).addDays(1),idn_auth__c ='Test123',cde_status_encmbr__c='2',cnt_hour_care__c=12,cde_type_unit_care__c='Reg',ExternalId='Test234',ind_0_36_months__c='N'));
                }
                for(batchsit_t_auth_encmbr__x anAuthEncmbr: fetchedEncumberence){
                    authEncumbranceRelatedListWrap encumb = new authEncumbranceRelatedListWrap();
                    encumb.ExternalId = anAuthEncmbr.ExternalId;
                    encumb.encumbId = anAuthEncmbr.ExternalId;
                    encumb.status = statusMap.get(String.valueOf(anAuthEncmbr.cde_status_encmbr__c));
                    encumb.rateType = rateTypeMap.get(String.valueOf(anAuthEncmbr.cde_type_unit_care__c)) ;
                    encumb.dateOfCare = anAuthEncmbr.dte_care__c;
                    encumb.actualAttendedHours = anAuthEncmbr.cnt_hour_attnd_actual__c;
                    encumb.authorizedHours = anAuthEncmbr.cnt_Hour_Care__c;
                    encumb.attendedFlag = HerokuService.globalAttended.get(encumb.ExternalId);
                    encumb.ind0to36months = anAuthEncmbr.ind_0_36_months__c == 'Y' ? true : false; //added for CCCAP-14174
                    authEncumbranceRelatedList.add(encumb);
                }
                // objectData.put('fetchedEncumberence',fetchedEncumberence);
            }
        } catch(Exception ex) {
            String message1 = ex.getMessage();
            if(fetchedEncumberence == null || fetchedEncumberence.size() <=0){
                message1 = 'Problem in connecting with external system.';
            }
            return new LightningServerResponse(false, message1, null);
        }
        return new LightningServerResponse(isSuccessful,'Validation check',new Map<String, object>{'authEncumbranceRelatedList' => authEncumbranceRelatedList});
    }

}