CHATS_SIT/force-app/main/default/objects/ByPass_Validation_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>By pass the validation rule</description>
    <fields>
        <fullName>Is_Batch_Excluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Batch Excluded</label>
        <type>Checkbox</type>
    </fields>
    <label>ByPass_Validation_Setting</label>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Exception_Log__c.object
<CustomObject>
    <description>The object stores all the exceptions that were catched through out the applications for debugging and reporting purpose.</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Stores the message that was returned from the exception generated.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>Stores the type of exception that has occured</description>
        <label>Exception Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_CLOSURE__c.object
<CustomObject>
    <fields>
        <fullName>DTE_BEGIN_CLOSURE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Closure</relationshipLabel>
        <relationshipName>Provider_Closure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVIDER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Closure Records</relationshipLabel>
        <relationshipName>Provider_Closure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_ACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Provider Closure</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>External ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Closure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_PROVD_CLS__c</fullName> 
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Closure Dates</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/ProviderClosureDatesBatch.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           4/18/2023                                                         
*  @description    Batch class for updating provider closure dates on FA.
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 4/18/2023
*  * Author: Shashank Singla                                                      
*  * Description: Initial version                   
*********************************************************************************************/
global with sharing class ProviderClosureDatesBatch implements 
Database.Batchable<sObject>, Database.Stateful,Schedulable {
    
    public Set<Id> providerId = new Set<Id>();
    public Set<String> providerCountySet = new Set<String>();
    public Exception_Log__c[] errors = new Exception_Log__c[0];
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    
    global void execute(SchedulableContext ctx) {
        database.executebatch(new ProviderClosureDatesBatch());
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String clsStatus ='CLS';
        String queryStr ='select id,(select id,DTE_PROVD_CLS__c,CDE_COUNTY__c from Provider_Fiscal_Agreements__r where CDE_TYPE_STATUS__c!=:clsStatus),(select id,DTE_BEGIN_CLOSURE__c,CDE_COUNTY__c from Provider_Closure__r where IND_ACTIVE__c=true) from T_CHATS_PROVR_STATUS__c where id in (select ID_SERVICE__c from T_PROVR_FISCAL_AGREMENT__c where CDE_TYPE_STATUS__c!=:clsStatus) and id in (select IDN_PROVIDER__c from T_PROVR_CLOSURE__c where IND_ACTIVE__c=true)';
        system.debug('queryStr--'+queryStr);
        return Database.getQueryLocator(queryStr);
    }
    global void execute(Database.BatchableContext bc, List<T_CHATS_PROVR_STATUS__c> providers){
        try{
            ByPass_Validation_Setting__c byPassValidation=[SELECT Is_Batch_Excluded__c FROM ByPass_Validation_Setting__c LIMIT 1];
            byPassValidation.Is_Batch_Excluded__c = TRUE;
            GenericDMLHandler.updateRecords(new List<SObject>{byPassValidation},new Map<String,Object>{'Method__c'=>'executeMethod','Class__c'=>'ProviderClosureDatesBatch'});
            Date pymtStartDate = Date.Today()-13 ;
            Date pymtEndDate = Date.Today()-7;
            system.debug('pymtStartDate'+pymtStartDate+'pymtEndDate'+pymtEndDate);
            List<T_PROVR_FISCAL_AGREMENT__c> agreementsToUpdate = new List<T_PROVR_FISCAL_AGREMENT__c>();
            for(T_CHATS_PROVR_STATUS__c prov : providers){
                Map<Id,String> countyVsDates = new Map<Id,String>();
                for(T_PROVR_CLOSURE__c provClos : prov.Provider_Closure__r){
                    String closeDates = '';
                    if(provClos.DTE_BEGIN_CLOSURE__c >=Date.valueOf(pymtStartDate) && provClos.DTE_BEGIN_CLOSURE__c<=Date.valueOf(pymtEndDate)){
                        if(countyVsDates.containsKey(provClos.CDE_COUNTY__c)){
                            closeDates = countyVsDates.get(provClos.CDE_COUNTY__c);
                        }
                        closeDates += provClos.DTE_BEGIN_CLOSURE__c.format()+';';
                        countyVsDates.put(provClos.CDE_COUNTY__c,closeDates);
                    }
                }
                if(countyVsDates.size()>0){
                    for(T_PROVR_FISCAL_AGREMENT__c agreement : prov.Provider_Fiscal_Agreements__r){
                        if(countyVsDates.containsKey(agreement.CDE_COUNTY__c)){
                            agreement.DTE_PROVD_CLS__c = countyVsDates.get(agreement.CDE_COUNTY__c);
                            agreementsToUpdate.add(agreement);
                            
                        }
                    }
                }
            }
            GenericDMLHandler.updateRecords(agreementsToUpdate,new Map<String,Object>{'Method__c'=>'executeMethod','Class__c'=>'ProviderClosureDatesBatch'});
            byPassValidation.Is_Batch_Excluded__c = false;
            GenericDMLHandler.updateRecords(new List<SObject>{byPassValidation},new Map<String,Object>{'Method__c'=>'executeMethod','Class__c'=>'ProviderClosureDatesBatch'});
        }
        catch(Exception e) {
            Exception_Log__c xLog = new Exception_Log__c();
            xLog.Class__c = 'ProviderClosureDatesBatch';
            xLog.Method__c = 'executeMethod';
            xLog.Exception_Message__c = 'ProviderClosureDatesBatch :- '+e.getMessage();
            xLog.Exception_Type__c = 'Error';
            errors.add(xLog);
        }
    }    
    global void finish(Database.BatchableContext bc){
        if(errors.size()>0){
            GenericDMLHandler.insertRecords(errors, new Map<String, Object>{'Method__c'=>'finish','Class__c'=>'ProviderClosureDatesBatch'});
        }
    }    
}