CHATS_SIT/force-app/main/default/objects/ByPass_Validation_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>By pass the validation rule</description>
    <fields>
        <fullName>Is_Batch_Excluded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Batch Excluded</label>
        <type>Checkbox</type>
    </fields>
    <label>ByPass_Validation_Setting</label>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_STATUS_PROVR__c</fullName>
        <label>License Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00692</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_PROVR__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00691</valueSetName>
        </valueSet>
    </fields>
	<fields>
        <fullName>CDE_REQ_BGC_CHK_STATE__c</fullName>
        <inlineHelpText>For Qualified Exempt Provider Only: This indicates the provider's State required background check status</inlineHelpText>
        <label>Required Background Check Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00865</valueSetName>
        </valueSet>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_CLOSURE__c.object
<CustomObject>
    <fields>
        <fullName>DTE_BEGIN_CLOSURE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Closure</relationshipLabel>
        <relationshipName>Provider_Closure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVIDER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Closure Records</relationshipLabel>
        <relationshipName>Provider_Closure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_ACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Provider Closure</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>External ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Closure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_AGRMT__c</fullName>
        <description>Renewal Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00692.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>R00692</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00865.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Not Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <description>Background Check Status Values</description>
    <masterLabel>R00865</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/ProviderClosureDatesBatch_Test.cls
@isTest
public class ProviderClosureDatesBatch_Test {
    public static final String openRecordTypeId = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Open').getRecordTypeId();
    
    public static testmethod void unitBatchTest(){
        String uuId = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1]?.Id;
        User u1 = TestClassUtility.createUserWithPS(uuId, 'System_Administrator_PS', 'test', 'test', 'test@example.com.invalid', 'test@example.com.'+string.valueof(math.random()*3), 'ttes');
        
        System.runAs(u1){
            ByPass_Validation_Setting__c byPass=new ByPass_Validation_Setting__c();
            byPass.Is_Batch_Excluded__c=false;
            insert byPass;
            T_COUNTY__c county = TestClassUtility.createCounty('countyName', 'countyDepartmentName',10,true);
            T_CHATS_PROVR_STATUS__c provider = TestClassUtility.createProvider(true, 'Test');
            provider.CDE_TYPE_PROVR__c = 'EFACH';
            provider.CDE_REQ_BGC_CHK_STATE__c = 'Cleared';
            provider.CDE_STATUS_PROVR__c = 'Open';
            update provider;
            
            Date begindateOpn=System.Today()-10;
            
            T_PROVR_FISCAL_AGREMENT__c fiscalAgreement = TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county.Id);
            fiscalAgreement.RecordtypeId = openRecordTypeId;
            fiscalAgreement.CDE_TYPE_STATUS__c = 'OPN';
            fiscalAgreement.ID_SERVICE__c = provider.Id;
            fiscalAgreement.DTE_END_AGRMT__c = Date.Today()+10;
            insert fiscalAgreement;	
            Date datetoday=System.Today();
            T_PROVR_CLOSURE__c provClosure = new T_PROVR_CLOSURE__c(IDN_PROVIDER__c=provider.Id, CDE_COUNTY__c = county.Id,IND_ACTIVE__c = true,DTE_BEGIN_CLOSURE__c=datetoday-8);
            insert provClosure;
            
            Test.startTest();
            ProviderClosureDatesBatch batch = new ProviderClosureDatesBatch();
            database.executebatch(batch);
            Test.stopTest();
        }
    }
}