CHATS_SIT/force-app/main/default/objects/Canned_Report__mdt.object
<CustomObject>
<fields>
        <fullName>isProviderDependentLkUp__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isProviderDependentLkUp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Start Date Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isOneYearReport__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is One Year Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EndDateRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EndDateRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date_Label__c</fullName>
        <label>End Date Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hide_County__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide County?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_End_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide End Date?</label>
        <type>Checkbox</type>
    </fields>    
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Report_Name__c</fullName>
        <label>Report Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Type__c</fullName>
        <label>Report Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Financial</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Provider</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>State Monitoring</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SYS</fullName>
                    <default>true</default>
                    <label>System Generated</label>
                </value>
                <value>
                    <fullName>MAN</fullName>
                    <label>Manual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date_Label__c</fullName>
        <label>Start Date Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isDateDefaulted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDateDefaulted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isDateRange__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDateRange</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isMonthYearFilter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isMonthYearFilter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isMonthYear__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isMonthYear</label>
        <type>Checkbox</type>
    </fields> 
<fields>
        <fullName>County_Label__c</fullName>
        <label>County Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FutureBeginDate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FutureBeginDate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FutureEndDate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FutureEndDate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>oneMonthDiffCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <label>oneMonthDiffCheck</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isCountyAutoAssigned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, user&apos;s primary assigned County will be auto selected</description>
        <label>isCountyAutoAssigned</label>
        <type>Checkbox</type>
    </fields>
    <label>Canned Report</label>
    <pluralLabel>Canned Reports</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Owner_County__c</fullName>
        <label>Owner County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00005</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Common_County__c</fullName>
        <label>Other County</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountyWithoutOther</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/CannedReportHomepageController.cls
public with sharing class CannedReportHomepageController {
    
    @AuraEnabled
    public static LightningServerResponse processViewResults(String reportType, String reportName){
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful = true;
        String message='';
        String soql, soqlSelect, soqlOrderBy, soqlcount;
        List<Canned_Report__mdt> searchResult = new List<Canned_Report__mdt>(); 
        soqlSelect = 'select Id, Report_Type__c, Report_Name__c, isOneYearReport__c, Description__c, DeveloperName, Request_Type__c, End_Date_Label__c, Hide_End_Date__c, Start_Date_Label__c, Date_Required__c, isMonthYear__c, County_Label__c, FutureBeginDate__c, FutureEndDate__c, isDateRange__c, EndDateRequired__c, isDateDefaulted__c, oneMonthDiffCheck__c, isMonthYearFilter__c, isProviderDependentLkUp__c, Hide_County__c, isCountyAutoAssigned__c from Canned_Report__mdt where ';
        soqlcount = 'select count() from Canned_Report__mdt where ';
        soql = 'id != null';
        if ((String.isNotBlank(reportType)) && reportType != 'None'){
            reportType = String.escapeSingleQuotes(reportType);
            soql += ' AND Report_Type__c =: reportType';
        }
        if ((String.isNotBlank(reportName)) && reportName != 'None'){
            reportName = String.escapeSingleQuotes(reportName);
            soql += ' AND Report_Name__c LIKE ';
            soql += '\'%'+reportName+'%\'';
        } 
        soqlOrderBy = ' LIMIT 200 ';    
        searchResult = Database.query(soqlSelect + soql + soqlOrderBy); 
        objectData.put('test',searchResult);
        // Start: Added for CCCAP-3230 by Rishav
        Map<String, String> userCountyMap = new Map<String, String>();
        User u = [SELECT Id, Owner_County__c, Common_County__c FROM User WHERE id =: userInfo.getUserId() LIMIT 1];
        userCountyMap.put('Owner_County__c', u.Owner_County__c);
        userCountyMap.put('Common_County__c', u.Common_County__c);
        objectData.put('userCountyMap', userCountyMap);
        // End: CCCAP-3230
        return new LightningServerResponse(isSuccessful,message,objectData); 
    }
    
    @AuraEnabled
    public static LightningServerResponse getAvailableReportsOnHomepage(){
        Boolean isSuccessful = true;
        String message = '';
        Map<String,Object> objectData = new Map<String,Object>();
        /* CCCAP-12937 : RE229 Report Decommission */
        List<Canned_Report__mdt> res = [SELECT toLabel(Report_Type__c), Report_Name__c, isOneYearReport__c, Request_Type__c, Description__c, DeveloperName, End_Date_Label__c, Hide_End_Date__c, Start_Date_Label__c, Date_Required__c, isMonthYear__c, County_Label__c, FutureBeginDate__c, FutureEndDate__c, isDateRange__c, EndDateRequired__c, isMonthYearFilter__c, isProviderDependentLkUp__c, Hide_County__c FROM Canned_Report__mdt 
                                        WHERE Request_Type__c ='MAN' AND Is_Active__c = true AND MasterLabel != 'RE229' ORDER BY Report_Name__c ASC];
        
        objectData.put('test',res);
        return new LightningServerResponse(isSuccessful,message, objectData);        
    }
    
    @AuraEnabled
    public static List<String> getAllReportName(){
        Set<String> reportTypeResultSet = new Set<String>();
        List<String> reportTypeResult = new List<String>();
        /* CCCAP-12937 : RE229 Report Decommission */
        List<Canned_Report__mdt> res = [SELECT Id, Report_Name__c FROM Canned_Report__mdt WHERE Request_Type__c ='MAN' AND Is_Active__c = true AND MasterLabel != 'RE229' ORDER BY Report_Name__c];
        if(res.size()>0){
            for(Canned_Report__mdt name : res){
                reportTypeResultSet.add(name.Report_Name__c);
            } 
        }
        reportTypeResult.addAll(reportTypeResultSet);
        return reportTypeResult; 
    }
    
    @AuraEnabled
    public static List<String> getReportName(String reportType){
        Set<String> reportTypeResultSet = new Set<String>();
        List<String> reportTypeResult = new List<String>();
        List<Canned_Report__mdt> res;
        /* CCCAP-12937 : RE229 Report Decommission */
        if(reportType != '1' && reportType != '2' && reportType != '3' && reportType != '4'){
            res = [SELECT Id, Report_Name__c FROM Canned_Report__mdt WHERE Request_Type__c ='MAN' AND Is_Active__c = true AND MasterLabel != 'RE229' ORDER BY Report_Name__c];
        }else{
            res = [SELECT Id, Report_Name__c FROM Canned_Report__mdt WHERE Report_Type__c =: reportType AND Request_Type__c ='MAN' AND Is_Active__c = true  AND MasterLabel != 'RE229' ORDER BY Report_Name__c];
        }
        if(res!= null && res.size()>0){
            for(Canned_Report__mdt name : res){
                reportTypeResultSet.add(name.Report_Name__c);
            } 
        }
        reportTypeResult.addAll(reportTypeResultSet);
        return reportTypeResult;  
    }
    
}