CHATS_SIT/force-app/main/default/objects/Canned_Report_Request__c.object
<CustomObject>
    <fields>
        <fullName>Date_Requested__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Requested Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Report_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Report Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Report Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Type__c</fullName>
        <label>Report Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Financial</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Provider</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>State Monitoring</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SYS</fullName>
                    <label>System Generated</label>
                </value>
                <value>
                    <fullName>MAN</fullName>
                    <label>Manual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INI</fullName>
                    <label>Initialized</label>
                </value>
                <value>
                    <fullName>REQ</fullName>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>GEN</fullName>
                    <label>Generated</label>
                </value>
                <value>
                    <fullName>FAL</fullName>
                    <label>Failed</label>
                </value>
                <value>
                    <fullName>PEN</fullName>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Canned Report Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Canned Report Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canned Report Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Canned_Report_Request_Filter__c.object
<CustomObject>
    <fields>
        <fullName>Canned_Report_Request__c</fullName>
        <label>Canned Report Request</label>
        <referenceTo>Canned_Report_Request__c</referenceTo>
        <relationshipLabel>Canned Report Request Filters</relationshipLabel>
        <relationshipName>Canned_Report_Request_Filters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Canned Report Request Filter</label>
    <nameField>
        <displayFormat>CRF-{0000}</displayFormat>
        <label>Canned Report Request Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canned Report Request Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY_OWNER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_NOTES__c.object
<CustomObject>
    <fields>
        <fullName>CDE_TYPE_NOTES__c</fullName>
        <description>Note Type</description>
        <label>Note Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00695</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Notes</relationshipLabel>
        <relationshipName>Provider_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TXT_DESC_NOTES__c</fullName>
        <description>Body</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Body</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TXT_SUBJECT__c</fullName>
        <description>Subject</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Provider Notes</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/Report304GeneratorBatch_Test.cls
@isTest(seeAllData=false)
public class Report304GeneratorBatch_Test {

    public static testMethod void testReport304GeneratorBatch(){
        Test.startTest();
        T_COUNTY__c county= TestClassUtility.createCounty('countyName', 'countyDepartmentName', 01, true);
        T_CHATS_PROVR_STATUS__c provider = new T_CHATS_PROVR_STATUS__c();
        provider.Name = 'XYZ';
        provider.CDE_COUNTY_OWNER__c=county.Id;
        insert provider;
        T_PROVR_NOTES__c pronotes =new T_PROVR_NOTES__c();
        pronotes.ID_SERVICE__c=provider.Id;
        pronotes.CDE_TYPE_NOTES__c='1';
        pronotes.TXT_SUBJECT__c= 'Testing';
        pronotes.TXT_DESC_NOTES__c= 'TESTING DONE';
        insert pronotes;
        
        Canned_Report_Request__c request = new Canned_Report_Request__c();
        request.Report_Id__c='RE304';
        request.Status__c='INI'; 
        request.Request_Type__c='MAN';
        request.Report_Name__c = 'RE304 - Provider Notes Report';
        request.Request_Description__c='A report for a specific provider containing all provider notes for a given time period.';
        request.Report_Type__c='3';
        request.Date_Requested__c=System.now();
        
        insert request;
        
        Canned_Report_Request_Filter__c filter1= new Canned_Report_Request_Filter__c();
        filter1.Field__c='FromDate';
        filter1.Value__c=String.valueOf(System.today().addDays(-30));
        filter1.Canned_Report_Request__c=request.Id;
        insert filter1;
        
        Canned_Report_Request_Filter__c filter2= new Canned_Report_Request_Filter__c();
        filter2.Field__c='ToDate';
        filter2.Value__c=String.valueOf(System.today()+1);
        filter2.Canned_Report_Request__c=request.Id;
        insert filter2;
        
        Canned_Report_Request_Filter__c filter3= new Canned_Report_Request_Filter__c();
        filter3.Field__c='ProviderId';
        filter3.Value__c=provider.id;
        filter3.Canned_Report_Request__c=request.Id;
        insert filter3;
        
        Canned_Report_Request_Filter__c filter4= new Canned_Report_Request_Filter__c();
        filter4.Field__c='Provider_Note_Type__c';
        filter4.Value__c='1';
        filter4.Canned_Report_Request__c=request.Id;
        insert filter4;
        
        
        Test.setMock(HttpCalloutMock.class, new corspdPrintQueueMockTest());
        Database.executeBatch(new Report304GeneratorBatch(), 1);
        Test.stopTest();
        	
    }
	
    public static testMethod void testReport304GeneratorScheduler(){
        Canned_Report_Request__c request = new 	Canned_Report_Request__c();
        request.Report_Id__c='RE304';
        request.Status__c='INI'; 
        request.Request_Type__c='MAN';
        request.Report_Name__c = 'RE304 - Provider Notes Report';
        request.Request_Description__c='A report for a specific provider containing all provider notes for a given time period.';
        request.Report_Type__c='3';
        request.Date_Requested__c=System.now();
        
        insert request;
        
        Canned_Report_Request_Filter__c filter1= new Canned_Report_Request_Filter__c();
        filter1.Field__c='FromDate';
        filter1.Value__c=String.valueOf(System.today().addDays(-30));
        filter1.Canned_Report_Request__c=request.Id;
        insert filter1;
        
        Canned_Report_Request_Filter__c filter2= new Canned_Report_Request_Filter__c();
        filter2.Field__c='ToDate';
        filter2.Value__c=String.valueOf(System.today());
        filter2.Canned_Report_Request__c=request.Id;
        insert filter2;
        Test.startTest();	
        Datetime dt = Datetime.now().addMinutes(5);
        String cronStr = '0 ' +  dt.minute() + ' ' + dt.hour() + ' ' + dt.day() + ' ' + dt.month()+ ' ? ' + dt.year();
        system.debug(cronStr);
        String batchName = 'RE304-Rpt-Gen';
        system.schedule(batchName, cronStr, new RE304GeneratorBatchScheduler());
        Test.stopTest();
    }
    
}