CHATS_SIT/force-app/main/default/objects/Canned_Report_Request__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00005</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Canned Report Request External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Report_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Report Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INI</fullName>
                    <label>Initialized</label>
                </value>
                <value>
                    <fullName>REQ</fullName>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>GEN</fullName>
                    <label>Generated</label>
                </value>
                <value>
                    <fullName>FAL</fullName>
                    <label>Failed</label>
                </value>
                <value>
                    <fullName>PEN</fullName>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Canned Report Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Canned Report Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canned Report Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Canned_Report_Request_Filter__c.object
<CustomObject>
    <fields>
        <fullName>Canned_Report_Request__c</fullName>
        <label>Canned Report Request</label>
        <referenceTo>Canned_Report_Request__c</referenceTo>
        <relationshipLabel>Canned Report Request Filters</relationshipLabel>
        <relationshipName>Canned_Report_Request_Filters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Canned Report Filter External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Canned Report Request Filter</label>
    <nameField>
        <displayFormat>CRF-{0000}</displayFormat>
        <label>Canned Report Request Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canned Report Request Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Exception_Log__c.object
<CustomObject>
    <description>The object stores all the exceptions that were catched through out the applications for debugging and reporting purpose.</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Stores the message that was returned from the exception generated.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>Stores the type of exception that has occured</description>
        <label>Exception Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>This field will be populated for Call out exceptions and will store the request that was passed to the webservice call out.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>This field is specifically for call out exceptions. It will store the response that we received from the wenservice call outs.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY_OWNER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_NOTES__c.object
<CustomObject>
    <fields>
        <fullName>CDE_TYPE_NOTES__c</fullName>
        <description>Note Type</description>
        <label>Note Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00695</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Notes</relationshipLabel>
        <relationshipName>Provider_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Notes</relationshipLabel>
        <relationshipName>Provider_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TXT_DESC_NOTES__c</fullName>
        <description>Body</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Body</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TXT_SUBJECT__c</fullName>
        <description>Subject</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Provider Notes</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/Report304GeneratorBatch.cls
/*************************************************************
Class Name	    - Report304GeneratorBatch
Test Class	    - Report304GeneratorBatch_Test
Description     - Batch Class for RE304 -- Provider Notes Report
Author          - Pragyan P Nayak
JIRA Id			- CCCAP - 3225
**************************************************************/
global class Report304GeneratorBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{ 
    global final String reportName;
    global final String status;
    
    global  Report304GeneratorBatch(){
        this.reportName = 'RE304 - Provider Notes Report';
        this.status = 'INI';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('SELECT Id,Name,createddate FROM Canned_Report_Request__c WHERE Report_Name__c =:reportName AND Status__c =:status');
    }
    
    global void execute(Database.BatchableContext BC, List<Canned_Report_Request__c> zCannedReportRequests){
        
        for(Canned_Report_Request__c canReportReq: zCannedReportRequests){
            
            String cannedReportId = canReportReq.Id;
            List<Canned_Report_Request_Filter__c> filterList = [SELECT Id, Value__c, Field__c,Canned_Report_Request__r.County__c, Canned_Report_Request__c FROM Canned_Report_Request_Filter__c WHERE Canned_Report_Request__c =:cannedReportId];
            if(filterList.isEmpty()) continue;
            Map<String, String> paramsMap = new Map<String,String>();
            String countyCode;
            for(Canned_Report_Request_Filter__c filterObj : filterList){
                countyCode =filterObj.Canned_Report_Request__r.County__c;
                if(filterObj.Field__c == 'ProviderId' || filterObj.Field__c == 'ToDate' ||filterObj.Field__c == 'FromDate' ||filterObj.Field__c == 'Provider_Note_Type__c' ){
                    paramsMap.put(filterObj.Field__c, filterObj.Value__c);
                }
            }
            String providerId = paramsMap.get('ProviderId');          
            String toDate = paramsMap.get('ToDate');
            String fromDate = paramsMap.get('FromDate');
            List<String> beginDateArr = new List<String>();
            List<String> endDateArr = new List<String>();
            Date requestBeginDate; 
            datetime requestEndDate;
            List<Id> countyIds = new List<Id>();
            if(String.isNotBlank(countyCode) && countyCode!='66'){
                //Added by Nikita for CCCAP-9539
                String[] countyCodes = countyCode.split(';');
                List<Decimal> countyCodeList = new List<Decimal>(); 
                for(String c : countyCodes){
                    countyCodeList.add(Decimal.valueOf(c));
                }
                List<T_COUNTY__c> countyList = [Select id from T_COUNTY__c where CDE_COUNTY__c in :countyCodeList];
                if(countyList != null && countyList.size()>0){
                    for(T_COUNTY__c county : countyList){
                        countyIds.add(county.Id);
                    }
                }
            }
            if(String.isNotBlank(fromDate)){
                beginDateArr= fromDate.split('-');
            }
            if(String.isNotBlank(toDate)){
                endDateArr= toDate.split('-');
            }
            if(beginDateArr.size()>2  ){
                requestBeginDate = Date.newInstance(Integer.valueOf(beginDateArr[0]), Integer.valueOf(beginDateArr[1]), Integer.valueOf(beginDateArr[2]));
            }
            if( endDateArr.size()>2 ){
                requestEndDate = datetime.newInstance(Integer.valueOf(endDateArr[0]), Integer.valueOf(endDateArr[1]), Integer.valueOf(endDateArr[2]),23,59,59);
            }
            String noteType = paramsMap.get('Provider_Note_Type__c');
            T_CHATS_PROVR_STATUS__c  providerObj;
            List<T_PROVR_NOTES__c> providerNoteLst;
            String finalProviderParam='';
            if(paramsMap.get('ProviderId') != null){
                providerObj = [Select Id, Name from T_CHATS_PROVR_STATUS__c where Id=:providerId Limit 1];
                String queryStr ='Select id,Name,IDN_EXTNL__c,CreatedDate,County__c,CreatedBy.Common_County__c,LastModifiedDate,toLabel(CDE_TYPE_NOTES__c),TXT_SUBJECT__c,TXT_DESC_NOTES__c,CreatedById,ID_SERVICE__c,ID_SERVICE__r.CDE_COUNTY_OWNER__c from T_PROVR_NOTES__c where ID_SERVICE__c=:providerId ';
                if(paramsMap.get('Provider_Note_Type__c') != null){
                    queryStr+= ' AND CDE_TYPE_NOTES__c =:noteType';
                }
                if(requestBeginDate != null){
                    queryStr+= ' AND CreatedDate >=:requestBeginDate';
                }
                if(requestEndDate != null){
                    queryStr+= ' AND CreatedDate <=:requestEndDate';
                }
                if(countyIds != null && countyIds.size()>0 && countyCode!='66'){
                    queryStr+= ' AND County__c IN :countyIds';
                }
                providerNoteLst = DataBase.query(queryStr);
            }
            
            String reportJsonBody = '';
            
            reportJsonBody += '[{"cannedReportId":"'+cannedReportId+'",';
            reportJsonBody += '"data":[';
            if(providerNoteLst != null && providerNoteLst.size()>0){
                for(T_PROVR_NOTES__c providerNoteObj:providerNoteLst){
                    String subjectStr ='';
                    String subjectOutput ='';
                    String noteDescStr ='';
                    String noteDescOutput ='';
                    if(providerNoteObj.TXT_SUBJECT__c != null){
                        subjectStr =providerNoteObj.TXT_SUBJECT__c;
                        Blob beforeblob = Blob.valueOf(subjectStr);
                        subjectOutput = EncodingUtil.base64Encode(beforeblob);
                    }if(providerNoteObj.TXT_DESC_NOTES__c !=null){
                        noteDescStr =providerNoteObj.TXT_DESC_NOTES__c;
                        Blob beforeblobNote = Blob.valueOf(noteDescStr);
                        noteDescOutput = EncodingUtil.base64Encode(beforeblobNote);
                    }
                    reportJsonBody += '{"externalId":"' + (providerNoteObj.Name == null? '' : String.valueOf(providerNoteObj.Name))  + '",' ;
                    reportJsonBody += '"createDate":"' + (providerNoteObj.CreatedDate == null? '' : String.valueOf(providerNoteObj.CreatedDate.format('yyyy-MM-dd hh:mm a')))  + '",' ;
                    reportJsonBody += '"lastModDate":"' + (providerNoteObj.LastModifiedDate == null? '' : String.valueOf(providerNoteObj.LastModifiedDate.format('yyyy-MM-dd hh:mm a')))  + '",' ;
                    reportJsonBody += '"county":"' + (providerNoteObj.County__c == null? '' : String.valueOf(providerNoteObj.County__c))  + '",' ;
		            reportJsonBody += '"noteType":"' + (providerNoteObj.CDE_TYPE_NOTES__c == null? '' : String.valueOf(providerNoteObj.CDE_TYPE_NOTES__c))  + '",' ;
                    reportJsonBody += '"subject":"' + (subjectOutput == null? '' : subjectOutput)  + '",' ;
                    reportJsonBody += '"note":"' + (noteDescOutput == null? '' : noteDescOutput)  + '",' ;
                    reportJsonBody += '"createdByUser":"' + (providerNoteObj.CreatedById == null? '' : String.valueOf(providerNoteObj.CreatedById))  + '"' ;
                    reportJsonBody += '},';
                }
            }                
            reportJsonBody = reportJsonBody.removeEnd(',');
            reportJsonBody += ']}]';
            
            //SEND TO API CALL
            
            String report304apiEndpoint = Label.RE304_Generator_API_Endpoint;
            Http http = new Http();
            Httprequest request = new Httprequest();
            request.setHeader('Content-Type', 'application/json;charset=UTF-8');
            request.setMethod('POST');
            request.setEndpoint(report304apiEndpoint);
            request.setBody(reportJsonBody);
            
            Integer timeOutVal = Integer.valueOf(System.Label.WebServiceTimeOut);
            request.setTimeout(timeOutVal);
            HttpResponse response;
            
              try{
				if(!Test.isRunningTest()){
						response = http.send(request);
				}
                if(response == null || response.getStatusCode() != 200){
                    Exception_Log__c xLog = new Exception_Log__c();
                    xLog.Class__c = 'Report304GeneratorBatch';
                    xLog.Method__c = 'Execute';
                    if (response != null) {
                        xLog.Exception_Message__c = 'Status is :' + response.getStatus() + ',Status Code is :' + String.valueOf(response.getStatusCode());
                        if (response.getStatusCode() != null) {
                            xLog.Exception_Type__c = 'Web Service';
                        }
                        xLog.Response__c = response.getBody();
                    }
                    if (response != null) {
                        xLog.Request__c = 'End point:' + request.getEndpoint() + ':' + response.getBody();
                    }
                    ExceptionLoggingServices.captureExceptionLog(xLog); 
                }
                
            }catch(Exception ex){
                Exception_Log__c xLog = new Exception_Log__c();
                xLog.Class__c = 'Report304GeneratorBatch';
                xLog.Method__c = 'Execute';
                xLog.Exception_Message__c = 'API Callout failure';
                xLog.Request__c = report304apiEndpoint;
                xLog.Response__c = 'null';
                ExceptionLoggingServices.captureExceptionLog(xLog); 
            }
            
            try {
                if(response != null && response.getStatusCode() == 200){
                    Canned_Report_Request__c canRptReq = new Canned_Report_Request__c();
                    canRptReq.id = cannedReportId;
                    canRptReq.Status__c = 'REQ';
                    update canRptReq;
                }
            } catch (Exception ex){
                Exception_Log__c xLog = new Exception_Log__c();
                xLog.Class__c = 'Report304GeneratorBatch';
                xLog.Method__c = 'Execute';
                xLog.Exception_Message__c = 'INI -> REQ status update failure';
                xLog.Request__c = report304apiEndpoint;
                xLog.Response__c = 'null';
                ExceptionLoggingServices.captureExceptionLog(xLog); 
            }
            
            
        }
        
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
}