CHATS_SIT/force-app/main/default/objects/CHATS_Support__c.object
<CustomObject>
    <description>Object for chats county users to log issues, requests and questions, as well as for supervisors to submit new system-access requests.</description>
    <fields>
        <fullName>CHATS_Area__c</fullName>
        <inlineHelpText>Choose the area in CAPS you are experiencing the issue with, or have a request for, etc.</inlineHelpText>
        <label>CHATS/Policy Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ATS</fullName>
                </value>
                <value>
                    <fullName>Authorization &amp; Parent Fee</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>CHATS Canned Reports</fullName>
                </value>
                <value>
                    <fullName>Colorado Works Referral</fullName>
                </value>
                <value>
                    <fullName>Correspondence</fullName>
                </value>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>County Level Case Reviews</fullName>
                </value>
                <value>
                    <fullName>County Plan</fullName>
                </value>
                <value>
                    <fullName>County Rate Plan</fullName>
                </value>
                <value>
                    <fullName>Dashboards &amp; Reports</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Fiscal Agreement for Licensed</fullName>
                </value>
                <value>
                    <fullName>Fiscal Agreement for QE</fullName>
                </value>
                <value>
                    <fullName>Fraud/IPV</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Manual Claim</fullName>
                </value>
                <value>
                    <fullName>Monitoring Reports</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                    <label>Payment Adjustment</label>
                </value>
                <value>
                    <fullName>PEAK</fullName>
                </value>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Quality Assurance Case Reviews</fullName>
                </value>
                <value>
                    <fullName>Recovery</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>SIDMOD</fullName>
                </value>
                <value>
                    <fullName>Sub Payment</fullName>
                    <isActive>false</isActive>
                    <label>Sub Payment</label>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Wait list</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00005</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description_Steps_to_Reproduce__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <inlineHelpText>In detail, describe the problem, question or issue. Provide examples, steps and actual and expected results. This will assist us in reproducing the issue and troubleshooting.</inlineHelpText>
        <label>Description of Issue/Policy Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Direct_Phone_Number__c</fullName>
        <description>Call back number for user who has logged ticket or had a ticket logged on their behafl</description>
        <label>Direct Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Root_Cause__c</fullName>
        <label>Root Cause</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cannot Reproduce</fullName>
                </value>
                <value>
                    <fullName>Change Request</fullName>
                </value>
                <value>
                    <fullName>Clarification</fullName>
                </value>
                <value>
                    <fullName>System Issue</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Pending Triage</fullName>
                    <default>true</default>
                    <label>Pending Triage</label>
                </value>
                <value>
                    <fullName>Access Request</fullName>
                </value>
                <value>
                    <fullName>Pending Research</fullName>
                </value>
                <value>
                    <fullName>Datafix</fullName>
                    <isActive>true</isActive>
                </value>
		<value>
                    <fullName>QE Provider</fullName>
                    <isActive>true</isActive>
                </value>  
                <value>
                    <fullName>Report Request</fullName>
                    <isActive>true</isActive>
                </value>   
                <value>
                    <fullName>Data Fix</fullName>
                    <isActive>false</isActive>
                </value>
                		    
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Default is &quot;new&quot;. State CCCAP Staff/Helpdesk update status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Awaiting User</fullName>
                </value>
                <value>
                    <fullName>Elevated</fullName>
                </value>
                <value>
                    <fullName>Fixed/Completed</fullName>
                </value>
                <value>
                    <fullName>Change Pending</fullName>
                </value>		
                <value>
                    <fullName>Change Approved</fullName>
                </value>
                <value>
                    <fullName>Change Denied</fullName>
                </value>
                <value>
                    <fullName>Change Implemented</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                 <value>
                    <fullName>Pending Research</fullName>
                </value>
                <value>
                    <fullName>Pending Leadership Review</fullName>
                </value>
                <value>
                    <fullName>Pending CCCAP Team Review</fullName>
                </value>
                <value>
                    <fullName>Pending CCMTG Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Category__c</fullName>
        <inlineHelpText>Please identify if your support ticket is related to CCCAP Policy or the CHATS System. Specify further in the Support Type field.</inlineHelpText>
        <label>Support Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Policy</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Type__c</fullName>
        <inlineHelpText>&quot;System Issue/Request&quot;-technical issues, requests, errors, etc.  &quot;Question/Clarification&quot;-questions regarding CCCAP rules or procedures. &quot;System Navigation Questions/Clarification&quot;- System navigation.
&quot;Ideas For CHATS&quot;-suggestions on improving CHATS.</inlineHelpText>
        <label>Support Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Support_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Question/Clarification</fullName>
                </value>
                <value>
                    <fullName>Log In/Reset Question/Issue</fullName>
                </value>
                <value>
                    <fullName>System Navigation Question/Clarification</fullName>
                </value>
                <value>
                    <fullName>System Issue/Request</fullName>
                </value>
                <value>
                    <fullName>System Access</fullName>
                </value>
                <value>
                    <fullName>Ideas for CHATS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Support</label>
    <nameField>
        <displayFormat>Support - {0000000000}</displayFormat>
        <label>CHATS Support Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Access_Request_Supervisor_Access_Only</fullName>
        <active>false</active>
        <description>Only Supervisors can select &quot;Access Request&quot;, &quot;Change Profile&quot;, or &quot;Deactivate Access&quot; from the pick-list</description>
        <errorConditionFormula>AND( 
ISPICKVAL(Support_Type__c, &quot;Access Request&quot;), 
ISPICKVAL(Support_Type__c, &quot;Deactivate Access&quot;),
ISPICKVAL(Support_Type__c, &quot;Change Profile&quot;),
And( 
$Profile.Name &lt;&gt; &quot;Eligibility Worker Supervisor&quot;, 
$Profile.Name &lt;&gt; &quot;Fiscal Worker Supervisor&quot;,
$Profile.Name &lt;&gt; &quot;Provider Worker Supervisor&quot;,
$Profile.Name &lt;&gt; &quot;Universal User&quot;,
$Profile.Name &lt;&gt; &quot;System Administrator&quot;,
$Profile.Name &lt;&gt; &quot;System Admin&quot;,
$Profile.Name &lt;&gt; &quot;CHATS System Administrator&quot;
))</errorConditionFormula>
        <errorDisplayField>Support_Type__c</errorDisplayField>
        <errorMessage>You must be a Supervisor or Universal Worker to select &quot;Access Request&quot;, &quot;Change Profile&quot;, or &quot;Deactivate Access&quot;.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_CHATS_Area_if_Supp_Cat_is_System</fullName>
        <active>false</active>
        <errorConditionFormula>AND(ISPICKVAL(Support_Category__c , &apos;System&apos;), RecordType.DeveloperName =&apos;Support_Ticket&apos;,  ISPICKVAL(CHATS_Area__c , &apos;&apos;)    )</errorConditionFormula>
        <errorDisplayField>CHATS_Area__c</errorDisplayField>
        <errorMessage>Required when Support Category is System.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_Temp_Access_if_Access_Req_Is_New_Wo</fullName>
        <active>false</active>
        <errorConditionFormula>AND(ISPICKVAL(  Access_Level_Requested__c , &apos;Universal User&apos;), RecordType.DeveloperName =&apos;System_Access_Request&apos;,  OR(ISBLANK(  Temporary_Access_End_Date__c ),Temporary_Access_End_Date__c &lt; TODAY(),Temporary_Access_End_Date__c &gt; TODAY() + ( ( 365 / 12 ) * 6) ))</errorConditionFormula>
        <errorDisplayField>Temporary_Access_End_Date__c</errorDisplayField>
        <errorMessage>Required when Access Type is New Worker Access Request. And it must be less than or equal to 6 months from Today.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Valid_Future_Scheduled_Date</fullName>
        <active>false</active>
        <errorConditionFormula>Scheduled_PROD_Release_Date__c &lt;= TODAY()</errorConditionFormula>
        <errorDisplayField>Scheduled_PROD_Release_Date__c</errorDisplayField>
        <errorMessage>It should have future date.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Linked_To__c.object
<CustomObject>
    <description>This object acts as a junction for linking the support tickets.</description>
    <fields>
        <fullName>Linked_Issues__c</fullName>
        <label>Linked Issues</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>blocks</fullName>
                </value>
                <value>
                    <fullName>is cloned by</fullName>
                </value>
                <value>
                    <fullName>clones</fullName>
                </value>
                <value>
                    <fullName>is duplicated by</fullName>
                </value>
                <value>
                    <fullName>duplicates</fullName>
                </value>
                <value>
                    <fullName>Implemented via</fullName>
                </value>
                <value>
                    <fullName>relates to</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Ticket1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Link Support Ticket</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You cannot link a Non Support Ticket</errorMessage>
            <filterItems>
                <field>CHATS_Support__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Support Ticket</value>
            </filterItems>
            <infoMessage>You can only link Support Tickets</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CHATS_Support__c</referenceTo>
        <relationshipLabel>Linked To</relationshipLabel>
        <relationshipName>Support_Ticket_Second</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Ticket__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Support Ticket</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You cannot link a non Support Ticket</errorMessage>
            <filterItems>
                <field>CHATS_Support__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Support Ticket</value>
            </filterItems>
            <infoMessage>You can link only Support Tickets</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CHATS_Support__c</referenceTo>
        <relationshipLabel>Linked To</relationshipLabel>
        <relationshipName>Support_Ticket</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Linked To</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked To</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/SupportTcktLnkdRelListCtrlTest.cls
@IsTest(SeeAllData=false)
public class SupportTcktLnkdRelListCtrlTest {
    
    static testMethod void testSupportTicket(){
        
        CHATS_Support__c supportRec = new CHATS_Support__c();
        supportRec.Support_Category__c = 'Policy';
        supportRec.Status__c = 'Fixed/Completed';
        supportRec.Support_Type__c = 'Question/Clarification';
        supportRec.Root_Cause__c = 'Pending Triage';
        supportRec.Direct_Phone_Number__c = '876543';
        supportRec.County__c = '1';
        supportRec.CHATS_Area__c = 'Adjustment';
        supportRec.Description_Steps_to_Reproduce__c = 'jfyufy';
        
        insert supportRec;
        
        CHATS_Support__c supportRec1 = new CHATS_Support__c();
        supportRec1.Support_Category__c = 'Policy';
        supportRec1.Status__c = 'Fixed/Completed';
        supportRec1.Support_Type__c = 'Question/Clarification';
        supportRec1.Root_Cause__c = 'Pending Triage';
        supportRec1.Direct_Phone_Number__c = '876543';
        supportRec1.County__c = '1';
        supportRec1.CHATS_Area__c = 'Adjustment';
        supportRec1.Description_Steps_to_Reproduce__c = 'jfyufy';
        
        insert supportRec1;
        
        Linked_To__c linkedToRecord = new Linked_To__c();
        linkedToRecord.Linked_Issues__c = '	is duplicated by';
        linkedToRecord.Support_Ticket__c = supportRec.Id;
        linkedToRecord.Support_Ticket1__c = supportRec1.Id;
        
        
        Test.startTest();
        insert linkedToRecord;
        
        Linked_To__c linkedTicket = [Select Id, name, Support_Ticket__c, Support_Ticket1__c from Linked_To__c Where Support_Ticket__c = :supportRec.Id LIMIT 1 ];
        LightningServerResponse  lightserresobj = SupportTicketLinkedRelatedListAPXCtrl.fetchRelatedObjectdata(supportRec.Id);
		system.assertEquals(true,lightserresobj.isSuccessful,'It should be successful');
        Test.stopTest();
    }
    
    static testMethod void testSupportTicket1(){
        
        CHATS_Support__c supportRec = new CHATS_Support__c();
        supportRec.Support_Category__c = 'Policy';
        supportRec.Status__c = 'Fixed/Completed';
        supportRec.Support_Type__c = 'Question/Clarification';
        supportRec.Root_Cause__c = 'Pending Triage';
        supportRec.Direct_Phone_Number__c = '876543';
        supportRec.County__c = '1';
        supportRec.CHATS_Area__c = 'Adjustment';
        supportRec.Description_Steps_to_Reproduce__c = 'jfyufy';
        
        insert supportRec;
        
        CHATS_Support__c supportRec1 = new CHATS_Support__c();
        supportRec1.Support_Category__c = 'Policy';
        supportRec1.Status__c = 'Fixed/Completed';
        supportRec1.Support_Type__c = 'Question/Clarification';
        supportRec1.Root_Cause__c = 'Pending Triage';
        supportRec1.Direct_Phone_Number__c = '876543';
        supportRec1.County__c = '1';
        supportRec1.CHATS_Area__c = 'Adjustment';
        supportRec1.Description_Steps_to_Reproduce__c = 'jfyufy';
        
        insert supportRec1;
        
        Linked_To__c linkedToRecord = new Linked_To__c();
        linkedToRecord.Linked_Issues__c = '	is duplicated by';
        linkedToRecord.Support_Ticket1__c = supportRec.Id;
        linkedToRecord.Support_Ticket__c = supportRec1.Id;
         
        Test.startTest();
        insert linkedToRecord;
        
        Linked_To__c linkedTicket = [Select Id, name, Support_Ticket__c, Support_Ticket1__c from Linked_To__c Where Support_Ticket1__c = :supportRec.Id LIMIT 1 ];
        LightningServerResponse  lightserresobj = SupportTicketLinkedRelatedListAPXCtrl.fetchRelatedObjectdata(supportRec.Id);
        system.assertEquals(true,lightserresobj.isSuccessful,'It should be successful');
        Test.stopTest();
    }

}