CHATS_SIT/force-app/main/default/objects/CHATS_Support__c.object
<CustomObject>
    <description>Object for chats county users to log issues, requests and questions, as well as for supervisors to submit new system-access requests.</description>
    <fields>
        <fullName>Actual_Results__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Actual Results</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Awaiting_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Awaiting User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CHATS_Support4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Results__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Expected Results</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Page_URL__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Enter the URL for the page you have an issue/question on (Copy the URL from the top of the page you are on, i.e., https://CCCAP--pilot.lightning.force.com). This provides a direct link to the page you are referring to in the description field.</inlineHelpText>
        <label>Page URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Default is &quot;new&quot;. State CCCAP Staff/Helpdesk update status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Awaiting User</fullName>
                </value>
                <value>
                    <fullName>Elevated</fullName>
                </value>
                <value>
                    <fullName>Fixed/Completed</fullName>
                </value>
                <value>
                    <fullName>Change Pending</fullName>
                </value>		
                <value>
                    <fullName>Change Approved</fullName>
                </value>
                <value>
                    <fullName>Change Denied</fullName>
                </value>
                <value>
                    <fullName>Change Implemented</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                 <value>
                    <fullName>Pending Research</fullName>
                </value>
                <value>
                    <fullName>Pending Leadership Review</fullName>
                </value>
                <value>
                    <fullName>Pending CCCAP Team Review</fullName>
                </value>
                <value>
                    <fullName>Pending CCMTG Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Category__c</fullName>
        <inlineHelpText>Please identify if your support ticket is related to CCCAP Policy or the CHATS System. Specify further in the Support Type field.</inlineHelpText>
        <label>Support Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Policy</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Team_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Team Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CHATS_Support3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Type__c</fullName>
        <inlineHelpText>&quot;System Issue/Request&quot;-technical issues, requests, errors, etc.  &quot;Question/Clarification&quot;-questions regarding CCCAP rules or procedures. &quot;System Navigation Questions/Clarification&quot;- System navigation.
&quot;Ideas For CHATS&quot;-suggestions on improving CHATS.</inlineHelpText>
        <label>Support Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Support_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Question/Clarification</fullName>
                </value>
                <value>
                    <fullName>Log In/Reset Question/Issue</fullName>
                </value>
                <value>
                    <fullName>System Navigation Question/Clarification</fullName>
                </value>
                <value>
                    <fullName>System Issue/Request</fullName>
                </value>
                <value>
                    <fullName>System Access</fullName>
                </value>
                <value>
                    <fullName>Ideas for CHATS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Communication_Log__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Communication Log</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Support</label>
    <nameField>
        <displayFormat>Support - {0000000000}</displayFormat>
        <label>CHATS Support Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Access_Request_Supervisor_Access_Only</fullName>
        <active>false</active>
        <description>Only Supervisors can select &quot;Access Request&quot;, &quot;Change Profile&quot;, or &quot;Deactivate Access&quot; from the pick-list</description>
        <errorConditionFormula>AND( 
ISPICKVAL(Support_Type__c, &quot;Access Request&quot;), 
ISPICKVAL(Support_Type__c, &quot;Deactivate Access&quot;),
ISPICKVAL(Support_Type__c, &quot;Change Profile&quot;),
And( 
$Profile.Name &lt;&gt; &quot;Eligibility Worker Supervisor&quot;, 
$Profile.Name &lt;&gt; &quot;Fiscal Worker Supervisor&quot;,
$Profile.Name &lt;&gt; &quot;Provider Worker Supervisor&quot;,
$Profile.Name &lt;&gt; &quot;Universal User&quot;,
$Profile.Name &lt;&gt; &quot;System Administrator&quot;,
$Profile.Name &lt;&gt; &quot;System Admin&quot;,
$Profile.Name &lt;&gt; &quot;CHATS System Administrator&quot;
))</errorConditionFormula>
        <errorDisplayField>Support_Type__c</errorDisplayField>
        <errorMessage>You must be a Supervisor or Universal Worker to select &quot;Access Request&quot;, &quot;Change Profile&quot;, or &quot;Deactivate Access&quot;.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_CHATS_Area_if_Supp_Cat_is_System</fullName>
        <active>false</active>
        <errorConditionFormula>AND(ISPICKVAL(Support_Category__c , &apos;System&apos;), RecordType.DeveloperName =&apos;Support_Ticket&apos;,  ISPICKVAL(CHATS_Area__c , &apos;&apos;)    )</errorConditionFormula>
        <errorDisplayField>CHATS_Area__c</errorDisplayField>
        <errorMessage>Required when Support Category is System.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_Temp_Access_if_Access_Req_Is_New_Wo</fullName>
        <active>false</active>
        <errorConditionFormula>AND(ISPICKVAL(  Access_Level_Requested__c , &apos;Universal User&apos;), RecordType.DeveloperName =&apos;System_Access_Request&apos;,  OR(ISBLANK(  Temporary_Access_End_Date__c ),Temporary_Access_End_Date__c &lt; TODAY(),Temporary_Access_End_Date__c &gt; TODAY() + ( ( 365 / 12 ) * 6) ))</errorConditionFormula>
        <errorDisplayField>Temporary_Access_End_Date__c</errorDisplayField>
        <errorMessage>Required when Access Type is New Worker Access Request. And it must be less than or equal to 6 months from Today.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Valid_Future_Scheduled_Date</fullName>
        <active>false</active>
        <errorConditionFormula>Scheduled_PROD_Release_Date__c &lt;= TODAY()</errorConditionFormula>
        <errorDisplayField>Scheduled_PROD_Release_Date__c</errorDisplayField>
        <errorMessage>It should have future date.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/CHATS_Support_Comment__c.object
<CustomObject>
    <fields>
        <fullName>CHATS_Support_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CHATS Support Number</label>
        <referenceTo>CHATS_Support__c</referenceTo>
        <relationshipLabel>Support Comments</relationshipLabel>
        <relationshipName>Support_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Communication_Log__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Communication Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Support Comment</label>
    <nameField>
        <displayFormat>Comment - {0000000000}</displayFormat>
        <label>CHATS Support Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Communication_Log__c.object
<CustomObject>
    <label>Communication Log</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Communication Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/SupportCommentTrigger_Test.cls
/*************************************************************
Class Name      - SupportCommentTrigger_Test
Description     - Test class for SupportCommentTrigger and SupportServices.sendBellNotificationSupportComment
**************************************************************/
@isTest
public class SupportCommentTrigger_Test {
    
    @TestSetup
    static void setupTestData() {
        Profile standardProfile = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'Assignee',
            Email = 'testassignee@test.com',
            Username = 'testassignee' + DateTime.now().getTime() + '@test.com',
            Alias = 'tassign',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = standardProfile.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;
        
        User awaitingUser = new User(
            FirstName = 'Awaiting',
            LastName = 'User',
            Email = 'awaitinguser@test.com',
            Username = 'awaitinguser' + DateTime.now().getTime() + '@test.com',
            Alias = 'awaitu',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = standardProfile.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert awaitingUser;
    }
    
    @isTest
    static void testInsertSupportComment() {
        User testUser = [SELECT Id FROM User WHERE Email = 'testassignee@test.com' LIMIT 1];
        Id supportTicketRecTypeId = Schema.SObjectType.CHATS_Support__c.getRecordTypeInfosByName().get('Support Ticket').getRecordTypeId();
        CHATS_Support__c supportRecord = new CHATS_Support__c(
            RecordTypeId = supportTicketRecTypeId,
            Status__c = 'New',
            Support_Team_Assignee__c = testUser.Id,
            Support_Category__c = 'System',
            Support_Type__c = 'System Issue/Request',
            Expected_Results__c = 'test results',
            Actual_Results__c ='test results',
            Page_URL__c ='url'
        );
        insert supportRecord;
        
        Test.startTest();
        CHATS_Support_Comment__c supportComment = new CHATS_Support_Comment__c(
            CHATS_Support_Number__c = supportRecord.Id,
            Communication_Log__c = 'Test communication log entry'
        );
        insert supportComment;
        Test.stopTest();
        
        List<CHATS_Support_Comment__c> insertedComments = [
            SELECT Id, Communication_Log__c, CHATS_Support_Number__c 
            FROM CHATS_Support_Comment__c 
            WHERE Id = :supportComment.Id
        ];
        System.assertEquals(1, insertedComments.size(), 'Support Comment should be inserted');
        System.assertEquals('Test communication log entry', insertedComments[0].Communication_Log__c, 'Communication Log should match');
    }
    
    @isTest
    static void testUpdateSupportComment() {
        User awaitingUser = [SELECT Id FROM User WHERE Email = 'awaitinguser@test.com' LIMIT 1];
        Id supportTicketRecTypeId = Schema.SObjectType.CHATS_Support__c.getRecordTypeInfosByName().get('Support Ticket').getRecordTypeId();
        CHATS_Support__c supportRecord = new CHATS_Support__c(
            RecordTypeId = supportTicketRecTypeId,
            Status__c = 'Awaiting User',
            Awaiting_User__c = awaitingUser.Id,
            Support_Category__c = 'System',
            Support_Type__c = 'System Issue/Request',
            Expected_Results__c = 'test results',
            Actual_Results__c ='test results',
            Page_URL__c ='url'
        );
        insert supportRecord;
        
        CHATS_Support_Comment__c supportComment = new CHATS_Support_Comment__c(
            CHATS_Support_Number__c = supportRecord.Id,
            Communication_Log__c = 'Initial log for awaiting user'
        );
        insert supportComment;
        
        Test.startTest();
        supportComment.Communication_Log__c = 'Updated log for awaiting user';
        update supportComment;
        Test.stopTest();
        
        CHATS_Support_Comment__c updatedComment = [
            SELECT Id, Communication_Log__c 
            FROM CHATS_Support_Comment__c 
            WHERE Id = :supportComment.Id
        ];
        System.assertEquals('Updated log for awaiting user', updatedComment.Communication_Log__c, 'Communication Log should be updated');
    }
}