CHATS_SIT/force-app/main/default/objects/CHATS_Support__c.object
<CustomObject>
    <description>Object for chats county users to log issues, requests and questions, as well as for supervisors to submit new system-access requests.</description>
    <fields>
        <fullName>Date_Elevated__c</fullName>
        <inlineHelpText>Enter the date and time this ticket was sent to Vendor or OIT CHATS Team</inlineHelpText>
        <label>Date Elevated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Elevated_to__c</fullName>
        <label>Elevated to</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OIT</fullName>
                </value>
                <value>
                    <fullName>Vendor Support</fullName>
                </value>
                <value>
                    <fullName>System Administrator</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>CDHS</fullName>
                    <isActive>false</isActive>
                    <label>CDHS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reopened_By_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reopened By User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reopen_Reason__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Reopen Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause__c</fullName>
        <label>Root Cause</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cannot Reproduce</fullName>
                </value>
                <value>
                    <fullName>Change Request</fullName>
                </value>
                <value>
                    <fullName>Clarification</fullName>
                </value>
                <value>
                    <fullName>System Issue</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Pending Triage</fullName>
                    <default>true</default>
                    <label>Pending Triage</label>
                </value>
                <value>
                    <fullName>Access Request</fullName>
                </value>
                <value>
                    <fullName>Pending Research</fullName>
                </value>
                <value>
                    <fullName>Datafix</fullName>
                    <isActive>true</isActive>
                </value>
		<value>
                    <fullName>QE Provider</fullName>
                    <isActive>true</isActive>
                </value>  
                <value>
                    <fullName>Report Request</fullName>
                    <isActive>true</isActive>
                </value>   
                <value>
                    <fullName>Data Fix</fullName>
                    <isActive>false</isActive>
                </value>
                		    
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Default is &quot;new&quot;. State CCCAP Staff/Helpdesk update status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Awaiting User</fullName>
                </value>
                <value>
                    <fullName>Elevated</fullName>
                </value>
                <value>
                    <fullName>Fixed/Completed</fullName>
                </value>
                <value>
                    <fullName>Change Pending</fullName>
                </value>		
                <value>
                    <fullName>Change Approved</fullName>
                </value>
                <value>
                    <fullName>Change Denied</fullName>
                </value>
                <value>
                    <fullName>Change Implemented</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                 <value>
                    <fullName>Pending Research</fullName>
                </value>
                <value>
                    <fullName>Pending Leadership Review</fullName>
                </value>
                <value>
                    <fullName>Pending CCCAP Team Review</fullName>
                </value>
                <value>
                    <fullName>Pending CCMTG Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ticket_Closure_Date__c</fullName>
        <inlineHelpText>Date this ticket was resolved by State CCCAP Team/Helpdesk</inlineHelpText>
        <label>Ticket Closure Date</label>
        <type>DateTime</type>
    </fields>
    <label>Support</label>
    <nameField>
        <displayFormat>Support - {0000000000}</displayFormat>
        <label>CHATS Support Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Access_Request_Supervisor_Access_Only</fullName>
        <active>false</active>
        <description>Only Supervisors can select &quot;Access Request&quot;, &quot;Change Profile&quot;, or &quot;Deactivate Access&quot; from the pick-list</description>
        <errorConditionFormula>AND( 
ISPICKVAL(Support_Type__c, &quot;Access Request&quot;), 
ISPICKVAL(Support_Type__c, &quot;Deactivate Access&quot;),
ISPICKVAL(Support_Type__c, &quot;Change Profile&quot;),
And( 
$Profile.Name &lt;&gt; &quot;Eligibility Worker Supervisor&quot;, 
$Profile.Name &lt;&gt; &quot;Fiscal Worker Supervisor&quot;,
$Profile.Name &lt;&gt; &quot;Provider Worker Supervisor&quot;,
$Profile.Name &lt;&gt; &quot;Universal User&quot;,
$Profile.Name &lt;&gt; &quot;System Administrator&quot;,
$Profile.Name &lt;&gt; &quot;System Admin&quot;,
$Profile.Name &lt;&gt; &quot;CHATS System Administrator&quot;
))</errorConditionFormula>
        <errorDisplayField>Support_Type__c</errorDisplayField>
        <errorMessage>You must be a Supervisor or Universal Worker to select &quot;Access Request&quot;, &quot;Change Profile&quot;, or &quot;Deactivate Access&quot;.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_CHATS_Area_if_Supp_Cat_is_System</fullName>
        <active>false</active>
        <errorConditionFormula>AND(ISPICKVAL(Support_Category__c , &apos;System&apos;), RecordType.DeveloperName =&apos;Support_Ticket&apos;,  ISPICKVAL(CHATS_Area__c , &apos;&apos;)    )</errorConditionFormula>
        <errorDisplayField>CHATS_Area__c</errorDisplayField>
        <errorMessage>Required when Support Category is System.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_Temp_Access_if_Access_Req_Is_New_Wo</fullName>
        <active>false</active>
        <errorConditionFormula>AND(ISPICKVAL(  Access_Level_Requested__c , &apos;Universal User&apos;), RecordType.DeveloperName =&apos;System_Access_Request&apos;,  OR(ISBLANK(  Temporary_Access_End_Date__c ),Temporary_Access_End_Date__c &lt; TODAY(),Temporary_Access_End_Date__c &gt; TODAY() + ( ( 365 / 12 ) * 6) ))</errorConditionFormula>
        <errorDisplayField>Temporary_Access_End_Date__c</errorDisplayField>
        <errorMessage>Required when Access Type is New Worker Access Request. And it must be less than or equal to 6 months from Today.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Valid_Future_Scheduled_Date</fullName>
        <active>false</active>
        <errorConditionFormula>Scheduled_PROD_Release_Date__c &lt;= TODAY()</errorConditionFormula>
        <errorDisplayField>Scheduled_PROD_Release_Date__c</errorDisplayField>
        <errorMessage>It should have future date.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/classes/updateSupportTicketController.cls
public with sharing class updateSupportTicketController {
    @auraEnabled
    public static void onCloseButtonClick(string recordId){
        System.debug('The Record Id -->'+recordId);
        List<CHATS_Support__c> clsRecordList = new List<CHATS_Support__c>();
        CHATS_Support__c updCloseRecord = new CHATS_Support__c( id = recordId,
                                                               Status__c = 'Fixed/Completed',
                                                               Root_Cause__c= 'Clarification',
                                                               Ticket_Closure_Date__c= system.now());
        clsRecordList.add(updCloseRecord);
        //update updCloseRecord;
        if(!clsRecordList.isEmpty()){
            GenericDMLHandler.updateRecords(clsRecordList,null);
        }
        
    }

    @auraEnabled
    public static Boolean canAccessReopenButtonComponent(){
        //List<Profile> profile = [SELECT Id FROM Profile WHERE Name='Read Only User' LIMIT 1]; Moving to custom permission CCCAP-14993
        // CCCAP-14993 Using custom permission
        if(FeatureManagement.checkPermission('Read_Only_User')){
            if([select Count() from PermissionSetAssignment where Assignee.Id = :UserInfo.getUserId() AND PermissionSet.Name = 'County_Security_Administrator']==0){
            	return false;    
            }            
        }
        return true;
    }
    
    @auraEnabled
    public static void onReopenButtonClick(string recordId, string reOpenReason){
        System.debug('The Record Id -->'+recordId);
        datetime emptyDate = null;
        List<CHATS_Support__c> reopenRecordList = new List<CHATS_Support__c>();
        CHATS_Support__c updReopenRecord = new CHATS_Support__c( id = recordId,
                                                               	Status__c = 'Reopened',
                                                               	Root_Cause__c= 'Pending Triage',
                                                               	Ticket_Closure_Date__c= emptyDate,
                                                              	Date_Elevated__c = emptyDate,
                                                                Reopened_By_User__c= true,
                                                                Reopen_Reason__c= reOpenReason,
                                                               	Elevated_to__c = null);
        
       	reopenRecordList.add(updReopenRecord);
        if(!reopenRecordList.isEmpty()){
            GenericDMLHandler.updateRecords(reopenRecordList,null);
        }
        
    }
    
}