CHATS_SIT/force-app/main/default/objects/Client_Complaint__c.object
<CustomObject>
    <description>CCCAP-15359</description>
    <fields>
        <fullName>IDN_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Client Complaints</relationshipLabel>
        <relationshipName>Client_Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>byPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CCCAP-15359 To bypass validation rules from backend</description>
        <label>byPassValidation</label>
        <type>Checkbox</type>
    </fields>
    <label>Client Complaint</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Complaint ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT__c.object
<CustomObject>
    <description>Adjustment parent table that contains information about provider and case payment corrections</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Adjustment County</relationshipLabel>
        <relationshipName>Adjustment_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Provider_License_Closed</fullName>
        <active>false</active>
        <description>On Closed Provier Adjustment of type Claim can not be created</description>
        <errorConditionFormula>AND(  TEXT(CDE_TYPE_ADJMT__c) = &apos;1&apos;,NOT(ISPICKVAL( IDN_PROVR__r.CDE_STATUS_PROVR__c , &apos;Open&apos;)),OR((TEXT( CDE_STATUS_ADJMT__c ) = &apos;&apos;),(TEXT(CDE_STATUS_ADJMT__c) = &apos;1&apos;)) )</errorConditionFormula>
        <errorMessage>Adjustment cannot be created for the care dates when provider license status is closed</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_CANCEL__c.object
<CustomObject>
    <description>This object will store the details of all the Recovery Adjustment Cancellations</description>
    <label>Adjustment Cancellation</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Cancellation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustment Cancellation</relationshipLabel>
        <relationshipName>Adjustment_Cancellation</relationshipName>
        <type>Lookup</type>
    </fields>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Status_Based_Access</fullName>
        <active>false</active>
        <description>When the cancellation record is in Submitted, Approved, Denied or Withdrawn the record will not be editable</description>
        <errorConditionFormula>AND(OR($Profile.Name = &quot;Business Office Supervisor&quot;, $Profile.Name = &quot;Universal User&quot;,$Profile.Name = &quot;Fiscal Worker Supervisor&quot;, $Profile.Name = &quot;CCCAP Program Internal Team&quot;),OR(ISPICKVAL(CDE_STATUS__c, &apos;2&apos;),ISPICKVAL(CDE_STATUS__c, &apos;3&apos;),ISPICKVAL(CDE_STATUS__c, &apos;4&apos;),ISPICKVAL(CDE_STATUS__c, &apos;6&apos;)))</errorConditionFormula>
        <errorMessage>This record can only be edited in Draft or Need Revision Status.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>T_AUTH</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_AUTH__c</fullName>
        <description>Authorization Begin Date</description>
        <label>Authorization Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_AUTH__c</fullName>
        <label>Authorization End Date</label>
        <type>Date</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY_OWNER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY_OWNER__c</fullName>
        <description>CHAT-489</description>
        <formula>IF(ISBLANK(ID_SERVICE__r.CDE_COUNTY_OWNER__c) , &apos;&apos;, 
HYPERLINK(&quot;/&quot; &amp; ID_SERVICE__r.CDE_COUNTY_OWNER__c, ID_SERVICE__r.CDE_COUNTY_OWNER__r.Name)
)</formula>
        <label>Owner County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SLOT_CONTRACT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Slot Contract</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slot Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SLOT_CONTRACT_ADDENDUM__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Slot Contract Addendums</relationshipLabel>
        <relationshipName>Slot_Contract_Addendums</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Slot Contract Addendum</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slot Contract Addendums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/BulkTransferAPXCtrl.cls
public without sharing class BulkTransferAPXCtrl {

    Public Static Boolean isSuccessful = true;
    Public Static String message = '';
    Public Static Integer successfulUpdates;
    Public Static Integer failedUpdates;

    @auraEnabled
    public Static LightningServerResponse transferItems(String countyId, String fromUserId, String toUserId, String transferType, String subject){
        Map<String, Object> objectData = new map<String, Object>();
        Boolean countyMatched = CHATSUtility.checkCountyWithUserCounty(countyId);
        if(countyMatched) {
            List<Id> lstItemIds = getItemIds(transferType, fromUserId, countyId, subject);
            //List<Id> lstItemIdsTask=getTaskId(lstItemIds,countyId,fromUserId);
            if(lstItemIds.size() > 1000) {
                BulkTransferBatch batchprocess = new BulkTransferBatch(lstItemIds, toUserId, transferType);
                Database.executeBatch(batchprocess);
                objectData.put('itemTransferred', lstItemIds.size());
                isSuccessful = true; 
            } else if(lstItemIds.size()>0) {
                updateOwner(transferType, toUserId, lstItemIds );
                objectData.put('itemTransferred', successfulUpdates);
                objectData.put('failedUpdates', failedUpdates);
            } else {
                isSuccessful = false;
                message = Label.No_Records_Found_for_transfer;
            }
        } else {
            String countyName = [SELECT Name FROM T_COUNTY__c WHERE Id =: countyId LIMIT 1][0].Name;
            String objType = transferType == '1' ? 'case' : (transferType=='2' ? 'Fiscal Agreement' : 'task');
            isSuccessful = false;
            message = 'The ' + objType + ' records that you are trying to access belong to ' + countyName + ' county. This does not match your assigned county(ies).';
        }   
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
       
    public static List<Id> getTaskId(List<Id> lstItemIds1, String countyId, String fromUserId){
        List<Id> lstItemTaskIds = new List<Id>();
        List<Id> lstRelatedCaseFAIds = new List<Id>();
        for(T_SBSD_Case__c caseRec : [SELECT Id FROM T_SBSD_Case__c WHERE CDE_COUNTY__c =: countyId WITH SECURITY_ENFORCED]){
            lstRelatedCaseFAIds.add(caseRec.Id);
        }
        for(T_PROVR_FISCAL_AGREMENT__c prvrFiscalRec : [SELECT Id FROM T_PROVR_FISCAL_AGREMENT__c WHERE CDE_COUNTY__c =: countyId WITH SECURITY_ENFORCED]){
            lstRelatedCaseFAIds.add(prvrFiscalRec.Id); 
        }
        for(Task task : [SELECT Id FROM task WHERE WhatId IN: lstItemIds1 AND Status != 'Completed' WITH SECURITY_ENFORCED]){
            lstItemTaskIds.add(task.Id); 
        }
        return lstItemTaskIds;
    }

    public static List<Id> getItemIds(String transferType, String fromUserId, String countyId, String subject){
        List<Id> lstItemIds = new List<Id>();
        List<Profile> profileName = [Select Name from Profile where Id =: UserInfo.getProfileId()];
        String countyName = [SELECT Name FROM T_COUNTY__c WHERE Id =: countyId LIMIT 1][0].Name;
        Boolean skipCountyCheck = false;
        if(countyName.contains('All County')){
            skipCountyCheck = true;
        }        
        // Escape all string parameters to prevent SOQL injection
        transferType = String.escapeSingleQuotes(transferType);
        fromUserId = String.escapeSingleQuotes(fromUserId);
        countyId = String.escapeSingleQuotes(countyId);
        if(String.isNotBlank(subject)){
            subject = String.escapeSingleQuotes(subject);
        }        
        if(transferType == '1') {
            String caseQuery = 'SELECT Id FROM T_SBSD_Case__c WHERE ownerId = :fromUserId';
            if(!skipCountyCheck) {
                caseQuery += ' AND CDE_COUNTY__c = :countyId';
            }
            caseQuery += ' WITH SECURITY_ENFORCED';
            
            for(T_SBSD_Case__c caseRec : Database.query(caseQuery)){
                lstItemIds.add(caseRec.Id); 
            }
        } else if(transferType == '2') {
            String fiscalQuery = 'SELECT Id FROM T_PROVR_FISCAL_AGREMENT__c WHERE ownerId = :fromUserId';
            if(!skipCountyCheck) {
                fiscalQuery += ' AND CDE_COUNTY__c = :countyId';
            }
            fiscalQuery += ' AND CDE_TYPE_STATUS__c != \'CLS\' WITH SECURITY_ENFORCED';
            
            for(T_PROVR_FISCAL_AGREMENT__c prvrFiscalRec : Database.query(fiscalQuery)){
                lstItemIds.add(prvrFiscalRec.Id); 
            }
        }
        else if (transferType=='3'){
            String query = 'SELECT Id, WhatId FROM Task Where OwnerId =:fromUserId and Status != \'Completed\'';
            if(String.isNotBlank(subject)){
                query += ' and Subject =:subject';
            }
            List<Task> taskList = Database.query(query);
            
            if(taskList.isEmpty()){
                return lstItemIds;
            }
            
            set<Id> whatIdSet = new set<Id>();            
            for(Task task : taskList){
                whatIdSet.add(task.WhatId);
            }
            
            set<Id> validWhatIds = new set<Id>();
            String caseQuery = 'SELECT Id FROM T_SBSD_Case__c WHERE Id IN :whatIdSet';
            if(!skipCountyCheck) {
                caseQuery += ' AND CDE_COUNTY__c = :countyId';
            }
            caseQuery += ' WITH SECURITY_ENFORCED';
            for (T_SBSD_Case__c caseRec : Database.query(caseQuery)){
                validWhatIds.add(caseRec.Id);
            }
            String fiscalQuery = 'SELECT Id FROM T_PROVR_FISCAL_AGREMENT__c WHERE Id IN :whatIdSet';
            if(!skipCountyCheck) {
                fiscalQuery += ' AND CDE_COUNTY__c = :countyId';
            }
            fiscalQuery += ' WITH SECURITY_ENFORCED';
            for (T_PROVR_FISCAL_AGREMENT__c prvrFiscalRec : Database.query(fiscalQuery)){
                validWhatIds.add(prvrFiscalRec.Id); 
            }
            Date todayDate = System.today();
            String authQuery = 'SELECT Id FROM T_AUTH__c WHERE DTE_BEGIN_EFFV_AUTH__c <= :todayDate AND (DTE_END_EFFV_AUTH__c = null OR DTE_END_EFFV_AUTH__c >= :todayDate) AND Id IN :whatIdSet';
            if(!skipCountyCheck) {
                authQuery += ' AND CDE_COUNTY__c = :countyId';
            }
            authQuery += ' WITH SECURITY_ENFORCED';
            for (T_AUTH__c authRec : Database.query(authQuery)){
                validWhatIds.add(authRec.Id); 
            }
            String slotQuery = 'SELECT Id FROM T_SLOT_CONTRACT__c WHERE Id IN :whatIdSet';
            if(!skipCountyCheck) {
                slotQuery += ' AND CDE_COUNTY__c = :countyId';
            }
            slotQuery += ' WITH SECURITY_ENFORCED';
            for (T_SLOT_CONTRACT__c slotRec : Database.query(slotQuery)){
                validWhatIds.add(slotRec.Id); 
            }
            String slotAddQuery = 'SELECT Id FROM T_SLOT_CONTRACT_ADDENDUM__c WHERE Id IN :whatIdSet';
            if(!skipCountyCheck) {
                slotAddQuery += ' AND CDE_COUNTY__c = :countyId';
            }
            slotAddQuery += ' WITH SECURITY_ENFORCED';
            for (T_SLOT_CONTRACT_ADDENDUM__c slotAdd : Database.query(slotAddQuery)){
                validWhatIds.add(slotAdd.Id); 
            }
            // Added by Rishav for CCCAP-4373
            String provStatusQuery = 'SELECT Id FROM T_CHATS_PROVR_STATUS__c WHERE Id IN :whatIdSet';
            if(!skipCountyCheck) {
                provStatusQuery += ' AND CDE_COUNTY_OWNER__c = :countyId';
            }
            provStatusQuery += ' WITH SECURITY_ENFORCED';
            for(T_CHATS_PROVR_STATUS__c provRec : Database.query(provStatusQuery)){
                validWhatIds.add(provRec.Id); 
            }

            String clientComplaintQuery = 'SELECT Id FROM Client_Complaint__c WHERE Id IN :whatIdSet';
            if(!skipCountyCheck) {
                clientComplaintQuery += ' AND IDN_COUNTY__c = :countyId';
            }
            for(Client_Complaint__c complaintRec : Database.query(clientComplaintQuery)){
                validWhatIds.add(complaintRec.Id); 
            }
            
            // Added by Raina for CCCAP-7876
            //CCCAP-14993 Using Custom Permission
            if(FeatureManagement.checkPermission('Universal_User') || FeatureManagement.checkPermission('Fiscal_Worker_Supervisor') || FeatureManagement.checkPermission('Business_Office_Supervisor') || FeatureManagement.checkPermission('System_Administrator') || FeatureManagement.checkPermission('CCCAP_Program_Internal_Team')) {
                String adjCancelQuery = 'SELECT Id FROM T_ADJMT_CANCEL__c WHERE Id IN :whatIdSet';
                if(!skipCountyCheck) {
                    adjCancelQuery += ' AND IDN_ADJMT__r.CDE_COUNTY__c = :countyId';
                }
                adjCancelQuery += ' WITH SECURITY_ENFORCED';
                for(T_ADJMT_CANCEL__c adjCanRec : Database.query(adjCancelQuery)){
                    validWhatIds.add(adjCanRec.Id); 
                }
            }
            
            for(Task task : taskList){
                if(validWhatIds.contains(task.WhatId)){
                	lstItemIds.add(task.Id); 
                }
            }
        }  

        return lstItemIds;
    }
    
    public static void updateOwner(String transferType, String toUserId, List<Id> lstItemIds){
        List<Id> lstToBeUpdated = new List<Id>();
        if(lstItemIds.size() > 10000) {
            for(integer i=0; i<10000; i++){
                lstToBeUpdated.add(lstItemIds[i]);
            }
        } else {
            for(Id eachId : lstItemIds){
                lstToBeUpdated.add(eachId);
            }
        }        
        try {
            T_SBSD_Case__c caseRec;
            if(transferType == '1'){
                List<T_SBSD_Case__c> lstCaseRec = new List<T_SBSD_Case__c>();
                for(Id itemId : lstToBeUpdated){
                    caseRec = new T_SBSD_Case__c();
                    caseRec.Id = itemId;
                    caseRec.OwnerId = toUserId;
                    lstCaseRec.add(caseRec);
                }
                List<Database.SaveResult> lstSr = Database.update(lstCaseRec, false);
                ExceptionLoggingServices.captureExceptionLog(lstSr, lstCaseRec, new Map<String, Object>{'Class__c'=>'BulkTransferAPXCtrl', 'Method__c'=>'updateOwner'});
                isSuccessful = true;
                Integer success = 0;
                Integer failed = 0;
                List<Id> itemsUpdated = new List<Id>();
                for(Database.SaveResult sr : lstSr){
                    if(sr.isSuccess()) {
                        success++;
                        itemsUpdated.add(sr.getId());
                    } else {
                        failed++;
                    }
                }
                successfulUpdates = success;
                failedUpdates = failed;
                updateTaskOwners(itemsUpdated, toUserId);             
            }
            if(transferType == '2'){
                List<T_PROVR_FISCAL_AGREMENT__c> lstPFARec = new List<T_PROVR_FISCAL_AGREMENT__c>();
                T_PROVR_FISCAL_AGREMENT__c pFARec;
                for (Id itemId : lstToBeUpdated){
                    pFARec = new T_PROVR_FISCAL_AGREMENT__c();
                    pFARec.Id = itemId;
                    pFARec.OwnerId = toUserId;
                    lstPFARec.add(pFARec);
                }
                List<Database.SaveResult> lstSr = Database.update(lstPFARec, false);
                ExceptionLoggingServices.captureExceptionLog(lstSr, lstPFARec, new Map<String, Object>{'Class__c'=>'BulkTransferAPXCtrl', 'Method__c'=>'updateOwner'});
                isSuccessful = true;
                Integer success = 0;
                Integer failed = 0;
                List<Id> itemsUpdated = new List<Id>();
                for(Database.SaveResult sr: lstSr){
                    if(sr.isSuccess()) {
                        success++;
                        itemsUpdated.add(sr.getId());
                    } else {
                        failed++;
                    }
                }
                successfulUpdates = success;
                failedUpdates = failed;
                updateTaskOwners(itemsUpdated, toUserId);           
            }
            if(transferType == '3'){
                // Identify T236/T237 tasks and bypass validation on related complaints
                Set<Id> complaintWhatIds = new Set<Id>();
                Set<String> clientComplaintSubjects = new Set<String>{
                    System.Label.Task_T236_Subject,
                    System.Label.Task_T237_Subject
                };
                for (Task t : [SELECT Id, Subject, WhatId FROM Task WHERE Id IN :lstToBeUpdated]) {
                    if (t.WhatId != null && clientComplaintSubjects.contains(t.Subject)) {
                        complaintWhatIds.add(t.WhatId);
                    }
                }
                List<Client_Complaint__c> complaintsToBypass = new List<Client_Complaint__c>();
                if (!complaintWhatIds.isEmpty()) {
                    for (Client_Complaint__c cc : [SELECT Id FROM Client_Complaint__c WHERE Id IN :complaintWhatIds]) {
                        complaintsToBypass.add(new Client_Complaint__c(Id = cc.Id, byPassValidation__c = true));
                    }
                    Database.update(complaintsToBypass, false);
                }

                List<Task> lstTaskRec = new List<Task>();
                Task taskRec;
                for(Id itemId : lstToBeUpdated){
                    taskRec = new Task();
                    taskRec.Id = itemId;
                    taskRec.OwnerId = toUserId;
                    lstTaskRec.add(taskRec);
                }
                List<Database.SaveResult> lstSr = Database.update(lstTaskRec, false);
                ExceptionLoggingServices.captureExceptionLog(lstSr, lstTaskRec, new Map<String, Object>{'Class__c'=>'BulkTransferAPXCtrl', 'Method__c'=>'updateOwner'});
                isSuccessful = true;
                Integer success = 0;
                Integer failed = 0;
                for(Database.SaveResult sr : lstSr){
                    if(sr.isSuccess()) {
                        success++;
                    } else {
                        failed++;
                    }
                }
                successfulUpdates = success;
                failedUpdates = failed;

                //Re-disable bypass flag after task owner update
                if (!complaintsToBypass.isEmpty()) {
                    for (Client_Complaint__c cc : complaintsToBypass) {
                        cc.byPassValidation__c = false;
                    }
                    Database.update(complaintsToBypass, false);
                }
            }
        } catch(Exception e) {
            message = e.getMessage();
            isSuccessful = false;
            Map<String, Object> exceptionMap = new Map<String, Object>();
            exceptionMap.put('Class__c', 'BulkTransferAPXCtrl');    
            exceptionMap.put('Method__c', 'updateOwner');            
            ExceptionLoggingServices.captureExceptionLog(e, exceptionMap);
        }
    }

    public static void updateTaskOwners(List<Id> recordIds, Id toUserId){
        List<task> lstTaskToBeUpdated = new List<task>();
        for(Task task : [SELECT Id FROM task WHERE WhatId IN: recordIds AND Status != 'Completed']){
            task.OwnerId = String.escapeSingleQuotes(toUserId);
            lstTaskToBeUpdated.add(task);
        }
        if(!lstTaskToBeUpdated.isEmpty()){
            List<Database.SaveResult> lstSr = Database.update(lstTaskToBeUpdated, false);
        }
    }
}