CHATS_SIT/force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CI_Client_Id__c</fullName>
        <label>Client Id</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Successful_Login__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Successful Login</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PIN_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PIN Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pin_Reset_Code_Generated_Time__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Pin Code Expiration</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/ContactTriggerTest.cls
@isTest
public class ContactTriggerTest {
    public static testmethod void testContact (){
        Contact c1 = new Contact(LastName = 'Lname', CI_Client_Id__c = 123456,Last_Successful_Login__c = system.now(), Pin_Reset_Code_Generated_Time__c = system.now(), PIN_Status__c = 'Expired');
        
        test.startTest();
        insert c1;
        system.assertNotEquals('Exp', c1.PIN_Status__c, 'Status mismatch as the contact gets deleted');
        test.stopTest();
    }
}