CHATS_SIT/force-app/main/default/objects/Exception_Log__c.object
<CustomObject>
    <description>The object stores all the exceptions that were catched through out the applications for debugging and reporting purpose.</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Stores the message that was returned from the exception generated.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>Stores the type of exception that has occured</description>
        <label>Exception Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PII_Information__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>PII Information</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>This field will be populated for Call out exceptions and will store the request that was passed to the webservice call out.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>This field is specifically for call out exceptions. It will store the response that we received from the wenservice call outs.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>Stores the stack trace returned from the Exception generated</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Type__c</fullName>
        <label>Log Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Exception_Logging_Framework_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This will store settings related to Exception Logging Framework.</description>
    <fields>
        <fullName>Enable_Exception_Log__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enable Exception Log</label>
        <type>Checkbox</type>
    </fields>
    <label>Exception Logging Framework Settings</label>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/PII_Exception__mdt.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <label>Method Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PII_in_Exception_Message__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PII in Exception Message</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PII_in_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PII in Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PII_in_Response__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PII in Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PII_in_Stack_Trace__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PII in Stack Trace</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Success_Log_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used for controlling the success callout logging.</description>
        <label>Success Log Required</label>
        <type>Checkbox</type>
    </fields>    
    <label>Log Setup</label>
    <pluralLabel>Log Setup</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/ExceptionLoggingServices.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           06/25/2018                                                          
*  @description    Utility class to log all the exceptions.
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 25-Jun-2018                                                            
*  * Author: Shubham Jain                                                      
*  * Description: Initial version                                                 
*  * JIRA Ticket: 
*  * 
*********************************************************************************************/
public with sharing class ExceptionLoggingServices {

    static Boolean logException = Exception_Logging_Framework_Settings__c.getInstance().Enable_Exception_Log__c;
    static List<PII_Exception__mdt> lstPIIExceptionData = [SELECT Class_Name__c, Method_Name__c,PII_in_Exception_Message__c,Success_Log_Required__c, PII_in_Stack_Trace__c, PII_in_Request__c ,PII_in_Response__c FROM PII_Exception__mdt];
    public static Boolean pIIData= false;
    public static Boolean pIIDataInStackTrace= false;
    public static Boolean pIIDataInExceptionMsg= false;
    public static Boolean pIIDataInRequest= false;
    public static Boolean pIIDataInResponse= false;
     public static Boolean isSuccessLog= false;
    private static Boolean insertLog = true;
    
    public static Exception_Log__c captureExceptionLogInstance(Exception ex, Map<String, Object> methodInfo){
        insertLog = false;
        return captureExceptionLog(ex,methodInfo);
    }
    public static List<Exception_Log__c> captureExceptionLogInstance(List<Database.SaveResult> lstSaveResults, List<SObject> lstSObject, Map<String, Object> methodInfo){
        insertLog = false;
        return captureExceptionLog(lstSaveResults,lstSObject,methodInfo);
    }
    
    public static List<Exception_Log__c> captureExceptionLog(List<Database.SaveResult> lstSaveResults, List<SObject> lstSObject, Map<String, Object> methodInfo){
        setPIIParameters(methodInfo);
        List<Exception_Log__c> xLogs = new List<Exception_Log__c>();
        if(logException){
            try{
                Exception_Log__c xLog;
                for(Integer i=0;i<lstSObject.size();i++){
                    if(lstSaveResults.size()>i && !lstSaveResults[i].isSuccess()){
                        String errorMessage = '';
                        for(Database.Error error:lstSaveResults[i].getErrors()){
                            errorMessage+=error.getMessage();
                        }
                        xLog = new Exception_Log__c();                
                        if(methodInfo!=null){
                            if(methodInfo.containsKey('Class__c')){
                                xLog.Class__c = String.valueOf(methodInfo.get('Class__c'));
                            }
                            if(methodInfo.containsKey('Method__c')){
                                xLog.Method__c = String.valueOf(methodInfo.get('Method__c'));
                            }
                        }
                        xLog.Record_ID__c = lstSObject[i].Id;
                        if(!pIIDataInExceptionMsg){
                            xLog.Exception_Message__c = errorMessage;
                        }
                        else{
                            xLog.Exception_Message__c = Label.PII_Information;
                            xLog.PII_Information__c += 'Exception Msg: '+errorMessage;
                        }
                        xLog.Exception_Type__c = 'DML Error';
                        if(errorMessage.containsIgnoreCase('exception') || errorMessage.length() > 0 ){
                            xLogs.add(trimXLogData(xLog));
                        }
                    }
                }
                if(methodInfo==null){
                    methodInfo = new Map<String, Object>();
                }
                methodInfo.put('byPassExceptionLogging',true);
                if(insertLog){
	                GenericDMLHandler.insertRecords(xLogs, methodInfo);                    
                }
            }catch(Exception ex){
                captureExceptionLog(ex,methodInfo);
            }
        }
        return xLogs;
    }
    
    public static Exception_Log__c captureExceptionLog(Exception ex, Map<String, Object> methodInfo){
        setPIIParameters(methodInfo);
        Exception_Log__c xLog = new Exception_Log__c();
        if(logException){
            try{
                if(methodInfo!=null){
                    if(methodInfo.containsKey('Class__c')){
                        xLog.Class__c = String.valueOf(methodInfo.get('Class__c'));
                    }
                    if(methodInfo.containsKey('Method__c')){
                        xLog.Method__c = String.valueOf(methodInfo.get('Method__c'));
                    }
                    if(methodInfo.containsKey('Record_ID__c')){
                        xLog.Record_ID__c = String.valueOf(methodInfo.get('Record_ID__c'));
                    }
                }
                if(ex!=null){
                    xLog.Exception_Type__c = ex.getTypeName();
                    if(!pIIDataInExceptionMsg){
                        xLog.Exception_Message__c = ex.getMessage();
                    }else{
                        xLog.Exception_Message__c = Label.PII_Information;
                        xLog.PII_Information__c += 'Exception Msg: '+ ex.getMessage();
                    }
                    if(!pIIDataInStackTrace){
                    xLog.Stack_Trace__c = ex.getStackTraceString();
                    } else{
                        xLog.Stack_Trace__c = Label.PII_Information ; 
                        xLog.PII_Information__c += 'Stack Trace: '+ ex.getStackTraceString();
                    }
                }
                if(xLog.getSObjectType().getDescribe().isCreateable() && insertLog){
                    insert trimXLogData(xLog);
                }
            }catch(Exception exc){
                captureExceptionLog(exc, methodInfo);
            }
        }
        return xLog;
    }
    
    public static void captureExceptionLog(Exception_Log__c xLog){
        setSuccessLogParam(xLog);
        if(logException){
            try{
                if(String.isNotEmpty(xLog.Log_Type__c) && xLog.Log_Type__c == 'Success'){
                    if(isSuccessLog){
                        if(xLog.getSObjectType().getDescribe().isCreateable()){
                            insert trimXLogData(xLog);
                        }   
                    }
                }else{
                    if(xLog.getSObjectType().getDescribe().isCreateable()){
                        insert trimXLogData(xLog);
                    } 
                }
            }catch(Exception exc){
                Map<String, Object> methodInfo = new Map<String, Object>();
                methodInfo.put('Class__c', xLog.Class__c);
                methodInfo.put('Method__c', xLog.Method__c);
                captureExceptionLog(exc, methodInfo);
            }
        }
    }
    
    public static void captureExceptionLog(HttpResponse res, HttpRequest req,Map<String, Object> methodInfo){
        setPIIParameters(methodInfo);
        if(logException){
            
            Exception_Log__c xLog = new Exception_Log__c();
            try{
                if(methodInfo!=null){
                    if(methodInfo.containsKey('Class__c')){
                        xLog.Class__c = String.valueOf(methodInfo.get('Class__c'));
                    }
                    if(methodInfo.containsKey('Method__c')){
                        xLog.Method__c = String.valueOf(methodInfo.get('Method__c'));
                    }
                    if(methodInfo.containsKey('Record_ID__c')){
                        xLog.Record_ID__c = String.valueOf(methodInfo.get('Record_ID__c'));
                    }
                }
                if(res!=null){
                    if(!pIIDataInExceptionMsg){
                    	xLog.Exception_Message__c = 'Status is :'+res.getStatus()+',Status Code is :'+String.valueOf(res.getStatusCode());
                    }else{
                        xLog.Exception_Message__c = Label.PII_Information;
                        xLog.PII_Information__c += 'Exception Msg: '+ 'Status is :'+res.getStatus()+',Status Code is :'+String.valueOf(res.getStatusCode());
                    }
                    if(res.getStatusCode()!=null){
                        xLog.Exception_Type__c = 'Web Service';
                    }
                    if(!pIIDataInResponse){
                    xLog.Response__c = res.getBody();
                    }
                    else{
                        xLog.Response__c = Label.PII_Information;
                        xLog.PII_Information__c += ' Response :'+res.getBody();
                    }
                }
                if(req!=null){
                    if(!pIIDataInRequest){
                    xLog.Request__c = 'End point:'+req.getEndpoint()+':'+req.getBody();
                    }
                    else{
                        xLog.Request__c =Label.PII_Information;
                        xLog.PII_Information__c += ' Request: '+ 'End point:'+req.getEndpoint()+':'+req.getBody();
                    }
                }
                if(xLog.getSObjectType().getDescribe().isCreateable()){
                    insert trimXLogData(xLog);
                }
            }catch(Exception ex){
                captureExceptionLog(ex,methodInfo);
            }
        }
    }   
    public static Exception_Log__c trimXLogData(Exception_Log__c xLog){
        if(String.isNotEmpty(xLog.Exception_Message__c) && xLog.Exception_Message__c.length()>255){
            xLog.Exception_Message__c = xLog.Exception_Message__c.subString(0,254);
        }        
        if(String.isNotEmpty(xLog.Exception_Type__c) && xLog.Exception_Type__c.length()>50){
            xLog.Exception_Type__c = xLog.Exception_Type__c.subString(0,49);
        } 
        if(String.isNotEmpty(xLog.Method__c) && xLog.Method__c.length()>50){
            xLog.Method__c = xLog.Method__c.subString(0,49);
        } 
        if(String.isNotEmpty(xLog.Request__c) && xLog.Request__c.length()>131072){
            xLog.Request__c = String.escapeSingleQuotes(xLog.Request__c).subString(0,131071);
        } 
        if(String.isNotEmpty(xLog.Response__c) && xLog.Response__c.length()>131072){
            xLog.Response__c = String.escapeSingleQuotes(xLog.Response__c).subString(0,131071);
        } 
        if(String.isNotEmpty(xLog.Stack_Trace__c) && xLog.Stack_Trace__c.length()>131072){
            xLog.Stack_Trace__c	= String.escapeSingleQuotes(xLog.Stack_Trace__c).subString(0,131071);
        }
        if(String.isNotEmpty(xLog.PII_Information__c) && xLog.PII_Information__c.length()>4){
            if(xLog.PII_Information__c.substring(0,4)=='null'){
                xLog.PII_Information__c = xLog.PII_Information__c.subString(4,xLog.PII_Information__c.length()-1);
            } 
        }
        if(String.isNotEmpty(xLog.PII_Information__c) && xLog.PII_Information__c.length()>131072){
            xLog.PII_Information__c	= String.escapeSingleQuotes(xLog.PII_Information__c).subString(0,131071);
        } 
        // Added by Diya for Success callout logging
        if(String.isNotEmpty(xLog.Log_Type__c)){
            xLog.Log_Type__c	= String.escapeSingleQuotes(xLog.Log_Type__c);
        }
        // end
        return xLog;
    }
    public static void setPIIParameters (Map<String, Object> methodInfo) {
        for (PII_Exception__mdt pIIDataRec : lstPIIExceptionData){
            if(methodInfo!=null && methodInfo.containsKey('Class__c') && pIIDataRec.Class_Name__c.trim() == String.valueOf(methodInfo.get('Class__c')).trim() &&
               methodInfo.containsKey('Method__c') && pIIDataRec.Method_Name__c.trim() == String.valueOf(methodInfo.get('Method__c')).trim() ){
                  pIIData = true;
                   if(pIIDataRec.PII_in_Request__c == true){
                       pIIDataInRequest = true;
                   }
                   if(pIIDataRec.PII_in_Response__c == true){
                       pIIDataInResponse = true;
                   }
                   if(pIIDataRec.PII_in_Stack_Trace__c == true){
                       pIIDataInStackTrace = true;
                   }
                   if(pIIDataRec.PII_in_Exception_Message__c == true){
                       pIIDataInExceptionMsg = true;
                   }
                   break;
               }
        }
    }
    public static void setSuccessLogParam (Exception_Log__c xLog) {
        for (PII_Exception__mdt pIIDataRec : lstPIIExceptionData){
            if(xLog!=null && String.isNotEmpty(xLog.Class__c) && pIIDataRec.Class_Name__c.trim() == xLog.Class__c.trim() &&
               String.isNotEmpty(xLog.Method__c) && pIIDataRec.Method_Name__c.trim() == xLog.Method__c ){
                   if(pIIDataRec.Success_Log_Required__c == true){
                       isSuccessLog = true;
                   }
                   break;
               }	
        }
    }
}