CHATS_SIT/force-app/main/default/objects/Exception_Log__c.object
<CustomObject>
    <description>The object stores all the exceptions that were catched through out the applications for debugging and reporting purpose.</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Stores the message that was returned from the exception generated.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>Stores the type of exception that has occured</description>
        <label>Exception Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>DTE_RCVD_PACKET_REDET__c</fullName>
        <description>Redetermination Packet Received Date</description>
        <label>Redetermination Packet Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_SENT_PACKET_REDET__c</fullName>
        <description>Redetermination Packet Sent Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Redetermination Packet Sent Date</label>
        <type>Date</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>CDE_MODE_CASE__c</fullName>
        <description>Case Mode</description>
        <label>Case Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00358</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00358.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INT</fullName>
        <label>Intake</label>
    </customValue>
    <customValue>
        <fullName>ONG</fullName>
        <label>Ongoing</label>
    </customValue>
    <customValue>
        <fullName>RED</fullName>
        <label>Redetermination</label>
    </customValue>
    <description>R00358</description>
    <masterLabel>R00358</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/T309TaskCreationBatch.cls
/*************************************************************
Class Name      - T309TaskCreationBatch
Test Class      - T309TaskCreationBatch_Test
Description     - Task to remind users to initiate Redetermination once packet Received date is not null
Author          - Shashank Singla
Requiremnt      - CCCAP-9179
**************************************************************/
global with sharing class T309TaskCreationBatch implements Database.Batchable<sObject>, Database.Stateful, schedulable {
    
    global static List<Exception_Log__c> errors = new List<Exception_Log__c>();
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        date past_13_day = Date.today()-13;
        String queryStr ='SELECT Id,DTE_RCVD_PACKET_REDET__c,DTE_SENT_PACKET_REDET__c from T_SBSD_CASE__c where DTE_RCVD_PACKET_REDET__c=:past_13_day';
        return Database.getQueryLocator(queryStr);
    }
    
    global void execute(Database.BatchableContext bc, List<T_SBSD_CASE__c> scope) {
        try {
            List<Task> tasksToInsert = new List<Task>();
            Set<Id> selCases = new Set<Id>();
            // Preparing Case/Provider IDs from scope
            for(T_SBSD_CASE__c cs : scope){
                if(cs.DTE_RCVD_PACKET_REDET__c > cs.DTE_SENT_PACKET_REDET__c){
                    selCases.add(cs.Id);
                }                
            }
            Set<Id> REDfound = new Set<Id>();
            Map<Id,T_SBSD_CASE__c> caseModeIdVsCase = new Map<Id,T_SBSD_CASE__c>();
            for(T_SBSD_CASE__c csRecord : [select id,DTE_RCVD_PACKET_REDET__c ,Name,OwnerId, (select name,DTE_BEGIN_EFFV__c,CDE_MODE_CASE__c from T_SBSD_CASE10__r order by createddate desc) from T_SBSD_CASE__c where id In:selCases]){
                if(!csRecord.T_SBSD_CASE10__r.isEmpty()){
                    for(T_SBSD_CASE_STATUS_MODE__c csMode: csRecord.T_SBSD_CASE10__r){
                        caseModeIdVsCase.put(csMode.Id,csRecord);
                    }
                }
            }
            // if same case status mode is being modified for status(RED) after packet received date then below logic will detect that
            for(T_SBSD_CASE_STATUS_MODE__History csmH: [select  parentId,OldValue, NewValue,createdDate from T_SBSD_CASE_STATUS_MODE__History 
                                                        where ParentId IN:caseModeIdVsCase.keyset() and Field ='CDE_MODE_CASE__c']){
                                                            if(csmH.NewValue == 'RED' || (csmH.OldValue == 'RED' && csmH.NewValue == 'ONG')){
                                                              T_SBSD_CASE__c chatsCase = caseModeIdVsCase.get(csmH.ParentId);
                                                                if(csmH.CreatedDate >= chatsCase.DTE_RCVD_PACKET_REDET__c){
                                                                    REDfound.add(caseModeIdVsCase.get(csmH.parentId).Id); // RED record found after pckt received date                                                                    
                                                                }
                                                            }
                                                        }
            for(T_SBSD_CASE__c csRecord : [select id,DTE_RCVD_PACKET_REDET__c ,Name,OwnerId, 
                                           (select name,DTE_BEGIN_EFFV__c,CDE_MODE_CASE__c,createddate from T_SBSD_CASE10__r order by createddate desc)
                                           from T_SBSD_CASE__c where id In:selCases]){
                                               boolean noREDfound = !REDfound.contains(csRecord.Id);
                                               for(T_SBSD_CASE_STATUS_MODE__c csMode : csRecord.T_SBSD_CASE10__r){
                                                   if(csMode.CDE_MODE_CASE__c == 'RED' 
                                                      && (csMode.DTE_BEGIN_EFFV__c >=csRecord.DTE_RCVD_PACKET_REDET__c || csMode.createddate >=csRecord.DTE_RCVD_PACKET_REDET__c)){
                                                       noREDfound = false;
                                                   }
                                               }
                                               if(noREDfound){ //if no track of RED found , create Task T309
                                                   tasksToInsert.add(new Task(
                                                       OwnerId		=	csRecord.OwnerId,
                                                       description 	= 'The redetermination for '+csRecord.Name + '  has not been processed. Please process the packet and put the case into redetermination mode.',
                                                       Subject		=	'T309 Redetermination packet received date is 12 days ago',
                                                       Status		=	'Not Started',
                                                       WhatId		=	csRecord.Id,
                                                       ActivityDate =  csRecord.DTE_RCVD_PACKET_REDET__c+15));
                                               }
                                           }
            // DML for final Tasks and sending Emails
            if(!tasksToInsert.isEmpty()){
                Database.insert(tasksToInsert, false);
            }
        } catch(Exception e) {
            setException(e);
        }
    }
    global void finish(Database.BatchableContext bc) {
        if(errors.size()>0){
            GenericDMLHandler.insertRecords(errors, new Map<String, Object>{'Method__c'=>'finish','Class__c'=>'T309TaskCreationBatch'});
        }
    }
    global void execute(SchedulableContext sc){
        database.executebatch(new T309TaskCreationBatch(), 200);
    }
    @testVisible
    private static void setException(Exception e){
        Exception_Log__c xLog = new Exception_Log__c();
        xLog.Class__c = 'T309TaskCreationBatch';
        xLog.Method__c = 'execute';
        xLog.Exception_Message__c = e.getMessage();
        xLog.Exception_Type__c = 'Error';
        errors.add(xLog);
    }
}