CHATS_SIT/force-app/main/default/objects/Exception_Log__c.object
<CustomObject>
    <description>The object stores all the exceptions that were catched through out the applications for debugging and reporting purpose.</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Stores the message that was returned from the exception generated.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>Stores the type of exception that has occured</description>
        <label>Exception Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT__c.object
<CustomObject>
    <description>Adjustment parent table that contains information about provider and case payment corrections</description>
    <fields>
        <fullName>CDE_STATUS_ADJMT__c</fullName>
        <description>Adjustment Status</description>
        <label>Adjustment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00719</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_START_ADJMT__c</fullName>
        <description>Care Start Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DTE_EFFV_RECOVERY__c</fullName>
        <description>Project 353 | JIRA CCCAP-6051 | Updated when Recovery is finalized for the first time</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Recovery Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Finalized</fullName>
        <active>true</active>
        <label>Finalized</label>
    </recordTypes>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Provider_License_Closed</fullName>
        <active>false</active>
        <description>On Closed Provier Adjustment of type Claim can not be created</description>
        <errorConditionFormula>AND(  TEXT(CDE_TYPE_ADJMT__c) = &apos;1&apos;,NOT(ISPICKVAL( IDN_PROVR__r.CDE_STATUS_PROVR__c , &apos;Open&apos;)),OR((TEXT( CDE_STATUS_ADJMT__c ) = &apos;&apos;),(TEXT(CDE_STATUS_ADJMT__c) = &apos;1&apos;)) )</errorConditionFormula>
        <errorMessage>Adjustment cannot be created for the care dates when provider license status is closed</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Triggers_On_Off_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Triggers_On_Off_Settings</label>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00719.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>In Process</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calculation Complete</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Satisfied</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Paid</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Cancellation In Progress</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Cancelled</label>
    </customValue>
    <description>R00719</description>
    <masterLabel>R00719</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/AdjustmentDataFixBatch.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           5/24/2022                                                         
*  @description    Adjustment batch class for datafix                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 244-May-2022                                                             
*  * Author: Diya Chaudhary                                                      
*  * Description: Initial version                   
*********************************************************************************************/
global with sharing class AdjustmentDataFixBatch implements 
Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    public List<T_ADJMT__c> authNameList = new List<T_ADJMT__c>();
    public Set<Id> authTerminate = new Set<Id>();
    public Exception_Log__c[] errors = new Exception_Log__c[0];
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Date todayDate = system.today(); // this is referred in below dynamic query
        Date weekDate = system.today()-7; // this is referred in below dynamic query
        String status ='2';
        Id RecordTypeId = Schema.SObjectType.T_ADJMT__c.getRecordTypeInfosByName().get('Finalized').getRecordTypeId();
        String queryStr ='SELECT ID,Name, DTE_START_ADJMT__c,CreatedById,CreatedDate,DTE_EFFV_RECOVERY__c, IDN_EXTNL__c FROM T_ADJMT__c Where CDE_STATUS_ADJMT__c =:status and RecordTypeId = :RecordTypeId';
        system.debug('queryStr--'+queryStr);
        return Database.getQueryLocator(queryStr);
    }
    global void execute(Database.BatchableContext bc, List<T_ADJMT__c> adjList){
        try{
            List<T_ADJMT__c> adjLstToUpdate=  new List<T_ADJMT__c>();
            List<T_ADJMT__History> adjHist=  new List<T_ADJMT__History>();
            Set<Id> adjIds = new Set<Id>();
            for(T_ADJMT__c adj :adjList){
                adjIds.add(adj.id);
            }
            Triggers_On_Off_Settings__c triggerService =[select id,Active__c from Triggers_On_Off_Settings__c where name ='adjustmentTrigger' LIMIT 1];
            triggerService.Active__c = false;
            GenericDMLHandler.updateRecords(new List<SObject>{triggerService},new Map<String,Object>{'Method__c'=>'syncIndivAgeWithPostgres','Class__c'=>'UpdateIndivOnBirthDayBatch'});
            
            Date legacyDate = Date.newInstance(2018, 09, 01);
            Map<string,Datetime> adjustMap= new Map<string,Datetime>();
            Map<string,string> adjustRecTypeMap= new Map<string,string>();
            for(T_ADJMT__History hist :[SELECT ParentId, Id, CreatedDate, CreatedById, Field, NewValue, OldValue FROM T_ADJMT__History where ParentId in:adjIds and
                                        (Field ='CDE_STATUS_ADJMT__c' or  Field='RecordType') order by CreatedDate desc]){
                                            if(hist.NewValue =='2'){
                                                adjustMap.put(hist.ParentId, hist.CreatedDate);
                                            }
                                            if(hist.Field=='RecordType' && hist.NewValue =='Finalized'){
                                                adjustRecTypeMap.put(hist.ParentId, String.valueOf(hist.NewValue));
                                            }
                                        }
            for(T_ADJMT__c adj :adjList){
                if(adjustMap.containsKey(adj.id) && adjustRecTypeMap.containsKey(adj.id)){
                    adj.DTE_EFFV_RECOVERY__c  =Date.valueOf(adjustMap.get(adj.id)).addDays(15);
                    adjLstToUpdate.add(adj);
                }else{
                    adj.DTE_EFFV_RECOVERY__c  =Date.valueOf(adj.CreatedDate).addDays(15);
                    adjLstToUpdate.add(adj);
                }
            }
            if(adjLstToUpdate != null && adjLstToUpdate.size()>0){
                Database.update(adjLstToUpdate);
            }
            triggerService.Active__c = true;
            GenericDMLHandler.updateRecords(new List<SObject>{triggerService},new Map<String,Object>{'Method__c'=>'syncIndivAgeWithPostgres','Class__c'=>'UpdateIndivOnBirthDayBatch'});
            
            
        }
        catch(Exception e) {
            Exception_Log__c xLog = new Exception_Log__c();
            xLog.Class__c = 'AdjustmentDataFixBatch';
            xLog.Method__c = 'executeMethod';
            xLog.Exception_Message__c = 'AdjustmentDataFixBatch  for adjustment'+e.getMessage();
            xLog.Exception_Type__c = 'Error';
            errors.add(xLog);
        }
    }    
    global void finish(Database.BatchableContext bc){
        
    }    
}