CHATS_SIT/force-app/main/default/objects/Exception_Log__c.object
<CustomObject>
    <description>The object stores all the exceptions that were catched through out the applications for debugging and reporting purpose.</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <description>Stores the message that was returned from the exception generated.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>Stores the type of exception that has occured</description>
        <label>Exception Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>This field will be populated for Call out exceptions and will store the request that was passed to the webservice call out.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>This field is specifically for call out exceptions. It will store the response that we received from the wenservice call outs.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_APPLN_CASE__c.object
<CustomObject>
    <description>PEAK application Case information, main data table others reference.</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CBMS_CASE_NUM__c</fullName>
        <label>CBMS Case Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDN_APPLN__c</fullName>
        <label>IDN_APPLN</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDN_CBMS_REF__c</fullName>
        <label>Referral ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Application Case</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Application Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_APPLN_PRCS_QUEUE__c.object
<CustomObject>
    <description>Track PEAK application processing</description>
    <fields>
        <fullName>IDN_APPLN__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Application Number</description>
        <label>Application Number</label>
        <referenceTo>T_APPLN_CASE__c</referenceTo>
        <relationshipLabel>Application Process Queue</relationshipLabel>
        <relationshipName>Application_case_26</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Process Queue</label>
    <nameField>
        <displayFormat>APRCS_QUEUE-{0}</displayFormat>
        <label>Application Process Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Process Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/WebServiceConfiguration__mdt.object
<CustomObject>
    <fields>
        <fullName>UserName__c</fullName>
        <description>Username for Web Service Call</description>
        <inlineHelpText>Username for Web Service Call</inlineHelpText>
        <label>UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password for Web Service Call</description>
        <inlineHelpText>Password for Web Service Call</inlineHelpText>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AuthId__c</fullName>
        <description>Auth Id or Client Id for Web Service Call</description>
        <inlineHelpText>Auth Id or Client Id for Web Service Call</inlineHelpText>
        <label>Auth Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AuthToken__c</fullName>
        <description>Auth Token or Client Secret for Web Service Call</description>
        <inlineHelpText>Auth Token or Client Secret for Web Service Call</inlineHelpText>
        <label>Auth Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceType__c</fullName>
        <label>Service Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>WebService Configuration</label>
    <pluralLabel>WebServiceConfigurations</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/viewReferralApplnPdfController.cls
public with sharing class viewReferralApplnPdfController {
    public static String viewReferralPdf = 'viewReferralPdf';
    public static String viewReferralAEMCred = 'viewReferralAEMCred';
    public static String strConvertedBlob {get; set;}
    public Blob blobResponse {get; set;}
    
    public viewReferralApplnPdfController(){
        viewReferralApplnPdfController.getFileString();
    }
    
    public static string getFileString(){
        Blob blobResponse;
        string responseString;
        try{
            String fileName = System.currentPageReference().getParameters().get('fileName');
            String recordId = System.currentPageReference().getParameters().get('recordId');
            System.debug('fileName:'+fileName);
            System.debug('recordId:'+recordId);
            HttpResponse response = cbmsCallout(fileName);
            if (response <> null && response.getStatusCode() == 200) {
                blobResponse = response.getBodyAsBlob();
                system.debug('The Blob: '+blobResponse);
                if(null!=blobResponse)
                    strConvertedBlob = EncodingUtil.base64Encode(blobResponse);
                else{
                   LightningServerResponse serverResponse = getReferralPdf(recordId);
                    if(null!=serverResponse && serverResponse.isSuccessful){
                        String responseJSON=(String)serverResponse.objectData.get('responseJSON');
                        HttpResponse response2ndCallout = cbmsCallout(fileName);
                        if (response2ndCallout <> null && response2ndCallout.getStatusCode() == 200) {
                            blobResponse = response2ndCallout.getBodyAsBlob();
                            system.debug('The Blob: '+blobResponse);
                            if(null!=blobResponse)
                                strConvertedBlob = EncodingUtil.base64Encode(blobResponse);}
                    }
                }
                system.debug('The stringResponse from File'+strConvertedBlob);
                //responseString = EncodingUtil.base64Encode(responseString);
            } else {
                system.debug('Res Code ' + response.getStatusCode() +', The string response--'+response.getBody());
            }
        } catch (exception e){
            system.debug('Exception occured in returning Peak PDF Blob - ' + e.getmessage());
            //ExceptionLoggingServices.captureExceptionLog(e, new Map<String,Object>{'Class__c'=>'viewPeakApplnPdfController','Method__c'=>'getFileBlob'});
            //throw new CorspdException('Exception occured in returning Peak PDF Blob - ' + e.getmessage(),e);
        }
        return strConvertedBlob;
    }
    
    @auraEnabled
    public static LightningServerResponse getReferralPdf(string recordId){
        List<WebServiceConfiguration__mdt> serviceMetaData = new List<WebServiceConfiguration__mdt>();
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful;
        String message;        
        String responseJSON;
        
        List<T_APPLN_PRCS_QUEUE__c> lstofApplnPrcsQueues = [select id, IDN_APPLN__r.Name, IDN_APPLN__r.CBMS_CASE_NUM__c, IDN_APPLN__r.IDN_CBMS_REF__c, IDN_APPLN__r.CreatedDate from T_APPLN_PRCS_QUEUE__c where id =:recordId];
        system.debug('The list application process queue--'+lstofApplnPrcsQueues);
        
        try{
            Httprequest request = new Httprequest();
            Http http = new Http();
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setHeader('Accept', 'application/json');
            String sUrl = Label.CBMSReferralPDFGenerateUrl;
            request.setTimeout(120000);
            request.setEndpoint(sUrl);
            
            JSONGenerator generator = JSON.createGenerator(true);
            if(lstofApplnPrcsQueues.size() > 0 ) {
                for(integer i = 0; i < lstofApplnPrcsQueues.size(); i++) {
                    generator.writeStartObject();
                    generator.writeObjectField('applicationId',lstofApplnPrcsQueues[i].IDN_APPLN__r.Name);
                    generator.writeObjectField('referralId',lstofApplnPrcsQueues[i].IDN_APPLN__r.IDN_CBMS_REF__c);
                    Datetime referralDate = lstofApplnPrcsQueues[i].IDN_APPLN__r.CreatedDate;
                    String formattedDate = referralDate.yearGmt()+'-'+referralDate.monthGmt()+'-'+referralDate.dayGmt();
                    generator.writeObjectField('referralCreationDate',formattedDate);
                    generator.writeEndObject();
                }
            }
            String JSONString = generator.getAsString();
            system.debug('The JSON Input--'+JSONString);
            request.setBody(JSONString);
            HttpResponse response = http.send(request);
            if (response <> null && response.getStatusCode() == 200) {
                responseJSON = response.getBody();
                system.debug('The string response--'+responseJSON);
                objectData.put('responseJSON', responseJSON);
                isSuccessful = true;
            }  else {
                isSuccessful = false;
                message = 'Webservice Status returned is : '+ response.getStatusCode() + ' ; ' + response.getStatus();
                Exception_Log__c xLog = new Exception_Log__c();
                xLog.Class__c = 'viewReferralApplnPdfController';
                xLog.Method__c = 'getReferralPdf';
                if (response != null) {
                    xLog.Exception_Message__c = 'Status is :' + response.getStatus() + ',Status Code is :' + String.valueOf(response.getStatusCode());
                    if (response.getStatusCode() != null) {
                        xLog.Exception_Type__c = 'Web Service';
                    }
                    xLog.Response__c = response.getBody();
                }
                if (response != null) {
                    xLog.Request__c = 'End point:' + request.getEndpoint() + ':' + response.getBody();
                }
                //ExceptionLoggingServices.captureExceptionLog(xLog); 
                system.debug(xLog.Exception_Message__c);
                system.debug(xLog.Request__c);
            }
        } catch(Exception ex){
            isSuccessful = false;
            message = 'Webservice Exception : '+ ex.getMessage(); 
            system.debug(message);
            //ExceptionLoggingServices.captureExceptionLog(ex, new Map<String,Object>{'Class__c'=>'viewReferralApplnPdfController','Method__c'=>'getReferralPdf'});
        }
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
    
    @auraEnabled
    public static string fetchPdfFileFromS3(string recordId){
        List<T_APPLN_PRCS_QUEUE__c> applnPrcsQueueList = new List<T_APPLN_PRCS_QUEUE__c>();
        string applnId;
        applnPrcsQueueList = [select id, IDN_APPLN__r.CBMS_CASE_NUM__c, IDN_APPLN__r.Name From T_APPLN_PRCS_QUEUE__c where id =: recordId];
        if(applnPrcsQueueList != null){
            applnId = string.valueOf(applnPrcsQueueList[0].IDN_APPLN__r.Name);
        }
        return applnId;
    }
    
    public static HttpResponse cbmsCallout(String fileName){
        List<WebServiceConfiguration__mdt> serviceMetaData = new List<WebServiceConfiguration__mdt>();
        serviceMetaData = [SELECT id, AuthId__c, AuthToken__c, EndPoint__c,UserName__c,Password__c, isActive__c, ServiceType__c, MasterLabel, DeveloperName FROM WebServiceConfiguration__mdt WHERE isActive__c = true AND DeveloperName = :viewReferralAEMCred LIMIT 1];
        String username;
        String password;
        Httprequest request = new Httprequest();
        Http http = new Http();
        request.setMethod('POST');
        String url = Label.correspondenceTargetPdfServlet + 'pathInAws=correspondence/cbmsreferrals'+'&fileName=' + fileName+'.pdf';
        if(!serviceMetaData.isEmpty() && serviceMetaData[0].Password__c != null && serviceMetaData[0].UserName__c != null){
                username  = serviceMetaData[0].UserName__c;
                password= serviceMetaData[0].Password__c;
            }            
        Blob headerValue = Blob.valueOf(username + ':' + password);
        String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
        request.setHeader('Authorization', authorizationHeader);
        request.setEndpoint(url);
        HttpResponse response = http.send(request);
        return response;
    }
}