CHATS_SIT/force-app/main/default/objects/Exception_Log__c.object
<CustomObject>
    <description>The object stores all the exceptions that were catched through out the applications for debugging and reporting purpose.</description>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Exception_Logging_Framework_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This will store settings related to Exception Logging Framework.</description>
    <fields>
        <fullName>Enable_Exception_Log__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enable Exception Log</label>
        <type>Checkbox</type>
    </fields>
    <label>Exception Logging Framework Settings</label>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT__c.object
<CustomObject>
    <description>Adjustment parent table that contains information about provider and case payment corrections</description>
    <fields>
        <fullName>CDE_AGNST_ADJMT__c</fullName>
        <description>Adjustment Payment Type</description>
        <label>Adjustment Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00727</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS_ADJMT__c</fullName>
        <description>Adjustment Status</description>
        <label>Adjustment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00719</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_ADJMT__c</fullName>
        <description>Adjustment Type</description>
        <label>Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00718</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_CLSFN__c</fullName>
        <description>Classification Type</description>
        <label>Classification Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00730</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_ADJMT__c</fullName>
        <description>Care End Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_START_ADJMT__c</fullName>
        <description>Care Start Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case#</description>
        <label>Case#</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Adjustment</relationshipLabel>
        <relationshipName>Case</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Adjustments</relationshipLabel>
        <relationshipName>Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Finalized</fullName>
        <active>true</active>
        <label>Finalized</label>
    </recordTypes>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Provider_License_Closed</fullName>
        <active>false</active>
        <description>On Closed Provier Adjustment of type Claim can not be created</description>
        <errorConditionFormula>AND(  TEXT(CDE_TYPE_ADJMT__c) = &apos;1&apos;,NOT(ISPICKVAL( IDN_PROVR__r.CDE_STATUS_PROVR__c , &apos;Open&apos;)),OR((TEXT( CDE_STATUS_ADJMT__c ) = &apos;&apos;),(TEXT(CDE_STATUS_ADJMT__c) = &apos;1&apos;)) )</errorConditionFormula>
        <errorMessage>Adjustment cannot be created for the care dates when provider license status is closed</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_INDIV_VERIF__c.object
<CustomObject>
    <description>Individual verification tracking</description>
    <fields>
        <fullName>CDE_TYPE_INFO_INDIV__c</fullName>
        <description>Type of Individual Information</description>
        <label>Type of Individual Information</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00366</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual Information ID</label>
        <referenceTo>T_SBSD_INDIV_INFO__c</referenceTo>
        <relationshipLabel>Individual Verification</relationshipLabel>
        <relationshipName>Individual_Verification</relationshipName>
        <type>Lookup</type> 
    </fields>
    <label>Individual Verification</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Individual Verification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>DTE_APPLN__c</fullName>
        <description>Date Application Received</description>
        <label>Date Application Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <description>Provider ID</description>
        <label>Provider ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_INFO__c.object
<CustomObject>
    <description>Information codes about individual</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_INFO_INDIV__c</fullName>
        <description>Type of Individual Information</description>
        <label>Individual Information Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00366</valueSetName>
        </valueSet>
    </fields> 
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Individual_Information</relationshipLabel>
        <relationshipName>Individual_Information</relationshipName>
        <type>Lookup</type>
    </fields>    
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Individual Information (Individual)</relationshipLabel>
        <relationshipName>Individual_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Individual Information</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Individual Information ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_MIL__c.object
<CustomObject>
    <fields>
        <fullName>CDE_STATUS_MIL__c</fullName>
        <description>Military Status</description>
        <label>Military Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00830</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Military Status</relationshipLabel>
        <relationshipName>T_SBSD_INDIV26</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Military Status</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Military Status ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Military Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00366.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CS</fullName>
        <label>citizenship status</label>
    </customValue>
    <customValue>
        <fullName>HDS</fullName>
        <label>head start</label>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
        <label>marital status</label>
    </customValue>
    <customValue>
        <fullName>FST</fullName>
        <label>foster care</label>
    </customValue>
    <customValue>
        <fullName>IMM</fullName>
        <isActive>false</isActive>
        <label>age appropriate immunization</label>
    </customValue>
    <description>R00366</description>
    <masterLabel>R00366</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00718.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Claim</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Recovery</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Funding Program</label>
    </customValue>
    <description>R00718</description>
    <masterLabel>R00718</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00719.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>In Process</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calculation Complete</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Satisfied</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Paid</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Cancellation In Progress</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Cancelled</label>
    </customValue>
    <description>R00719</description>
    <masterLabel>R00719</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00727.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Sub-Payment</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Non Sub-Payment</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <description>R00727</description>
    <masterLabel>R00727</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00730.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Fraud/IPV</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Judgment Recovery</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Household/Provider Error</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Other Recoveries</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <isActive>false</isActive>
        <label>Agency Error</label>
    </customValue>
    <description>R00730</description>
    <masterLabel>R00730</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00830.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <label>No Military Affiliation</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Yes, Active Duty, US Military</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Yes, National Guard/Military Reserve</label>
    </customValue>
    <description>R00830</description>
    <masterLabel>R00830</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/GenericDataSaverApxCtrlTest.cls
/**********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           11/29/2017                                                          
*  @description    Test class for Generic Data Saver
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 29-Nov-2017                                                             
*  * Author: Shubham Jain                                                      
*  * Description: Initial version                                                 
*  * JIRA Ticket: 
*                                                                                 
*********************************************************************************************/

@isTest
public class GenericDataSaverApxCtrlTest {
    public static testmethod void testUpsertRecords(){
        List<Account> accountsToBeUpdated = new List<Account>();         
        List<Account> existingAccounts = [SELECT Id, Name FROM Account limit 1000]; 
        //System.assertEquals(true, existingAccounts.size()>0, 'existingAccounts should not be empty');
        for(Account existingAccount:existingAccounts){
            existingAccount.Name = 'Updated '+existingAccount.Name;
            accountsToBeUpdated.add(existingAccount);
        }
        LightningServerResponse lsr = GenericDataSaverApxCtrl.upsertRecords(accountsToBeUpdated);
        System.assertEquals(true, lsr.isSuccessful, 'lsr.isSuccessful should be true');
        
        lsr = GenericDataSaverApxCtrl.upsertRecords(new List<SObject>{new Contact(FirstName = 'FName')});
        System.assertEquals(false, lsr.isSuccessful, 'lsr.isSuccessful should be false');
    }

    public static testmethod void testUpsertRecordsFinal(){
        List<Account> accountsToBeUpdated = new List<Account>();         
        List<Account> existingAccounts = [SELECT Id, Name FROM Account limit 1000];
        //System.assertEquals(true, existingAccounts.size()>0, 'existingAccounts should not be empty');
        for(Account existingAccount:existingAccounts){
            existingAccount.Name = 'Updated '+existingAccount.Name;
            accountsToBeUpdated.add(existingAccount);
        }
        LightningServerResponse lsr = GenericDataSaverApxCtrl.upsertRecordsFinal(accountsToBeUpdated, true);
        System.assertEquals(true, lsr.isSuccessful, 'lsr.isSuccessful should be true');
        
        lsr = GenericDataSaverApxCtrl.upsertRecordsFinal(new List<SObject>{new Contact(FirstName = 'FName')},true);
        System.assertEquals(false, lsr.isSuccessful, 'lsr.isSuccessful should be false');
        
        Contact tempContactToBedeleted = new Contact(FirstName = 'FName', LastName='test'); 
        insert tempContactToBedeleted;
        
        GenericDataSaverApxCtrl.deleteRecords(new List<SObject>{tempContactToBedeleted});
        List<Contact> conList = [SELECT Id FROM Contact WHERE Id = :tempContactToBedeleted.Id];
        System.assertEquals(true, conList.isEmpty(), 'conList should be empty');

        GenericDataSaverApxCtrl.deleteRecords(new List<SObject>{tempContactToBedeleted});
        
    }

    public static testmethod void testDeleteJunkRecords(){
        List<Account> accountsToBeUpdated = new List<Account>();         
        List<Account> existingAccounts = [SELECT Id, Name FROM Account limit 1000];
        //System.assertEquals(true, existingAccounts.size()>0, 'existingAccounts should not be empty');
        for(Account existingAccount:existingAccounts){
            existingAccount.Name = 'Updated '+existingAccount.Name;
            accountsToBeUpdated.add(existingAccount);
        }
        LightningServerResponse lsr = GenericDataSaverApxCtrl.upsertRecordsFinal(accountsToBeUpdated, true);
        System.assertEquals(true, lsr.isSuccessful, 'lsr.isSuccessful should be true');
        
        lsr = GenericDataSaverApxCtrl.upsertRecordsFinal(new List<SObject>{new Contact(FirstName = 'FName')},true);
        System.assertEquals(false, lsr.isSuccessful, 'lsr.isSuccessful should be false');
        
        Contact tempContactToBedeleted = new Contact(FirstName = 'FName', LastName='test'); 
        insert tempContactToBedeleted;
        
        GenericDataSaverApxCtrl.deleteJunkRecords(new List<SObject>{tempContactToBedeleted});
        List<Contact> conList = [SELECT Id FROM Contact WHERE Id = :tempContactToBedeleted.Id];
        System.assertEquals(true, conList.isEmpty(), 'conList should be empty');
        
    }

    public static testmethod void testDeleteJunkRecordsByIds(){
        List<Account> accountsToBeUpdated = new List<Account>();         
        List<Account> existingAccounts = [SELECT Id, Name FROM Account limit 1000];
        //System.assertEquals(true, existingAccounts.size()>0, 'existingAccounts should not be empty');
        for(Account existingAccount:existingAccounts){
            existingAccount.Name = 'Updated '+existingAccount.Name;
            accountsToBeUpdated.add(existingAccount);
        }
        LightningServerResponse lsr = GenericDataSaverApxCtrl.upsertRecordsFinal(accountsToBeUpdated, true);
        System.assertEquals(true, lsr.isSuccessful, 'lsr.isSuccessful should be true');
        
        lsr = GenericDataSaverApxCtrl.upsertRecordsFinal(new List<SObject>{new Contact(FirstName = 'FName')},true);
        System.assertEquals(false, lsr.isSuccessful, 'lsr.isSuccessful should be false');
        
        Contact tempContactToBedeleted = new Contact(FirstName = 'FName', LastName='test'); 
        insert tempContactToBedeleted;
        
        GenericDataSaverApxCtrl.deleteJunkRecordsByIds(new List<Id>{tempContactToBedeleted.Id});
        List<Contact> conList = [SELECT Id FROM Contact WHERE Id = :tempContactToBedeleted.Id];
        System.assertEquals(true, conList.isEmpty(), 'conList should be empty');

        
    }
    
    public static testmethod void testgetCrudResponseFromSaveResults(){
        T_COUNTY__c countyRec = TestClassUtility.createCounty('Denver','Denver',1,true);
        T_SBSD_CASE__c caseRec = TestClassUtility.createCase(false, countyRec.Id);
        caseRec.DTE_APPLN__c = System.today().addDays(-10);
        insert caseRec;
        Id recordTypeId = Schema.SObjectType.T_ADJMT__c.getRecordTypeInfosByName().get('Finalized').getRecordTypeId();
        List<T_ADJMT__c> adjustmentList= new List<T_ADJMT__c>();
        adjustmentList.add( new T_ADJMT__c(IDN_CASE__c=caseRec.Id,RecordtypeId=recordTypeId,CDE_STATUS_ADJMT__c='1',CDE_TYPE_ADJMT__c='1',CDE_TYPE_CLSFN__c='3',CDE_AGNST_ADJMT__c='1',DTE_END_ADJMT__c=date.newInstance(2018, 1, 10),DTE_START_ADJMT__c=date.newInstance(2018, 1, 8)));
        List<Database.SaveResult> lstSaveResult = new List<Database.SaveResult>();
        lstSaveResult.addAll(Database.insert(adjustmentList, false));
        CrudResponseApxCtrl.getCrudResponseFromSaveResults(adjustmentList, lstSaveResult);
        system.assert([select Id from T_ADJMT__c].size()==0,'Adjustment records');
    }
    
    public static testmethod void testUpsertRecordsAuth() {
        Date datetoday=System.Today();
        Date begindate = date.newInstance(datetoday.year(),datetoday.month(),1);
        Date dob = date.newInstance(datetoday.year()-20, datetoday.month(), 1);
        Date enddate = begindate.addDays(25);
        begindate = begindate.addDays(21);
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_INDIV__c individual = TestClassUtility.createIndividual(true, dob, 'firstName', '1', 'lastName', '123', 'CC');
        T_SBSD_CASE__c case1 = TestClassUtility.createCase(true, county.Id);
        T_CHATS_PROVR_STATUS__c provider = TestClassUtility.createProvider(true, 'Level 3');
        T_AUTH__c authorization=TestClassUtility.createAuthorization(false,enddate,begindate,county.Id,null);
        authorization.IDN_CASE__c= case1.Id;
        authorization.IDN_CLIENT__c= individual.Id;
        authorization.IDN_PROVR__c= provider.Id;
        insert authorization;
       
        LightningServerResponse lsr1 = GenericDataSaverApxCtrl.upsertRecordAuth(new List<T_AUTH__C>{authorization},string.valueOf(system.today()),true);
        System.assertEquals(true, lsr1.isSuccessful, 'lsr.isSuccessful should be true');
    
    }
    
    public static testmethod void testDeleteJunkRecords2() {
         Map<String, SObject> caseData = CaseLastUpdatedTestFactory.createCaseData();
         T_SBSD_INDIV_MIL__c mil= new T_SBSD_INDIV_MIL__c(CDE_STATUS_MIL__c='0',IDN_CLIENT__c=caseData.get('individual').Id);
         insert mil;
         T_SBSD_INDIV_INFO__c info= new T_SBSD_INDIV_INFO__c(CDE_TYPE_INFO_INDIV__c='CS',IDN_CLIENT__c=caseData.get('individual').Id,IDN_CASE__c=caseData.get('caseRec').Id);
         insert info;
         T_INDIV_VERIF__c verif= new T_INDIV_VERIF__c(IDN_CLIENT__c=info.Id);
         insert verif;
         
         LightningServerResponse lsr = GenericDataSaverApxCtrl.deleteJunkRecords(new List<SObject>{caseData.get('individual')});
         System.assertEquals(true, lsr.isSuccessful, 'lsr.isSuccessful should be true');
    
        
    }
    
    public static testMethod void testLogException(){
        Exception_Logging_Framework_Settings__c exceptionFrameworkSetting = new Exception_Logging_Framework_Settings__c(SetupOwnerId=UserInfo.getOrganizationId(), Enable_Exception_Log__c = true);
        insert exceptionFrameworkSetting;
    	
    	
        Exception_Log__c xLog = new Exception_Log__c();
        xLog.Class__c = 'Test';
        xLog.Method__c = 'Test';
        GenericDataSaverApxCtrl.logException(xLog);
        Integer xLogCount = [SELECT Count() FROM Exception_Log__c];
        System.assertEquals(1, xLogCount, 'xLogCount should be 1');
    }
    
    @testSetup
    public static void setUpData(){
        List<Account> accounts = new List<Account>();
        for(integer i = 0; i<10; i++){
            accounts.add(new Account(Name = 'Test'+i));
        }
        insert accounts;
    }
}