CHATS_SIT/force-app/main/default/objects/Individual_E_mail__c.object
<CustomObject>
    <fields>
        <fullName>Email_Information__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email Information</label>
        <type>Email</type>
    </fields>
     <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Individual E-mails</relationshipLabel>
        <relationshipName>Individual_E_mails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Individual E-mail</label>
    <nameField>
        <displayFormat>EI-{000000}</displayFormat>
        <label>E-mail Information Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual E-mails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_APPLN_CASE__c.object
<CustomObject>
    <description>PEAK application Case information, main data table others reference.</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_INFO_EM__c</fullName>
        <description>CDE_INFO_EM</description>
        <label>CDE_INFO_EM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTE_RCVD_APPLN__c</fullName>
        <description>DTE_RCVD_APPLN</description>
        <label>DTE_RCVD_APPLN</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_APPLN__c</fullName>
        <label>IDN_APPLN</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application Case</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Application Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_APPLN_PRCS_QUEUE__c.object
<CustomObject>
    <description>Track PEAK application processing</description>
    <fields>
        <fullName>CDE_SOURCE__c</fullName>
        <description>Application Source</description>
        <label>Application Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00834</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_RCVD_APPLN__c</fullName>
        <description>Application Received Date</description>
        <label>Application Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_APPLN_COMPASS__c</fullName>
        <label>IDN_APPLN_COMPASS</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDN_APPLN__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Application Number</description>
        <label>Application Number</label>
        <referenceTo>T_APPLN_CASE__c</referenceTo>
        <relationshipLabel>Application Process Queue</relationshipLabel>
        <relationshipName>Application_case_26</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Application Process Queues</relationshipLabel>
        <relationshipName>Application_Process_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Process Queue</label>
    <nameField>
        <displayFormat>APRCS_QUEUE-{0}</displayFormat>
        <label>Application Process Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Process Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Triggers_On_Off_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Triggers_On_Off_Settings</label>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00834.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CB</fullName>
        <label>CBMS</label>
    </customValue>
    <customValue>
        <fullName>PK</fullName>
        <default>true</default>
        <label>PEAK</label>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
        <label>Paper</label>
    </customValue>
    <description>R00834</description>
    <masterLabel>R00834</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/MS_FetchClientDataHelperTest.cls
@isTest
public class MS_FetchClientDataHelperTest {
    @testSetup
    public static void prepareData(){
        Triggers_On_Off_Settings__c triggerOnOffRec= new Triggers_On_Off_Settings__c(Name='CaseTrigger',Active__c=false);
        Triggers_On_Off_Settings__c triggerOnOffRecIndiv= new Triggers_On_Off_Settings__c(Name='IndividualTrigger',Active__c=false);
        Triggers_On_Off_Settings__c triggerOnOffRecApp= new Triggers_On_Off_Settings__c(Name='applicationPrcsQueueTrigger',Active__c=false);
        
        
        insert new List<Triggers_On_Off_Settings__c>{triggerOnOffRec,triggerOnOffRecIndiv,triggerOnOffRecApp};
            T_SBSD_INDIV__c indivRec = TestClassUtility.createIndividual(true, System.today().addYears(-15), 'firstName','1', 'lastName','123456789','CC');
        Individual_E_mail__c emailRecord = new Individual_E_mail__c(
            Individual__c = indivRec.Id,
            Email_Information__c = 'test@info.com'
        );
        insert emailRecord;
        T_COUNTY__c countyObj = TestClassUtility.createCounty('Denver','Denver',1,true);
        T_SBSD_CASE__c caseObj = TestClassUtility.createCase(true, countyObj.Id);
        TestClassUtility.createCaseIndividual(true, caseObj.Id, indivRec.Id,true);
        T_APPLN_CASE__c applnCaseRec = new T_APPLN_CASE__c(IDN_APPLN__c = 12345,CDE_INFO_EM__c='test@info.com');
        T_APPLN_CASE__c applnCaseRec1 = new T_APPLN_CASE__c(IDN_APPLN__c = 54321,CDE_INFO_EM__c='test@info.com');
        
        insert new List<T_APPLN_CASE__c>{applnCaseRec,applnCaseRec1};
            
            T_APPLN_PRCS_QUEUE__c applnPrcsQueueRec = new T_APPLN_PRCS_QUEUE__c(IDN_APPLN_COMPASS__c = 12345,
                                                                                IDN_Case__c=caseObj.Id,
                                                                                CDE_SOURCE__c ='PK',
                                                                                DTE_RCVD_APPLN__c = system.today(),
                                                                                IDN_APPLN__c=applnCaseRec.Id);
        T_APPLN_PRCS_QUEUE__c applnPrcsQueueRec1 = new T_APPLN_PRCS_QUEUE__c(IDN_APPLN_COMPASS__c = 54321,
                                                                             CDE_SOURCE__c ='CB',
                                                                             DTE_RCVD_APPLN__c = system.today(),
                                                                             IDN_APPLN__c=applnCaseRec1.Id);
        
        insert new list<T_APPLN_PRCS_QUEUE__c>{applnPrcsQueueRec,applnPrcsQueueRec1};
    }
    @isTest
    static void testGetClientInfoByEmail() {
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = 'https://example.com/getClientInfo';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serializePretty(new Map<String,String>{'email_id'=> 'test@info.com'}));
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        List<UFE_ResponseWrapper> response = MS_FetchClientData.getClientInfobyPost();
        Test.stopTest();
    }
    @isTest
    static void testGetClientInfoByCaseId() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = 'https://example.com/getClientInfo';
        req.httpMethod = 'POST';
        List<T_SBSD_Case__c> cases = [select id from T_SBSD_Case__c limit 1];
        req.requestBody = Blob.valueOf(JSON.serializePretty(new Map<String,String>{'id'=> cases[0].Id,'iType'=>'case'}));
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        List<UFE_ResponseWrapper> response = MS_FetchClientData.getClientInfobyPost();
        Test.stopTest();
    }
    @isTest
    static void testGetClientInfoByAppId() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = 'https://example.com/getClientInfo';
        req.httpMethod = 'POST';
        Id appId = [select id from T_APPLN_CASE__c limit 1]?.Id;
        req.requestBody = Blob.valueOf(JSON.serializePretty(new Map<String,String>{'id'=> appId,'iType'=>'application'}));
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        List<UFE_ResponseWrapper> response = MS_FetchClientData.getClientInfobyPost();
        Test.stopTest();
    }
}