CHATS_SIT/force-app/main/default/objects/Individual_E_mail__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Begin_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Information__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email Information</label>
        <type>Email</type>
    </fields>
     <fields>
        <fullName>Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Individual E-mails</relationshipLabel>
        <relationshipName>Individual_E_mails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Individual E-mail</label>
    <nameField>
        <displayFormat>EI-{000000}</displayFormat>
        <label>E-mail Information Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual E-mails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_ASSIST_PROVR__c</fullName>
        <description>Did a provider assist you in completing</description>
        <label>Provider assisted with application?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00619</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IND_ELG_PRE_PROVR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pre-Eligibility Determination</description>
        <label>Pre-Eligibility Determination</label>
        <type>Checkbox</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <formula>IDN_CASE__r.CDE_COUNTY__c</formula>
        <label>code county</label>
        <type>Text</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INFO__c.object
<CustomObject>
    <description>Method of contact like email</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_INFO_CASE__c</fullName>
        <description>Case Information Type</description>
        <label>Case Information Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00833</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>T_SBSD_CASE13</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TXT_VALUE_INFO_CASE__c</fullName>
        <description>Case Information</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Case Information</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Case Information</label>
  	<nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Information ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>CDE_GENDER__c</fullName>
        <description>Gender</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00080</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_SOURCE_VRFYD_IDNTY__c</fullName>
        <description>How Verified (Identity)</description>
        <label>How Verified (Identity)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00707</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_DOB__c</fullName>
        <description>DOB</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    
    <fields>
        <fullName>IND_CDE_TYPE_VERIF_DOB__c</fullName>
        <description>This is new field for DOB verification for removing global picklist Set R000367 reference.</description>
        <label>DOB verified?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A-adult caretaker</fullName>
                </value>
                <value>
                    <fullName>N/A-not requesting child</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <label>Not Available</label>
                </value>
                <value>
                    <fullName>SD</fullName>
                    <label>Verbal Verification</label>
                </value>
                <value>
                    <fullName>V</fullName>
                    <label>Written Verification</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

    <fields>
        <fullName>NAM_FIRST__c</fullName>
        <description>First Name</description>
        <label>First Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_LAST__c</fullName>
        <description>Last Name</description>
        <label>Last Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NBR_SSN__c</fullName>
        <description>SSN</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>SSN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00080.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Male</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Female</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>X</label>
    </customValue>
    <description>R00080</description>
    <masterLabel>R00080</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00619.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <description>R00619</description>
    <masterLabel>R00619</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00833.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EM</fullName>
        <label>Email</label>
    </customValue>
    <customValue>
        <fullName>PMC</fullName>
        <label>Primary Method of Contact</label>
    </customValue>
    <description>R00833</description>
    <masterLabel>R00833</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/IndividualEmailTriggerTest.cls
@isTest
public class IndividualEmailTriggerTest {
     
    public static testMethod void invoke(){
        Test.startTest();
        T_COUNTY__c countyRec = TestClassUtility.createCounty('Denver','Denver',1,true);
        T_SBSD_CASE__c sbsdcase=new T_SBSD_CASE__c();
        sbsdcase.CDE_COUNTY__c=countyRec.Id;
        sbsdcase.IND_ASSIST_PROVR__c = 'N';
        sbsdcase.IND_ELG_PRE_PROVR__c  = false;
        insert sbsdcase;
        T_SBSD_CASE_INFO__c caseinforec=new T_SBSD_CASE_INFO__c ();
        caseinforec.IDN_CASE__c=sbsdcase.Id;
        caseinforec.CDE_TYPE_INFO_CASE__c='EM';
        caseinforec.TXT_VALUE_INFO_CASE__c='test@gmail.com';
        insert caseinforec;
        T_SBSD_INDIV__c sbsdIndiv = new T_SBSD_INDIV__c();
        sbsdIndiv.DTE_DOB__c=system.today().addYears(-30);
        sbsdIndiv.NAM_FIRST__c='Satty';
        sbsdIndiv.CDE_GENDER__c='2';
        sbsdIndiv.NAM_LAST__c='Nayak';
        sbsdIndiv.NBR_SSN__c='123456789';
        sbsdIndiv.CDE_SOURCE_VRFYD_IDNTY__c='MI';
        sbsdIndiv.IND_CDE_TYPE_VERIF_DOB__c='NA';
        Insert sbsdIndiv;
        T_SBSD_INDIV__c sbsdIndivone = new T_SBSD_INDIV__c();
        sbsdIndivone.DTE_DOB__c=system.today().addYears(-20);
        sbsdIndivone.NAM_FIRST__c='Matty';
        sbsdIndivone.CDE_GENDER__c='2';
        sbsdIndivone.NAM_LAST__c='Naik';
        sbsdIndivone.NBR_SSN__c='123456789';
        sbsdIndivone.CDE_SOURCE_VRFYD_IDNTY__c='MI';
        sbsdIndivone.IND_CDE_TYPE_VERIF_DOB__c='NA';
        Insert sbsdIndivone;
        T_SBSD_CASE_INDIV__c Caseindiv=TestClassUtility.createCaseIndividual(true,sbsdcase.Id,sbsdIndiv.Id,true);
        T_SBSD_CASE_INDIV__c Caseindivone=TestClassUtility.createCaseIndividual(true,sbsdcase.Id,sbsdIndiv.Id,false);
        Individual_E_mail__c indiemailrec1=new Individual_E_mail__c();
        indiemailrec1.Effective_Begin_Date__c=System.today();
        indiemailrec1.Email_Information__c='pragnayak@gmail.com';
        indiemailrec1.Individual__c=sbsdIndiv.Id;
        insert indiemailrec1;
         indiemailrec1.Email_Information__c='satarupa@gmail.com';
        update indiemailrec1;
        List<Individual_E_mail__c> IndemList = [Select Id from Individual_E_mail__c where Id =:indiemailrec1.Id];
        System.assertEquals(IndemList.size(),1);
        Test.stopTest();
        
    }    

}