CHATS_SIT/force-app/main/default/objects/IPV_Information__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>IPV Informations</relationshipLabel>
        <relationshipName>IPV_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disqualification_Begin_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disqualification Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disqualification_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disqualification End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disqualification_determination_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disqualification Determination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Individual_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>IPV Information</relationshipLabel>
        <relationshipName>IPV_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_occurrences__c</fullName>
        <label>Number of occurrences</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IPV Information</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IPV Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPV Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_CNTC_INFO__c.object
<CustomObject>
    <description>County Contact Information</description>
    <fields>
        <fullName>IDN_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Contacts</relationshipLabel>
        <relationshipName>County</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NAM_FIRST__c</fullName>
        <description>First Name</description>
        <label>First Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_LAST__c</fullName>
        <description>Last Name</description>
        <label>Last Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>County Contact</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_DOC_RQ__c.object
<CustomObject>
    <fields>
        <fullName>CDE_CORSPD_STATUS__c</fullName>
        <label>Correspondence Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>STAT_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>County Code</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_REQ__c</fullName>
        <label>Date Requested</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPV_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IPV Information ID</label>
        <referenceTo>IPV_Information__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NME_CORSPD__c</fullName>
        <label>Correspondence Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NME_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Disqualification_Begin_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disqualification Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disqualification_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disqualification End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Occurrences__c</fullName>
        <label>Number of occurrences</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Correspondence Request</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Date Person Entered Home</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <formula>IDN_CASE__r.CDE_COUNTY__c</formula>
        <label>code county</label>
        <type>Text</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>CDE_MODE_CASE__c</fullName>
        <description>Case Mode</description>
        <label>Case Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00358</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS_CASE__c</fullName>
        <description>Case Status</description>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00357</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    

    <fields>
        <fullName>NAM_FIRST__c</fullName>
        <description>First Name</description>
        <label>First Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_LAST__c</fullName>
        <description>Last Name</description>
        <label>Last Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00357.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>REO</fullName>
        <label>Reopen</label>
    </customValue>
    <description>R00357</description>
    <masterLabel>R00357</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00358.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INT</fullName>
        <label>Intake</label>
    </customValue>
    <customValue>
        <fullName>ONG</fullName>
        <label>Ongoing</label>
    </customValue>
    <customValue>
        <fullName>RED</fullName>
        <label>Redetermination</label>
    </customValue>
    <description>R00358</description>
    <masterLabel>R00358</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/STAT_CORSPD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Generated</fullName>
    </customValue>
    <customValue>
        <fullName>Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <masterLabel>Correspondence Status</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/IPVDisQualifycationService.cls
/************************************************************
*  Author:         Deloitte Consulting LLP.
*  Date:           06/16/2021
*  Description:    Handler class for IPVDisQualifycationApxTrigger.apxt
*  Test class:     IPVDisQualifycationApxTrigger_Test
*
*  Modification Log:
*  * Version: 1.0
*  * Date: 14-July-2021
*  * Author: Diya Chaudhary
*  * Description: Initial version
*
*  * Version: 1.1
*  * Date: 03/03/2023
*  * Author: Rishav Maji
*  * Description: API Upgrade, Code cleanup, CheckMarx fix
************************************************************/
public class IPVDisQualifycationService {
    public static final String CR110RsnCode = 'CR0023';
    public static void triggerCR110(List<IPV_Information__c> disQualListNewList,List<IPV_Information__c> disQualListOldList,Boolean triggerContext)    {
        Set<Id> indivIds = new Set<Id>();
        Set<Id> caseIds = new Set<Id>();
        Set<Decimal> countyCodeSet = new Set<Decimal>();
        Map<String, String> caseIndivMap = new Map<String, String> ();
        Set<Id> disQualIds = new Set<Id>();
        Map<string,string> keyParams = new Map<string, string>();
        Map<Id, IPV_Information__c> disQualOldMap = new Map<Id, IPV_Information__c> ();
        Map<Id, IPV_Information__c> disQualNewMap = new Map<Id, IPV_Information__c> ();
        Map<String, T_DOC_RQ__c> oldDOCRQMap = new Map<String, T_DOC_RQ__c> ();
        Map<String,String> caseIndivSortedMap = new Map<String,String>();
        Map<String,String> ipvCountyMap = new Map<String,String>();
        Map<String,String> indivCaseMap = new Map<String,String>();
        Map<String,Date> caseIndivDateMap = new Map<String,Date>();
        integer countyCode;
        List<T_DOC_RQ__c> corrReq = new List<T_DOC_RQ__c>();
        List<T_DOC_RQ__c> updAlreadyExistingFACorrespondence = new List<T_DOC_RQ__c>();
        List<T_DOC_RQ__c> existingAuthCorrespondence = new List<T_DOC_RQ__c>();
        for(IPV_Information__c eachDisQual : disQualListNewList){
            disQualIds.add(eachDisQual.Id);
        }
        system.debug('disQualListOldList--'+disQualListOldList);
        if(disQualListOldList!=null){
            for(IPV_Information__c eachDisQual : disQualListOldList){
                disQualOldMap.put(eachDisQual.Id,eachDisQual);
                indivIds.add(eachDisQual.Individual_ID__c);
              //  countyCodeSet.add(Decimal.valueOf(eachDisQual.County__c));
                ipvCountyMap.put(eachDisQual.Individual_ID__c, eachDisQual.County__c);
            }  
        }
        for(T_DOC_RQ__c obj :[select id,IPV_Information__c,IDN_CLIENT__c,CDE_CORSPD_STATUS__c from T_DOC_RQ__c where IPV_Information__c =:disQualIds and DTE_REQ__c =: system.today() and CDE_CORSPD_STATUS__c='Requested' And NME_CORSPD__c='CR110']){
            oldDOCRQMap.put(obj.IPV_Information__c, obj); 
            existingAuthCorrespondence.add(obj);
        } 
        Map<Id,List<T_SBSD_CASE__c>> indivOpenCases= new Map<Id,List<T_SBSD_CASE__c>>() ;
        List<T_SBSD_CASE_INDIV__c> caseIndivList =[SELECT IDN_CLIENT__r.NAM_FIRST__c,IDN_CASE__c,DTE_BEGIN_EFFV__c,IDN_CLIENT__c,IDN_CASE__r.CDE_COUNTY__r.CDE_COUNTY__c,
                                                   IDN_CLIENT__r.NAM_LAST__c FROM T_SBSD_CASE_INDIV__c WHERE IDN_CLIENT__c IN:indivIds AND
                                                   DTE_BEGIN_EFFV__c<=TODAY AND (DTE_END_EFFV__c = null OR DTE_END_EFFV__c>TODAY) and IDN_CASE__r.CDE_COUNTY__c IN:ipvCountyMap.values() order by DTE_BEGIN_EFFV__c DESC ];
        for(T_SBSD_CASE_INDIV__c caseIndiv :caseIndivList){
            caseIds.add(caseIndiv.IDN_CASE__c);
           
        }
        system.debug('caseIds--'+caseIds);
        if(caseIds!= null && caseIds.size()>0){
            for(T_SBSD_CASE__c cseRec :[SELECT Id,Name,CDE_COUNTY__R.NAME,OWNER.NAME,(SELECT IDN_CASE__r.Name, IDN_CLIENT__r.NAM_FIRST__c,IDN_CASE__c,DTE_BEGIN_EFFV__c,IDN_CLIENT__c,IDN_CASE__r.CDE_COUNTY__r.CDE_COUNTY__c,
                                             IDN_CLIENT__r.NAM_LAST__c FROM CaseIndividuals__r WHERE IDN_CLIENT__c IN:indivIds AND DTE_BEGIN_EFFV__c<=TODAY AND (DTE_END_EFFV__c = null OR DTE_END_EFFV__c>TODAY)),                                 
                                             (SELECT CDE_STATUS_CASE__c,toLabel(CDE_MODE_CASE__c), DTE_BEGIN_EFFV__c FROM T_SBSD_CASE10__r where DTE_END_EFFV__c = null Order by DTE_BEGIN_EFFV__c,createddate Desc NULLS FIRST Limit 1)
                                        FROM T_SBSD_CASE__c where CDE_COUNTY__c in:ipvCountyMap.values() and id IN:caseIds ]){
                                            system.debug('cseRec--'+cseRec);
                                            if(cseRec.T_SBSD_CASE10__r != null && cseRec.T_SBSD_CASE10__r.size()>0 && (new List<String>{'OPN','CLS'}.contains((string)cseRec.T_SBSD_CASE10__r[0].CDE_STATUS_CASE__c))){
                                                 system.debug('cseRec.T_SBSD_CASE10__r--'+cseRec.T_SBSD_CASE10__r);
                                                if(cseRec.CaseIndividuals__r != null && cseRec.CaseIndividuals__r.size()>0){
                                                     
                                                    for(T_SBSD_CASE_INDIV__c caseIndiv:cseRec.CaseIndividuals__r){
                                                        system.debug('caseIndiv--'+caseIndiv);
                                                        if(caseIndivDateMap.containsKey(caseIndiv.IDN_CLIENT__c)){
                                                            Date beginDate = caseIndivDateMap.get(caseIndiv.IDN_CLIENT__c);
                                                            if(beginDate<caseIndiv.DTE_BEGIN_EFFV__c){
                                                                caseIndivDateMap.put(caseIndiv.IDN_CLIENT__c, caseIndiv.DTE_BEGIN_EFFV__c);
                                                                if(ipvCountyMap.get(caseIndiv.IDN_CLIENT__c) == caseIndiv.IDN_CASE__r.CDE_COUNTY__c){
                                                                    caseIndivMap.put(caseIndiv.IDN_CLIENT__c,caseIndiv.IDN_CASE__r.Name);
                                                                }
                                                                
                                                            }
                                                        }else{
                                                            caseIndivDateMap.put(caseIndiv.IDN_CLIENT__c, caseIndiv.DTE_BEGIN_EFFV__c); 
                                                            if(ipvCountyMap.get(caseIndiv.IDN_CLIENT__c) == caseIndiv.IDN_CASE__r.CDE_COUNTY__c){
                                                                caseIndivMap.put(caseIndiv.IDN_CLIENT__c,caseIndiv.IDN_CASE__r.Name);
                                                            }
                                                        } 
                                                    }
                                                    
                                                    
                                                }   
                                            }
                                        }
        }
        system.debug('caseIndivMap--'+caseIndivMap);
        
        for(IPV_Information__c disQual :[Select id,Number_of_occurrences__c,Disqualification_Begin_Date__c,
                                         Disqualification_End_Date__c,Disqualification_determination_Date__c,Name,Disqualification_Result__c,
                                         Individual_ID__c,Individual_ID__r.Name,County__c,County__r.CDE_COUNTY__c from IPV_Information__c where id IN:disQualIds]){
                                             disQualNewMap.put(disQual.id,disQual);
                                             
                                         }
        for(IPV_Information__c disQual:disQualListNewList){
            
            if(triggerContext){
                if((disQual.disqualification_created__c ==true) && (disQual.Disqualification_determination_Date__c!= NULL) && ((disQual.Number_of_occurrences__c != disQualOldMap.get(disQual.Id).Number_of_occurrences__c) ||
                   (disQual.Disqualification_Begin_Date__c != disQualOldMap.get(disQual.Id).Disqualification_Begin_Date__c)||
                   (disQual.Disqualification_End_Date__c != disQualOldMap.get(disQual.Id).Disqualification_End_Date__c) ||
                   (disQual.Disqualification_determination_Date__c != disQualOldMap.get(disQual.Id).Disqualification_determination_Date__c))){
                        IPV_Information__c ipvRec = disQualNewMap.get(disQual.Id);

                       String clientId= ipvRec.Individual_ID__r.Name;
                       if(disQual.County__c != null){
                           countyCode = integer.valueOf(ipvRec.County__r.CDE_COUNTY__c);
                       }
                       if(caseIndivMap.containsKey(ipvRec.Individual_ID__c)){
                           keyParams.put('caseId', caseIndivMap.get(ipvRec.Individual_ID__c));
                       }
                       keyParams.put('clientId', clientId);
                       if(disQual.Number_of_occurrences__c != null){
                          keyParams.put('numOfOccurrences', String.valueOf(disQual.Number_of_occurrences__c)); 
                       }
                       if(disQual.Disqualification_Begin_Date__c != null){
                            keyParams.put('DQBeginDate', String.valueOf(disQual.Disqualification_Begin_Date__c));
                       }
                       if(disQual.Disqualification_End_Date__c != null){
                           keyParams.put('DQEndDate', String.valueOf(disQual.Disqualification_End_Date__c));
                       }
                       if(disQual.Disqualification_determination_Date__c != null){
                           keyParams.put('DQHearingDate', String.valueOf(disQual.Disqualification_determination_Date__c));
                       }
                       keyParams.put('IPVRecordId', String.valueOf(ipvRec.Id));
                       if(caseIndivMap.containsKey(ipvRec.Individual_ID__c)){
                            if(!oldDOCRQMap.containsKey(ipvRec.Id)){
                                CorspdTrigger.createCorspdRequest(CR110RsnCode,NULL,NULL,countyCode,keyParams);
                            }else{
                                T_DOC_RQ__C updAuthCorrRec = oldDOCRQMap.get(ipvRec.Id);
                                updAuthCorrRec.Disqualification_Begin_Date__c =disQual.Disqualification_Begin_Date__c;
                                updAuthCorrRec.Disqualification_End_Date__c =disQual.Disqualification_End_Date__c;
                                updAuthCorrRec.Disqualification_Hearing_Date__c =disQual.Disqualification_determination_Date__c;
                                updAuthCorrRec.Number_of_Occurrences__c =Decimal.valueOf(disQual.Number_of_occurrences__c);
                                updAlreadyExistingFACorrespondence.add(updAuthCorrRec);  
                            }  
                        }
                   }
            }else{
                if(disQual.disqualification_created__c ==true){
                     IPV_Information__c ipvRec = disQualNewMap.get(disQual.Id);

                       String clientId= ipvRec.Individual_ID__r.Name;
                    if(disQual.County__c != null){
                        countyCode = integer.valueOf(ipvRec.County__r.CDE_COUNTY__c);
                    }
                    if(caseIndivMap.containsKey(ipvRec.Individual_ID__c)){
                           keyParams.put('caseId', caseIndivMap.get(ipvRec.Individual_ID__c));
                       }
                    keyParams.put('IPVRecordId', String.valueOf(ipvRec.Id));
                    keyParams.put('clientId', clientId);
                    keyParams.put('numOfOccurrences', String.valueOf(disQual.Number_of_occurrences__c));
                    keyParams.put('DQBeginDate', String.valueOf(disQual.Disqualification_Begin_Date__c));
                    keyParams.put('DQEndDate', String.valueOf(disQual.Disqualification_End_Date__c));
                    keyParams.put('DQHearingDate', String.valueOf(disQual.Disqualification_determination_Date__c));
                    if(caseIndivMap.containsKey(ipvRec.Individual_ID__c) && (disQual.Disqualification_determination_Date__c != NULL)){
                        if(!oldDOCRQMap.containsKey(ipvRec.Id)){
                            CorspdTrigger.createCorspdRequest(CR110RsnCode,NULL,NULL,countyCode,keyParams);
                        }else{
                            T_DOC_RQ__C updAuthCorrRec = oldDOCRQMap.get(ipvRec.Id);
                            updAuthCorrRec.Disqualification_Begin_Date__c =disQual.Disqualification_Begin_Date__c;
                            updAuthCorrRec.Disqualification_End_Date__c =disQual.Disqualification_End_Date__c;
                            updAuthCorrRec.Disqualification_Hearing_Date__c =disQual.Disqualification_determination_Date__c;
                            updAuthCorrRec.Number_of_Occurrences__c =Decimal.valueOf(disQual.Number_of_occurrences__c);
                            updAlreadyExistingFACorrespondence.add(updAuthCorrRec);  
                        }
                    }
                }
                
            }
            
        }
        if(updAlreadyExistingFACorrespondence!=null && updAlreadyExistingFACorrespondence.size()>0 && !Test.isRunningTest()){
            GenericDMLHandler.updateRecords(updAlreadyExistingFACorrespondence, null);
        }
        
    }
}