CHATS_SIT/force-app/main/default/objects/IPV_Information__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>IPV Informations</relationshipLabel>
        <relationshipName>IPV_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disqualification_Begin_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disqualification Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disqualification_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disqualification Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disqualification_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disqualification End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disqualification_determination_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disqualification Determination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Individual_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>IPV Information</relationshipLabel>
        <relationshipName>IPV_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_occurrences__c</fullName>
        <label>Number of occurrences</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IPV Information</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>IPV Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPV Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_DOC_RQ__c.object
<CustomObject>
    <fields>
        <fullName>CDE_CORSPD_STATUS__c</fullName>
        <label>Correspondence Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>STAT_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>County Code</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_RCPT__c</fullName>
        <label>Recepient Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TYPE_RCPT_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_REQ__c</fullName>
        <label>Date Requested</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPV_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IPV Information ID</label>
        <referenceTo>IPV_Information__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NME_CORSPD__c</fullName>
        <label>Correspondence Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NME_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Disqualification_Begin_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disqualification Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disqualification_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disqualification End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Occurrences__c</fullName>
        <label>Number of occurrences</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Correspondence Request</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Peak_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Peak Data</label>
        <type>Checkbox</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Date Person Entered Home</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_CRTKR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is the Primary Parent/Caretaker</description>
        <label>Primary Parent/Caretaker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <formula>IDN_CASE__r.CDE_COUNTY__c</formula>
        <label>code county</label>
        <type>Text</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    

    <fields>
        <fullName>Is_Peak_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Peak Data</label>
        <type>Checkbox</type>
    </fields>
    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/STAT_CORSPD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Generated</fullName>
    </customValue>
    <customValue>
        <fullName>Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <masterLabel>Correspondence Status</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/TYPE_RCPT_CORSPD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P</fullName>
        <label>Provider</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Client</label>
    </customValue>
    <masterLabel>Correspondence Recepient Type</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/IPVDisQualifycationApxTrigger_Test.cls
@isTest
public class IPVDisQualifycationApxTrigger_Test {
    static testMethod void triggerCR110Scenario() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstName','1','lastName','1','CC');
        IPV_Information__c ipvRecord = new IPV_Information__c();
        ipvRecord.Individual_ID__c=sbsdIndiv.id;
        ipvRecord.Number_of_occurrences__c='1';
        ipvRecord.Disqualification_Begin_Date__c = system.today().addDays(-15);
        ipvRecord.Disqualification_End_Date__c = system.today();
        ipvRecord.Disqualification_determination_Date__c = system.today().addDays(-1);
        ipvRecord.County__c = county.id;
        ipvRecord.disqualification_created__c = true;
        
        
        Test.startTest();
        insert ipvRecord;
        ipvRecord.Number_of_occurrences__c ='2';
        update ipvRecord;
        Test.stopTest();
    }
    static testMethod void triggerCR110Scenario2() {
        
        
        
        Test.startTest();
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstName','1','lastName','1','CC');
        T_SBSD_CASE__c caseRec = TestClassUtility.createCase(true, county.Id);
        T_SBSD_CASE__c caseRec2 = TestClassUtility.createCase(true, county.Id);
        caseRec.Is_Peak_Data__c = true;
        T_SBSD_INDIV__c individual = TestClassUtility.createIndividual(true,system.today().addYears(-15),'firstName','1','lastName','123','CC');
        T_SBSD_CASE_INDIV__c caseIndiv = TestClassUtility.createCaseIndividual(true, caseRec.Id, individual.Id,true);
        T_SBSD_CASE_INDIV__c caseIndiv2 = new T_SBSD_CASE_INDIV__c();
        caseIndiv2.IDN_CASE__c = caseRec2.Id;
        caseIndiv2.IDN_CLIENT__c = individual.Id;
        caseIndiv2.IND_CRTKR__c = true;
        caseIndiv2.DTE_BEGIN_EFFV__c = system.today().addDays(-1);
        insert caseIndiv2;
        T_SBSD_CASE_STATUS_MODE__c caseStaMod = TestClassUtility.createCaseStatusMode(true, caseRec.Id);
        T_SBSD_CASE_STATUS_MODE__c caseStaMod2 = TestClassUtility.createCaseStatusMode(true, caseRec2.Id);
        IPV_Information__c ipvRecord = new IPV_Information__c();
        ipvRecord.Individual_ID__c=individual.id;
        ipvRecord.Number_of_occurrences__c='1';
        ipvRecord.Disqualification_Begin_Date__c = system.today().addDays(-15);
        ipvRecord.Disqualification_End_Date__c = system.today();
        ipvRecord.Disqualification_determination_Date__c = system.today().addDays(-1);
        ipvRecord.County__c = county.id;
        ipvRecord.disqualification_created__c = true;
        insert ipvRecord;
        T_DOC_RQ__c req = new T_DOC_RQ__c();
        req.IPV_Information__c =ipvRecord.id;
        req.CDE_COUNTY__c=county.id;
        req.IDN_CLIENT__c=individual.id;
        req.DTE_REQ__c = system.today();
        req.CDE_CORSPD_STATUS__c = 'Requested';
        req.NME_CORSPD__c='CR110';
        req.CDE_TYPE_RCPT__c ='P';        
        insert req;
        ipvRecord.Number_of_occurrences__c ='2';
        ipvRecord.Disqualification_Begin_Date__c = system.today().addDays(-14);
        ipvRecord.Disqualification_determination_Date__c = system.today().addDays(-2);
        ipvRecord.Disqualification_End_Date__c = system.today().addDays(1);
        update ipvRecord;
        Test.stopTest();
    }
}