CHATS_SIT/force-app/main/default/objects/Reverse_Referral_Interface_Report__c.object
<CustomObject>
    <label>Reverse Referral Interface Report</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reverse Referral Interface Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Date_Sent_to_CBMS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Sent to CBMS</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referral_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Referral Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>    
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Reverse Referral ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Reverse_Referral_Interface_Report__c/fields/IDN_EXTNL__c.field-meta.xml
<CustomField>
    <fullName>IDN_EXTNL__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Reverse Referral ID External</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CHATS_SIT/force-app/main/default/classes/ReverseRefInterface_Test.cls
/******************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           05-03-2024
*  @description    Reverse Ref Interface Trigger Test
*********************************************************************************************/
@isTest
public class ReverseRefInterface_Test {
    public static testMethod void testStampSalesforceIdToExternalId(){
        Test.startTest();
        Reverse_Referral_Interface_Report__c revRef = TestClassUtility.createReverseRef(true,null,null,Date.today(),'323232');
        Reverse_Referral_Interface_Report__c refAfterInsert = [select Id,IDN_EXTNL__c from Reverse_Referral_Interface_Report__c where Id=:revRef.Id];
        Test.stopTest();
        System.assert(refAfterInsert.IDN_EXTNL__c!=null && refAfterInsert.IDN_EXTNL__c == revRef.Id, 
                      'Salesforce ID was successfully stamped to external ID');
    }
}