CHATS_SIT/force-app/main/default/objects/Schedule_c__x.object
<CustomObject>
    <externalDataSource>OEC_Provider_Datasource</externalDataSource>
    <externalName>Schedule__c</externalName>
    <fields>
        <fullName>Attended_c__c</fullName>
        <defaultValue>false</defaultValue>
        <externalDeveloperName>Attended__c</externalDeveloperName>
        <label>Attended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CI_Authorization_Date_c__c</fullName>
        <externalDeveloperName>CI_Authorization_Date__c</externalDeveloperName>
        <inlineHelpText>Integration Driven - Date of the authorization. Format: CCYY-MM-DD</inlineHelpText>
        <label>Authorization Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CI_Authorization_Hours_c__c</fullName>
        <externalDeveloperName>CI_Authorization_Hours__c</externalDeveloperName>
        <inlineHelpText>Integration Driven - # of hours authorized</inlineHelpText>
        <label>Authorization Hours</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CI_Authorization_Id_c__c</fullName>
        <externalDeveloperName>CI_Authorization_Id__c</externalDeveloperName>
        <inlineHelpText>Integration Driven - Number identifying the authorization</inlineHelpText>
        <label>Authorization Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_c__c</fullName>
        <externalDeveloperName>Hours__c</externalDeveloperName>
        <label>Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_c__c</fullName>
        <externalDeveloperName>Type__c</externalDeveloperName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CCCAP_AUTHORIZED</fullName>
                    <label>CCCAP Authorized</label>
                </value>
                <value>
                    <fullName>PRIVATE_PAY</fullName>
                    <label>Private Pay</label>
                </value>
                <value>
                    <fullName>DROP_IN</fullName>
                    <label>Drop In</label>
                </value>
                <value>
                    <fullName>CCCAP_NOT_AUTHORIZED</fullName>
                    <label>CCCAP Not Authorized</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Schedule</label>
    <pluralLabel>Schedules</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>T_AUTH</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_AUTH__c</fullName>
        <description>Authorization Begin Date</description>
        <label>Authorization Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_AUTH__c</fullName>
        <label>Authorization End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authorization_Status__c</fullName>
        <label>Authorization Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <default>true</default>
                    <label>Authorized</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Terminated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isFinishedFlow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check successfully created authorization using flow.</description>
        <label>isFinishedFlow</label>
        <type>Checkbox</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_AUTH_ABSENCE__c.object
<CustomObject>
    
    <fields>
        <fullName>IDN_AUTH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Authorization ID</label>
        <referenceTo>T_AUTH__c</referenceTo>
        <relationshipLabel>Authorization Absences</relationshipLabel>
        <relationshipName>Authorization_Absences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Authorization Absence External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Number_of_Absences_From_ATS__c</fullName>
        <label>Number of Absences From ATS</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Authorization Absence</label>
    <nameField>
        <displayFormat>AA-{0}</displayFormat>
        <label>Authorization Absence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorization Absences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_TYPE_PROVR__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00691</valueSetName>
        </valueSet>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_RATE__c.object
<CustomObject>
    <description>County Rate</description>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>Status</description>
        <label>Status(Old)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00676</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_RATE__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_RATE__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Rate Plan</relationshipLabel>
        <relationshipName>County4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IND_RATE_PLAN_TEMPLT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>County Rate Plan Template Indicator</description>
        <label>County Rate Plan Template Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAYMENT_Q13_1__c</fullName>
        <description>PAYMENT_Q13_1</description>
        <label>PAYMENT_Q13_1</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_PAYMENT_Q13_1</valueSetName>
        </valueSet>
    </fields>

    <label>County Rate Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Rate Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Approved Plan cannot be updated</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)), TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_YEAR_HOL__c.object
<CustomObject>
    <description>Year Holiday</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_HOL__c</fullName>
        <description>CDE_HOL</description>
        <label>Holiday ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_PAYMENT_Q13_1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_YEAR__c</fullName>
        <description>Year</description>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTE_HOL__c</fullName>
        <description>Holiday Date</description>
        <label>Holiday Date</label>
        <type>Date</type>
    </fields>
    <label>Holiday Date</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holiday Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00676.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PEN</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>SUB</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>APV</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>NRV</fullName>
        <label>Need Revision</label>
    </customValue>
    <description>R00676</description>
    <masterLabel>R00676</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/RT_PAYMENT_Q13_1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>Christmas Day</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Francis Xavier Cabrini Day</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Independence Day</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Labor Day</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Martin Luther King Jr. Day</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Memorial Day</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>New Year&apos;s Day</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>President&apos;s Day</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Thanksgiving Day</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Veteran&apos;s Day</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Juneteenth</label>
    </customValue>
    <description>RT_PAYMENT_Q13_1</description>
    <masterLabel>RT_PAYMENT_Q13_1</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/AuthAbsenceHoursFromATS.cls
global with sharing class AuthAbsenceHoursFromATS implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        Date dateToday =  System.today() ;
        return Database.getQueryLocator('SELECT Id,Name,isFinishedFlow__c,Authorization_Status__c, DTE_BEGIN_EFFV_AUTH__c,DTE_END_EFFV_AUTH__c, IDN_EXTNL__c, IDN_PROVR__c, CDE_COUNTY__c FROM T_AUTH__c Where DTE_BEGIN_EFFV_AUTH__c <=:dateToday and (DTE_END_EFFV_AUTH__c = null or DTE_END_EFFV_AUTH__c >=: dateToday)');   
        
    }
    
    
    global void execute(Database.BatchableContext BC, List<T_AUTH__c> scope){
        
        Map<date,T_YEAR_HOL__c> holidayMapForCurrentYear = new Map<date,T_YEAR_HOL__c>();
        Map<string,date> holidayMapFromCodeToDate = new Map<string, date>();
        Map<date,string> holidayMapFromDateToCode = new Map<date, string>();
        
        Map<decimal, List<Schedule_c__x>> mapAuthIdToScheduleList = new Map<decimal, List<Schedule_c__x>>();
        Map<string, decimal> mapAuthSfidToAbsenceHours = new Map<string,decimal>();
        List<T_AUTH_ABSENCE__c> ListOfStagingRecordsToBeUpdtd = new List<T_AUTH_ABSENCE__c>();
        Map<decimal,string> authIdToSfid = new Map<decimal,string>();
        integer currentYear = system.today().year();
        Date todayMinusNineDays = system.today() - 9;
        
        set<string> provrSfidsFromAuth = new set<string>();
        set<string> countySfidsFromAuth = new set<string>();
        Map<string, string> provrSfidToType = new Map<string, string>();
        Map<string, string> countySfidToCRPHolidays = new Map<string, string>();
        Map<decimal,string> mapAuthIdToProvrType = new Map<decimal, string>();
        Map<decimal,list<string>> mapAuthIdToCRPHolidays = new Map<decimal,list<string>>();
        Map<decimal,set<string>> mapAuthIdToCRPHolidaysSet = new Map<decimal,set<string>>();
        Map<decimal,string> mapAuthIdToCRPHolidaysString = new Map<decimal,string>();
        
        
        for(T_AUTH__C eachAuth : scope){
            provrSfidsFromAuth.add(eachAuth.IDN_PROVR__c);
            countySfidsFromAuth.add(eachAuth.CDE_COUNTY__c);
        }
        
        
        for(T_YEAR_HOL__c eachHoliday : [SELECT Id, Name, CDE_HOL__c, CDE_YEAR__c, DTE_HOL__c FROM T_YEAR_HOL__c where DTE_HOL__c = LAST_N_DAYS:9 WITH SECURITY_ENFORCED]){
            holidayMapForCurrentYear.put(eachHoliday.DTE_HOL__c,eachHoliday);
            holidayMapFromCodeToDate.put(eachHoliday.CDE_HOL__c,eachHoliday.DTE_HOL__c);
            holidayMapFromDateToCode.put(eachHoliday.DTE_HOL__c,eachHoliday.CDE_HOL__c);
        }
        
        for(T_CHATS_PROVR_STATUS__c eachProvr : [SELECT Id, Name, CDE_TYPE_PROVR__c FROM T_CHATS_PROVR_STATUS__c where Id in:provrSfidsFromAuth WITH SECURITY_ENFORCED]){
            provrSfidToType.put(eachProvr.Id, eachProvr.CDE_TYPE_PROVR__c);
        }
        
        for(T_COUNTY_RATE__c eachCRP : [SELECT  Id, IDN_COUNTY__c, PAYMENT_Q13_1__c
                                        FROM T_COUNTY_RATE__c 
                                        WHERE IDN_COUNTY__c in:countySfidsFromAuth
                                        AND DTE_BEGIN_EFFV_RATE__c<=:system.today()
                                        AND (DTE_END_EFFV_RATE__c>=:system.today() OR DTE_END_EFFV_RATE__c=null)
                                        AND CDE_STATUS__c = 'APV'
                                        AND IND_RATE_PLAN_TEMPLT__c = false WITH SECURITY_ENFORCED]){
                                            
                                            countySfidToCRPHolidays.put(eachCRP.IDN_COUNTY__c, eachCRP.PAYMENT_Q13_1__c);  
                                            
                                        }
        
        for(T_AUTH__C eachAuth : scope){
            authIdToSfid.put(decimal.valueOf(eachAuth.Name), eachAuth.Id);
            mapAuthIdToProvrType.put(decimal.valueOf(eachAuth.Name), provrSfidToType.get(eachAuth.IDN_PROVR__c));
            
            if(countySfidToCRPHolidays.containsKey(eachAuth.CDE_COUNTY__c)){
                if(countySfidToCRPHolidays.get(eachAuth.CDE_COUNTY__c) != null){
                    List<string> listOfHolidaysPerAuthPerCRP = countySfidToCRPHolidays.get(eachAuth.CDE_COUNTY__c).split(';');
                    set<string> setOfHolidaysPerAuthPerCRP = new set<string>();
                    setOfHolidaysPerAuthPerCRP.addAll(listOfHolidaysPerAuthPerCRP);
                	mapAuthIdToCRPHolidays.put(decimal.valueOf(eachAuth.Name), countySfidToCRPHolidays.get(eachAuth.CDE_COUNTY__c).split(';')); 
                    mapAuthIdToCRPHolidaysSet.put(decimal.valueOf(eachAuth.Name), setOfHolidaysPerAuthPerCRP); 
                }
                mapAuthIdToCRPHolidaysString.put(decimal.valueOf(eachAuth.Name), countySfidToCRPHolidays.get(eachAuth.CDE_COUNTY__c));
            }
        }
        
        if(!authIdToSfid.isEmpty()){
            for(Schedule_c__x eachSchedule : [select CI_Authorization_Id_c__c, CI_Authorization_Hours_c__c, Hours_c__c, Type_c__c, Attended_c__c, CI_Authorization_Date_c__c
                                              FROM Schedule_c__x
                                              WHERE CI_Authorization_Date_c__c >=: todayMinusNineDays
                                              AND CI_Authorization_Date_c__c <: system.today()
                                              AND CI_Authorization_Id_c__c in:authIdToSfid.keySet()
                                              AND CI_Authorization_Hours_c__c > 0 WITH SECURITY_ENFORCED]){
                                                  
                                                  if(mapAuthIdToScheduleList.containsKey(eachSchedule.CI_Authorization_Id_c__c)) {
                                                      List<Schedule_c__x> existingScheduleList = mapAuthIdToScheduleList.get(eachSchedule.CI_Authorization_Id_c__c);
                                                      existingScheduleList.add(eachSchedule);
                                                      mapAuthIdToScheduleList.put(eachSchedule.CI_Authorization_Id_c__c, existingScheduleList);
                                                  } else {
                                                      List<Schedule_c__x> newScheduleList = new List<Schedule_c__x>();
                                                      newScheduleList.add(eachSchedule);
                                                      mapAuthIdToScheduleList.put(eachSchedule.CI_Authorization_Id_c__c, newScheduleList);
                                                  }
                                                  
                                              }
            
            for(decimal eachAuthId : authIdToSfid.keySet()){
                decimal numberofAbsences = 0;
                if(mapAuthIdToScheduleList.containsKey(eachAuthId)){
                    if(mapAuthIdToProvrType.containsKey(eachAuthId) && mapAuthIdToProvrType.get(eachAUthId) == 'EFACH'){
                        for(Schedule_c__x eachOfCompleteScheduleListForAuth : mapAuthIdToScheduleList.get(eachAuthId)){
                            if(	(eachOfCompleteScheduleListForAuth.Hours_c__c == null && eachOfCompleteScheduleListForAuth.Type_c__c == 'CCCAP_AUTHORIZED') || 
                               (eachOfCompleteScheduleListForAuth.Hours_c__c == 0.00 && eachOfCompleteScheduleListForAuth.Type_c__c == 'CCCAP_AUTHORIZED' && eachOfCompleteScheduleListForAuth.Attended_c__c == false)
                              ){
                                  numberofAbsences++;
                              }
                        }
                    }else if(mapAuthIdToCRPHolidaysString.containsKey(eachAuthId)){
                        for(Schedule_c__x eachOfCompleteScheduleListForAuth : mapAuthIdToScheduleList.get(eachAuthId)){
                            if(	(eachOfCompleteScheduleListForAuth.Hours_c__c == null && eachOfCompleteScheduleListForAuth.Type_c__c == 'CCCAP_AUTHORIZED') || 
                               (eachOfCompleteScheduleListForAuth.Hours_c__c == 0.00 && eachOfCompleteScheduleListForAuth.Type_c__c == 'CCCAP_AUTHORIZED' && eachOfCompleteScheduleListForAuth.Attended_c__c == false)
                              ){
                                  if(holidayMapFromDateToCode.containsKey(eachOfCompleteScheduleListForAuth.CI_Authorization_Date_c__c)){
                                      if(mapAuthIdToCRPHolidaysString.get(eachAuthId) != null){ 
                                          if(mapAuthIdToCRPHolidaysSet.get(eachAuthId).contains(holidayMapFromDateToCode.get(eachOfCompleteScheduleListForAuth.CI_Authorization_Date_c__c))){
                                              
                                          }else{
                                              numberofAbsences++;
                                          } 
                                      } else {
                                      	numberofAbsences++;    
                                      }
                                  }else {
                                      numberofAbsences++;
                                  }
                              }
                        }
                    }
                    mapAuthSfidToAbsenceHours.put(authIdToSfid.get(eachAuthId), numberofAbsences);
                }                                     
            }
            
            // Using the map<authSfid,numberOfAbsences>, get the list of Staging table records that needs to be updated.
            
            if(!mapAuthSfidToAbsenceHours.isEmpty()){
                for(T_AUTH_ABSENCE__c eachAuthAbsenceRecord : [select Id, IDN_AUTH__c, Number_of_Absences_From_ATS__c FROM T_AUTH_ABSENCE__c WHERE IDN_AUTH__C in:mapAuthSfidToAbsenceHours.keySet() WITH SECURITY_ENFORCED]){
                    if(mapAuthSfidToAbsenceHours.containsKey(eachAuthAbsenceRecord.IDN_AUTH__c)){
                        T_AUTH_ABSENCE__c stagingRecordToBeUpdtd = new T_AUTH_ABSENCE__c();
                        stagingRecordToBeUpdtd.Id = eachAuthAbsenceRecord.Id;
                        stagingRecordToBeUpdtd.Number_of_Absences_From_ATS__c = mapAuthSfidToAbsenceHours.get(eachAuthAbsenceRecord.IDN_AUTH__c);
                        ListOfStagingRecordsToBeUpdtd.add(stagingRecordToBeUpdtd);
                    }
                    
                }
            }
            
            if(!ListOfStagingRecordsToBeUpdtd.isEmpty()){
                GenericDMLHandler.updateRecords(ListOfStagingRecordsToBeUpdtd, false,new Map<String,Object>{'Class__c'=>'AuthAbsenceHoursFromATS','Method__c'=>'execute'});
            }
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
        
    }
}