CHATS_SIT/force-app/main/default/objects/Service_Period_Config__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Release_Day__c</fullName>
        <label>Payment Release Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Monday</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Tuesday</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Wednesday</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Thursday</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Friday</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>Saturday</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>Sunday</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Period_Frequency__c</fullName>
        <description>Number of service periods (1, 2, 3, or 4 weeks) for which the state will pay
            providers at a time.</description>
        <label>Service Period Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>1 week</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 weeks</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 weeks</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 weeks</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Calculation_Day__c</fullName>
        <label>Payment Calculation Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>1 day before payment processing day</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 day before payment processing day</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Period Config</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Service Period Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Period Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SERV_PERIOD__c.object
<CustomObject>
    <description>Service period for payroll</description>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <label>Service Period</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Period ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/ServicePeriodConfigControllerTest.cls
@isTest
private class ServicePeriodConfigControllerTest {
    
    @TestSetup
    static void setup() {
        Service_Period_Config__c config = new Service_Period_Config__c(
            Service_Period_Frequency__c = '2',
            Payment_Release_Day__c = '1',
            Payment_Calculation_Day__c = '2'
        );
        insert config;
        
        T_SERV_PERIOD__c servicePeriod = new T_SERV_PERIOD__c(
            Name = '795',
            DTE_BEGIN_EFFV__c = Date.today().addDays(-7),
            DTE_END_EFFV__c = Date.today().addDays(-1)
        );
        insert servicePeriod;
    }
    
    @isTest
    static void testProcessRequestAllMethods() {
        ServicePeriodConfigController controller = new ServicePeriodConfigController();
        
        // Test getExistingServicePeriodConfig method
        Test.startTest();
        Object getResponse = controller.processRequest('getExistingServicePeriodConfig', null);
        
        LightningServerResponse getServerResponse = (LightningServerResponse) getResponse;
        // Test upsertServicePeriodConfig method
        Service_Period_Config__c newConfig = new Service_Period_Config__c(
            Service_Period_Frequency__c = '2',
            Payment_Release_Day__c = '3',
            Payment_Calculation_Day__c = '1'
        );
        String configData = JSON.serialize(newConfig);
        Map<String, Object> requestData = new Map<String, Object>{
            'configData' => configData
                };
                    String jsonParam = JSON.serialize(requestData);
        
        
        Object upsertResponse = controller.processRequest('upsertServicePeriodConfig', jsonParam);
        
        LightningServerResponse upsertServerResponse = (LightningServerResponse) upsertResponse;
        
        Object invalidResponse = controller.processRequest('invalidMethod', null);
        Test.stopTest();
        System.assertNotEquals(null, invalidResponse, 'Invalid response should not be null');
        LightningServerResponse invalidServerResponse = (LightningServerResponse) invalidResponse;
        System.assertEquals(true, invalidServerResponse.isSuccessful, 'Default response should be successful');
    }
}