CHATS_SIT/force-app/main/default/objects/T_ADJMT_CANCEL__c.object
<CustomObject>
    <description>This object will store the details of all the Recovery Adjustment Cancellations</description>
    <label>Adjustment Cancellation</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Cancellation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>CDE_RSN_CANCELLATION__c</fullName>
        <label>Reason for Cancellation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00862</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <label>Cancellation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00863</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_DISC_CANCELLATION__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cancellation Discovery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustment Cancellation</relationshipLabel>
        <relationshipName>Adjustment_Cancellation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSN_CANCEL_BODY__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reason for Cancellation Body</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RSN_CANCEL_SUBJECT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reason for Cancellation Subject</label>
        <length>38</length>
        <type>Text</type>
    </fields>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Status_Based_Access</fullName>
        <active>false</active>
        <description>When the cancellation record is in Submitted, Approved, Denied or Withdrawn the record will not be editable</description>
        <errorConditionFormula>AND(OR($Profile.Name = &quot;Business Office Supervisor&quot;, $Profile.Name = &quot;Universal User&quot;,$Profile.Name = &quot;Fiscal Worker Supervisor&quot;, $Profile.Name = &quot;CCCAP Program Internal Team&quot;),OR(ISPICKVAL(CDE_STATUS__c, &apos;2&apos;),ISPICKVAL(CDE_STATUS__c, &apos;3&apos;),ISPICKVAL(CDE_STATUS__c, &apos;4&apos;),ISPICKVAL(CDE_STATUS__c, &apos;6&apos;)))</errorConditionFormula>
        <errorMessage>This record can only be edited in Draft or Need Revision Status.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_PMT_DETAIL__c.object
<CustomObject>
    <description>Detail information about sub payment, payment corrections</description>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustment Payment Details</relationshipLabel>
        <relationshipName>AdjustmentPaymentDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment Payment Detail</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00862.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Created in error</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Death of Responsible Party/Head of Household</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Duplicate</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Invalid Recovery/Does Not Meet Policy</label>
    </customValue>
    <description>Reason for Cancellation of Adjustment</description>
    <masterLabel>R00862</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00863.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Denied</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Needs Revision</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Withdrawn</label>
    </customValue>
    <description>Status for Cancellation of Adjustment</description>
    <masterLabel>R00863</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/adjustmentCancellationApxCtrl.cls
//Created by Raina Yeole 10/19/2022
// Created for CCCAP-7013

public with sharing class adjustmentCancellationApxCtrl implements IRequest{
    public String jsonParam;
    private static Map<String, Object> requestObj;
    
    private static String getMapValue(String fieldName) {
        return (String)requestObj.get(fieldName);
    }
    
    public Object processRequest(String methodName, String jsonParam) {
        Object response = null;
        this.jsonParam = jsonParam;
        if(this.jsonParam != null){
            requestObj = (Map<String, Object>)JSON.deserializeUntyped(jsonParam);  
        }
        if (methodName == 'getAdjustmentDetails') {
            response = getAdjustmentDetails(getMapValue('adjustmentId'));
        } else if (methodName == 'getAdjustmentPayments') {
            response = getAdjustmentPayments(getMapValue('adjustmentId'));
        }
        return response;
    }
    
    @AuraEnabled 
    public static LightningServerResponse getAdjustmentDetails(String adjustmentId){
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful;
        List<User> user = [select Id,Profile.Name from User where id =: Userinfo.getUserId() limit 1];
        objectData.put('userProfile',user[0].Profile.Name);
        List<T_ADJMT_CANCEL__c> adjCanRecList = [Select Id, Name, IDN_ADJMT__c, DTE_DISC_CANCELLATION__c, CDE_STATUS__c,
                                                 CDE_RSN_CANCELLATION__c, RSN_CANCEL_BODY__c, RSN_CANCEL_SUBJECT__c 
                                                 from T_ADJMT_CANCEL__c where (IDN_ADJMT__c =: adjustmentId
                                                 and CDE_STATUS__c in ('1','2','5')) OR Id =:adjustmentId order by Createddate DESC Limit 1];
        
        if(!adjCanRecList.isEmpty() && adjCanRecList.size()>0){
            objectData.put('adjCanRecList',adjCanRecList[0]);
        }
        
        List<T_ADJMT_PMT_DETAIL__c> adjPaymentList = [Select Id from T_ADJMT_PMT_DETAIL__c where IDN_ADJMT__c =:adjustmentId limit 1];
        
        if(!adjPaymentList.isEmpty() && adjPaymentList.size()>0){
            objectData.put('adjPaymentList',adjPaymentList[0]);
        }
        
        isSuccessful = true;
        return new LightningServerResponse(isSuccessful,'Done',objectData);
    }
    
    @AuraEnabled
    public static LightningServerResponse getAdjustmentPayments(String adjustmentId){
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful;
        String message;
        
        List<T_ADJMT_PMT_DETAIL__c> adjPaymentList = [Select Id from T_ADJMT_PMT_DETAIL__c where IDN_ADJMT__c =:adjustmentId limit 1];
        
        if(!adjPaymentList.isEmpty() && adjPaymentList.size()>0){
            isSuccessful= false;
            message='This Adjustment Recovery has payments and cannot be cancelled.';
            objectData.put('redirect',false);
        }else{
            isSuccessful= true;
            objectData.put('redirect',true);
        }
        
        return new LightningServerResponse(isSuccessful,message,objectData);
    } 
}