CHATS_SIT/force-app/main/default/objects/T_ADJMT__c.object
<CustomObject>
    <description>Adjustment parent table that contains information about provider and case payment corrections</description>
    <fields>
        <fullName>AMT_ADJMT__c</fullName>
        <formula>CASE(TEXT(CDE_AGNST_ADJMT__c), &apos;1&apos;, Adjustment_Details_Amount__c, &apos;2&apos;, Non_Adjustment_Details_Amount__c,Null )</formula>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Provider_License_Closed</fullName>
        <active>false</active>
        <description>On Closed Provier Adjustment of type Claim can not be created</description>
        <errorConditionFormula>AND(  TEXT(CDE_TYPE_ADJMT__c) = &apos;1&apos;,NOT(ISPICKVAL( IDN_PROVR__r.CDE_STATUS_PROVR__c , &apos;Open&apos;)),OR((TEXT( CDE_STATUS_ADJMT__c ) = &apos;&apos;),(TEXT(CDE_STATUS_ADJMT__c) = &apos;1&apos;)) )</errorConditionFormula>
        <errorMessage>Adjustment cannot be created for the care dates when provider license status is closed</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV_ROLE__c.object
<CustomObject>
    <description>Identifies the primary applicant/head of household for a case</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <label>Case Individual Role</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/CR207DataLoader.cls
public class CR207DataLoader extends AbstractCorspdDataLoader {
    public CR207DataLoader(String corspdName, String caseId, Integer providerId, String corrId, String cntySfid, String adjustmentId, Boolean isCase, Boolean isProvider, String clientId){
        this.corspdName = corspdName;
        this.caseId = caseId;
        this.providerId = providerId;
        this.corrId = corrId;
        this.cntySfid = cntySfid;
        this.adjustmentId = adjustmentId;
        this.isCase = isCase;
        this.isProvider = isProvider;
        this.clientId = clientId;
    }
    
    public override String getxmldata() {
        XmlStreamWriter xmlWrtr = new XmlStreamWriter();
        xmlWrtr.writeStartDocument(null, '1.0" encoding="US-ASCII');
        xmlWrtr.writeStartElement(null, 'Correspondence', null);
        if(isCase == true) {
            setClientHeaderInfo(xmlWrtr);
        }
        if(isProvider == true) {
            setProviderHeaderAdjmtCntyInfo(xmlWrtr);
        }
        setKeyParameters(xmlWrtr);
        setFlags(xmlWrtr);
        xmlWrtr.writeEndElement(); 
        xmlWrtr.writeEndDocument();
        xmldata = xmlWrtr.getXmlString();
        xmlWrtr.close();
        return xmldata;
    }
    
    public override void setCorspdInfo(XmlStreamWriter xmlWrtr) {
        createElement(xmlWrtr, 'Template_Name', this.corspdName);
        createElement(xmlWrtr, 'Reason_Code', 'CR0005');
        createElement(xmlWrtr, 'CORSPD_Effective_Date', '2017-10-18');
        createElement(xmlWrtr, 'REPRINT_SW', 'N');
        createElement(xmlWrtr, 'lang_cd', 'EN');
    }
    
    public override void setKeyParameters(XmlStreamWriter xmlWrtr) {
        String providerIds = String.valueOf(this.providerId);
        List<T_SBSD_CASE_INDIV_ROLE__c> caseStateId = new List<T_SBSD_CASE_INDIV_ROLE__c>();
        List<T_ADJMT__c> adjustmentdetails=new List<T_ADJMT__c>();
        adjustmentdetails=[select id,Name,AMT_ADJMT__c from T_ADJMT__c where id=:adjustmentId limit 1];
        xmlWrtr.writeStartElement(null, 'KeyParameter', null);
        createElement(xmlWrtr, 'CorrespondenceId', this.corrId);
        if(isCase==true) {
            createElement(xmlWrtr, 'CaseNumber','Case #                        : '+ this.caseId);
        }
        if(isProvider==true) {
            createElement(xmlWrtr, 'CaseNumber','Provider Id                  : '+ providerIds);
        }
        Date dt = system.today();
        String dateRequested = dt.month() + '/' + dt.day() + '/' + dt.year();
        createElement(xmlWrtr, 'CreationDate', 'Date                            : '+dateRequested);
        
        if(adjustmentdetails.size() == 1) {
            createElement(xmlWrtr, 'AdjustmentNum','Adjustment #               : '+ adjustmentdetails[0].Name);
        } else {
            createElement(xmlWrtr, 'AdjustmentNum','');
        }
        
        if(adjustmentdetails.size() == 1) {
            createElement(xmlWrtr, 'BalanceOwed', 'Current Balance Owed: $'+String.valueOf(adjustmentdetails[0].AMT_ADJMT__c));
        } else {
            createElement(xmlWrtr, 'BalanceOwed', '');
        }
        xmlWrtr.writeEndElement();
    }
    
    public void setFlags(XmlStreamWriter xmlWrtr){
        xmlWrtr.writeStartElement(null, 'Flags' , null);
        createElement(xmlWrtr, 'isClient', 'true');
        createElement(xmlWrtr, 'isClientDeclaration', 'true');
        createElement(xmlWrtr, 'isHeader1', 'true');
        createElement(xmlWrtr, 'isHeader2', 'false');
        createElement(xmlWrtr, 'isProvider', 'false');
        createElement(xmlWrtr, 'isProviderDeclaration', 'false');
        xmlWrtr.writeEndElement();
    }
}