CHATS_SIT/force-app/main/default/objects/T_ADJMT__c.object
<CustomObject>
    <description>Adjustment parent table that contains information about provider and case payment corrections</description>
    <fields>
        <fullName>CDE_STATUS_ADJMT__c</fullName>
        <description>Adjustment Status</description>
        <label>Adjustment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00719</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_ADJMT__c</fullName>
        <description>Adjustment Type</description>
        <label>Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00718</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_DISCV_ADJMT_ORIG__c</fullName>
        <description>Original Discovery Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Original Discovery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Adjustments</relationshipLabel>
        <relationshipName>Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Finalized</fullName>
        <active>true</active>
        <label>Finalized</label>
    </recordTypes>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Provider_License_Closed</fullName>
        <active>false</active>
        <description>On Closed Provier Adjustment of type Claim can not be created</description>
        <errorConditionFormula>AND(  TEXT(CDE_TYPE_ADJMT__c) = &apos;1&apos;,NOT(ISPICKVAL( IDN_PROVR__r.CDE_STATUS_PROVR__c , &apos;Open&apos;)),OR((TEXT( CDE_STATUS_ADJMT__c ) = &apos;&apos;),(TEXT(CDE_STATUS_ADJMT__c) = &apos;1&apos;)) )</errorConditionFormula>
        <errorMessage>Adjustment cannot be created for the care dates when provider license status is closed</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_DETAIL__c.object
<CustomObject>
    <description>Detail information about payment corrections</description>
    <fields>
        <fullName>AMT_DETAIL_ADJMT__c</fullName>
        <description>Adjusted Amount (Adjusted Rate Paid minu</description>
        <label>Adjusted Amount (Adjusted Rate Paid minu</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustment Detail</relationshipLabel>
        <relationshipName>Adjustment3</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Adjustment Detail</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_PMT__c.object
<CustomObject>
    <description>Information about payments made to satisfy the debt recorded for a provider or case</description>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Adjustment Payments</relationshipLabel>
        <relationshipName>Adjustment_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_PMT_DETAIL__c.object
<CustomObject>
    <description>Detail information about sub payment, payment corrections</description>
    <fields>
        <fullName>AMT_PMT_DETAIL_ADJMT__c</fullName>
        <description>Amount</description>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS_DETAIL_PMT_ADJMT__c</fullName>
        <defaultValue>&apos;3&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00716</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustment Payment Details</relationshipLabel>
        <relationshipName>AdjustmentPaymentDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment Payment Detail</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Tax_Intercept__c.object
<CustomObject>
    <description>OEC Project 282 - JIRA CCCAP-3890. The Colorado Child Care Assistance Program under statute, has the ability to intercept state income tax refunds for any individual or entity who owes a recovery for benefits for which they were not eligible.</description>
    <fields>
        <fullName>Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment ID</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Tax Intercepts</relationshipLabel>
        <relationshipName>Tax_Intercepts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tax Intercept</label>
    <nameField>
        <displayFormat>TI{YYYY}{MM}{DD}{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Intercepts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00716.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Calculated</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Paid</label>
    </customValue>
    <description>R00716</description>
    <masterLabel>R00716</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00718.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Claim</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Recovery</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Funding Program</label>
    </customValue>
    <description>R00718</description>
    <masterLabel>R00718</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00719.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>In Process</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calculation Complete</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Satisfied</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Paid</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Cancellation In Progress</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Cancelled</label>
    </customValue>
    <description>R00719</description>
    <masterLabel>R00719</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/adjustmentPaymentDetailTriggerTest.cls
/***********************************************************
*  @author         Deloitte Consulting LLP.
*  @date           02/17/2018
*  @description    Adjustment Payment Detail Trigger Test
*  * Version: 1.0
*  * Date: 02/17/2018
*  * Author: Gaurav Dharra
*  * Description: Initial version
***********************************************************/
@isTest
public class adjustmentPaymentDetailTriggerTest {

    public static testMethod void testStampSalesforceIdToExternalId(){
        T_COUNTY__c countyObj = TestClassUtility.createCounty('Denver', 'Denver', 16, false);
        Insert countyObj;
        TestClassUtility.createCase(true, countyObj.Id);
        T_CHATS_PROVR_STATUS__c providerObj = TestClassUtility.createProvider(true, 'Test');
        Id recordTypeId = Schema.SObjectType.T_ADJMT__c.getRecordTypeInfosByName().get('Finalized').getRecordTypeId();
        T_ADJMT__c adjObj = TestClassUtility.createAdjustment(false, countyObj.Id, null, null);
        adjObj.IDN_PROVR__c = providerObj.Id;
        adjObj.CDE_STATUS_ADJMT__c = '2';
        adjObj.CDE_TYPE_ADJMT__c = '2';
        adjObj.RecordtypeId = recordTypeId;
        adjObj.DTE_DISCV_ADJMT_ORIG__c = System.today();
        insert adjObj;
        T_ADJMT_DETAIL__c adjDetail = TestClassUtility.createAdjustmentDetail(false, adjObj.Id);
        adjDetail.AMT_DETAIL_ADJMT__c = 10;
        T_ADJMT_PMT__c adjPayment = TestClassUtility.createAdjustmentPayment(false, null, providerObj.Id);
        Insert adjPayment;
        Tax_Intercept__c ti = new Tax_Intercept__c(Adjustment__c = adjObj.Id);
        Insert ti;
        Test.startTest();
        List<T_ADJMT_PMT_DETAIL__c> adjPmtDetList = new List<T_ADJMT_PMT_DETAIL__c>();
        T_ADJMT_PMT_DETAIL__c adjPmtDet1 = TestClassUtility.createAdjustmentPaymentDetail(false, adjDetail.Id, adjObj.Id, adjPayment.Id);
        adjPmtDet1.IDN_ADJMT__c = adjObj.Id;
        adjPmtDet1.CDE_STATUS_DETAIL_PMT_ADJMT__c = '4';
        adjPmtDet1.AMT_PMT_DETAIL_ADJMT__c = 10;
        adjPmtDetList.add(adjPmtDet1);
        T_ADJMT_PMT_DETAIL__c adjPmtDet2 = TestClassUtility.createAdjustmentPaymentDetail(false, adjDetail.Id, adjObj.Id, adjPayment.Id);
        adjPmtDet2.IDN_ADJMT__c = adjObj.Id;
        adjPmtDet2.CDE_STATUS_DETAIL_PMT_ADJMT__c = '4';
        adjPmtDet2.AMT_PMT_DETAIL_ADJMT__c = 5;
        adjPmtDetList.add(adjPmtDet2);
        Insert adjPmtDetList;
        Test.stopTest();
    }
}