CHATS_SIT/force-app/main/default/objects/T_ADJMT__c.object
<CustomObject>
    <description>Adjustment parent table that contains information about provider and case payment corrections</description>
    <fields>
        <fullName>CDE_AGNST_ADJMT__c</fullName>
        <description>Adjustment Payment Type</description>
        <label>Adjustment Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00727</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS_ADJMT__c</fullName>
        <description>Adjustment Status</description>
        <label>Adjustment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00719</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_ADJMT__c</fullName>
        <description>Adjustment Type</description>
        <label>Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00718</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_CLSFN__c</fullName>
        <description>Classification Type</description>
        <label>Classification Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00730</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_DISCV_ADJMT_ORIG__c</fullName>
        <description>Original Discovery Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Original Discovery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_ADJMT__c</fullName>
        <description>Care End Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_START_ADJMT__c</fullName>
        <description>Care Start Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Adjustments</relationshipLabel>
        <relationshipName>Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Provider_License_Closed</fullName>
        <active>false</active>
        <description>On Closed Provier Adjustment of type Claim can not be created</description>
        <errorConditionFormula>AND(  TEXT(CDE_TYPE_ADJMT__c) = &apos;1&apos;,NOT(ISPICKVAL( IDN_PROVR__r.CDE_STATUS_PROVR__c , &apos;Open&apos;)),OR((TEXT( CDE_STATUS_ADJMT__c ) = &apos;&apos;),(TEXT(CDE_STATUS_ADJMT__c) = &apos;1&apos;)) )</errorConditionFormula>
        <errorMessage>Adjustment cannot be created for the care dates when provider license status is closed</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_ADDR__c.object
<CustomObject>
    <description>Information about the address used to create adjustment related correspondence</description>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustment Address</relationshipLabel>
        <relationshipName>Adjustment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment Address</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_CMT__c.object
<CustomObject>
    <description>Information about worker comments entered for adjustments</description>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipName>Adjustment2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TXT_SUBJ__c</fullName>
        <description>Subject</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Subject</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Adjustment Note</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_RESPBL_PARTY__c.object
<CustomObject>
    <description>Entity/caretaker responsible for the repayment of a debt incurred as a result of payment correction</description>
   <!--<enableChangeDataCapture>false</enableChangeDataCapture>--> 
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustent5</relationshipLabel>
        <relationshipName>Adjustent5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Adjustment Responsible Parties</relationshipLabel>
        <relationshipName>Adjustment_Responsible_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment Responsible Party</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Responsible Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00718.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Claim</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Recovery</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Funding Program</label>
    </customValue>
    <description>R00718</description>
    <masterLabel>R00718</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00719.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>In Process</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calculation Complete</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Satisfied</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Paid</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Cancellation In Progress</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Cancelled</label>
    </customValue>
    <description>R00719</description>
    <masterLabel>R00719</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00727.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Sub-Payment</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Non Sub-Payment</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <description>R00727</description>
    <masterLabel>R00727</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00730.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Fraud/IPV</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Judgment Recovery</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Household/Provider Error</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Other Recoveries</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <isActive>false</isActive>
        <label>Agency Error</label>
    </customValue>
    <description>R00730</description>
    <masterLabel>R00730</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/AdjustmentServices_Test.cls
@isTest
private class AdjustmentServices_Test {
public static final String newRecordTypeId = Schema.SObjectType.T_ADJMT__c.getRecordTypeInfosByName().get('New').getRecordTypeId();
       @testSetup static void setup() {
        List<T_ADJMT_RESPBL_PARTY__c> adjmtRespblPartyList = new List<T_ADJMT_RESPBL_PARTY__c>();
        List<T_ADJMT_ADDR__c> adjmtAddressList = new List<T_ADJMT_ADDR__c>();
        List<T_ADJMT_CMT__c> adjmtCmtList = new List<T_ADJMT_CMT__c>();
        List<T_ADJMT__c> adjmtList = new List<T_ADJMT__c>();
        List<T_CHATS_PROVR_STATUS__c> providerList= new List<T_CHATS_PROVR_STATUS__c>();
        
        for(Integer i=0;i<201;i++) {
            providerList.add(new T_CHATS_PROVR_STATUS__c());
        }
        
        insert providerList;
        
        for(Integer i=0;i<201;i++) {
            adjmtList.add(new T_ADJMT__c(CDE_STATUS_ADJMT__c='1',CDE_TYPE_ADJMT__c='2',CDE_TYPE_CLSFN__c='3',CDE_AGNST_ADJMT__c='1',IDN_PROVR__c=providerList[i].Id,DTE_END_ADJMT__c=date.newInstance(2018, 1, 10),DTE_START_ADJMT__c=date.newInstance(2018, 1, 8),RecordtypeId=newRecordTypeId,DTE_DISCV_ADJMT_ORIG__c=System.today()));
        }
        insert adjmtList;
        
        for(Integer i=0;i<201;i++) {
            adjmtCmtList.add(new T_ADJMT_CMT__c(TXT_SUBJ__c='subject test',IDN_ADJMT__c=adjmtList[i].Id));
        }
        insert adjmtCmtList;
        
        for(Integer i=0;i<201;i++) {
            adjmtAddressList.add(new T_ADJMT_ADDR__c(IDN_ADJMT__c=adjmtList[i].Id));
        
        }
        insert adjmtAddressList;
        
        for(Integer i=0;i<201;i++) {
            adjmtRespblPartyList.add(new T_ADJMT_RESPBL_PARTY__c(IDN_PROVR__c=providerList[i].Id,IDN_ADJMT__c=adjmtList[i].Id));
        
        }
        insert adjmtRespblPartyList;
        
    }
     
    
    static testMethod void deleteAllChildAdjustmentRecordsBulkTest() {
        List<T_ADJMT_RESPBL_PARTY__c> adjmtRespblPartyList =[select Id from T_ADJMT_RESPBL_PARTY__c Limit 202];
        List<T_ADJMT_ADDR__c> adjmtAddressList =[select Id from T_ADJMT_ADDR__c Limit 202];
        List<T_ADJMT_CMT__c> adjmtCmtList =[select Id from T_ADJMT_CMT__c Limit 202];
        List<T_ADJMT__c> adjmtList=[select Id from T_ADJMT__c Limit 202];
        
        
        system.assert(adjmtList.size()>200,'Records count mismatch');
        system.assert(adjmtCmtList.size()>200,'Records count mismatch');
        system.assert(adjmtAddressList.size()>200,'Records count mismatch');
        system.assert(adjmtRespblPartyList.size()>200,'Records count mismatch');
        
        delete adjmtList;
        
        List<T_ADJMT_RESPBL_PARTY__c> adjmtRespblPartyList2 =[select Id from T_ADJMT_RESPBL_PARTY__c Limit 202];
        List<T_ADJMT_ADDR__c> adjmtAddressList2 =[select Id from T_ADJMT_ADDR__c Limit 202];
        List<T_ADJMT_CMT__c> adjmtCmtList2 =[select Id from T_ADJMT_CMT__c Limit 202];
        List<T_ADJMT__c> adjmtList2=[select Id from T_ADJMT__c Limit 202];
        
        system.assertEquals(0,adjmtList2.size(),'Records are not deleted');
        system.assertEquals(0,adjmtCmtList2.size(),'Records are not deleted');
        system.assertEquals(0,adjmtAddressList2.size(),'Records are not deleted');
        system.assertEquals(0,adjmtRespblPartyList2.size(),'Records are not deleted');
        
        
    }


}