CHATS_SIT/force-app/main/default/objects/T_ADJMT__c.object
<CustomObject>
    <description>Adjustment parent table that contains information about provider and case payment corrections</description>
    <fields>
        <fullName>CDE_AGNST_ADJMT__c</fullName>
        <description>Adjustment Payment Type</description>
        <label>Adjustment Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00727</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Adjustment County</relationshipLabel>
        <relationshipName>Adjustment_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS_ADJMT__c</fullName>
        <description>Adjustment Status</description>
        <label>Adjustment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00719</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_ADJMT__c</fullName>
        <description>Adjustment Type</description>
        <label>Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00718</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_CLSFN__c</fullName>
        <description>Classification Type</description>
        <label>Classification Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00730</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_DISCV_ADJMT_ORIG__c</fullName>
        <description>Original Discovery Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Original Discovery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_ADJMT__c</fullName>
        <description>Care End Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_START_ADJMT__c</fullName>
        <description>Care Start Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Care Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Adjustments</relationshipLabel>
        <relationshipName>Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Finalized</fullName>
        <active>true</active>
        <label>Finalized</label>
    </recordTypes>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Provider_License_Closed</fullName>
        <active>false</active>
        <description>On Closed Provier Adjustment of type Claim can not be created</description>
        <errorConditionFormula>AND(  TEXT(CDE_TYPE_ADJMT__c) = &apos;1&apos;,NOT(ISPICKVAL( IDN_PROVR__r.CDE_STATUS_PROVR__c , &apos;Open&apos;)),OR((TEXT( CDE_STATUS_ADJMT__c ) = &apos;&apos;),(TEXT(CDE_STATUS_ADJMT__c) = &apos;1&apos;)) )</errorConditionFormula>
        <errorMessage>Adjustment cannot be created for the care dates when provider license status is closed</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_DETAIL__c.object
<CustomObject>
    <description>Detail information about payment corrections</description>
    <fields>
        <fullName>AMT_DETAIL_ADJMT__c</fullName>
        <description>Adjusted Amount (Adjusted Rate Paid minu</description>
        <label>Adjusted Amount (Adjusted Rate Paid minu</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS_DETAIL_ADJMT__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00719</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustment Detail</relationshipLabel>
        <relationshipName>Adjustment3</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Adjustment Detail</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_PMT__c.object
<CustomObject>
    <description>Information about payments made to satisfy the debt recorded for a provider or case</description>
    <fields>
        <fullName>AMT_PMT_ADJMT__c</fullName>
        <description>Amount</description>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AMT_PMT_SRPLUS_ADJMT__c</fullName>
        <description>Surplus Amount</description>
        <label>Surplus Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_PMT_ADJMT__c</fullName>
        <description>Payment Type</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00733</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_PMT_ADJMT__c</fullName>
        <description>Date Paid</description>
        <label>Date Paid</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Adjustment Payments</relationshipLabel>
        <relationshipName>Adjustment_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00005</valueSetName>
        </valueSet>
    </fields>
    <label>Adjustment Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_PMT_DETAIL__c.object
<CustomObject>
    <description>Detail information about sub payment, payment corrections</description>
    <fields>
        <fullName>AMT_PMT_DETAIL_ADJMT__c</fullName>
        <description>Amount</description>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustment Payment Details</relationshipLabel>
        <relationshipName>AdjustmentPaymentDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_DETAIL_ADJMT_NON__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Non Adjustment Detail</description>
        <label>Non Adjustment Detail</label>
        <referenceTo>T_NON_ADJMT_DETAIL__c</referenceTo>
        <relationshipLabel>Non Adjustment details</relationshipLabel>
        <relationshipName>Non_Adjustment_details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_DETAIL_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment Detail</description>
        <label>Adjustment Detail</label>
        <referenceTo>T_ADJMT_DETAIL__c</referenceTo>
        <relationshipLabel>Adjustment Details</relationshipLabel>
        <relationshipName>Adjustment_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PMT_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment Payment</description>
        <label>Adjustment Payment</label>
        <referenceTo>T_ADJMT_PMT__c</referenceTo>
        <relationshipLabel>Adjustment Payment Detail</relationshipLabel>
        <relationshipName>Adjustment_Payment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment Payment Detail</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CNTY_DEPT_NAME__c</fullName>
        <description>County Department Name</description>
        <label>County Department Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_NON_ADJMT_DETAIL__c.object
<CustomObject>
    <description>Detail information for non sub payment adjustments</description>
    <fields>
        <fullName>AMT_DETAIL_ADJMT__c</fullName>
        <description>Adjustment Amount</description>
        <label>Adjustment Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS_DETAIL_ADJMT__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00719</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Non Adjustment Details</relationshipLabel>
        <relationshipName>Adjustment6</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IDN_DETAIL_ADJMT_NON__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Non Adjustment Detail</label>
    <nameField>
        <label>Non Adjustment Detail ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non Adjustment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <description>Provider ID</description>
        <label>Provider ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00718.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Claim</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Recovery</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Funding Program</label>
    </customValue>
    <description>R00718</description>
    <masterLabel>R00718</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00719.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>In Process</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calculation Complete</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Satisfied</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Paid</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Cancellation In Progress</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Cancelled</label>
    </customValue>
    <description>R00719</description>
    <masterLabel>R00719</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00727.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Sub-Payment</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Non Sub-Payment</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <description>R00727</description>
    <masterLabel>R00727</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00730.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Fraud/IPV</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Judgment Recovery</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Household/Provider Error</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Other Recoveries</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <isActive>false</isActive>
        <label>Agency Error</label>
    </customValue>
    <description>R00730</description>
    <masterLabel>R00730</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00733.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Cash</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Check</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Credit Card</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>EBT Adjustment</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Administrative Action</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Adjustment Reduction, Court Ordered Judgment</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Refund/Over Payment</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>CDOR</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Payment Through Payment Plan</label>
    </customValue>
    <description>R00733</description>
    <masterLabel>R00733</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/AdjustmentPaymentServices_Test.cls
@isTest
private class AdjustmentPaymentServices_Test {
    
    static testMethod void testCreateAdjustmentPaymentDetails() {
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1');
        insert provider;
        Id recordTypeId = Schema.SObjectType.T_ADJMT__c.getRecordTypeInfosByName().get('Finalized').getRecordTypeId();
        
        List<T_ADJMT__c> adjustmentList= new List<T_ADJMT__c>();
        adjustmentList.add( new T_ADJMT__c(RecordtypeId=recordTypeId,CDE_STATUS_ADJMT__c='2',CDE_TYPE_ADJMT__c='2',CDE_TYPE_CLSFN__c='3',CDE_AGNST_ADJMT__c='1',IDN_PROVR__c=provider.Id,DTE_END_ADJMT__c=date.newInstance(2018, 1, 10),DTE_START_ADJMT__c=date.newInstance(2018, 1, 8),DTE_DISCV_ADJMT_ORIG__c=date.newInstance(2018, 1, 8)));
        adjustmentList.add( new T_ADJMT__c(RecordtypeId=recordTypeId,CDE_STATUS_ADJMT__c='2',CDE_TYPE_ADJMT__c='2',CDE_TYPE_CLSFN__c='1',CDE_AGNST_ADJMT__c='2',IDN_PROVR__c=provider.Id,DTE_END_ADJMT__c=date.newInstance(2018, 1, 10),DTE_START_ADJMT__c=date.newInstance(2018, 1, 8),DTE_DISCV_ADJMT_ORIG__c=date.newInstance(2018, 1, 8)));
        adjustmentList.add( new T_ADJMT__c(RecordtypeId=recordTypeId,CDE_STATUS_ADJMT__c='2',CDE_TYPE_ADJMT__c='2',CDE_TYPE_CLSFN__c='1',CDE_AGNST_ADJMT__c='2',IDN_PROVR__c=provider.Id,DTE_END_ADJMT__c=date.newInstance(2018, 1, 10),DTE_START_ADJMT__c=date.newInstance(2018, 1, 8),DTE_DISCV_ADJMT_ORIG__c=date.newInstance(2018, 1, 8)));
        insert adjustmentList;
        
        List<T_ADJMT_DETAIL__c> adjustDetailList = new List<T_ADJMT_DETAIL__c>();
        adjustDetailList.add(new T_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=100,IDN_ADJMT__c=adjustmentList[0].Id));
        adjustDetailList.add(new T_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=200,IDN_ADJMT__c=adjustmentList[0].Id));
        adjustDetailList.add(new T_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=300,IDN_ADJMT__c=adjustmentList[0].Id));
        insert adjustDetailList;
        
        List<T_NON_ADJMT_DETAIL__c> nonAdjustDetailList = new List<T_NON_ADJMT_DETAIL__c>();
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=100,IDN_ADJMT__c=adjustmentList[1].Id));
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=200,IDN_ADJMT__c=adjustmentList[1].Id));
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=300,IDN_ADJMT__c=adjustmentList[1].Id));
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=10,IDN_ADJMT__c=adjustmentList[2].Id));
        insert nonAdjustDetailList;
        
        Test.startTest();
        
        T_ADJMT_PMT__c adjustmentPayment = new T_ADJMT_PMT__c(CDE_TYPE_PMT_ADJMT__c='1',AMT_PMT_ADJMT__c=600,IDN_PROVR__c=provider.Id,DTE_PMT_ADJMT__c=System.Today());
        insert adjustmentPayment;
        
        for(T_ADJMT_PMT_DETAIL__c adjutPaymDet:[Select Id,IDN_DETAIL_ADJMT_NON__r.AMT_DETAIL_ADJMT__c,IDN_DETAIL_ADJMT_NON__r.IDN_ADJMT__c,IDN_DETAIL_ADJMT_NON__r.CDE_STATUS_DETAIL_ADJMT__c, IDN_ADJMT__c,IDN_DETAIL_ADJMT_NON__c,IDN_PMT_ADJMT__c,AMT_PMT_DETAIL_ADJMT__c from T_ADJMT_PMT_DETAIL__c where IDN_PMT_ADJMT__c=:adjustmentPayment.Id and IDN_ADJMT__c=:adjustmentList[1].Id]) {
            system.assertEquals(adjutPaymDet.AMT_PMT_DETAIL_ADJMT__c,adjutPaymDet.IDN_DETAIL_ADJMT_NON__r.AMT_DETAIL_ADJMT__c,'Amount mismatch');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT_NON__r.IDN_ADJMT__c,adjutPaymDet.IDN_ADJMT__c,'Adjustment not Properly assigned');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT_NON__r.CDE_STATUS_DETAIL_ADJMT__c,'3','Status not changed to Satisfied');
        }
        system.assertEquals('2',[select CDE_STATUS_ADJMT__c from T_ADJMT__c where Id=:adjustmentList[1].Id Limit 1].CDE_STATUS_ADJMT__c ,'Adjustment not Satisfied');
        
        T_ADJMT_PMT__c adjustmentPayment2 = new T_ADJMT_PMT__c(CDE_TYPE_PMT_ADJMT__c='1',AMT_PMT_ADJMT__c=650,IDN_PROVR__c=provider.Id,DTE_PMT_ADJMT__c=System.Today());
        insert adjustmentPayment2;
        
        for(T_ADJMT_PMT_DETAIL__c adjutPaymDet:[Select Id,IDN_DETAIL_ADJMT__r.AMT_DETAIL_ADJMT__c,IDN_DETAIL_ADJMT__r.IDN_ADJMT__c,IDN_DETAIL_ADJMT__r.CDE_STATUS_DETAIL_ADJMT__c, IDN_ADJMT__c,IDN_DETAIL_ADJMT__c,IDN_PMT_ADJMT__c,AMT_PMT_DETAIL_ADJMT__c from T_ADJMT_PMT_DETAIL__c where IDN_PMT_ADJMT__c=:adjustmentPayment.Id and IDN_ADJMT__c=:adjustmentList[0].Id]) {
            system.assertEquals(adjutPaymDet.AMT_PMT_DETAIL_ADJMT__c,adjutPaymDet.IDN_DETAIL_ADJMT__r.AMT_DETAIL_ADJMT__c,'Amount mismatch');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT__r.IDN_ADJMT__c,adjutPaymDet.IDN_ADJMT__c,'Adjustment not Properly assigned');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT__r.CDE_STATUS_DETAIL_ADJMT__c,'3','Status not changed to Satisfied');
        }
        system.assertEquals('2',[select CDE_STATUS_ADJMT__c from T_ADJMT__c where Id=:adjustmentList[0].Id Limit 1].CDE_STATUS_ADJMT__c ,'Adjustment not Satisfied');
        // system.assertEquals(40,[Select AMT_PMT_SRPLUS_ADJMT__c from T_ADJMT_PMT__c where Id=:adjustmentPayment2.Id].AMT_PMT_SRPLUS_ADJMT__c, 'Surplus amount is not adjusted');
        Test.StopTest();
    }
    
    static testMethod void testCreateAdjustmentPaymentDetails2() {
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1');
        insert provider;
        Id recordTypeId = Schema.SObjectType.T_ADJMT__c.getRecordTypeInfosByName().get('Finalized').getRecordTypeId();
        
        List<T_ADJMT__c> adjustmentList= new List<T_ADJMT__c>();
        adjustmentList.add( new T_ADJMT__c(RecordtypeId=recordTypeId,CDE_STATUS_ADJMT__c='2',CDE_TYPE_ADJMT__c='2',CDE_TYPE_CLSFN__c='3',CDE_AGNST_ADJMT__c='1',IDN_PROVR__c=provider.Id,DTE_END_ADJMT__c=date.newInstance(2018, 1, 10),DTE_START_ADJMT__c=date.newInstance(2018, 1, 8),DTE_DISCV_ADJMT_ORIG__c=date.newInstance(2018, 1, 8)));
        adjustmentList.add( new T_ADJMT__c(RecordtypeId=recordTypeId,CDE_STATUS_ADJMT__c='2',CDE_TYPE_ADJMT__c='2',CDE_TYPE_CLSFN__c='1',CDE_AGNST_ADJMT__c='2',IDN_PROVR__c=provider.Id,DTE_END_ADJMT__c=date.newInstance(2018, 1, 10),DTE_START_ADJMT__c=date.newInstance(2018, 1, 8),DTE_DISCV_ADJMT_ORIG__c=date.newInstance(2018, 1, 8)));
        insert adjustmentList;
        
        List<T_ADJMT_DETAIL__c> adjustDetailList = new List<T_ADJMT_DETAIL__c>();
        adjustDetailList.add(new T_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=100,IDN_ADJMT__c=adjustmentList[0].Id));
        adjustDetailList.add(new T_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=200,IDN_ADJMT__c=adjustmentList[0].Id));
        adjustDetailList.add(new T_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=300,IDN_ADJMT__c=adjustmentList[0].Id));
        insert adjustDetailList;
        
        List<T_NON_ADJMT_DETAIL__c> nonAdjustDetailList = new List<T_NON_ADJMT_DETAIL__c>();
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=100,IDN_ADJMT__c=adjustmentList[1].Id));
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=200,IDN_ADJMT__c=adjustmentList[1].Id));
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=300,IDN_ADJMT__c=adjustmentList[1].Id));
        insert nonAdjustDetailList;
        
        Test.startTest();
        
        T_ADJMT_PMT__c adjustmentPayment = new T_ADJMT_PMT__c(CDE_TYPE_PMT_ADJMT__c='1',AMT_PMT_ADJMT__c=400,IDN_PROVR__c=provider.Id,DTE_PMT_ADJMT__c=System.Today());
        insert adjustmentPayment;
        T_ADJMT_PMT__c adjustmentPayment2 = new T_ADJMT_PMT__c(CDE_TYPE_PMT_ADJMT__c='1',AMT_PMT_ADJMT__c=200,IDN_PROVR__c=provider.Id,DTE_PMT_ADJMT__c=System.Today());
        insert adjustmentPayment2;
        
        for(T_ADJMT_PMT_DETAIL__c adjutPaymDet:[Select Id,IDN_DETAIL_ADJMT_NON__r.AMT_DETAIL_ADJMT__c,IDN_DETAIL_ADJMT_NON__r.IDN_ADJMT__c,IDN_DETAIL_ADJMT_NON__r.CDE_STATUS_DETAIL_ADJMT__c, IDN_ADJMT__c,IDN_DETAIL_ADJMT_NON__c,IDN_PMT_ADJMT__c,AMT_PMT_DETAIL_ADJMT__c from T_ADJMT_PMT_DETAIL__c where IDN_ADJMT__c=:adjustmentList[1].Id]) {
            system.assert(adjutPaymDet.AMT_PMT_DETAIL_ADJMT__c<=adjutPaymDet.IDN_DETAIL_ADJMT_NON__r.AMT_DETAIL_ADJMT__c,'Amount mismatch');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT_NON__r.IDN_ADJMT__c,adjutPaymDet.IDN_ADJMT__c,'Adjustment not Properly assigned');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT_NON__r.CDE_STATUS_DETAIL_ADJMT__c,'3','Status not changed to Satisfied');
        }
        system.assertEquals('2',[select CDE_STATUS_ADJMT__c from T_ADJMT__c where Id=:adjustmentList[1].Id Limit 1].CDE_STATUS_ADJMT__c ,'Adjustment not Satisfied');
        
        T_ADJMT_PMT__c adjustmentPayment3 = new T_ADJMT_PMT__c( CDE_TYPE_PMT_ADJMT__c='1',AMT_PMT_ADJMT__c=200,IDN_PROVR__c=provider.Id,DTE_PMT_ADJMT__c=System.Today());
        insert adjustmentPayment3;
        
        T_ADJMT_PMT__c adjustmentPayment4 = new T_ADJMT_PMT__c( CDE_TYPE_PMT_ADJMT__c='1',AMT_PMT_ADJMT__c=400,IDN_PROVR__c=provider.Id,DTE_PMT_ADJMT__c=System.Today());
        insert adjustmentPayment4;
        
        for(T_ADJMT_PMT_DETAIL__c adjutPaymDet:[Select Id,IDN_DETAIL_ADJMT__r.AMT_DETAIL_ADJMT__c,IDN_DETAIL_ADJMT__r.IDN_ADJMT__c,IDN_DETAIL_ADJMT__r.CDE_STATUS_DETAIL_ADJMT__c, IDN_ADJMT__c,IDN_DETAIL_ADJMT__c,IDN_PMT_ADJMT__c,AMT_PMT_DETAIL_ADJMT__c from T_ADJMT_PMT_DETAIL__c where IDN_ADJMT__c=:adjustmentList[0].Id]) {
            system.assert(adjutPaymDet.AMT_PMT_DETAIL_ADJMT__c<=adjutPaymDet.IDN_DETAIL_ADJMT__r.AMT_DETAIL_ADJMT__c,'Amount mismatch');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT__r.IDN_ADJMT__c,adjutPaymDet.IDN_ADJMT__c,'Adjustment not Properly assigned');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT__r.CDE_STATUS_DETAIL_ADJMT__c,'3','Status not changed to Satisfied');
        }
        system.assertEquals('2',[select CDE_STATUS_ADJMT__c from T_ADJMT__c where Id=:adjustmentList[0].Id Limit 1].CDE_STATUS_ADJMT__c ,'Adjustment not Satisfied');
        
        Test.StopTest();
    }
    
    static testMethod void testCreateAdjustmentPaymentDetailsonCase() {
        T_COUNTY__c countyObj =  new T_COUNTY__c (CNTY_DEPT_NAME__c = 'Arapahoe County', CDE_COUNTY__c = 3);
        insert countyObj;
        T_SBSD_CASE__c caseObj = new T_SBSD_CASE__c (CDE_COUNTY__c = countyObj.Id, IND_ASSIST_PROVR__c = 'N', CDE_ASST_HSNG__c = 'N');
        insert caseObj;
        Id recordTypeId = Schema.SObjectType.T_ADJMT__c.getRecordTypeInfosByName().get('Finalized').getRecordTypeId();
        
        List<T_ADJMT__c> adjustmentList= new List<T_ADJMT__c>();
        adjustmentList.add( new T_ADJMT__c(RecordtypeId=recordTypeId,CDE_STATUS_ADJMT__c='2',CDE_TYPE_ADJMT__c='2',CDE_TYPE_CLSFN__c='3',CDE_AGNST_ADJMT__c='1',IDN_CASE__c=caseObj.Id,DTE_END_ADJMT__c=date.newInstance(2018, 1, 10),DTE_START_ADJMT__c=date.newInstance(2018, 1, 8),DTE_DISCV_ADJMT_ORIG__c=date.newInstance(2018, 1, 8)));
        adjustmentList.add( new T_ADJMT__c(RecordtypeId=recordTypeId,CDE_STATUS_ADJMT__c='2',CDE_TYPE_ADJMT__c='2',CDE_TYPE_CLSFN__c='1',CDE_AGNST_ADJMT__c='2',IDN_CASE__c=caseObj.Id,DTE_END_ADJMT__c=date.newInstance(2018, 1, 10),DTE_START_ADJMT__c=date.newInstance(2018, 1, 8),DTE_DISCV_ADJMT_ORIG__c=date.newInstance(2018, 1, 8)));
        adjustmentList.add( new T_ADJMT__c(RecordtypeId=recordTypeId,CDE_STATUS_ADJMT__c='2',CDE_TYPE_ADJMT__c='2',CDE_TYPE_CLSFN__c='1',CDE_AGNST_ADJMT__c='2',IDN_CASE__c=caseObj.Id,DTE_END_ADJMT__c=date.newInstance(2018, 1, 10),DTE_START_ADJMT__c=date.newInstance(2018, 1, 8),DTE_DISCV_ADJMT_ORIG__c=date.newInstance(2018, 1, 8)));
        insert adjustmentList;
        
        List<T_ADJMT_DETAIL__c> adjustDetailList = new List<T_ADJMT_DETAIL__c>();
        adjustDetailList.add(new T_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=100,IDN_ADJMT__c=adjustmentList[0].Id));
        adjustDetailList.add(new T_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=200,IDN_ADJMT__c=adjustmentList[0].Id));
        adjustDetailList.add(new T_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=300,IDN_ADJMT__c=adjustmentList[0].Id));
        insert adjustDetailList;
        
        List<T_NON_ADJMT_DETAIL__c> nonAdjustDetailList = new List<T_NON_ADJMT_DETAIL__c>();
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=100,IDN_ADJMT__c=adjustmentList[1].Id));
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=200,IDN_ADJMT__c=adjustmentList[1].Id));
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=300,IDN_ADJMT__c=adjustmentList[1].Id));
        nonAdjustDetailList.add(new T_NON_ADJMT_DETAIL__c(AMT_DETAIL_ADJMT__c=10,IDN_ADJMT__c=adjustmentList[2].Id));
        insert nonAdjustDetailList;
        
        Test.startTest();
        
        T_ADJMT_PMT__c adjustmentPayment = new T_ADJMT_PMT__c( CDE_TYPE_PMT_ADJMT__c='1',AMT_PMT_ADJMT__c=600,IDN_CASE__c=caseObj.Id,DTE_PMT_ADJMT__c=System.Today());
        insert adjustmentPayment;
        
        for(T_ADJMT_PMT_DETAIL__c adjutPaymDet:[Select Id,IDN_DETAIL_ADJMT_NON__r.AMT_DETAIL_ADJMT__c,IDN_DETAIL_ADJMT_NON__r.IDN_ADJMT__c,IDN_DETAIL_ADJMT_NON__r.CDE_STATUS_DETAIL_ADJMT__c, IDN_ADJMT__c,IDN_DETAIL_ADJMT_NON__c,IDN_PMT_ADJMT__c,AMT_PMT_DETAIL_ADJMT__c from T_ADJMT_PMT_DETAIL__c where IDN_PMT_ADJMT__c=:adjustmentPayment.Id and IDN_ADJMT__c=:adjustmentList[1].Id]) {
            system.assertEquals(adjutPaymDet.AMT_PMT_DETAIL_ADJMT__c,adjutPaymDet.IDN_DETAIL_ADJMT_NON__r.AMT_DETAIL_ADJMT__c,'Amount mismatch');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT_NON__r.IDN_ADJMT__c,adjutPaymDet.IDN_ADJMT__c,'Adjustment not Properly assigned');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT_NON__r.CDE_STATUS_DETAIL_ADJMT__c,'3','Status not changed to Satisfied');
        }
        system.assertEquals('2',[select CDE_STATUS_ADJMT__c from T_ADJMT__c where Id=:adjustmentList[1].Id Limit 1].CDE_STATUS_ADJMT__c ,'Adjustment not Satisfied');
        
        T_ADJMT_PMT__c adjustmentPayment2 = new T_ADJMT_PMT__c( CDE_TYPE_PMT_ADJMT__c='1',AMT_PMT_ADJMT__c=650,IDN_CASE__c=caseObj.Id,DTE_PMT_ADJMT__c=System.Today());
        insert adjustmentPayment2;
        
        for(T_ADJMT_PMT_DETAIL__c adjutPaymDet:[Select Id,IDN_DETAIL_ADJMT__r.AMT_DETAIL_ADJMT__c,IDN_DETAIL_ADJMT__r.IDN_ADJMT__c,IDN_DETAIL_ADJMT__r.CDE_STATUS_DETAIL_ADJMT__c, IDN_ADJMT__c,IDN_DETAIL_ADJMT__c,IDN_PMT_ADJMT__c,AMT_PMT_DETAIL_ADJMT__c from T_ADJMT_PMT_DETAIL__c where IDN_PMT_ADJMT__c=:adjustmentPayment.Id and IDN_ADJMT__c=:adjustmentList[0].Id]) {
            system.assertEquals(adjutPaymDet.AMT_PMT_DETAIL_ADJMT__c,adjutPaymDet.IDN_DETAIL_ADJMT__r.AMT_DETAIL_ADJMT__c,'Amount mismatch');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT__r.IDN_ADJMT__c,adjutPaymDet.IDN_ADJMT__c,'Adjustment not Properly assigned');
            system.assertEquals(adjutPaymDet.IDN_DETAIL_ADJMT__r.CDE_STATUS_DETAIL_ADJMT__c,'3','Status not changed to Satisfied');
        }
        system.assertEquals('2',[select CDE_STATUS_ADJMT__c from T_ADJMT__c where Id=:adjustmentList[0].Id Limit 1].CDE_STATUS_ADJMT__c ,'Adjustment not Satisfied');
        // system.assertEquals(40,[Select AMT_PMT_SRPLUS_ADJMT__c from T_ADJMT_PMT__c where Id=:adjustmentPayment2.Id].AMT_PMT_SRPLUS_ADJMT__c, 'Surplus amount is not adjusted');
        Test.StopTest();
    }
}