CHATS_SIT/force-app/main/default/objects/T_ADJMT__c.object
<CustomObject>
    <description>Adjustment parent table that contains information about provider and case payment corrections</description>
    <fields>
        <fullName>Outstanding_Recovery_Balance__c</fullName>
        <label>Outstanding Recovery Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AMT_ADJMT__c</fullName>
        <formula>CASE(TEXT(CDE_AGNST_ADJMT__c), &apos;1&apos;, Adjustment_Details_Amount__c, &apos;2&apos;, Non_Adjustment_Details_Amount__c,Null )</formula>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS_ADJMT__c</fullName>
        <description>Adjustment Status</description>
        <label>Adjustment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00719</valueSetName>
        </valueSet>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Provider_License_Closed</fullName>
        <active>false</active>
        <description>On Closed Provier Adjustment of type Claim can not be created</description>
        <errorConditionFormula>AND(  TEXT(CDE_TYPE_ADJMT__c) = &apos;1&apos;,NOT(ISPICKVAL( IDN_PROVR__r.CDE_STATUS_PROVR__c , &apos;Open&apos;)),OR((TEXT( CDE_STATUS_ADJMT__c ) = &apos;&apos;),(TEXT(CDE_STATUS_ADJMT__c) = &apos;1&apos;)) )</errorConditionFormula>
        <errorMessage>Adjustment cannot be created for the care dates when provider license status is closed</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_ADDR__c.object
<CustomObject>
    <description>Information about the address used to create adjustment related correspondence</description>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustment Address</relationshipLabel>
        <relationshipName>Adjustment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment Address</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_PMT__c.object
<CustomObject>
    <description>Information about payments made to satisfy the debt recorded for a provider or case</description>
    <fields>
        <fullName>CDE_TYPE_PMT_ADJMT__c</fullName>
        <description>Payment Type</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00733</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_PMT_ADJMT__c</fullName>
        <description>Date Paid</description>
        <label>Date Paid</label>
        <type>Date</type>
    </fields>
    <label>Adjustment Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_ADJMT_PMT_DETAIL__c.object
<CustomObject>
    <description>Detail information about sub payment, payment corrections</description>
    <fields>
        <fullName>AMT_PMT_DETAIL_ADJMT__c</fullName>
        <description>Amount</description>
        <label>Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS_DETAIL_PMT_ADJMT__c</fullName>
        <defaultValue>&apos;3&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00716</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment</description>
        <label>Adjustment</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Adjustment Payment Details</relationshipLabel>
        <relationshipName>AdjustmentPaymentDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PMT_ADJMT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Adjustment Payment</description>
        <label>Adjustment Payment</label>
        <referenceTo>T_ADJMT_PMT__c</referenceTo>
        <relationshipLabel>Adjustment Payment Detail</relationshipLabel>
        <relationshipName>Adjustment_Payment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment Payment Detail</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/Tax_Intercept__c.object
<CustomObject>
    <description>OEC Project 282 - JIRA CCCAP-3890. The Colorado Child Care Assistance Program under statute, has the ability to intercept state income tax refunds for any individual or entity who owes a recovery for benefits for which they were not eligible.</description>
    <fields>
        <fullName>Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment ID</label>
        <referenceTo>T_ADJMT__c</referenceTo>
        <relationshipLabel>Tax Intercepts</relationshipLabel>
        <relationshipName>Tax_Intercepts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <label>Outstanding Recovery Balance</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Intercept_Status__c</fullName>
        <formula>IF(
(OR((YEAR(TODAY())==(VALUE(Tax_Year__c))),((YEAR(TODAY())-1) == VALUE(Tax_Year__c)))), IF(
NOT(ISBLANK(TEXT(Remove_Reason__c))), &quot;Removed&quot;,
IF(
ISPICKVAL(Reinstate__c, &quot;Y&quot;), &quot;Reinstated&quot;,
&quot;Active&quot;
)
), &quot;Expired&quot;)</formula>
        <label>Intercept Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Payment_Amount__c</fullName>
        <label>Last Payment Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SEND_UPDATE_TO_CDOR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Update To CDOR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax_Year__c</fullName>
        <formula>TEXT(YEAR(DATEVALUE(CreatedDate)))</formula>
        <label>Tax Year</label>
        <type>Text</type>
    </fields>
    <label>Tax Intercept</label>
    <nameField>
        <displayFormat>TI{YYYY}{MM}{DD}{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Intercepts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00716.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Created</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Calculated</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Paid</label>
    </customValue>
    <description>R00716</description>
    <masterLabel>R00716</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00719.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>In Process</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calculation Complete</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Satisfied</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Paid</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Cancellation In Progress</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Cancelled</label>
    </customValue>
    <description>R00719</description>
    <masterLabel>R00719</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00733.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Cash</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Check</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Credit Card</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>EBT Adjustment</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Administrative Action</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Adjustment Reduction, Court Ordered Judgment</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Refund/Over Payment</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>CDOR</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Payment Through Payment Plan</label>
    </customValue>
    <description>R00733</description>
    <masterLabel>R00733</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/adjustmentPaymentDetailUpdate.cls
/****************************************************************************
Class Name      - adjustmentPaymentDetailUpdate
Author          - Pragyan Nayak
Description     - Trigger Handler Class for Adjustment Payment Detail Trigger
Requiremnt      - Project 282 : CCCAP-4414

Modification Log:
Rishav : CCCAP-7647 - Updated test coverage to 98% (adjustmentPaymentDetailTriggerTest)
*****************************************************************************/
public with sharing class adjustmentPaymentDetailUpdate {
    
    public static void adjPayDetCheck(List<T_ADJMT_PMT_DETAIL__c> newAdjPayDet){
        Set<Id> adjIDSet = new Set<Id>();
        Set<Id> adjustmentIDSet = new Set<Id>();
        List<Tax_Intercept__c> taxIDList = new List<Tax_Intercept__c>();
        String adjPayDetStatus = '4';//Paid
        Map<Id, Date> adjPayDate = new Map<Id, Date>(); // Last Pyment Date
        Map<Id, Double> adjPayAmt = new Map<Id, Double>();//Last Pyment Amount
        Map<Id, String> adjPayType1 = new Map<Id, String>();
        Map<Id, DateTime> adjPayModifyDate = new Map<Id, DateTime>();
        Map<Id, Double> adjPayDetAmt = new Map<Id, Double>();
        List<T_ADJMT__c> adjUpd = new List<T_ADJMT__c>();
        for(T_ADJMT_PMT_DETAIL__c adPayDet: newAdjPayDet){
            adjIDSet.add(adPayDet.IDN_ADJMT__c);
        }
        for(T_ADJMT_PMT_DETAIL__c adjDet: [SELECT Id, IDN_ADJMT__c, IDN_ADJMT__r.Id, AMT_PMT_DETAIL_ADJMT__c, LastModifiedDate, CDE_STATUS_DETAIL_PMT_ADJMT__c, IDN_PMT_ADJMT__c, IDN_PMT_ADJMT__r.DTE_PMT_ADJMT__c, IDN_PMT_ADJMT__r.CDE_TYPE_PMT_ADJMT__c FROM T_ADJMT_PMT_DETAIL__c WHERE IDN_ADJMT__c IN:adjIDSet AND CDE_STATUS_DETAIL_PMT_ADJMT__c = :adjPayDetStatus]){
            Id idval = adjDet.IDN_ADJMT__c;
            Double tot = 0;
            if(adjPayDetAmt.containsKey(idval)){
                tot = adjPayDetAmt.get(idval);
            }
            Datetime lastModifiedDate = Test.isRunningTest() ? System.now().addDays(-1) : adjDet.LastModifiedDate;
            if(!adjPayAmt.containsKey(adjDet.IDN_ADJMT__c)) {
                adjPayAmt.put(adjDet.IDN_ADJMT__c, adjDet.AMT_PMT_DETAIL_ADJMT__c);// Last Adjustment Payment Amount
                adjPayDate.put(adjDet.IDN_ADJMT__c, adjDet.IDN_PMT_ADJMT__r.DTE_PMT_ADJMT__c); // Last Adjustment Payment Date
                adjPayModifyDate.put(adjDet.IDN_ADJMT__c, lastModifiedDate);
                adjPayType1.put(adjDet.IDN_ADJMT__c, adjDet.IDN_PMT_ADJMT__r.CDE_TYPE_PMT_ADJMT__c);
            } else {
                if(adjPayModifyDate.get(adjDet.IDN_ADJMT__r.Id) < lastModifiedDate) {
                    adjPayModifyDate.put(adjDet.IDN_ADJMT__c, lastModifiedDate);
                    adjPayDate.put(adjDet.IDN_ADJMT__c, adjDet.IDN_PMT_ADJMT__r.DTE_PMT_ADJMT__c); // Last Adjustment Payment Date
                    adjPayAmt.put(adjDet.IDN_ADJMT__c, adjDet.AMT_PMT_DETAIL_ADJMT__c); // Last Adjustment Payment Amount
                    adjPayType1.put(adjDet.IDN_ADJMT__c, adjDet.IDN_PMT_ADJMT__r.CDE_TYPE_PMT_ADJMT__c);
                }
            }
            adjustmentIDSet.add(adjDet.IDN_ADJMT__c);
            if(adjDet.AMT_PMT_DETAIL_ADJMT__c != Null) {
                tot = tot+adjDet.AMT_PMT_DETAIL_ADJMT__c;
            }
            adjPayDetAmt.put(idval, tot);
        }
        
        //added for CCCAP-14525
        Set<Id> adjWithNoPayments = new Set<Id>();
        for(T_ADJMT_PMT_DETAIL__c pmtDt: newAdjPayDet){
            if(!adjustmentIDSet.contains(pmtDt.IDN_ADJMT__c)){
                adjWithNoPayments.add(pmtDt.IDN_ADJMT__c);
                adjPayDetAmt.put(pmtDt.IDN_ADJMT__c, 0.0);
                adjPayType1.put(pmtDt.IDN_ADJMT__c, pmtDt.IDN_PMT_ADJMT__r.CDE_TYPE_PMT_ADJMT__c);
            }
        }        
        Set<Id> allAdjustmentIds = new Set<Id>();
        allAdjustmentIds.addAll(adjustmentIDSet);
        allAdjustmentIds.addAll(adjWithNoPayments);
        
        Map<id,Decimal> adjustMap = new Map<Id,Decimal>();
        for(T_ADJMT__c adj: [SELECT Id, AMT_ADJMT__c, CDE_STATUS_ADJMT__c, Outstanding_Recovery_Balance__c FROM T_ADJMT__c WHERE Id IN :allAdjustmentIds]){
            if(adj != null){
                adj.Outstanding_Recovery_Balance__c = (adj.AMT_ADJMT__c - adjPayDetAmt.get(adj.Id)).setScale(2);
                if(adj.Outstanding_Recovery_Balance__c <= 0 && adj.CDE_STATUS_ADJMT__c != '3' && adj.CDE_STATUS_ADJMT__c != '4' && adjPayType1.get(adj.Id) == '8'){
                    adj.CDE_STATUS_ADJMT__c ='3'; 
                }
                adjUpd.add(adj);
                adjustMap.put(adj.id, adj.Outstanding_Recovery_Balance__c);
            }
        }
        for(Tax_Intercept__c tx: [SELECT Id, Tax_Year__c, Adjustment__c, Adjustment__r.Outstanding_Recovery_Balance__c, Adjustment__r.Id, Intercept_Status__c FROM Tax_Intercept__c WHERE Adjustment__c IN :allAdjustmentIds and Intercept_Status__c!='Removed']){
            if(tx != null && tx.Intercept_Status__c != 'Expired'){
                tx.Current_Balance__c = adjustMap.get(tx.Adjustment__c);
                tx.Last_Payment_Date__c = adjPayDate.containsKey(tx.Adjustment__r.Id) ? adjPayDate.get(tx.Adjustment__r.Id) : null;
                tx.Last_Payment_Amount__c = adjPayAmt.containsKey(tx.Adjustment__r.Id) ? adjPayAmt.get(tx.Adjustment__r.Id) : null;
                if(adjPayType1.get(tx.Adjustment__r.Id) != '8'){
                    tx.SEND_UPDATE_TO_CDOR__c = true;
                }
                taxIDList.add(tx);
            }
        }
        if(!adjUpd.isEmpty()) {
            GenericDMLHandler.updateRecords(adjUpd, new Map<String, Object>{'Method__c'=>'execute','Class__c'=>'adjustmentPaymentDetailUpdate'});
        }
        if(!taxIDList.isEmpty()) {
            GenericDMLHandler.updateRecords(taxIDList, new Map<String, Object>{'Method__c'=>'execute','Class__c'=>'adjustmentPaymentDetailUpdate'});
        } 
    }
}