CHATS_SIT/force-app/main/default/objects/T_APPLN_PRCS_QUEUE__c.object
<CustomObject>
    <description>Track PEAK application processing</description>
    <fields>
        <fullName>DTE_RCVD_APPLN__c</fullName>
        <description>Application Received Date</description>
        <label>Application Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_APPLN_COMPASS__c</fullName>
        <label>IDN_APPLN_COMPASS</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application Process Queue</label>
    <nameField>
        <displayFormat>APRCS_QUEUE-{0}</displayFormat>
        <label>Application Process Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Process Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/applicationPrcsQueueTriggerTest.cls
@isTest
public class applicationPrcsQueueTriggerTest {
    static testmethod void testApplicationPrcsQueueTrigger(){
    	test.startTest();
        T_APPLN_PRCS_QUEUE__c applnPrcsQueueRec = new T_APPLN_PRCS_QUEUE__c(IDN_APPLN_COMPASS__c = 12345, DTE_RCVD_APPLN__c = system.today());
        insert applnPrcsQueueRec;
        system.assertEquals(1,[select Id from T_APPLN_PRCS_QUEUE__c limit 10].size(),'Query should return Application Process queue record');
        test.stopTest();
    }
}