CHATS_SIT/force-app/main/default/objects/T_APPLN_CASE__c.object
<CustomObject>
    <description>PEAK application Case information, main data table others reference.</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>IDN_APPLN__c</fullName>
        <label>IDN_APPLN</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDN_CBMS_REF__c</fullName>
        <label>Referral ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NBR_APPLN_SEC__c</fullName>
        <description>NBR_APPLN_SEC</description>
        <label>NBR_APPLN_SEC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Application Case</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Application Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_APPLN_PRCS_QUEUE__c.object
<CustomObject>
    <description>Track PEAK application processing</description>
    <fields>
        <fullName>IDN_APPLN__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Application Number</description>
        <label>Application Number</label>
        <referenceTo>T_APPLN_CASE__c</referenceTo>
        <relationshipLabel>Application Process Queue</relationshipLabel>
        <relationshipName>Application_case_26</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Process Queue</label>
    <nameField>
        <displayFormat>APRCS_QUEUE-{0}</displayFormat>
        <label>Application Process Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Process Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/viewReferralApplnPdfTest.cls
@isTest
private class viewReferralApplnPdfTest {
    
    static testmethod void testGetPdf() {
        T_APPLN_CASE__c applnCase = new T_APPLN_CASE__c(IDN_APPLN__c=123456543, NBR_APPLN_SEC__c='ApplnNumber', IDN_CBMS_REF__c='12345');
        insert applnCase;
        T_APPLN_PRCS_QUEUE__c applnPrcsQueue = new T_APPLN_PRCS_QUEUE__c(IDN_APPLN__c = applnCase.Id);
        insert applnPrcsQueue;
        
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new viewPeakApplnPdfMockTest());
        LightningServerResponse rtrn = viewReferralApplnPdfController.getReferralPdf(applnPrcsQueue.Id);
        system.assertEquals(true,rtrn.isSuccessful,'isSuccessful is set to true');
        
        Test.setMock(HttpCalloutMock.class, new corspdPrintQueueMockFailureTest());
        LightningServerResponse rtrn1 = viewReferralApplnPdfController.getReferralPdf(applnPrcsQueue.Id);
        string applnId = viewReferralApplnPdfController.fetchPdfFileFromS3(applnPrcsQueue.Id);
        viewReferralApplnPdfController constructorTest = new viewReferralApplnPdfController() ;
		test.stopTest();
    }
}