CHATS_SIT/force-app/main/default/objects/T_APPLN_CASE__c.object
<CustomObject>
    <description>PEAK application Case information, main data table others reference.</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>CDE_COUNTY</description>
        <label>CDE_COUNTY</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTE_RCVD_APPLN__c</fullName>
        <description>DTE_RCVD_APPLN</description>
        <label>DTE_RCVD_APPLN</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_APPLN__c</fullName>
        <label>IDN_APPLN</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application Case</label>
    <nameField>
        <displayFormat>AC-{0}</displayFormat>
        <label>Application Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_APPLN_INDIV__c.object
<CustomObject>
    <description>PEAK application individual(s)</description>
  <!--  <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>IDN_APPLN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IDN_APPLN</description>
        <label>IDN_APPLN</label>
        <referenceTo>T_APPLN_CASE__c</referenceTo>
        <relationshipLabel>Application Individual</relationshipLabel>
        <relationshipName>Application_case_16</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_CRTKR_PRIM__c</fullName>
        <label>Primary Caretaker</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_FIRST__c</fullName>
        <description>First Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_LAST__c</fullName>
        <description>Last Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NBR_SSN__c</fullName>
        <description>SSN</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SSN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Application Individual</label>
    <nameField>
        <displayFormat>AINDIV-{0}</displayFormat>
        <label>Application Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Individuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_APPLN_PRCS_QUEUE__c.object
<CustomObject>
    <description>Track PEAK application processing</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County</description>
        <label>County</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CDE_REJECT_APPLN__c</fullName>
        <label>Reason for Application Rejection</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00823</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_SOURCE__c</fullName>
        <description>Application Source</description>
        <label>Application Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00834</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS_APPLN__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00553</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_RCVD_APPLN__c</fullName>
        <description>Application Received Date</description>
        <label>Application Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_APPLN__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Application Number</description>
        <label>Application Number</label>
        <referenceTo>T_APPLN_CASE__c</referenceTo>
        <relationshipLabel>Application Process Queue</relationshipLabel>
        <relationshipName>Application_case_26</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Application Process Queues</relationshipLabel>
        <relationshipName>Application_Process_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County Name</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Application Process Queues</relationshipLabel>
        <relationshipName>Application_Process_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Process Queue</label>
    <nameField>
        <displayFormat>APRCS_QUEUE-{0}</displayFormat>
        <label>Application Process Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Process Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00553.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NEW</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>REJ</fullName>
        <label>Rejected</label>
    </customValue>
    <customValue>
        <fullName>PRC</fullName>
        <label>Processed</label>
    </customValue>
    <customValue>
        <fullName>INC</fullName>
        <label>Incorrect Information</label>
    </customValue>
    <masterLabel>R00553</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00823.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3</fullName>
        <label>Processed as Paper Application</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Duplicate Application</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Unable to contact Adult Caretaker</label>
    </customValue>
    <customValue>
        <fullName>kjc</fullName>
        <isActive>false</isActive>
        <label>kjc</label>
    </customValue>
    <customValue>
        <fullName>no</fullName>
        <isActive>false</isActive>
        <label>no</label>
    </customValue>
    <masterLabel>R00823</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00834.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CB</fullName>
        <label>CBMS</label>
    </customValue>
    <customValue>
        <fullName>PK</fullName>
        <default>true</default>
        <label>PEAK</label>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
        <label>Paper</label>
    </customValue>
    <description>R00834</description>
    <masterLabel>R00834</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/PeakInboxScreenCtrlTest.cls
@isTest
public class PeakInboxScreenCtrlTest {
    
    public static testMethod void testgetInitPeakRequestData(){
        LightningServerResponse lsr = PeakInboxScreenCtrl.getInitPeakRequestData(); 
    }
    
    public static testMethod void testSearchIndividualsForSimpleSearchIndividual(){
        List<T_APPLN_CASE__c> cases = [SELECT Id, IDN_APPLN__c FROM T_APPLN_CASE__c];
        System.assertEquals(false, cases.isEmpty(),'cases should not be empty');
        List<T_APPLN_INDIV__c> appIndiv = [SELECT Id, IDN_APPLN__c, NBR_SSN__c, NAM_FIRST__c, NAM_LAST__c FROM T_APPLN_INDIV__c Where IDN_APPLN__c=:cases.get(0).Id];
        System.assertEquals(false, appIndiv.isEmpty(),'appIndiv should not be empty');
        List<T_APPLN_PRCS_QUEUE__c> appQueues = [SELECT Id, Name, IDN_CASE__r.Name, CDE_SOURCE__c,IDN_APPLN__c, CDE_REJECT_APPLN__c,CDE_STATUS_APPLN__c,CDE_COUNTY__c,DTE_RCVD_APPLN__c, County_Name__r.Name  FROM T_APPLN_PRCS_QUEUE__c Where IDN_APPLN__c=:cases.get(0).Id];
        System.assertEquals(false, appQueues.isEmpty(),'appQueues should not be empty');
        Date fromDate = system.today() -1;
        Date toDate = system.today() +10;
        String applId = appQueues.get(0).Id;
        PeakInboxWrapper peakInboxWrapper = new PeakInboxWrapper(appQueues.get(0).CDE_COUNTY__c, appQueues.get(0).CDE_STATUS_APPLN__c,appIndiv.get(0).NBR_SSN__c, string.valueOf(cases.get(0).IDN_APPLN__c), 'StringSearch',appIndiv.get(0).NAM_FIRST__c,appIndiv.get(0).NAM_LAST__c,fromDate,toDate);
        PeakInboxWrapper peakInboxWrapper1 = new PeakInboxWrapper(appQueues.get(0).CDE_COUNTY__c, appQueues.get(0).CDE_STATUS_APPLN__c,appIndiv.get(0).NBR_SSN__c, string.valueOf(cases.get(0).IDN_APPLN__c), 'SoundexSearch',appIndiv.get(0).NAM_FIRST__c,appIndiv.get(0).NAM_LAST__c,fromDate,toDate);
        PeakInboxWrapper peakInboxWrapperLstNameNull = new PeakInboxWrapper(appQueues.get(0).CDE_COUNTY__c, appQueues.get(0).CDE_STATUS_APPLN__c,appIndiv.get(0).NBR_SSN__c, string.valueOf(cases.get(0).IDN_APPLN__c), 'SoundexSearch',appIndiv.get(0).NAM_FIRST__c,null,fromDate,toDate);
        PeakInboxWrapper peakInboxWrapper1FstnameNull = new PeakInboxWrapper(appQueues.get(0).CDE_COUNTY__c, appQueues.get(0).CDE_STATUS_APPLN__c,appIndiv.get(0).NBR_SSN__c, string.valueOf(cases.get(0).IDN_APPLN__c), 'SoundexSearch',null,appIndiv.get(0).NAM_LAST__c,fromDate,toDate);
        List<PeakResultWrapper> appCasesLst = (List<PeakResultWrapper>)PeakInboxScreenCtrl.processViewResults(JSON.serialize(peakInboxWrapper)).objectData.get('test');
        List<PeakResultWrapper> appCasesLst1 = (List<PeakResultWrapper>)PeakInboxScreenCtrl.processViewResults(JSON.serialize(peakInboxWrapper1)).objectData.get('test');
        List<PeakResultWrapper> appCasesLst2 = (List<PeakResultWrapper>)PeakInboxScreenCtrl.processViewResults(JSON.serialize(peakInboxWrapperLstNameNull)).objectData.get('test');
        List<PeakResultWrapper> appCasesLst3 = (List<PeakResultWrapper>)PeakInboxScreenCtrl.processViewResults(JSON.serialize(peakInboxWrapper1FstnameNull)).objectData.get('test');
    }
    
    @testSetup
    public static void doSetUp(){
        T_COUNTY__c countyRec = TestClassUtility.createCounty('Adams','Adams',1,true);
        T_SBSD_CASE__c caseRec = TestClassUtility.createCase(true, countyRec.Id);
        Date appDate = system.today();
        
        T_APPLN_CASE__c appCaseRec1 = new T_APPLN_CASE__c();
        appCaseRec1.IDN_APPLN__c = 55;
        appCaseRec1.DTE_RCVD_APPLN__c = appDate;
        insert appCaseRec1;
        
        T_APPLN_PRCS_QUEUE__c appQueueRec1 = new T_APPLN_PRCS_QUEUE__c();
        appQueueRec1.CDE_STATUS_APPLN__c = 'PRC';
        appQueueRec1.CDE_COUNTY__c = '1';
        appQueueRec1.CDE_SOURCE__c = 'PK';
        appQueueRec1.IDN_APPLN__c = appCaseRec1.Id;
        appQueueRec1.IDN_CASE__c = caseRec.Id;
        appQueueRec1.CDE_REJECT_APPLN__c = '';
        insert appQueueRec1;
        LightningServerResponse lsr = PeakInboxScreenCtrl.validateCounty(appQueueRec1.Id);
        T_APPLN_INDIV__c appIndivRec1 = new T_APPLN_INDIV__c();
        appIndivRec1.IDN_APPLN__c = appCaseRec1.Id;
        appIndivRec1.NBR_SSN__c = '12345';
        appIndivRec1.NAM_FIRST__c = 'Test1';
        appIndivRec1.NAM_LAST__c = 'Name1';
        appIndivRec1.IND_CRTKR_PRIM__c = 'Y';
        insert appIndivRec1;
        
    }
}