CHATS_SIT/force-app/main/default/objects/T_APPLN_PRCS_QUEUE__c.object
<CustomObject>
    <description>Track PEAK application processing</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County</description>
        <label>County</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CDE_SOURCE__c</fullName>
        <description>Application Source</description>
        <label>Application Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00834</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS_APPLN__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00553</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_RCVD_APPLN__c</fullName>
        <description>Application Received Date</description>
        <label>Application Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>County_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County Name</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Application Process Queues</relationshipLabel>
        <relationshipName>Application_Process_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Process Queue</label>
    <nameField>
        <displayFormat>APRCS_QUEUE-{0}</displayFormat>
        <label>Application Process Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Process Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Owner_County__c</fullName>
        <label>Owner County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00005</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00553.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NEW</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>REJ</fullName>
        <label>Rejected</label>
    </customValue>
    <customValue>
        <fullName>PRC</fullName>
        <label>Processed</label>
    </customValue>
    <customValue>
        <fullName>INC</fullName>
        <label>Incorrect Information</label>
    </customValue>
    <masterLabel>R00553</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00834.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CB</fullName>
        <label>CBMS</label>
    </customValue>
    <customValue>
        <fullName>PK</fullName>
        <default>true</default>
        <label>PEAK</label>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
        <label>Paper</label>
    </customValue>
    <description>R00834</description>
    <masterLabel>R00834</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/T108_AppQueueCheckBatch_Test.cls
@isTest 
public class T108_AppQueueCheckBatch_Test {
    static testMethod void testMethod1(){
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Profile p = [SELECT Id FROM Profile WHERE Name='Eligibility Worker Supervisor'];
        User user1 = new User(Alias = 'standt', Email='standarduser12@testorg.com',
                              EmailEncodingKey='UTF-8', LastName='Testing', FirstName='Testing', LanguageLocaleKey='en_US',
                              LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', 
                              UserName=dateString+'standard1@testorg.com', IsActive = true, Owner_County__c = '1');
        insert user1;
        
        User user2 = new User();
        user2 = [Select Id, Name from User Where Id =: user1.ID];
        
        T_COUNTY__c aCounty=TestClassUtility.createCounty('Test County', 'Test County Department', 11, false);
        aCounty.OwnerId = user2.Id;
        aCounty.CDE_COUNTY__c = 1;
        insert aCounty;
        
        T_APPLN_PRCS_QUEUE__c appQueueRec = new T_APPLN_PRCS_QUEUE__c();
        appQueueRec.CDE_SOURCE__c = 'PK';
        appQueueRec.CDE_STATUS_APPLN__c ='PEN';
        appQueueRec.DTE_RCVD_APPLN__c = System.today();
        appQueueRec.County_Name__c = aCounty.Id;
        appQueueRec.CDE_COUNTY__c = '1';
        insert appQueueRec; 
        
        appQueueRec.DTE_RCVD_APPLN__c = System.today() - 10;
        update appQueueRec;
        
        Task taskRcrd = new Task();
        taskRcrd.Subject = 'T108 - Peak Application received 10 days ago is due for processing';
        taskRcrd.Status = 'Not Started';
        taskRcrd.Priority = 'Normal';
        taskRcrd.WhatId = appQueueRec.Id;
        taskRcrd.ActivityDate = system.today().addDays(+5);
        taskRcrd.OwnerId = aCounty.OwnerId;
        insert taskRcrd;
        
        Test.startTest();
        T108_AppQueueCheckBatch batch = new T108_AppQueueCheckBatch();
        database.executeBatch(batch,10);
        Test.stopTest(); 
    }
    
    static testMethod void testMethod2(){
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Profile p = [SELECT Id FROM Profile WHERE Name='Universal User'];
        User user1 = new User(Alias = 'standt', Email='standarduser12@testorg.com',
                              EmailEncodingKey='UTF-8', LastName='Testing', FirstName='Testing', LanguageLocaleKey='en_US',
                              LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', 
                              UserName=dateString+'standard2@testorg.com', IsActive = true, Owner_County__c = '1');
        insert user1;
        
        User user2 = new User();
        user2 = [Select Id, Name from User Where Id =: user1.ID];
        
        T_COUNTY__c aCounty=TestClassUtility.createCounty('Test County', 'Test County Department', 11, false);
        aCounty.OwnerId = user2.Id;
        aCounty.CDE_COUNTY__c = 1;
        insert aCounty;
        
        T_APPLN_PRCS_QUEUE__c appQueueRec = new T_APPLN_PRCS_QUEUE__c();
        appQueueRec.CDE_SOURCE__c = 'PK';
        appQueueRec.CDE_STATUS_APPLN__c ='PEN';
        appQueueRec.DTE_RCVD_APPLN__c = System.today();
        appQueueRec.County_Name__c = aCounty.Id;
        appQueueRec.CDE_COUNTY__c = '1';
        insert appQueueRec; 
        
        appQueueRec.DTE_RCVD_APPLN__c = System.today() - 10;
        update appQueueRec;
        
        Task taskRcrd = new Task();
        taskRcrd.Subject = 'T108 - Peak Application received 10 days ago is due for processing';
        taskRcrd.Status = 'Not Started';
        taskRcrd.Priority = 'Normal';
        taskRcrd.WhatId = appQueueRec.Id;
        taskRcrd.ActivityDate = system.today().addDays(+5);
        taskRcrd.OwnerId = aCounty.OwnerId;
        insert taskRcrd;
        
        Test.startTest();
        T108_AppQueueCheckBatch batch = new T108_AppQueueCheckBatch();
        database.executeBatch(batch,10);
        Test.stopTest();
    }
    
    static testMethod void testMethod3(){
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Profile p = [SELECT Id FROM Profile WHERE Name='Provider Worker Supervisor'];
        User user1 = new User(Alias = 'standt', Email='standarduser12@testorg.com',
                              EmailEncodingKey='UTF-8', LastName='Testing', FirstName='Testing', LanguageLocaleKey='en_US',
                              LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', 
                              UserName=dateString+'standard3@testorg.com', IsActive = true, Owner_County__c = '1');
        insert user1;
        
        User user2 = new User();
        user2 = [Select Id, Name from User Where Id =: user1.ID];
        
        T_COUNTY__c aCounty=TestClassUtility.createCounty('Test County', 'Test County Department', 11, false);
        aCounty.OwnerId = user2.Id;
        aCounty.CDE_COUNTY__c = 1;
        insert aCounty;
        
        T_APPLN_PRCS_QUEUE__c appQueueRec = new T_APPLN_PRCS_QUEUE__c();
        appQueueRec.CDE_SOURCE__c = 'PK';
        appQueueRec.CDE_STATUS_APPLN__c ='PEN';
        appQueueRec.DTE_RCVD_APPLN__c = System.today();
        appQueueRec.County_Name__c = aCounty.Id;
        appQueueRec.CDE_COUNTY__c = '1';
        insert appQueueRec; 
        
        appQueueRec.DTE_RCVD_APPLN__c = System.today() - 10;
        update appQueueRec;
        
        Task taskRcrd = new Task();
        taskRcrd.Subject = 'T108 - Peak Application received 10 days ago is due for processing';
        taskRcrd.Status = 'Not Started';
        taskRcrd.Priority = 'Normal';
        taskRcrd.WhatId = appQueueRec.Id;
        taskRcrd.ActivityDate = system.today().addDays(+5);
        taskRcrd.OwnerId = aCounty.OwnerId;
        insert taskRcrd;
        
        Test.startTest();
        T108_AppQueueCheckBatch batch = new T108_AppQueueCheckBatch();
        database.executeBatch(batch,10);
        Test.stopTest();
    }
    
    static testMethod void testMethod4(){
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Profile p = [SELECT Id FROM Profile WHERE Name='Fiscal Worker Supervisor'];
        User user1 = new User(Alias = 'standt', Email='standarduser12@testorg.com',
                              EmailEncodingKey='UTF-8', LastName='Testing', FirstName='Testing', LanguageLocaleKey='en_US',
                              LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', 
                              UserName=dateString+'standard4@testorg.com', IsActive = true, Owner_County__c = '1');
        insert user1;
        
        User user2 = new User();
        user2 = [Select Id, Name from User Where Id =: user1.ID];
        
        T_COUNTY__c aCounty=TestClassUtility.createCounty('Test County', 'Test County Department', 11, false);
        aCounty.OwnerId = user2.Id;
        aCounty.CDE_COUNTY__c = 1;
        insert aCounty;
        
        T_APPLN_PRCS_QUEUE__c appQueueRec = new T_APPLN_PRCS_QUEUE__c();
        appQueueRec.CDE_SOURCE__c = 'PK';
        appQueueRec.CDE_STATUS_APPLN__c ='PEN';
        appQueueRec.DTE_RCVD_APPLN__c = System.today();
        appQueueRec.County_Name__c = aCounty.Id;
        appQueueRec.CDE_COUNTY__c = '1';
        insert appQueueRec; 
        
        appQueueRec.DTE_RCVD_APPLN__c = System.today() - 10;
        update appQueueRec;
        
        Task taskRcrd = new Task();
        taskRcrd.Subject = 'T108 - Peak Application received 10 days ago is due for processing';
        taskRcrd.Status = 'Not Started';
        taskRcrd.Priority = 'Normal';
        taskRcrd.WhatId = appQueueRec.Id;
        taskRcrd.ActivityDate = system.today().addDays(+5);
        taskRcrd.OwnerId = aCounty.OwnerId;
        insert taskRcrd;
        
        Test.startTest();
        T108_AppQueueCheckBatch batch = new T108_AppQueueCheckBatch();
        database.executeBatch(batch,10);
        Test.stopTest();
    }
    
    static testMethod void testMethod5(){
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Profile p = [SELECT Id FROM Profile WHERE Name='Business Office Worker'];
        User user1 = new User(Alias = 'standt', Email='standarduser12@testorg.com',
                              EmailEncodingKey='UTF-8', LastName='Testing', FirstName='Testing', LanguageLocaleKey='en_US',
                              LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', 
                              UserName=dateString+'standard5@testorg.com', IsActive = true, Owner_County__c = '1');
        insert user1;
        
        User user2 = new User();
        user2 = [Select Id, Name from User Where Id =: user1.ID];
        
        T_COUNTY__c aCounty=TestClassUtility.createCounty('Test County', 'Test County Department', 11, false);
        aCounty.OwnerId = user2.Id;
        aCounty.CDE_COUNTY__c = 1;
        insert aCounty;
        
        T_APPLN_PRCS_QUEUE__c appQueueRec = new T_APPLN_PRCS_QUEUE__c();
        appQueueRec.CDE_SOURCE__c = 'PK';
        appQueueRec.CDE_STATUS_APPLN__c ='PEN';
        appQueueRec.DTE_RCVD_APPLN__c = System.today();
        appQueueRec.County_Name__c = aCounty.Id;
        appQueueRec.CDE_COUNTY__c = '1';
        insert appQueueRec; 
        
        appQueueRec.DTE_RCVD_APPLN__c = System.today() - 10;
        update appQueueRec;
        
        Task taskRcrd = new Task();
        taskRcrd.Subject = 'T108 - Peak Application received 10 days ago is due for processing';
        taskRcrd.Status = 'Not Started';
        taskRcrd.Priority = 'Normal';
        taskRcrd.WhatId = appQueueRec.Id;
        taskRcrd.ActivityDate = system.today().addDays(+5);
        taskRcrd.OwnerId = aCounty.OwnerId;
        insert taskRcrd;
        
        Test.startTest();
        T108_AppQueueCheckBatch batch = new T108_AppQueueCheckBatch();
        database.executeBatch(batch,10);
        Test.stopTest();
    }
    
    static testMethod void testMethod6(){
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Profile p = [SELECT Id FROM Profile WHERE Name='Read Only User'];
        User user1 = new User(Alias = 'standt', Email='standarduser12@testorg.com',
                              EmailEncodingKey='UTF-8', LastName='Testing', FirstName='Testing', LanguageLocaleKey='en_US',
                              LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', 
                              UserName=dateString+'standard6@testorg.com', IsActive = true, Owner_County__c = '1');
        insert user1;
        
        User user2 = new User();
        user2 = [Select Id, Name from User Where Id =: user1.ID];
        
        T_COUNTY__c aCounty=TestClassUtility.createCounty('Test County', 'Test County Department', 11, false);
        aCounty.OwnerId = user2.Id;
        aCounty.CDE_COUNTY__c = 1;
        insert aCounty;
        
        T_APPLN_PRCS_QUEUE__c appQueueRec = new T_APPLN_PRCS_QUEUE__c();
        appQueueRec.CDE_SOURCE__c = 'PK';
        appQueueRec.CDE_STATUS_APPLN__c ='PEN';
        appQueueRec.DTE_RCVD_APPLN__c = System.today();
        appQueueRec.County_Name__c = aCounty.Id;
        appQueueRec.CDE_COUNTY__c = '1';
        insert appQueueRec; 
        
        appQueueRec.DTE_RCVD_APPLN__c = System.today() - 10;
        update appQueueRec;
        
        Task taskRcrd = new Task();
        taskRcrd.Subject = 'T108 - Peak Application received 10 days ago is due for processing';
        taskRcrd.Status = 'Not Started';
        taskRcrd.Priority = 'Normal';
        taskRcrd.WhatId = appQueueRec.Id;
        taskRcrd.ActivityDate = system.today().addDays(+5);
        taskRcrd.OwnerId = aCounty.OwnerId;
        insert taskRcrd;
        
        Test.startTest();
        T108_AppQueueCheckBatch batch = new T108_AppQueueCheckBatch();
        database.executeBatch(batch,10);
        Test.stopTest();
    }
    
    public static testMethod void testSchedulableT108Batch(){
        Test.startTest();
        SchedulableT108AppQueueCheckBatch schObj =  new SchedulableT108AppQueueCheckBatch();
        String sch = '0 0 7 * * ?';
        String jobId =system.schedule('Test Deleted Record Archive Batch Check', sch, schObj); 
        // Get the information from the CronTrigger API object 
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
        // Verify the expressions are the same System.assertEquals(CRON_EXP, ct.CronExpression); 
        // Verify the job has not run 
        System.assertEquals(0, ct.TimesTriggered,'Cron trigger should return zero jobs'); 
        
        Test.stopTest();
    }
}