CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>Batch_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Batch Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authorization_Status__c</fullName>
        <label>Authorization Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <default>true</default>
                    <label>Authorized</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Terminated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>NBR_SSN__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>SSN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Batch Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <description>Provider ID</description>
        <label>Provider ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    

    <fields>
        <fullName>NBR_SSN__c</fullName>
        <description>SSN</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>SSN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/classes/UpdateFlagOnAuthorizationTest.cls
/*
*/
@isTest
public class UpdateFlagOnAuthorizationTest {
    public testMethod static void testBatchClass(){
        Date datetoday=System.Today();
        Date begindate = date.newInstance(datetoday.year(),datetoday.month(),1);
        Date dob = date.newInstance(datetoday.year()-20, datetoday.month(), 1);
        Date enddate = begindate.addDays(25);
        begindate = begindate.addDays(21);
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_CASE__c case1 = TestClassUtility.createCase(true, county.Id);
        T_CHATS_PROVR_STATUS__c provider = TestClassUtility.createProvider(true, 'Level 3');
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement = TestClassUtility.createFiscaAgreement(false, 'name', System.Today(), county.Id);
        fiscalAgreement.ID_SERVICE__c = provider.Id;
        insert fiscalAgreement;
        TestClassUtility.createCaseWaitlist(true, case1.Id, System.today(), System.today().addDays(30), 'WLT');
        List<T_SBSD_INDIV__c> individuals = new List<T_SBSD_INDIV__c>();
        Test.startTest();
        T_SBSD_INDIV__c individual;
        for(Integer i=0;i<1;i++){
            individual= TestClassUtility.createIndividual(false, dob, 'firstName', '1', 'lastName', 'SSN'+i, 'CC');
            individual.NBR_SSN__c = '123';
            individuals.add(individual);
         }
        insert individuals;
        List<T_AUTH__c> authRecords = new List<T_AUTH__c>();
        T_AUTH__c newAuth;
        for(T_SBSD_INDIV__c indiv:individuals){
            newAuth = TestClassUtility.createAuthorization(false,enddate,begindate,county.Id,null);
            indiv.NBR_SSN__c='123';
            newAuth.IDN_CASE__c= case1.Id;
            newAuth.IDN_CLIENT__c= indiv.Id;
            newAuth.IDN_PROVR__c= provider.Id;
            authRecords.add(newAuth);
        }
        insert authRecords;
        System.assert([select Id from T_AUTH__c WHERE Authorization_Status__c='2' AND Batch_Flag__c=false].size()==1,'There should be 100 authorised records');
        UpdateFlagOnAuthorization updateAuthBatch= new UpdateFlagOnAuthorization();
        Database.executeBatch(updateAuthBatch);     
        Test.stopTest();
        System.assert([select Id from T_AUTH__c WHERE Authorization_Status__c='2' AND Batch_Flag__c=false].isEmpty(),'Query should return zero rows as all records should get terminated');
    }
}