CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_IMM__c</fullName>
        <label>Immunized</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00389</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_SOURCE_VRFYD_IMMU__c</fullName>
        <description>Immunization How Verified</description>
        <label>Immunization How Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00709</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Immunization Verified</description>
        <label>Immunization Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_AUTH__c</fullName>
        <description>Authorization Begin Date</description>
        <label>Authorization Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_CHILD_ENROLLMENT__c.object
<CustomObject>
	<fields>
        <fullName>IsWavierProvider__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsWavierProvider</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enrollment_Reason__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
	 <fullName>DTE_BEGIN_EFFV__c</fullName>
    <description>Child Enrollment Begin Date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Enrollment Flag Begin Date</label>
    <type>Date</type>
	</fields>
	
	<fields>
	<fullName>Enroll_Flag__c</fullName>
    <label>Enrollment Flag</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
	</fields>
	<fields>
	 <fullName>IDN_CLIENT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Id</label>
    <referenceTo>T_SBSD_INDIV__c</referenceTo>
    <relationshipLabel>Child Enrollments</relationshipLabel>
    <relationshipName>Child_Enrollments</relationshipName>
    <type>Lookup</type>
	</fields>
	<fields>
	<fullName>IDN_EXTNL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>IDN_EXTNL</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
	</fields>
	<fields>
	<fullName>IDN_PROVR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider Id</label>
    <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
    <relationshipLabel>Child Enrollments</relationshipLabel>
    <relationshipName>Child_Enrollments</relationshipName>
    <type>Lookup</type>
	</fields>
    <label>Child Enrollment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Child Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <label>License Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <description>Provider ID</description>
        <label>Provider ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00367.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Available</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <label>Verbal Verification</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Written Verification</label>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
        <isActive>false</isActive>
        <label>CV</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
        <isActive>false</isActive>
        <label>N/A-adult caretaker</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <isActive>false</isActive>
        <label>SV</label>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
        <isActive>false</isActive>
        <label>N/A-not requesting child</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>R00367</description>
    <masterLabel>R00367</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00389.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NMD</fullName>
        <label>No. Medical reason</label>
    </customValue>
    <customValue>
        <fullName>NNW</fullName>
        <label>No. Not immunized</label>
    </customValue>
    <customValue>
        <fullName>NRL</fullName>
        <label>No. Religious Reasons</label>
    </customValue>
    <customValue>
        <fullName>NW</fullName>
        <label>No. In Process</label>
    </customValue>
    <customValue>
        <fullName>YES</fullName>
        <label>Yes. Immunized</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <description>R00389</description>
    <masterLabel>R00389</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00709.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NUR</fullName>
        <label>Dr/Nurse Statement</label>
    </customValue>
    <customValue>
        <fullName>PRO</fullName>
        <label>Provider</label>
    </customValue>
    <customValue>
        <fullName>SAG</fullName>
        <label>School Age</label>
    </customValue>
    <customValue>
        <fullName>SRD</fullName>
        <label>Shot Record</label>
    </customValue>
    <description>R00709</description>
    <masterLabel>R00709</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/ChildEnrollmentTriggerTest.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           10/25/2022                                                          
*  @description    Child ENrollment batch test batch class for T555 generation                          
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 25-Oct-2022                                                             
*  * Author: Diya Chaudhary                                                      
*  * Description: Initial version                   
*********************************************************************************************/
@isTest
public class ChildEnrollmentTriggerTest {
    
    public static final String OPEN = 'OPN';
    public static final String openRecordTypeId = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Open').getRecordTypeId();
    
    static testMethod void isCaseEligibletestScenario1() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1');
        insert provider;
        
        T_CHATS_PROVR_STATUS__c provider1= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 3');
        insert provider1;
        
        T_SBSD_CASE__c sbsdcase=TestClassUtility.createCase(false,county.Id);
        Date datetoday=System.Today();
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today().addYears(4);
        sbsdcase.IDN_EXTNL__c='12345';
        upsert sbsdcase;
        
        Date begindate = date.newInstance(datetoday.year(),datetoday.month(),1);
        begindate = begindate.addDays(25);
        //Removed unused variable on 5/13/2018 BG        
        Date enddate = begindate.addDays(20);
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstName','1','lastName','1','CC');
        T_AUTH__c authorization=TestClassUtility.createAuthorization(false,enddate,begindate,county.Id,provider.Id);
        authorization.IDN_CASE__c=sbsdcase.Id;
        authorization.IDN_CLIENT__c=sbsdIndiv.Id;
        authorization.CDE_TYPE_VERIF__c = 'NA';
        authorization.CDE_SOURCE_VRFYD_IMMU__c ='PRO';
        authorization.CDE_IMM__c ='NRL';
        insert authorization;
        Test.startTest();
        T_CHATS_CHILD_ENROLLMENT__c enroll = new T_CHATS_CHILD_ENROLLMENT__c();
        enroll.IDN_CLIENT__c = authorization.IDN_CLIENT__c;
        enroll.IDN_PROVR__c = authorization.IDN_PROVR__c;
        enroll.Enroll_Flag__c='Enrolled';
        enroll.IsWavierProvider__c = true;
        enroll.DTE_BEGIN_EFFV__c=authorization.DTE_BEGIN_EFFV_AUTH__c;
        insert enroll;
        T_CHATS_CHILD_ENROLLMENT__c enroll1 = new T_CHATS_CHILD_ENROLLMENT__c();
        enroll1.IDN_CLIENT__c = authorization.IDN_CLIENT__c;
        enroll1.IDN_PROVR__c = authorization.IDN_PROVR__c;
        enroll1.Enroll_Flag__c='Enrolled';
        enroll1.IsWavierProvider__c = true;
        enroll1.DTE_BEGIN_EFFV__c=authorization.DTE_BEGIN_EFFV_AUTH__c;
        insert enroll1;
        enroll.Enrollment_Reason__c = 'Child never attended';
        update enroll;
        
        enroll1.Enrollment_Reason__c = 'Child stopped attending after previous attendance';
        update enroll1;
        AuthTaskBasedOnEnrollBatchApxCtrl obj = new AuthTaskBasedOnEnrollBatchApxCtrl();
        DataBase.executeBatch(obj); 
        Test.stopTest();
    }
}