CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <label>License Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PAYMT__c.object
<CustomObject>
    <description>Parent table containing payment information generated through the payroll process</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SERV_PERIOD__c.object
<CustomObject>
    <description>Service period for payroll</description>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Period</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Period ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/CopySalesforceId_Test.cls
/*
*/
@isTest
private class CopySalesforceId_Test {

    @testSetup static void setup() {
        T_COUNTY__c county= TestClassUtility.createCounty('Test Name','Department',2,true);
        List<T_SBSD_CASE__c> caseList = new List<T_SBSD_CASE__c>();
        List<T_SBSD_INDIV__c> indivList = new List<T_SBSD_INDIV__c>();
        List<T_CHATS_PROVR_STATUS__c> providerList = new List<T_CHATS_PROVR_STATUS__c >();
        List<T_PAYMT__c> pmtList= new List<T_PAYMT__c>();
        List<T_SERV_PERIOD__c> servPeriodList= new List<T_SERV_PERIOD__c>();
        List<T_AUTH__c> authList= new List<T_AUTH__c>();
        
        for(Integer i=0;i<100;i++) {
            caseList.add((T_SBSD_CASE__c)TestClassUtility.createCase(false,county.Id));      
        }
        
        insert caseList;
        
        for(Integer i=0;i<100;i++) {
            indivList.add((T_SBSD_INDIV__c)TestClassUtility.createIndividual(false,date.newInstance(1983, 7, 15),'firstName','1','lastName','1','CC'));      
        }
        
        insert indivList;
        
        for(Integer i=0;i<100;i++) {
            providerList.add(new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1'));      
        }
        
        insert providerList;
              
        Date datetoday=System.Today();
        Date begindate = date.newInstance(datetoday.year(),datetoday.month(),1);
        Date enddate = begindate.addDays(25);
        begindate = begindate.addDays(21);
        
       
        for(Integer i=0;i<100;i++) {
            authList.add((T_AUTH__c)TestClassUtility.createAuthorization(false,enddate,begindate,county.Id,providerList[i].Id));
            authList[i].IDN_CASE__c=caseList[i].Id;
            authList[i].IDN_CLIENT__c=indivList[i].Id;
        }
         
       insert authList;
       
       for(Integer i=0;i<100;i++) {
            pmtList.add(new T_PAYMT__c());      
        }
        
        insert pmtList;
        
        for(Integer i=0;i<100;i++) {
            servPeriodList.add(new T_SERV_PERIOD__c(DTE_BEGIN_EFFV__c=system.today()));      
        }
        
        insert servPeriodList;
        
       
    }
        
    static testMethod void CopySalesforceIdBulkTest() {
        List<T_SBSD_CASE__c> caseList = [select Id, IDN_EXTNL__c from T_SBSD_CASE__c Limit 202];
        List<T_SBSD_INDIV__c> indivList = [select Id, IDN_EXTNL__c from T_SBSD_INDIV__c Limit 202];
        List<T_AUTH__c> authList= [select Id, IDN_EXTNL__c from T_AUTH__c Limit 202];
        List<T_PAYMT__c> pmtList= [select Id, IDN_EXTNL__c from T_PAYMT__c Limit 202];
        List<T_SERV_PERIOD__c> servPeriodList= [select Id, IDN_EXTNL__c from T_SERV_PERIOD__c Limit 202];
        Test.starttest();
        
        system.assert(caseList.size()>99,'Incorrect list of records returned');
        system.assert(indivList.size()>99,'Incorrect list of records returned');
        system.assert(authList.size()>99,'Incorrect list of records returned');
        system.assert(pmtList.size()>99,'Incorrect list of records returned');
        system.assert(servPeriodList.size()>99,'Incorrect list of records returned');
        
        
        //Authorization object check
        for(T_AUTH__c authEach:authList) {
           system.assertEquals(authEach.Id,authEach.IDN_EXTNL__c,'External Id is not matching with record Id');
        }
        
        //Case object check
        for(T_SBSD_CASE__c caseEach:caseList) {
           system.assertEquals(caseEach.Id,caseEach.IDN_EXTNL__c,'External Id is not matching with record Id');
        }
        
        //Individual object check
        for(T_SBSD_INDIV__c indivEach:indivList) {
           system.assertEquals(indivEach.Id,indivEach.IDN_EXTNL__c,'External Id is not matching with record Id');
        }
        
        //Payment object check
        for(T_PAYMT__c pmtEach:pmtList) {
           system.assertEquals(pmtEach.Id,pmtEach.IDN_EXTNL__c,'External Id is not matching with record Id');
        }
        
        //Service Period object check
        for(T_SERV_PERIOD__c servPeriodEach:servPeriodList) {
           system.assertEquals(servPeriodEach.Id,servPeriodEach.IDN_EXTNL__c,'External Id is not matching with record Id');
        }
        
        
        Test.stoptest();
    }
}