CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>T_AUTH</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_AUTH__c</fullName>
        <description>Authorization Begin Date</description>
        <label>Authorization Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_AUTH__c</fullName>
        <label>Authorization End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <formula>IDN_PROVR__r.NAM_FACILITY__c</formula>
        <label>Provider Name</label>
        <type>Text</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <label>License Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <label>License Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Provider Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_SCH__c.object
<CustomObject>
    <fields>
        <fullName>CDE_RATE_TYPE__c</fullName>
        <description>Rate Type</description>
        <label>Rate Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00751</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_AGRMT_FISCAL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement</description>
        <label>Fiscal Agreement</label>
        <referenceTo>T_PROVR_FISCAL_AGREMENT__c</referenceTo>
        <relationshipLabel>Rate Schedules</relationshipLabel>
        <relationshipName>Rate_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Schedules</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_AGRMT__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_AGRMT__c</fullName>
        <description>Renewal Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SLOT_CONTRACT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_CARE_LEVEL__c</fullName>
        <label>Care Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_CARE_UNIT__c</fullName>
        <label>Care Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_PRG_TYPE__c</fullName>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_RATE_TYPE__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rate_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CNT_DAYS_OF_WEEK__c</fullName>
        <label>Days of Week</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_ADDENDUM__c</fullName>
        <label>Slot Contract Addendum</label>
        <referenceTo>T_SLOT_CONTRACT_ADDENDUM__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IDN_PROVIDER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLOT_CONTRACT_DESCRIPTION__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Slot Contract Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Slot Contract</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slot Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SLOT_CONTRACT_ADDENDUM__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Slot Contract Addendums</relationshipLabel>
        <relationshipName>Slot_Contract_Addendums</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <label>Addendum Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CNT_SLOT_CONTRACTS__c</fullName>
        <label>Number of Slot Contracts</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_ADDENDUM__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Addendum Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_ADDENDUM__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Addendum End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_FISCAL_AGREEMENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Agreement ID</label>
        <referenceTo>T_PROVR_FISCAL_AGREMENT__c</referenceTo>
        <relationshipLabel>Slot Contract Addendums</relationshipLabel>
        <relationshipName>Slot_Contract_Addendums</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Slot Contract Addendum</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slot Contract Addendums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/Care_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>0-6 Months</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>06-12 Months</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>12-18 Months</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>18-24 Months</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>24-30 Months</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>30-36 Months</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>36 - School Age</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>School Age</label>
    </customValue>
    <masterLabel>Care Level</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/Care_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>PT</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>FT</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>FTPT</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>FTFT</label>
    </customValue>
    <masterLabel>Care Unit</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/Program_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>LI</fullName>
        <label>Low Income Child Care</label>
    </customValue>
    <customValue>
        <fullName>TF</fullName>
        <label>TANF</label>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
        <label>Child Welfare Child Care</label>
    </customValue>
    <masterLabel>Program Type</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/Rate_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Regular</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Before School</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>After School</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>B and A School</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>Overnight</label>
    </customValue>
    <customValue>
        <fullName>37</fullName>
        <label>Weekend</label>
    </customValue>
    <customValue>
        <fullName>43</fullName>
        <label>Evening</label>
    </customValue>
    <customValue>
        <fullName>55</fullName>
        <label>Disability</label>
    </customValue>
    <customValue>
        <fullName>91</fullName>
        <label>Out-of-County</label>
    </customValue>
    <masterLabel>Rate Type</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/SlotContractFlowApxCtrl.cls
public with sharing class SlotContractFlowApxCtrl {
    
    //method to get initial details
    @AuraEnabled
    public static LightningServerResponse getInitData(string recordid)
    {
        Map<String, Object> objectData = new map<String, Object>();    
        Boolean isSuccessful;
        String message;  
        
        List<T_CHATS_PROVR_STATUS__c> provider=[SELECT Id ,name,NAM_FACILITY__c,(select id,CDE_COUNTY__r.name,CDE_TYPE_STATUS__c from Provider_Fiscal_Agreements__r where CDE_TYPE_STATUS__c !='CLS' order by CDE_COUNTY__r.name) from T_CHATS_PROVR_STATUS__c where id= :recordid];
        
        Map<id,string> countySet=new Map<id,string>();
        
        if(provider[0].Provider_Fiscal_Agreements__r!=null && !provider[0].Provider_Fiscal_Agreements__r.isEmpty())
        {
            for(T_PROVR_FISCAL_AGREMENT__c indiFA : provider[0].Provider_Fiscal_Agreements__r)
            {
                if(!countySet.containsKey(indiFA.CDE_COUNTY__c))
                {
                    countySet.put(indiFA.CDE_COUNTY__c,indiFA.CDE_COUNTY__r.name );
                }
            }
        }
        
        Map<string,string> plValues = getPicklistDetails('T_SLOT_CONTRACT__c','CNT_DAYS_OF_WEEK__c');
        Map<string,string> cLevel =getPicklistDetails('T_SLOT_CONTRACT__c','CDE_CARE_LEVEL__c');
        Map<string,string> cUnit = getPicklistDetails('T_SLOT_CONTRACT__c','CDE_CARE_UNIT__c');
        Map<string,string> rType =getPicklistDetails('T_SLOT_CONTRACT__c','CDE_RATE_TYPE__c');
        Map<string,string> pType = getPicklistDetails('T_SLOT_CONTRACT__c','CDE_PRG_TYPE__c');
        
        List<T_SLOT_CONTRACT__c> scList=[select id , Name from T_SLOT_CONTRACT__c order by Name  desc limit 1];
        
        if(scList!=null && !scList.isEmpty())
        {
            Integer original,nowle,diff;
            String seq=String.valueof(Integer.valueOf(scList[0].Name)+1);
            original=String.valueOf(scList[0].Name).length();
            nowle=String.valueOf(Integer.valueOf(scList[0].Name)).length();
            diff=original-nowle;
            
            objectData.put('sequence', seq.leftPad(diff, '0'));
        }else
        {
            objectData.put('sequence','000001');
        }
        
        objectData.put('providername', provider[0].name);
        objectData.put('provdName',provider[0].NAM_FACILITY__c);
        objectData.put('weekdays', plValues);
        objectData.put('careLevel', cLevel);
        objectData.put('careUnit', cUnit);
        objectData.put('rateType', rType);
        objectData.put('progType', pType);
        objectData.put('countySet', countySet);
        isSuccessful = true;
        
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
    public static Map<string,string> getPicklistDetails(String objectName,String fieldName)
    {
        Map<string,string> pValues=new Map<string,string>();
        Schema.SObjectType objType = Schema.getGlobalDescribe().get(objectName);
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        Schema.DescribeFieldResult objFieldInfo = objDescribe.fields.getMap().get(fieldName).getDescribe();
        List<Schema.PicklistEntry> picklistvalues = objFieldInfo.getPicklistValues();
        
        //Add the picklist values to list.
        for(Schema.PicklistEntry plv: picklistvalues) {
            if(plv.isActive())
            {
                pValues.put(plv.getLabel(),plv.getValue());
            }
        }
        return pValues;
    }
    
    //this method will be called on save click
    @AuraEnabled
    public static LightningServerResponse saveData(string recordData)
    {
        // Setting savepoint to rollback the transaction is case of any failures. CCCAP-15551
        savepoint Sp = database.setsavepoint();
        Map<String, Object> objectData = new map<String, Object>();    
        Boolean isSuccessful;
        String message;  
        String authMsg;
        try{
            SlotWrapper slotRec=(SlotWrapper)System.JSON.deserialize(recordData,SlotWrapper.class);  
            
            authMsg =checkForAuthorization(slotRec);
            //check if user county different than selected county
            if(!CHATSUtility.checkCountyWithUserCounty(slotRec.countyVal))
            {
                isSuccessful=false;
                message='User County not matching with selected county';
                objectData.put('countyCheck',false);
            }
            else if(authMsg !='true')
            {
                if(authMsg =='authFalse')
                { 
                    isSuccessful=false;
                    message='User County not matching with selected county';
                    objectData.put('authDate',false);
                    
                }else if(authMsg =='slotBeFalse')
                {
                    isSuccessful=false;
                    message='User County not matching with selected county';
                    objectData.put('slotBeFalse',false);
                }else if(authMsg =='authPrFalse'){
                    isSuccessful=false;
                    message='User County not matching with selected county';
                    objectData.put('authPrFalse',false);
                }else if(authMsg =='existSlot'){
                    isSuccessful=false;
                    message='User County not matching with selected county';
                    objectData.put('existSlot',false);
                }else{
                    isSuccessful=false;
                    message='User County not matching with selected county';
                    objectData.put('authCounty',false);
                }
                
            }
            else
            {
                //using provider id and county id get the latest addendum record
                List<T_SLOT_CONTRACT_ADDENDUM__c> indiAdd=getFinalAddendumRecord(slotRec);
                
                if(indiAdd!=null && !indiAdd.isEmpty())
                {
                    //if no addendum records
                    if(slotRec.endDate > indiAdd[0].DTE_END_ADDENDUM__c)
                    {
                        isSuccessful=false;
                        message='No Addendum record found ';
                        objectData.put('addendumEndCheck',false);
                    }
                    else //check if allowed to create more slot records
                    {
                        List<AggregateResult> sCList=[select COUNT_DISTINCT(SLOT_CONTRACT_DESCRIPTION__c )dtnct from T_SLOT_CONTRACT__c where IDN_PROVIDER__c =: slotRec.provdId and CDE_COUNTY__c =:slotRec.countyVal and IDN_ADDENDUM__c=:indiAdd[0].id];
                        
                        Integer extSlot =Integer.valueOf(sCList[0].get('dtnct'));
                        if(extSlot<indiAdd[0].CNT_SLOT_CONTRACTS__c)
                        {
                            
                            //method to finally create slot records
                            Response fResp = createSlotContracts(slotRec,indiAdd[0]);
                            Boolean issucces=fResp.succ;
                            string sno;
                            string sid;
                            if(issucces)
                            {
                                sno=fResp.sno;
                                sid=fResp.sid;
                                isSuccessful=true;
                                message='Success';
                                objectData.put('createError',true);
                                objectData.put('sno',sno);
                                objectData.put('sid',sid);
                            }
                            else{
                                isSuccessful=false;
                                message='Error occurred !';
                                objectData.put('createError',false);
                            }
                        }else{
                            isSuccessful=false;
                            message='count error';
                            objectData.put('addendumCountCheck',false);
                        }
                    }
                    
                }else{
                    isSuccessful=false;
                    message='No Addendum record found for selected county and provider';
                    objectData.put('addendumcheck',false);
                }
                
                
            }
        }catch(Exception e){
            database.rollback(sp);
            isSuccessful = false;
            message = e.getMessage();
            objectData.put('createError',false);
        }
        
        
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
    @AuraEnabled
    public static LightningServerResponse getRateTypeByBegin(string recordData)
    {
        Map<String, Object> objectData = new map<String, Object>(); 
        Map<string,string> fValues=new Map<string,string>();
        Boolean isSuccessful;
        String message;  
        Set<string> pValues=new Set<string>();
        SlotWrapper slotRec=(SlotWrapper)System.JSON.deserialize(recordData,SlotWrapper.class); 
        
        List<T_PROVR_FISCAL_AGREMENT__c> fas=[SELECT Id ,DTE_BEGIN_AGRMT__c,DTE_END_AGRMT__c,CDE_COUNTY__c,ID_SERVICE__c
                                              ,(select id,DTE_BEGIN_EFFV__c,DTE_END_EFFV__c,toLabel(CDE_RATE_TYPE__c) from Rate_Schedules__r )
                                              from T_PROVR_FISCAL_AGREMENT__c where CDE_TYPE_STATUS__c !='CLS' and CDE_COUNTY__c= :slotRec.countyVal  and ID_SERVICE__c=: slotRec.provdId];
        
        if(fas!=null && !fas.isEmpty())
        {
            for(T_PROVR_FISCAL_AGREMENT__c indiObj : fas)
            {
                if(slotRec.beginDate >=indiObj.DTE_BEGIN_AGRMT__c)
                {
                    if(indiObj.Rate_Schedules__r!=null && !indiObj.Rate_Schedules__r.isEmpty())
                    {
                        for(T_FISCAL_SCH__c rSched : indiObj.Rate_Schedules__r)
                        {
                            if(slotRec.beginDate >=rSched.DTE_BEGIN_EFFV__c && (rSched.DTE_END_EFFV__c==null || (slotRec.beginDate<=rSched.DTE_END_EFFV__c )) )
                            {
                                List<string> tmpStrings=rSched.CDE_RATE_TYPE__c.split(';');
                                for(String indiS : tmpStrings)
                                {
                                    pValues.add(indiS);            
                                }
                                Schema.SObjectType objType = Schema.getGlobalDescribe().get('T_SLOT_CONTRACT__c');
                                Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
                                Schema.DescribeFieldResult objFieldInfo = objDescribe.fields.getMap().get('CDE_RATE_TYPE__c').getDescribe();
                                List<Schema.PicklistEntry> picklistvalues = objFieldInfo.getPicklistValues();
                                
                                //Add the picklist values to list.
                                for(Schema.PicklistEntry plv: picklistvalues) {
                                    if(pValues.contains(plv.getLabel()))
                                    {
                                        fValues.put(plv.getLabel(),plv.getValue());
                                    }
                                }
                                break;
                            }
                        }
                        break;
                    }
                }
            }
        }
        
        objectData.put('rtype', fValues);
        isSuccessful = true;
        message='success';
        return new LightningServerResponse(isSuccessful,message,objectData);
        
    }
    //method to get addendum against county and provider
    public static List<T_SLOT_CONTRACT_ADDENDUM__c> getFinalAddendumRecord(SlotWrapper slotRec) {
        List<T_SLOT_CONTRACT_ADDENDUM__c> finAde=new List<T_SLOT_CONTRACT_ADDENDUM__c>();
        
        List<T_SLOT_CONTRACT_ADDENDUM__c> addendumList=[select id,DTE_BEGIN_ADDENDUM__c,DTE_END_ADDENDUM__c,IDN_FISCAL_AGREEMENT__c,IDN_FISCAL_AGREEMENT__r.ID_SERVICE__c ,CDE_COUNTY__c ,CNT_SLOT_CONTRACTS__c,CDE_STATUS__c from T_SLOT_CONTRACT_ADDENDUM__c where
                                                        IDN_FISCAL_AGREEMENT__r.ID_SERVICE__c=:slotRec.provdId and CDE_COUNTY__c=:slotRec.countyVal and CDE_STATUS__c  in ('FIN','OPN')  order by CDE_STATUS__c  asc];
        
        if(addendumList!=null && !addendumList.isEmpty())
        {
            for(T_SLOT_CONTRACT_ADDENDUM__c indiObj : addendumList)
            {
                if(slotRec.beginDate >=indiObj.DTE_BEGIN_ADDENDUM__c && slotRec.beginDate<=indiObj.DTE_END_ADDENDUM__c)
                {
                    finAde.add(indiObj);
                    break;
                }
            }
        }  
        return finAde;
    }
    //method to check if auth is present and if auth date is less
    public static string checkForAuthorization(SlotWrapper slotRec){
        String finResult='true';
        if(string.isNotBlank(slotRec.authVal)){
            T_AUTH__c auth=[select id,DTE_BEGIN_EFFV_AUTH__c,DTE_END_EFFV_AUTH__c,CDE_COUNTY__c,IDN_PROVR__c,IDN_SLOT_CONTRACT__c from T_AUTH__c where id=:slotRec.authVal];
            if(slotRec.countyVal == auth.CDE_COUNTY__c){
                if(slotRec.provdId == auth.IDN_PROVR__c){
                    if(auth.DTE_END_EFFV_AUTH__c<slotRec.beginDate ){
                        finResult='authFalse';
                    }
                    if(auth.DTE_BEGIN_EFFV_AUTH__c > slotRec.endDate){
                        finResult = 'slotBeFalse';
                    }
                    if(finResult=='true'){
                        /*if(string.isNotBlank(auth.IDN_SLOT_CONTRACT__c)){
                            List<T_SLOT_CONTRACT__c> allSlots = [select id, name,SLOT_CONTRACT_DESCRIPTION__c, DTE_BEGIN_SLOT__c,DTE_END_SLOT__c  from T_SLOT_CONTRACT__c where id=:auth.IDN_SLOT_CONTRACT__c];
							if(allSlots.size()>1)
                            {
                                for(T_SLOT_CONTRACT__c indiSlot : allSlots)
                                {
                                    if(slotRec.beginDate>=indiSlot.DTE_BEGIN_SLOT__c && slotRec.beginDate<=indiSlot.DTE_END_SLOT__c && slotRec.endDate>=indiSlot.DTE_BEGIN_SLOT__c && slotRec.endDate<=indiSlot.DTE_END_SLOT__c )
                                    {
                                        finResult='existSlot';
                                    }
                                }
                            }
                        }*/
                        date beginDate;
                        Integer betDays = slotRec.beginDate.daysBetween(slotRec.endDate);
                        List<T_SLOT_CONTRACT__c> allSlots = [select id, NAME, SLOT_CONTRACT_DESCRIPTION__c, DTE_BEGIN_SLOT__c, DTE_END_SLOT__c FROM T_SLOT_CONTRACT__c WHERE IDN_AUTH__c =:auth.Id];
                        for(T_SLOT_CONTRACT__c indiSlot : allSlots){
                            beginDate=slotRec.beginDate;
                            for(integer i=0;i<=betDays;i++)
							{
                                 if(beginDate>= indiSlot.DTE_BEGIN_SLOT__c && beginDate<= indiSlot.DTE_END_SLOT__c)
                                 {
                                	finResult='existSlot';
                            	}
                                beginDate=beginDate+1;
                            }
                           
                        }
                    }
                }
                else{
                    finResult='authPrFalse';
                }
            }else{
                finResult='countyFalse';
            }
                         
        }
        
        return finResult;
    }
    //method to create slot contract
    public static Response createSlotContracts(SlotWrapper slotRec,T_SLOT_CONTRACT_ADDENDUM__c indiAdd)
    {
        Response resp=new  Response();
        Boolean issuccess=false;
        string scno;
        String scId;
        
        T_SLOT_CONTRACT__c scObToInsert=getSlotRecord(slotRec,indiAdd);
        
        Database.SaveResult sr = Database.insert(scObToInsert, false);
        
        if (sr.isSuccess()) {
            scId=sr.getId();
            scno=[select id, name from T_SLOT_CONTRACT__c where id = :scId].name;
            updateDesc(scId);
            if(string.isNotBlank(slotRec.authVal)){
                furtherOperations(slotRec,scId,indiAdd);
            }
            
            issuccess=true; 
            
        }else{
            issuccess=false; 
        }
        
        resp.succ=issuccess;
        resp.sno=scno;
        resp.sid=scId;
        return resp;
    }
    public static void furtherOperations(SlotWrapper slotRec,id scId,T_SLOT_CONTRACT_ADDENDUM__c indiAdd)
    {
        T_AUTH__c auth=[select id ,DTE_BEGIN_SLOT__c,DTE_BEGIN_EFFV_AUTH__c, DTE_END_EFFV_AUTH__c,IDN_SLOT_CONTRACT__r.DTE_END_SLOT__c, IDN_SLOT_CONTRACT__c from T_AUTH__c where id=:slotRec.authVal];
        
        T_SLOT_CONTRACT__c sc=[select id , DTE_BEGIN_SLOT__c,DTE_END_SLOT__c,Name,SLOT_CONTRACT_DESCRIPTION__c,IDN_AUTH__c,IND_AVAILABLE__c,IND_FUTURE_VACANT__c,IND_OCCUPIED__c from T_SLOT_CONTRACT__c where id=:scID];
        Id finSCId;
        Date finDate;

        if(slotRec.beginDate >=auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate <= auth.DTE_END_EFFV_AUTH__c  )
        {
            sc.IDN_AUTH__c=auth.Id;
            finSCId=sc.Id;
            finDate=sc.DTE_BEGIN_SLOT__c;

            GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{sc},new Map<String,Object>{'Method__c'=>'furtherOperations','Class__c'=>'SlotContractFlowApxCtrl'});
            
        }else if(slotRec.beginDate >= auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate > auth.DTE_END_EFFV_AUTH__c)
        {
            sc.IDN_AUTH__c=auth.Id;
            sc.DTE_END_SLOT__c = auth.DTE_END_EFFV_AUTH__c;
            finSCId=sc.Id;
            finDate=sc.DTE_BEGIN_SLOT__c;
            
            GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{sc},new Map<String,Object>{'Method__c'=>'furtherOperations','Class__c'=>'SlotContractFlowApxCtrl'});
            
            T_SLOT_CONTRACT__c scObToInsert=getSlotRecord(slotRec,indiAdd);
            scObToInsert.DTE_BEGIN_SLOT__c = auth.DTE_END_EFFV_AUTH__c+1;
            scObToInsert.SLOT_CONTRACT_DESCRIPTION__c = sc.SLOT_CONTRACT_DESCRIPTION__c;
            scObToInsert.IDN_AUTH__c=null;
  
            GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert},new Map<String,Object>{'Method__c'=>'furtherOperations','Class__c'=>'SlotContractFlowApxCtrl'});
            
        }else if(slotRec.beginDate < auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate > auth.DTE_END_EFFV_AUTH__c)
        {
            sc.IDN_AUTH__c=null;
            sc.DTE_END_SLOT__c=auth.DTE_BEGIN_EFFV_AUTH__c-1;
            
            GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{sc},new Map<String,Object>{'Method__c'=>'furtherOperations','Class__c'=>'SlotContractFlowApxCtrl'});
      
            
            T_SLOT_CONTRACT__c scObToInsert=getSlotRecord(slotRec,indiAdd);
            scObToInsert.DTE_BEGIN_SLOT__c =auth.DTE_BEGIN_EFFV_AUTH__c;
            scObToInsert.IDN_AUTH__c=auth.Id;
            scObToInsert.SLOT_CONTRACT_DESCRIPTION__c = sc.SLOT_CONTRACT_DESCRIPTION__c;
            scObToInsert.DTE_END_SLOT__c=auth.DTE_END_EFFV_AUTH__c;
            
            GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert},new Map<String,Object>{'Method__c'=>'furtherOperations','Class__c'=>'SlotContractFlowApxCtrl'});   
            
            T_SLOT_CONTRACT__c vcsobject=getSlotRecord(slotRec,indiAdd);
            vcsobject.DTE_BEGIN_SLOT__c =auth.DTE_END_EFFV_AUTH__c+1;
            vcsobject.IDN_AUTH__c=null;
            vcsobject.SLOT_CONTRACT_DESCRIPTION__c = sc.SLOT_CONTRACT_DESCRIPTION__c;

            GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{vcsobject},new Map<String,Object>{'Method__c'=>'furtherOperations','Class__c'=>'SlotContractFlowApxCtrl'});
            
            finSCId=scObToInsert.Id;
            finDate=scObToInsert.DTE_BEGIN_SLOT__c;
        }else if(slotRec.beginDate < auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate <= auth.DTE_END_EFFV_AUTH__c)
        {
            sc.IDN_AUTH__c=null;
            sc.DTE_END_SLOT__c=auth.DTE_BEGIN_EFFV_AUTH__c-1;

            GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{sc},new Map<String,Object>{'Method__c'=>'furtherOperations','Class__c'=>'SlotContractFlowApxCtrl'});
            
            T_SLOT_CONTRACT__c scObToInsert=getSlotRecord(slotRec,indiAdd);
            scObToInsert.IDN_AUTH__c=auth.id;
            scObToInsert.DTE_BEGIN_SLOT__c=auth.DTE_BEGIN_EFFV_AUTH__c;
            scObToInsert.SLOT_CONTRACT_DESCRIPTION__c = sc.SLOT_CONTRACT_DESCRIPTION__c;

            GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert},new Map<String,Object>{'Method__c'=>'furtherOperations','Class__c'=>'SlotContractFlowApxCtrl'});
            
            finSCId=scObToInsert.Id;
            finDate=scObToInsert.DTE_BEGIN_SLOT__c;
        }
        auth.DTE_BEGIN_SLOT__c=finDate;
        auth.IDN_SLOT_CONTRACT__c =finSCId;
        GenericDMLHandler.updateRecords(new List<T_AUTH__c>{auth},new Map<String,Object>{'Method__c'=>'furtherOperations','Class__c'=>'SlotContractFlowApxCtrl'});
        
    }
    public static void updateDesc(Id scID){
        String tmpDsc;
        T_SLOT_CONTRACT__c sc=[select id , Name,SLOT_CONTRACT_DESCRIPTION__c from T_SLOT_CONTRACT__c where id=:scID];
        tmpDsc = sc.SLOT_CONTRACT_DESCRIPTION__c.substringBeforeLast('_');
        sc.SLOT_CONTRACT_DESCRIPTION__c=tmpDsc+'_'+sc.Name;

        GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{sc},new Map<String,Object>{'Method__c'=>'updateDesc','Class__c'=>'SlotContractFlowApxCtrl'});
    }
    
    public static T_SLOT_CONTRACT__c  getSlotRecord(SlotWrapper slotRec,T_SLOT_CONTRACT_ADDENDUM__c indiAdd){
        
        T_SLOT_CONTRACT__c scObToInsert =new T_SLOT_CONTRACT__c();
        scObToInsert.SLOT_CONTRACT_DESCRIPTION__c =slotRec.scdesc;
        scObToInsert.IDN_ADDENDUM__c=indiAdd.id;
        scObToInsert.IDN_PROVIDER__c=slotRec.provdId;
        scObToInsert.CDE_COUNTY__c=slotRec.countyVal;
        scObToInsert.DTE_BEGIN_SLOT__c=slotRec.beginDate;
        scObToInsert.DTE_END_SLOT__c=slotRec.endDate;
        scObToInsert.CNT_DAYS_OF_MONTH__c=slotRec.noDays;
        
        String finWeek;
        for(String indiS : slotRec.weekData)
        {        
            if(string.isBlank(finWeek))
            {
                finWeek=indiS+';';
            }else
            {
                finWeek=finWeek+indiS+';';
            }
            
        }
        //system.debug('finWeek '+finWeek);
        
        scObToInsert.CNT_DAYS_OF_WEEK__c=finWeek;
        scObToInsert.CDE_CARE_LEVEL__c=slotRec.clevelVal;
        scObToInsert.CDE_RATE_TYPE__c=slotRec.rtypeVal;
        scObToInsert.IDN_AUTH__c=slotRec.authVal;
        scObToInsert.IND_AVAILABLE__c=slotRec.avaVal;
        scObToInsert.CDE_PRG_TYPE__c=slotRec.progTyp;
        scObToInsert.CDE_CARE_UNIT__c=slotRec.cunitVal;        
        return scObToInsert;
        
    }
    public class Response{
        @AuraEnabled
        public boolean succ {get;set;}
        @AuraEnabled
        public String sno {get;set;}
        @AuraEnabled
        public String sid {get;set;}
    }
    public class SlotWrapper{
        @AuraEnabled
        public boolean avaVal {get;set;}
        @AuraEnabled
        public String progTyp {get;set;}
        @AuraEnabled
        public String provdId {get;set;}
        @AuraEnabled
        public String countyVal {get;set;}
        @AuraEnabled
        public String rtypeVal {get;set;}
        @AuraEnabled
        public String clevelVal {get;set;}
        @AuraEnabled
        public String cunitVal {get;set;}        
        @AuraEnabled
        public Integer noDays {get;set;}
        @AuraEnabled
        public Date beginDate {get;set;}
        @AuraEnabled
        public Date endDate {get;set;}
        @AuraEnabled
        public String authVal {get;set;}
        @AuraEnabled
        public String scdesc {get;set;}
        @AuraEnabled
        public List<String> weekData {get;set;}
    }
}