CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>AMT_ACTV_AUTH__c</fullName>
        <description>Authorization Activity Amount</description>
        <label>Authorization Activity Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>T_AUTH</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Authorization</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <formula>IDN_PROVR__r.NAM_FACILITY__c</formula>
        <label>Provider Name</label>
        <type>Text</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <label>License Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <label>License Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Provider Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>CDE_STATUS_CASE__c</fullName>
        <description>Case Status</description>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00357</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00357.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>REO</fullName>
        <label>Reopen</label>
    </customValue>
    <description>R00357</description>
    <masterLabel>R00357</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/OutputRollupSummaryApxCtrlTest.cls
@isTest
public class OutputRollupSummaryApxCtrlTest {

    public static testMethod void testGetRollupSummaryValueCOUNT(){
        List<T_COUNTY__c> counties = [SELECT Id FROM T_COUNTY__c limit 1000];
        System.assertEquals(false, counties.isEmpty(), 'counties should not be empty');
        String query = 'SELECT Id FROM T_SBSD_CASE_STATUS_MODE__c WHERE IDN_CASE__r.CDE_COUNTY__c = :recordId AND CDE_STATUS_CASE__c = \'OPN\'';
        Decimal lsr = OutputRollupSummaryApxCtrl.getRollupSummaryValue(query, 'Id', 'COUNT', counties.get(0).Id,false);
        System.debug(lsr);
       // System.assertEquals(true, lsr.isSuccessful, 'lsr.isSuccessful should be true');
        System.assertEquals(1, lsr, 'lsr.objectDate.value should be equal to 1');
    }

    public static testMethod void testGetRollupSummaryValueMAX(){
        List<T_COUNTY__c> counties = [SELECT Id FROM T_COUNTY__c limit 1000];
        System.assertEquals(false, counties.isEmpty(), 'counties should not be empty');
       //System.debug([SELECT ACTIVE_AUTH_STATUS__c FROM T_AUTH__c]);
        String query = 'SELECT AMT_ACTV_AUTH__c FROM T_AUTH__c WHERE CDE_COUNTY__c = :recordId';
        Decimal lsr = OutputRollupSummaryApxCtrl.getRollupSummaryValue(query, 'AMT_ACTV_AUTH__c', 'MAX', counties.get(0).Id,false);
        System.debug(lsr);
       
        System.assertEquals(20.00, lsr, 'value should be 20');
    }

    public static testMethod void testGetRollupSummaryValueMIN(){
        List<T_COUNTY__c> counties = [SELECT Id FROM T_COUNTY__c limit 1000];
        System.assertEquals(false, counties.isEmpty(), 'counties should not be empty');
        //System.debug([SELECT ACTIVE_AUTH_STATUS__c FROM T_AUTH__c]);
        String query = 'SELECT AMT_ACTV_AUTH__c FROM T_AUTH__c WHERE CDE_COUNTY__c = :recordId';
        Decimal lsr = OutputRollupSummaryApxCtrl.getRollupSummaryValue(query, 'AMT_ACTV_AUTH__c', 'MIN', counties.get(0).Id,false);
        System.debug(lsr);
        
        System.assertEquals(10.00, lsr, 'value should be 10');
    }

    public static testMethod void testGetRollupSummaryValueSUM(){
        List<T_COUNTY__c> counties = [SELECT Id FROM T_COUNTY__c limit 1000];
        System.assertEquals(false, counties.isEmpty(), 'counties should not be empty');
        //System.debug([SELECT ACTIVE_AUTH_STATUS__c FROM T_AUTH__c]);
        String query = 'SELECT AMT_ACTV_AUTH__c FROM T_AUTH__c WHERE CDE_COUNTY__c = :recordId';
        Decimal lsr = OutputRollupSummaryApxCtrl.getRollupSummaryValue(query, 'AMT_ACTV_AUTH__c', 'SUM', counties.get(0).Id,false);
        System.debug(lsr);
        
        System.assertEquals(30.00, lsr, 'value should be 30');
    }

    
    public static testMethod void testGetRollupSummaryValueException(){
        String query = 'blah blah query';
        Decimal lsr = OutputRollupSummaryApxCtrl.getRollupSummaryValue(query, 'blah blah Summarized field', 'blah blah type', 'xxxxxWrongId',false);
        System.assertEquals(0, lsr,'value should be zero');
    }
    
    @testSetup
    public static void setUpdata(){
        User user;
        Profile userProfile=[Select id from Profile where Name ='System Administrator'];
        user = TestClassUtility.createUserWithPS(userProfile.Id ,'System_Administrator_PS', 'test','test','test@example.com','test@example.com.uesername','ttes');
            
        System.runAs(user){
            T_COUNTY__c countyRec = TestClassUtility.createCounty('Denver','Denver',1,true);
            T_SBSD_CASE__c caseRec = TestClassUtility.createCase(true,countyRec.Id);
            T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(NAM_FACILITY__c = 'Provider Test', TXT_CHATS_RATING__c ='Level 1');
        	insert provider;
            T_AUTH__c authorization = TestClassUtility.createAuthorization(false, System.today()+5, System.today()-5, countyRec.Id, provider.Id);
            authorization.AMT_ACTV_AUTH__c = 10;
            T_AUTH__c authorization2 = TestClassUtility.createAuthorization(false, System.today()+5, System.today()-5, countyRec.Id, provider.Id);
            authorization2.AMT_ACTV_AUTH__c = 20;
            insert new List<SObject>{authorization, authorization2};
            insert new List<SObject>{
                new T_SBSD_CASE_STATUS_MODE__c(IDN_CASE__c = caseRec.Id, DTE_BEGIN_EFFV__c = System.today()-5, CDE_STATUS_CASE__c = 'OPN'),
                    new T_SBSD_CASE_STATUS_MODE__c(IDN_CASE__c = caseRec.Id, DTE_BEGIN_EFFV__c = System.today()-5, DTE_END_EFFV__c = System.today()-2, CDE_STATUS_CASE__c = 'CLS')
                };
        }
    }
}