CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>T_AUTH</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_AUTH__c</fullName>
        <description>Authorization Begin Date</description>
        <label>Authorization Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_AUTH__c</fullName>
        <label>Authorization End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_SLOT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Authorization Slot Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_SLOT_CONTRACT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Slot Contract ID</label>
        <referenceTo>T_SLOT_CONTRACT__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_SCH__c.object
<CustomObject>
    <fields>
        <fullName>CDE_RATE_TYPE__c</fullName>
        <description>Rate Type</description>
        <label>Rate Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00751</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_AGRMT_FISCAL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement</description>
        <label>Fiscal Agreement</label>
        <referenceTo>T_PROVR_FISCAL_AGREMENT__c</referenceTo>
        <relationshipLabel>Rate Schedules</relationshipLabel>
        <relationshipName>Rate_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Schedules</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_AGRMT__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_AGRMT__c</fullName>
        <description>Renewal Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SLOT_CONTRACT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_CARE_LEVEL__c</fullName>
        <label>Care Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_CARE_UNIT__c</fullName>
        <label>Care Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_PRG_TYPE__c</fullName>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_RATE_TYPE__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rate_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CNT_DAYS_OF_MONTH__c</fullName>
        <label># of days per month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CNT_DAYS_OF_WEEK__c</fullName>
        <label>Days of Week</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_SLOT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Slot Contract Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_SLOT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Slot Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_ADDENDUM__c</fullName>
        <label>Slot Contract Addendum</label>
        <referenceTo>T_SLOT_CONTRACT_ADDENDUM__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IDN_AUTH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Authorization ID</label>
        <referenceTo>T_AUTH__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVIDER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_AVAILABLE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available for Use</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IND_FUTURE_VACANT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Future Dated Vacant?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IND_OCCUPIED__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Occupied?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLOT_CONTRACT_DESCRIPTION__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Slot Contract Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Slot Contract</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slot Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/Care_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>0-6 Months</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>06-12 Months</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>12-18 Months</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>18-24 Months</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>24-30 Months</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>30-36 Months</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>36 - School Age</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>School Age</label>
    </customValue>
    <masterLabel>Care Level</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/Care_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>PT</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>FT</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>FTPT</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>FTFT</label>
    </customValue>
    <masterLabel>Care Unit</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/Program_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>LI</fullName>
        <label>Low Income Child Care</label>
    </customValue>
    <customValue>
        <fullName>TF</fullName>
        <label>TANF</label>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
        <label>Child Welfare Child Care</label>
    </customValue>
    <masterLabel>Program Type</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/Rate_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Regular</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Before School</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>After School</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>B and A School</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>Overnight</label>
    </customValue>
    <customValue>
        <fullName>37</fullName>
        <label>Weekend</label>
    </customValue>
    <customValue>
        <fullName>43</fullName>
        <label>Evening</label>
    </customValue>
    <customValue>
        <fullName>55</fullName>
        <label>Disability</label>
    </customValue>
    <customValue>
        <fullName>91</fullName>
        <label>Out-of-County</label>
    </customValue>
    <masterLabel>Rate Type</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/EditSlotContractFlowApxCtrl.cls
/*
Author : Pooja Pramod Aher
Description : Class for Creation of Edit slot contract functionality.
Test Class : EditSlotContractFlowApxCtrlTest.apxc
*/
public with sharing class EditSlotContractFlowApxCtrl {
    
    //method to get initial details
    @AuraEnabled
    public static LightningServerResponse getInitData(string recordid)
    {
        Map<String, Object> objectData = new map<String, Object>();    
        Boolean isSuccessful;
        String message;  
        
        T_SLOT_CONTRACT__c slotData=[select id,CDE_COUNTY__c,CDE_COUNTY__r.name,IDN_PROVIDER__c,
                                     IDN_ADDENDUM__c,CDE_CARE_LEVEL__c,CDE_RATE_TYPE__c,CDE_CARE_UNIT__c,
                                     IDN_AUTH__c,CNT_DAYS_OF_MONTH__c,DTE_END_SLOT__c,DTE_BEGIN_SLOT__c,
                                     IND_AVAILABLE__c,CNT_DAYS_OF_WEEK__c,CDE_PRG_TYPE__c,SLOT_CONTRACT_DESCRIPTION__c from T_SLOT_CONTRACT__c where id=:recordid];
        LightningServerResponse resp=SlotContractFlowApxCtrl.getInitData(slotData.IDN_PROVIDER__c);
        List<string> weekval=slotData.CNT_DAYS_OF_WEEK__c.split(';');
        
        SlotContractFlowApxCtrl.SlotWrapper slotRec=new SlotContractFlowApxCtrl.SlotWrapper();
        slotRec.beginDate = slotData.DTE_BEGIN_SLOT__c;
        slotRec.countyVal = slotData.CDE_COUNTY__c;
        slotRec.provdId = slotData.IDN_PROVIDER__c;
        
        String slot=JSON.serialize(slotRec);
        LightningServerResponse resp1=getRateTypeByBegin(slot);
        resp.objectData.put('newRate',  resp1.objectData.get('rtype'));
        resp.objectData.put('weekval', weekval);
        resp.objectData.put('slotData', slotData);
        
        List<Profile> PROFILE = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
        String MyProflieName = PROFILE[0].Name;
        //Replaced using custom permission CCCAP-14993
        if(FeatureManagement.checkPermission('Eligibility_Worker') || FeatureManagement.checkPermission('Eligibility_Worker_Supervisor') || FeatureManagement.checkPermission('Fiscal_Worker') || FeatureManagement.checkPermission('Fiscal_Worker_Supervisor') || FeatureManagement.checkPermission('Read_Only_User'))
        {
            resp.objectData.put('profileCheck', false);
            resp.objectData.put('profileName', MyProflieName);
        }
        
        return resp;
    }
    @AuraEnabled
    public static LightningServerResponse getRateTypeByBegin(string recordData)
    {
        Map<String, Object> objectData = new map<String, Object>(); 
        Map<string,string> fValues=new Map<string,string>();
        Boolean isSuccessful;
        String message;  
        Set<string> pValues=new Set<string>();
        SlotContractFlowApxCtrl.SlotWrapper slotRec=(SlotContractFlowApxCtrl.SlotWrapper)System.JSON.deserialize(recordData,SlotContractFlowApxCtrl.SlotWrapper.class); 
        List<T_PROVR_FISCAL_AGREMENT__c> fas=[SELECT Id ,DTE_BEGIN_AGRMT__c,DTE_END_AGRMT__c,CDE_COUNTY__c,ID_SERVICE__c
                                              ,(select id,DTE_BEGIN_EFFV__c,DTE_END_EFFV__c,toLabel(CDE_RATE_TYPE__c) from Rate_Schedules__r )
                                              from T_PROVR_FISCAL_AGREMENT__c where CDE_TYPE_STATUS__c !='CLS' and CDE_COUNTY__c= :slotRec.countyVal  and ID_SERVICE__c=: slotRec.provdId];
        
        if(fas!=null && !fas.isEmpty())
        {
            for(T_PROVR_FISCAL_AGREMENT__c indiObj : fas)
            {
                if(slotRec.beginDate >=indiObj.DTE_BEGIN_AGRMT__c)
                {
                    if(indiObj.Rate_Schedules__r!=null && !indiObj.Rate_Schedules__r.isEmpty())
                    {
                        for(T_FISCAL_SCH__c rSched : indiObj.Rate_Schedules__r)
                        {
                            if(slotRec.beginDate >=rSched.DTE_BEGIN_EFFV__c && (rSched.DTE_END_EFFV__c==null || (slotRec.beginDate<=rSched.DTE_END_EFFV__c )))
                            {
                                List<string> tmpStrings=rSched.CDE_RATE_TYPE__c.split(';');
                                for(String indiS : tmpStrings)
                                {
                                    pValues.add(indiS);            
                                }
                                Schema.SObjectType objType = Schema.getGlobalDescribe().get('T_SLOT_CONTRACT__c');
                                Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
                                Schema.DescribeFieldResult objFieldInfo = objDescribe.fields.getMap().get('CDE_RATE_TYPE__c').getDescribe();
                                List<Schema.PicklistEntry> picklistvalues = objFieldInfo.getPicklistValues();
                                
                                //Add the picklist values to list.
                                for(Schema.PicklistEntry plv: picklistvalues) {
                                    if(pValues.contains(plv.getLabel()))
                                    {
                                        fValues.put(plv.getLabel(),plv.getValue());
                                    }
                                }
                                break;
                            }
                        }
                        break;
                    }
                }
            }
        }
        //system.debug('fValues '+fValues);
        objectData.put('rtype', fValues);
        isSuccessful = true;
        message='success';
        return new LightningServerResponse(isSuccessful,message,objectData);
        
    }
    //this method will be called on save click
    @AuraEnabled
    public static LightningServerResponse updateData(string recordData,string recordid,boolean occCheck)
    {
        Map<String, Object> objectData = new map<String, Object>();    
        Boolean isSuccessful;
        String message;  
        id authidtoremove;
        boolean removeAuth=false;
        id eId;
        try{
            SlotContractFlowApxCtrl.SlotWrapper slotRec=(SlotContractFlowApxCtrl.SlotWrapper)System.JSON.deserialize(recordData,SlotContractFlowApxCtrl.SlotWrapper.class); 
            
            T_SLOT_CONTRACT__c scObToUpdate=[select id,CDE_COUNTY__c,CDE_COUNTY__r.name,IDN_PROVIDER__c,IDN_ADDENDUM__c,
                                             CDE_CARE_LEVEL__c,CDE_RATE_TYPE__c,CDE_CARE_UNIT__c,IDN_AUTH__c,CNT_DAYS_OF_MONTH__c,
                                             DTE_END_SLOT__c,DTE_BEGIN_SLOT__c,IND_AVAILABLE__c,CNT_DAYS_OF_WEEK__c,CDE_PRG_TYPE__c,
                                             SLOT_CONTRACT_DESCRIPTION__c from T_SLOT_CONTRACT__c where id=:recordid];
            Boolean andInToday=false;
            eId=scObToUpdate.id;
            if(string.isnotblank(scObToUpdate.IDN_AUTH__c) && (string.isBlank(slotRec.authVal) ||  scObToUpdate.IDN_AUTH__c!=slotRec.authVal) )
            {
                authidtoremove=scObToUpdate.IDN_AUTH__c;
                removeAuth=true;
            }
            if(slotRec.beginDate >= system.today()-9  && slotRec.beginDate <= system.today())
            {
                andInToday=true;
            }
            
            //|| andInToday 
            
            if(occCheck==true)
            {
                scObToUpdate.IDN_AUTH__c=null;  
                scObToUpdate.DTE_END_SLOT__c=slotRec.beginDate-1;
                
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                
                T_SLOT_CONTRACT__c scObToInsert2=getSlotRecord(slotRec,scObToUpdate);
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert2},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert2;
                
                T_AUTH__c auth=[select id ,DTE_BEGIN_SLOT__c,DTE_BEGIN_EFFV_AUTH__c, DTE_END_EFFV_AUTH__c,IDN_SLOT_CONTRACT__r.DTE_END_SLOT__c, IDN_SLOT_CONTRACT__c from T_AUTH__c where id=:slotRec.authVal];
                
                auth.IDN_SLOT_CONTRACT__c=scObToInsert2.id;
                auth.DTE_BEGIN_SLOT__c = scObToInsert2.DTE_BEGIN_SLOT__c;
                GenericDMLHandler.updateRecords(new List<T_AUTH__c>{auth},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update auth;
                isSuccessful = true;
                message ='success';
                
                
            }
            else if(scObToUpdate.DTE_BEGIN_SLOT__c==slotRec.beginDate && ( scObToUpdate.IDN_AUTH__c==slotRec.authVal ||  string.isBlank(slotRec.authVal)))
            {
                // scObToUpdate.DTE_BEGIN_SLOT__c=slotRec.beginDate;
                scObToUpdate.CNT_DAYS_OF_MONTH__c=slotRec.noDays;
                if(string.isNotBlank(scObToUpdate.IDN_AUTH__c) &&string.isBlank(slotRec.authVal) )
                {
                    scObToUpdate.IDN_AUTH__c=null;  
                }
                String finWeek;
                for(String indiS : slotRec.weekData)
                {        
                    if(string.isBlank(finWeek))
                    {
                        finWeek=indiS+';';
                    }else
                    {
                        finWeek=finWeek+indiS+';';
                    }
                    
                }
                //system.debug('finWeek '+finWeek);
                
                scObToUpdate.CNT_DAYS_OF_WEEK__c=finWeek;
                scObToUpdate.CDE_CARE_LEVEL__c=slotRec.clevelVal;
                scObToUpdate.CDE_RATE_TYPE__c=slotRec.rtypeVal;
                
                //scObToUpdate.IND_AVAILABLE__c=slotRec.avaVal;
                scObToUpdate.CDE_PRG_TYPE__c=slotRec.progTyp;
                scObToUpdate.CDE_CARE_UNIT__c=slotRec.cunitVal;   
                
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                isSuccessful = true;
                message ='success';
                
                
            }
            else if(scObToUpdate.DTE_BEGIN_SLOT__c!=slotRec.beginDate  && (scObToUpdate.IDN_AUTH__c==slotRec.authVal || string.isBlank(slotRec.authVal) ))
            {
                T_SLOT_CONTRACT__c scObToInsert=getSlotRecord(slotRec,scObToUpdate);
                scObToUpdate.DTE_END_SLOT__c = slotRec.beginDate -1;
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert;
                
                isSuccessful = true;
                message ='success';
            }
            else{ //create new record in any case
                
                /* if(scObToUpdate.DTE_BEGIN_SLOT__c!=slotRec.beginDate  && scObToUpdate.IDN_AUTH__c==slotRec.authVal)
{
T_SLOT_CONTRACT__c scObToInsert=getSlotRecord(slotRec,scObToUpdate);
scObToUpdate.DTE_END_SLOT__c = slotRec.beginDate -1;

update scObToUpdate;

insert scObToInsert;

isSuccessful = true;
message ='success';

}else{*/
                string authMsg ;
                authMsg = checkForAuthorization(slotRec);
                if(authMsg !='true')
                {
                    if(authMsg =='authFalse')
                    { 
                        isSuccessful=false;
                        message='Record creation failed. Authorization End Date is less than Slot Contract Begin Date';
                        objectData.put('authDate',false);
                        
                    }else if(authMsg =='slotBeFalse')
                    {
                        isSuccessful=false;
                        message='User County not matching with selected county';
                        objectData.put('slotBeFalse',false);
                    }else if(authMsg =='authPrFalse'){
                        isSuccessful=false;
                        message='User County not matching with selected county';
                        objectData.put('authPrFalse',false);
                    }else if(authMsg =='existSlot'){
                        isSuccessful=false;
                        message='User County not matching with selected county';
                        objectData.put('existSlot',false);
                    }else{
                        isSuccessful=false;
                        message='User County not matching with selected county';
                        objectData.put('authCounty',false);
                    }
                    
                }else{
                    Boolean issucces =  updateRecordAndAuth(slotRec,scObToUpdate,andInToday);
                    if(issucces)
                    {
                        isSuccessful=true;
                        message='Success';
                        objectData.put('updateError',true);
                    }
                    else{
                        isSuccessful=false;
                        message='Error occurred !';
                        objectData.put('updateError',false);
                    }
                }
                
                // }
            }
            
            
        }catch(Exception e){
            isSuccessful = false;
            message = e.getMessage();
            objectData.put('updateError',false);
            system.debug('exception '+ e.getMessage()+' ggg '+e.getLineNumber());
        }
        
        if(isSuccessful && removeAuth)
        {
            T_AUTH__c auth=[select id ,DTE_BEGIN_SLOT__c,DTE_BEGIN_EFFV_AUTH__c, DTE_END_EFFV_AUTH__c,IDN_SLOT_CONTRACT__r.DTE_END_SLOT__c, IDN_SLOT_CONTRACT__c from T_AUTH__c where id=:authidtoremove];
            if(auth.IDN_SLOT_CONTRACT__c==eId)
            {
                auth.IDN_SLOT_CONTRACT__c=null;
                auth.DTE_BEGIN_SLOT__c = null;
            }
            GenericDMLHandler.updateRecords(new List<T_AUTH__c>{auth},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
            //update auth;
        }
        return new LightningServerResponse(isSuccessful,message,objectData);
    }    
    public static boolean updateRecordAndAuth(SlotContractFlowApxCtrl.SlotWrapper slotRec,T_SLOT_CONTRACT__c scObToUpdate,boolean andInToday)
    {
        Boolean isSuccess;
        
        T_AUTH__c auth=[select id ,DTE_BEGIN_SLOT__c,DTE_BEGIN_EFFV_AUTH__c, DTE_END_EFFV_AUTH__c,IDN_SLOT_CONTRACT__r.DTE_END_SLOT__c, IDN_SLOT_CONTRACT__c from T_AUTH__c where id=:slotRec.authVal];
        
        // T_SLOT_CONTRACT__c sc=[select id , DTE_BEGIN_SLOT__c,DTE_END_SLOT__c,Name,SLOT_CONTRACT_DESCRIPTION__c,IDN_AUTH__c,IND_AVAILABLE__c,IND_FUTURE_VACANT__c,IND_OCCUPIED__c from T_SLOT_CONTRACT__c where id=:earlObj.id];
        Id finSCId;
        Date finDate;
        id sobjectid=scObToUpdate.id;
        
        if(slotRec.beginDate==scObToUpdate.DTE_BEGIN_SLOT__c )
        {
            if(slotRec.beginDate >=auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate <= auth.DTE_END_EFFV_AUTH__c  )
            {
                scObToUpdate =getSlotRecord(slotRec,scObToUpdate);
                scObToUpdate.IDN_AUTH__c = auth.Id;
                scObToUpdate.id=sobjectid;
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                
                finSCId=scObToUpdate.Id;
                finDate=scObToUpdate.DTE_BEGIN_SLOT__c;
                isSuccess=true;
            }else if(slotRec.beginDate >= auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate > auth.DTE_END_EFFV_AUTH__c)
            {
                scObToUpdate =getSlotRecord(slotRec,scObToUpdate);
                scObToUpdate.IDN_AUTH__c = auth.Id;
                scObToUpdate.DTE_END_SLOT__c = auth.DTE_END_EFFV_AUTH__c;
                scObToUpdate.id=sobjectid;
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                
                finSCId=scObToUpdate.Id;
                finDate=scObToUpdate.DTE_BEGIN_SLOT__c;
                
                T_SLOT_CONTRACT__c scObToInsert2=getSlotRecord(slotRec,scObToUpdate);
                scObToInsert2.DTE_BEGIN_SLOT__c = auth.DTE_END_EFFV_AUTH__c+1;
                scObToInsert2.IDN_AUTH__c=null;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert2},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert2;
                isSuccess=true;
            }else if(slotRec.beginDate < auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate > auth.DTE_END_EFFV_AUTH__c)
            {
                scObToUpdate =getSlotRecord(slotRec,scObToUpdate);
                scObToUpdate.IDN_AUTH__c=null;
                scObToUpdate.DTE_END_SLOT__c=auth.DTE_BEGIN_EFFV_AUTH__c-1;
                scObToUpdate.id=sobjectid;
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                
                T_SLOT_CONTRACT__c scObToInsert2=getSlotRecord(slotRec,scObToUpdate);
                scObToInsert2.DTE_BEGIN_SLOT__c =auth.DTE_BEGIN_EFFV_AUTH__c;
                scObToInsert2.IDN_AUTH__c=auth.Id;
                scObToInsert2.DTE_END_SLOT__c=auth.DTE_END_EFFV_AUTH__c;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert2},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert2;   
                
                T_SLOT_CONTRACT__c vcsobject=getSlotRecord(slotRec,scObToUpdate);
                vcsobject.DTE_BEGIN_SLOT__c =auth.DTE_END_EFFV_AUTH__c+1;
                vcsobject.IDN_AUTH__c=null;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{vcsobject},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert vcsobject;
                
                finSCId=scObToInsert2.Id;
                finDate=scObToInsert2.DTE_BEGIN_SLOT__c;
                isSuccess=true;
            }else if(slotRec.beginDate < auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate <= auth.DTE_END_EFFV_AUTH__c)
            { 
                scObToUpdate =getSlotRecord(slotRec,scObToUpdate);
                scObToUpdate.IDN_AUTH__c=null;
                scObToUpdate.DTE_END_SLOT__c=auth.DTE_BEGIN_EFFV_AUTH__c-1;
                scObToUpdate.id=sobjectid;
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                
                T_SLOT_CONTRACT__c scObToInsert2=getSlotRecord(slotRec,scObToUpdate);
                scObToInsert2.IDN_AUTH__c=auth.id;
                scObToInsert2.DTE_BEGIN_SLOT__c=auth.DTE_BEGIN_EFFV_AUTH__c;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert2},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert2;
                finSCId=scObToInsert2.Id;
                finDate=scObToInsert2.DTE_BEGIN_SLOT__c;
                isSuccess=true;
            }
            
        }else{
            if(slotRec.beginDate >=auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate <= auth.DTE_END_EFFV_AUTH__c  )
            {
                
                scObToUpdate.DTE_END_SLOT__c = slotRec.beginDate -1;
                scObToUpdate.id=sobjectid;
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                
                T_SLOT_CONTRACT__c scObToInsert=getSlotRecord(slotRec,scObToUpdate);
                scObToInsert.IDN_AUTH__c=auth.Id;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert;
                
                finSCId=scObToInsert.Id;
                finDate=scObToInsert.DTE_BEGIN_SLOT__c;
                isSuccess=true;
            }else if(slotRec.beginDate >= auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate > auth.DTE_END_EFFV_AUTH__c)
            {
                scObToUpdate.DTE_END_SLOT__c = slotRec.beginDate -1;
                scObToUpdate.id=sobjectid;
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                T_SLOT_CONTRACT__c scObToInsert=getSlotRecord(slotRec,scObToUpdate);
                
                scObToInsert.IDN_AUTH__c=auth.Id;
                scObToInsert.DTE_END_SLOT__c = auth.DTE_END_EFFV_AUTH__c;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert;
                
                finSCId=scObToInsert.Id;
                finDate=scObToInsert.DTE_BEGIN_SLOT__c;
                
                T_SLOT_CONTRACT__c scObToInsert2=getSlotRecord(slotRec,scObToUpdate);
                scObToInsert2.DTE_BEGIN_SLOT__c = auth.DTE_END_EFFV_AUTH__c+1;
                scObToInsert2.IDN_AUTH__c=null;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert2},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert2;
                isSuccess=true;
            }else if(slotRec.beginDate < auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate > auth.DTE_END_EFFV_AUTH__c)
            {
                scObToUpdate.DTE_END_SLOT__c = slotRec.beginDate -1;
                scObToUpdate.id=sobjectid;
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                
                T_SLOT_CONTRACT__c scObToInsert=getSlotRecord(slotRec,scObToUpdate);
                scObToInsert.IDN_AUTH__c=null;
                scObToInsert.DTE_END_SLOT__c=auth.DTE_BEGIN_EFFV_AUTH__c-1;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert;
                
                T_SLOT_CONTRACT__c scObToInsert2=getSlotRecord(slotRec,scObToUpdate);
                scObToInsert2.DTE_BEGIN_SLOT__c =auth.DTE_BEGIN_EFFV_AUTH__c;
                scObToInsert2.IDN_AUTH__c=auth.Id;
                scObToInsert2.DTE_END_SLOT__c=auth.DTE_END_EFFV_AUTH__c;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert2},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert2;   
                
                T_SLOT_CONTRACT__c vcsobject=getSlotRecord(slotRec,scObToUpdate);
                vcsobject.DTE_BEGIN_SLOT__c =auth.DTE_END_EFFV_AUTH__c+1;
                vcsobject.IDN_AUTH__c=null;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{vcsobject},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert vcsobject;
                
                finSCId=scObToInsert2.Id;
                finDate=scObToInsert2.DTE_BEGIN_SLOT__c;
                isSuccess=true;
            }else if(slotRec.beginDate < auth.DTE_BEGIN_EFFV_AUTH__c && slotRec.endDate <= auth.DTE_END_EFFV_AUTH__c)
            {
                scObToUpdate.DTE_END_SLOT__c = slotRec.beginDate -1;
                scObToUpdate.id=sobjectid;
                GenericDMLHandler.updateRecords(new List<T_SLOT_CONTRACT__c>{scObToUpdate},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
                //update scObToUpdate;
                
                T_SLOT_CONTRACT__c scObToInsert=getSlotRecord(slotRec,scObToUpdate);
                scObToInsert.IDN_AUTH__c=null;
                scObToInsert.DTE_END_SLOT__c=auth.DTE_BEGIN_EFFV_AUTH__c-1;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert;
                
                T_SLOT_CONTRACT__c scObToInsert2=getSlotRecord(slotRec,scObToUpdate);
                scObToInsert2.IDN_AUTH__c=auth.id;
                scObToInsert2.DTE_BEGIN_SLOT__c=auth.DTE_BEGIN_EFFV_AUTH__c;
                GenericDMLHandler.insertRecords(new List<T_SLOT_CONTRACT__c>{scObToInsert2},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'});
                //insert scObToInsert2;
                finSCId=scObToInsert2.Id;
                finDate=scObToInsert2.DTE_BEGIN_SLOT__c;
                isSuccess=true;
            }
        }
        
        auth.DTE_BEGIN_SLOT__c=finDate;
        auth.IDN_SLOT_CONTRACT__c =finSCId;
        GenericDMLHandler.updateRecords(new List<T_AUTH__c>{auth},new Map<String,Object>{'Method__c'=>'updateData','Class__c'=>'EditSlotContractFlowApxCtrl'}); 
        //update auth;
        return isSuccess;
    }
    //method to check if auth is present and if auth date is less
    public static string checkForAuthorization(SlotContractFlowApxCtrl.SlotWrapper slotRec)
    {    
        String finResult='true';
        if(string.isNotBlank(slotRec.authVal)){
            T_AUTH__c auth=[select id,DTE_BEGIN_EFFV_AUTH__c,DTE_END_EFFV_AUTH__c,CDE_COUNTY__c,IDN_PROVR__c,IDN_SLOT_CONTRACT__c from T_AUTH__c where id=:slotRec.authVal];
            if(slotRec.countyVal == auth.CDE_COUNTY__c){
                if(slotRec.provdId == auth.IDN_PROVR__c){
                    if(auth.DTE_END_EFFV_AUTH__c<slotRec.beginDate ){
                        finResult='authFalse';
                    }
                    if(auth.DTE_BEGIN_EFFV_AUTH__c > slotRec.endDate){
                        finResult = 'slotBeFalse';
                    }
                    if(finResult=='true'){
                        /*if(string.isNotBlank(auth.IDN_SLOT_CONTRACT__c)){
                            List<T_SLOT_CONTRACT__c> allSlots = [select id, name,SLOT_CONTRACT_DESCRIPTION__c, DTE_BEGIN_SLOT__c,DTE_END_SLOT__c  from T_SLOT_CONTRACT__c where id=:auth.IDN_SLOT_CONTRACT__c];
							if(allSlots.size()>1)
                            {
                                for(T_SLOT_CONTRACT__c indiSlot : allSlots)
                                {
                                    if(slotRec.beginDate>=indiSlot.DTE_BEGIN_SLOT__c && slotRec.beginDate<=indiSlot.DTE_END_SLOT__c && slotRec.endDate>=indiSlot.DTE_BEGIN_SLOT__c && slotRec.endDate<=indiSlot.DTE_END_SLOT__c )
                                    {
                                        finResult='existSlot';
                                    }
                                }
                            }
                        }*/
                        date beginDate;
                        Integer betDays = slotRec.beginDate.daysBetween(slotRec.endDate);
                        List<T_SLOT_CONTRACT__c> allSlots = [select id, NAME, SLOT_CONTRACT_DESCRIPTION__c, DTE_BEGIN_SLOT__c, DTE_END_SLOT__c FROM T_SLOT_CONTRACT__c WHERE IDN_AUTH__c =:auth.Id];
                        for(T_SLOT_CONTRACT__c indiSlot : allSlots){
                            beginDate=slotRec.beginDate;
                            for(integer i=0;i<=betDays;i++)
							{
                                 if(beginDate>= indiSlot.DTE_BEGIN_SLOT__c && beginDate<= indiSlot.DTE_END_SLOT__c)
                                 {
                                	finResult='existSlot';
                            	}
                                beginDate=beginDate+1;
                            }
                           
                        }
                        
                    }
                }
                else{
                    finResult='authPrFalse';
                }
            }else{
                finResult='countyFalse';
            }
                         
        }
        
        return finResult;
    }
    
    public static T_SLOT_CONTRACT__c getSlotRecord(SlotContractFlowApxCtrl.SlotWrapper slotRec,T_SLOT_CONTRACT__c earlObj){
        
        T_SLOT_CONTRACT__c scObToInsert =new T_SLOT_CONTRACT__c();
        scObToInsert.SLOT_CONTRACT_DESCRIPTION__c =slotRec.scdesc;
        scObToInsert.IDN_ADDENDUM__c=earlObj.IDN_ADDENDUM__c;
        scObToInsert.IDN_PROVIDER__c=slotRec.provdId;
        scObToInsert.CDE_COUNTY__c=earlObj.CDE_COUNTY__c;
        scObToInsert.DTE_BEGIN_SLOT__c=slotRec.beginDate;
        scObToInsert.DTE_END_SLOT__c=slotRec.endDate;
        scObToInsert.CNT_DAYS_OF_MONTH__c=slotRec.noDays;
        
        String finWeek;
        for(String indiS : slotRec.weekData)
        {        
            if(string.isBlank(finWeek))
            {
                finWeek=indiS+';';
            }else
            {
                finWeek=finWeek+indiS+';';
            }            
        }
        //system.debug('finWeek '+finWeek);
        
        scObToInsert.CNT_DAYS_OF_WEEK__c=finWeek;
        scObToInsert.CDE_CARE_LEVEL__c=slotRec.clevelVal;
        scObToInsert.CDE_RATE_TYPE__c=slotRec.rtypeVal;
        scObToInsert.IDN_AUTH__c=slotRec.authVal;
        scObToInsert.IND_AVAILABLE__c=slotRec.avaVal;
        scObToInsert.CDE_PRG_TYPE__c=slotRec.progTyp;
        scObToInsert.CDE_CARE_UNIT__c=slotRec.cunitVal;        
        return scObToInsert;
    }
}