CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>T_AUTH</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <formula>IDN_PROVR__r.NAM_FACILITY__c</formula>
        <label>Provider Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_SLOT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Authorization Slot Begin Date</label>
        <type>Date</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_STATUS_PROVR__c</fullName>
        <label>License Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00692</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_PROVR__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00691</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Provider Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Slot_Contract_Suggestion__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Slot Contract Suggestion</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>CDE_REQ_BGC_CHK_STATE__c</fullName>
        <inlineHelpText>For Qualified Exempt Provider Only: This indicates the provider's State required background check status</inlineHelpText>
        <label>Required Background Check Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00865</valueSetName>
        </valueSet>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_AGRMT__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_RCV_AGRMT_FISCAL__c</fullName>
        <description>Date Received</description>
        <label>Date Fiscal Agreement Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finalized</fullName>
        <active>true</active>
        <label>Finalized</label>
    </recordTypes>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SLOT_CONTRACT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_SLOT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Slot Contract Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_SLOT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Slot Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_ADDENDUM__c</fullName>
        <label>Slot Contract Addendum</label>
        <referenceTo>T_SLOT_CONTRACT_ADDENDUM__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IDN_AUTH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Authorization ID</label>
        <referenceTo>T_AUTH__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVIDER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_AVAILABLE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available for Use</label>
        <type>Checkbox</type>
    </fields>
    <label>Slot Contract</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slot Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SLOT_CONTRACT_ADDENDUM__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Slot Contract Addendums</relationshipLabel>
        <relationshipName>Slot_Contract_Addendums</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Slot Contract Addendum</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slot Contract Addendums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Owner_County__c</fullName>
        <label>Owner County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00005</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00692.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>R00692</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00865.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Not Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <description>Background Check Status Values</description>
    <masterLabel>R00865</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/ProviderServicesTest.cls
@isTest
public class ProviderServicesTest {
    
    @testSetup
    static void testDataSetup()
    {
        Profile userProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User fromUser = TestClassUtility.createUserWithPS(userProfile.Id, 'System_Administrator_PS', 'test1', 'test1', 'test1@example.com', 'test1@example.com.' + string.valueof(math.random() * 3), 'ttes1');
        if (fromUser != null) {
            fromUser.Owner_County__c = '1';
            update fromUser;
        }

        System.runAs(fromUser) {
            T_CHATS_PROVR_STATUS__c provrObj = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'abc', CDE_STATUS_PROVR__c = 'Open', CDE_TYPE_PROVR__c = 'PRS', Slot_Contract_Suggestion__c = 'test~BREAK~test:vlaue', TXT_CHATS_RATING__c = '0');
            insert provrObj;
            T_COUNTY__c county = TestClassUtility.createCounty('Test Name', 'Department', 2, true);
            T_AUTH__c authorization = TestClassUtility.createAuthorization(true, System.today().addDays(20), System.today().addDays(25), county.Id, provrObj.Id);

            T_SLOT_CONTRACT_ADDENDUM__c scAdd = new T_SLOT_CONTRACT_ADDENDUM__c();
            	scAdd.CDE_COUNTY__c = county.Id;
            Insert scAdd;
            T_SLOT_CONTRACT__c sc = new T_SLOT_CONTRACT__c();
                sc.IDN_AUTH__c = authorization.Id;
                sc.CDE_COUNTY__c = county.Id;
                sc.IDN_PROVIDER__c = provrObj.Id;
                sc.IDN_ADDENDUM__c = scAdd.Id;
                sc.DTE_END_SLOT__c = System.today().addDays(1);
                sc.DTE_BEGIN_SLOT__c = system.today();
                sc.IND_AVAILABLE__c = true;
            Insert sc;

            T_PROVR_FISCAL_AGREMENT__c fiscAgrRec = new T_PROVR_FISCAL_AGREMENT__c(ID_SERVICE__c = provrObj.Id, CDE_TYPE_STATUS__c = 'DFT');
            insert fiscAgrRec;

            Task task1 = TestClassUtility.createTask(false, 'T116 – Provider has made a suggestion for a Slot Contract record', 'Test Decription', 'Not started', authorization.Id, fromUser.Id);
        }
    }
    
    static testmethod void testProviderTrigger(){
        T_CHATS_PROVR_STATUS__c provrClosedUpd = new T_CHATS_PROVR_STATUS__c();
        T_CHATS_PROVR_STATUS__c provrQRISUpd = new T_CHATS_PROVR_STATUS__c();
        
        T_CHATS_PROVR_STATUS__c provrObj = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'abc', CDE_STATUS_PROVR__c = 'Open', TXT_CHATS_RATING__c = 'abcdef');
        T_CHATS_PROVR_STATUS__c provrObj1 = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'abcd', CDE_STATUS_PROVR__c = 'Open', TXT_CHATS_RATING__c = 'abcdef');
        T_CHATS_PROVR_STATUS__c provrObj2 = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'test', CDE_STATUS_PROVR__c = 'Open', TXT_CHATS_RATING__c = 'abcdef', CDE_TYPE_PROVR__c = 'EFACH', CDE_REQ_BGC_CHK_STATE__c = 'Cleared');
        T_COUNTY__c countyObj = new T_COUNTY__c (CDE_COUNTY__c = 3);
        T_COUNTY__c countyObj1 = new T_COUNTY__c (CDE_COUNTY__c = 4);
        GenericDMLHandler.insertRecords(new List<Sobject>{provrObj, provrObj1, provrObj2, countyObj, countyObj1}, null);
        
        Id recordTypeId = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Finalized').getRecordTypeId();
        Id recordTypeId2 = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Open').getRecordTypeId();
        T_PROVR_FISCAL_AGREMENT__c fiscAgrmntObj = new T_PROVR_FISCAL_AGREMENT__c (RecordTypeId = recordTypeId, CDE_TYPE_STATUS__c = 'FIN', ID_SERVICE__c = provrObj.Id, CDE_COUNTY__c = countyObj.Id, DTE_BEGIN_AGRMT__c = date.today(), DTE_RCV_AGRMT_FISCAL__c = date.today());
        T_PROVR_FISCAL_AGREMENT__c fiscAgrmntObj1 = new T_PROVR_FISCAL_AGREMENT__c (RecordTypeId = recordTypeId, CDE_TYPE_STATUS__c = 'FIN', ID_SERVICE__c = provrObj1.Id, CDE_COUNTY__c = countyObj.Id, DTE_BEGIN_AGRMT__c = date.today(), DTE_RCV_AGRMT_FISCAL__c = date.today());
        T_PROVR_FISCAL_AGREMENT__c fiscAgrmntObj2 = new T_PROVR_FISCAL_AGREMENT__c (RecordTypeId = recordTypeId2, CDE_TYPE_STATUS__c = 'OPN', ID_SERVICE__c = provrObj2.Id, CDE_COUNTY__c = countyObj1.Id, DTE_BEGIN_AGRMT__c = date.today(), DTE_RCV_AGRMT_FISCAL__c = date.today());
        GenericDMLHandler.insertRecords(new List<Sobject>{fiscAgrmntObj, fiscAgrmntObj1, fiscAgrmntObj2}, null);
        
        test.startTest();
        provrClosedUpd.Id = provrObj.Id;
        provrClosedUpd.CDE_STATUS_PROVR__c = 'Closed';
        Update provrClosedUpd;
        
        List<Task> clsdTask = [select OwnerId, Subject, WhatId FROM TASk WHERE OwnerId =:UserInfo.getUserId() AND WhatId =:fiscAgrmntObj.Id];
        if(clsdTask.size()>0){
            system.assertEquals('T200 - Provider License is Closed' , clsdTask.get(0).Subject,'Subject of the task should match'); 
            // CHATS_1_46_2_H
        }
        
        provrQRISUpd.Id = provrObj1.Id;
        provrQRISUpd.TXT_CHATS_RATING__c = 'xyz';
        Update provrQRISUpd;
        
        List<Task> qrisUpdtdTask = [select OwnerId, Subject, WhatId FROM TASk WHERE OwnerId =:UserInfo.getUserId() AND WhatId =:fiscAgrmntObj1.Id];
        if (qrisUpdtdTask.size()> 0){
            system.assertEquals('T205 - Provider Rating Changed To Quality Rating Tier xyz' , qrisUpdtdTask.get(0).Subject,'Subject of the task should match');
        }
        
        provrObj2.CDE_REQ_BGC_CHK_STATE__c = 'Not Cleared';
        Update provrObj2;
        ProviderServices.getUserAssignedCounties();
        test.stopTest();
    }
    
    static testmethod void setDefaultValue(){
        Test.startTest();
        T_CHATS_PROVR_STATUS__c provrObj = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'abc', CDE_STATUS_PROVR__c = 'Open', CDE_TYPE_PROVR__c = 'PRS');
        insert provrObj;
        Test.stopTest();
    }
    
    static testmethod void updateFacilityTypeonFiscalAgreements_Test(){
        
        /*T_CHATS_PROVR_STATUS__c provrObj = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'abc', CDE_STATUS_PROVR__c = 'Open', CDE_TYPE_PROVR__c = 'PRS', Slot_Contract_Suggestion__c = 'test~BREAK~test:vlaue');
        insert provrObj;
        T_COUNTY__c county= TestClassUtility.createCounty('Test Name','Department',2,true);
        T_AUTH__c authorization=TestClassUtility.createAuthorization(true,System.today().addDays(20),System.today().addDays(25),county.Id,provrObj.Id);
        
        T_SLOT_CONTRACT_ADDENDUM__c scAdd = new T_SLOT_CONTRACT_ADDENDUM__c();
        	scAdd.CDE_COUNTY__c = county.Id;
        Insert scAdd;
        T_SLOT_CONTRACT__c sc = new T_SLOT_CONTRACT__c();
            sc.IDN_AUTH__c = authorization.Id;
            sc.CDE_COUNTY__c = county.Id;
            sc.IDN_PROVIDER__c = provrObj.Id;
            sc.IDN_ADDENDUM__c = scAdd.Id;
            sc.DTE_END_SLOT__c = System.today().addDays(1);
            sc.DTE_BEGIN_SLOT__c = system.today();
            sc.IND_AVAILABLE__c = true;
        Insert sc;
        
        T_PROVR_FISCAL_AGREMENT__c fiscAgrRec = new T_PROVR_FISCAL_AGREMENT__c(ID_SERVICE__c = provrObj.Id, CDE_TYPE_STATUS__c = 'DFT');
        insert fiscAgrRec;*/
        
        List<T_CHATS_PROVR_STATUS__c> provrObj = [Select Id, Name,NAM_FACILITY__c,CDE_STATUS_PROVR__c,CDE_TYPE_PROVR__c,Slot_Contract_Suggestion__c from T_CHATS_PROVR_STATUS__c LIMIT 1];
        List<T_AUTH__c> authorization = [Select Id, Name from T_AUTH__c LIMIT 1];
        List<T_SLOT_CONTRACT__c> sc = [Select Id, name from T_SLOT_CONTRACT__c LIMIT 1];
        List<Task> taskValue = [Select Id from Task LIMIT 1];
        
        Test.startTest();
        
        provrObj[0].TXT_CHATS_RATING__c = '0';
        provrObj[0].CDE_TYPE_PROVR__c = 'CPD ';
        provrObj[0].Slot_Contract_Suggestion__c = 'Authorization:' + authorization[0].Name + '~BREAK~'+'SlotContract:'+sc[0].Name+'~BREAK~COMMENT:' + authorization[0].Id;
        system.debug('value of Slot_Contract_Suggestion__c is: ' + provrObj[0].Slot_Contract_Suggestion__c);
        update provrObj;
        
        T_CHATS_PROVR_STATUS__c provrObj1 = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'abc', CDE_STATUS_PROVR__c = 'Open', CDE_TYPE_PROVR__c = 'CPD');
        insert provrObj1;
		T_PROVR_FISCAL_AGREMENT__c fiscAgrRec1 = new T_PROVR_FISCAL_AGREMENT__c(ID_SERVICE__c = provrObj1.Id, CDE_TYPE_STATUS__c = '');
        insert fiscAgrRec1;
        provrObj1.CDE_TYPE_PROVR__c = '';
        update provrObj1;  
       
        Test.stopTest();
    }
}