CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>T_AUTH</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_AUTH__c</fullName>
        <description>Authorization Begin Date</description>
        <label>Authorization Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_AUTH__c</fullName>
        <label>Authorization End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <formula>IDN_PROVR__r.NAM_FACILITY__c</formula>
        <label>Provider Name</label>
        <type>Text</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Provider Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_PLAN__c.object
<CustomObject>
    <description>County Plans</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Plan</relationshipLabel>
        <relationshipName>County2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>Status</description>
        <label>Status(old)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00676</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flow_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flow Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>County Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Once the plan is in an Approved status, users should not be able to edit</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)),  TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_RATE__c.object
<CustomObject>
    <description>County Rate</description>
    <fields>
        <fullName>CDE_RATE_PLAN_TEMPLT__c</fullName>
        <description>County Rate Plan Template</description>
        <label>County Rate Plan Template</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_COUNTY_RATE_PLAN_TEMPLT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>Status</description>
        <label>Status(Old)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00676</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_RATE__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_RATE__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flow_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The field is marked true when all the fields are filled on the flow and record
            can be submitted for approval</description>
        <label>Flow Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IDN_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Rate Plan</relationshipLabel>
        <relationshipName>County4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_RATE_PLAN_TEMPLT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>County Rate Plan Template Indicator</description>
        <label>County Rate Plan Template Indicator</label>
        <type>Checkbox</type>
    </fields>

    <fields>
        <fullName>RATE_TYPE__c</fullName>
        <description>RATE_TYPE</description>
        <label>RATE_TYPE</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00751</valueSetName>
        </valueSet>
    </fields>
    <label>County Rate Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Rate Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Approved Plan cannot be updated</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)), TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Owner_County__c</fullName>
        <label>Owner County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00005</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00676.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PEN</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>SUB</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>APV</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>NRV</fullName>
        <label>Need Revision</label>
    </customValue>
    <description>R00676</description>
    <masterLabel>R00676</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/RT_COUNTY_RATE_PLAN_TEMPLT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>County Specific Template</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <isActive>false</isActive>
        <label>2</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <isActive>false</isActive>
        <label>4</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <isActive>false</isActive>
        <label>5</label>
    </customValue>
    <description>RT_COUNTY_RATE_PLAN_TEMPLT</description>
    <masterLabel>RT_COUNTY_RATE_PLAN_TEMPLT</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CountyDropInDaysBatchApxCtrl_Test.cls
@isTest(seeAllData=false)
public class CountyDropInDaysBatchApxCtrl_Test {
public static T_COUNTY_PLAN__c aCountyPlan=null;
    static final String CENTER='CEN';
    static final String FT = '3'; 
    static final String PT = '2'; 
    static final String FTPT = '4';
    static final String FTFT = '5'; 
    public static User user;
    public static final String COUNTY_RATE_PLAN_APPROVAL_PROCESS = 'County_Rate_Plan_Approval_Process';
    public static T_COUNTY__c aCounty;
    public static T_COUNTY_RATE__c aCountyRateForApprovalProcess;
    public static T_COUNTY_RATE__c aCountyRatePlan=null; 
    public static T_COUNTY_RATE__c aCountyRatePlan1=null; 
    public static T_COUNTY_RATE__c aCountyRatePlan2=null; 
    
    static void createTestData(){
        aCounty =TestClassUtility.createCounty('County','Dept',10,true);
        T_COUNTY__c county2 =TestClassUtility.createCounty('County2','Dept2',9,true);
        T_COUNTY__c county1 =TestClassUtility.createCounty('County11','Dept11',10,true);
        aCountyRatePlan=TestClassUtility.createCountyRatePlan('PEN',false);
        //aCounty=[Select Id from T_COUNTY__c Limit 1];
        aCountyRatePlan.CDE_RATE_PLAN_TEMPLT__c='1';
        aCountyRatePlan.IND_RATE_PLAN_TEMPLT__c=false;
        aCountyRatePlan.DTE_BEGIN_EFFV_RATE__c=System.today().addMonths(3).toStartOfMonth();
        aCountyRatePlan.IDN_COUNTY__c=county1.id;
        
        aCountyRatePlan1=TestClassUtility.createCountyRatePlan('PEN',false);
        aCountyRatePlan1.CDE_RATE_PLAN_TEMPLT__c='1';
        aCountyRatePlan1.IND_RATE_PLAN_TEMPLT__c=true;
        aCountyRatePlan1.DTE_BEGIN_EFFV_RATE__c=System.today().addMonths(4).toStartOfMonth();
        aCountyRatePlan1.IDN_COUNTY__c=county2.id;
        
        
        aCountyRateForApprovalProcess = TestClassUtility.createCountyRatePlan('PEN',false);
        aCountyRateForApprovalProcess.IDN_COUNTY__c = aCounty.Id;
        aCountyRateForApprovalProcess.CDE_RATE_PLAN_TEMPLT__c = '1';
        aCountyRateForApprovalProcess.IND_RATE_PLAN_TEMPLT__c=false;
        aCountyRateForApprovalProcess.DTE_BEGIN_EFFV_RATE__c=System.today().addMonths(2).toStartOfMonth();
        aCountyRateForApprovalProcess.Flow_Completed__c=true;
        
        if(aCountyRateForApprovalProcess!=null){
            insert aCountyRateForApprovalProcess;
        }
            T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(NAM_FACILITY__c = 'Provider Test', TXT_CHATS_RATING__c ='Level 1');
        insert provider;
        T_AUTH__c acc = new T_AUTH__c();
            acc.DTE_END_EFFV_AUTH__c = system.today();
            acc.DTE_BEGIN_EFFV_AUTH__c = System.today();
            acc.IDN_PROVR__c = provider.Id;
        acc.CDE_COUNTY__c = county1.Id;
        insert acc;
        
        Profile userProfile=[Select id from Profile where Name ='System Administrator'];
        user = TestClassUtility.createUser(userProfile.Id , 'test','test','test@example.com','test@example.com.uesername','ttes');
        
        if(user!=null){
            List<User> users = [SELECT Owner_County__c FROM User WHERE id = :UserInfo.getUserId()];
            if(!users.isEmpty()){
                user.Owner_County__c  = users.get(0).Owner_County__c;
            }
            insert user; 
        }
    }

    static testmethod void testCountyRatePlanTrigger(){
        Boolean expectedExceptionThrown;
        createTestData();
        
        Test.startTest();
        //try{
            insert aCountyRatePlan;
      /*  user u =[Select id from User where UserName='newuserchats@testorg.com'];
        system.runAs(u){
            insert aCountyRatePlan1;}*/
        /*}catch(Exception e){
            expectedExceptionThrown =  e.getMessage().contains('You can not add multiple draft version of County Rate Plan') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }*/
        aCountyRatePlan.RATE_TYPE__c = '13';
        update aCountyRatePlan;
        aCountyRatePlan.RATE_TYPE__c ='1';
        update aCountyRatePlan;
        //insert aCountyRatePlan1;
        aCountyRatePlan.CDE_STATUS__c = CountyRatePlanServices.APPROVED;
        aCountyRatePlan.DTE_BEGIN_EFFV_RATE__c = system.today();
        aCountyRatePlan.DTE_END_EFFV_RATE__c = system.today().addDays(10);
        aCountyRatePlan.IND_RATE_PLAN_TEMPLT__c = false;
        
            
        try{
            update aCountyRatePlan;
            CountyDropInDaysBatchApxCtrl obj = new CountyDropInDaysBatchApxCtrl();
            DataBase.executeBatch(obj); 
        }
        catch(Exception e){
           // expectedExceptionThrown =  e.getMessage().contains('Template already exists for County') ? true : false;
        }
        Test.stopTest(); 
    }
}