CHATS_SIT/force-app/main/default/objects/T_CBMS_ADDNL_INFO__c.object
<CustomObject>
    <description>Information about TANF and EF cases captured through CHATS application</description>
  <!--  <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_CAT_ACTIV__c</fullName>
        <description>Activity</description>
        <label>Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00797</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFEV__c</fullName>
        <label>Effective Begin Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE_INTFC__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>CBMS Case Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>TANF Details</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>TANF Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TANF Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
     <!--validationRules>
        <fullName>Effective_End_Date_GreaterThn_Begin_Date</fullName>
        <active>false</active>
        <description>Effective End Date must be equal to or greater than the Effective Begin Date.</description>
        <errorConditionFormula>DTE_END_EFFEV__c &lt; DTE_BEGIN_EFFEV__c</errorConditionFormula>
        <errorMessage>Effective End Date must be equal to or greater than the Effective Begin Date.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00797.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AWE</fullName>
        <label>Alternative Work Experience (AWEP)</label>
    </customValue>
    <customValue>
        <fullName>CMA</fullName>
        <label>Case Management Activities</label>
    </customValue>
    <customValue>
        <fullName>CS</fullName>
        <label>Community Services</label>
    </customValue>
    <customValue>
        <fullName>CWE</fullName>
        <label>Community Work Experience (CWEP)</label>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
        <label>Education Activities (ABE, GED, ESL, High School)</label>
    </customValue>
    <customValue>
        <fullName>EF</fullName>
        <label>Employment First / Job Search</label>
    </customValue>
    <customValue>
        <fullName>EMP</fullName>
        <label>Employed</label>
    </customValue>
    <customValue>
        <fullName>HSL</fullName>
        <label>High School/Jr High</label>
    </customValue>
    <customValue>
        <fullName>JR</fullName>
        <label>Job Readiness</label>
    </customValue>
    <customValue>
        <fullName>JS</fullName>
        <label>Job Search/Job Finding Club</label>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
        <label>Post Secondary Education includes pre-registration</label>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
        <label>OJT/Subsidized Employment</label>
    </customValue>
    <customValue>
        <fullName>SEM</fullName>
        <label>Self-employed</label>
    </customValue>
    <customValue>
        <fullName>VOC</fullName>
        <label>Vocational/Job Skills Training</label>
    </customValue>
    <description>R00797</description>
    <masterLabel>R00797</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CBMSAdditionalInformTriggerTest.cls
@isTest
public class CBMSAdditionalInformTriggerTest {
    public static testMethod void testCaseServices(){
        Test.startTest();
        T_CBMS_ADDNL_INFO__c cs = new T_CBMS_ADDNL_INFO__c();
        cs.IDN_CASE_INTFC__c = 'test';
        cs.CDE_CAT_ACTIV__c = 'CMA';
        cs.DTE_BEGIN_EFFEV__c = system.today();
        insert cs; 
        List<T_CBMS_ADDNL_INFO__c> csList = [Select Id from T_CBMS_ADDNL_INFO__c where Id =:cs.Id];
        System.assertEquals(csList.size(),1);
        Test.stopTest();
        
    }
}