CHATS_SIT/force-app/main/default/objects/T_CBMS_ADDNL_INFO__c.object
<CustomObject>
    <description>Information about TANF and EF cases captured through CHATS application</description>
  <!--  <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_CAT_ACTIV__c</fullName>
        <description>Activity</description>
        <label>Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00797</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFEV__c</fullName>
        <label>Effective Begin Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFEV__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE_CHATS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>TANF Details</relationshipLabel>
        <relationshipName>CBMS_Additional_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CASE_INTFC__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>CBMS Case Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Identifier External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>TANF Details</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>TANF Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TANF Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
     <!--validationRules>
        <fullName>Effective_End_Date_GreaterThn_Begin_Date</fullName>
        <active>false</active>
        <description>Effective End Date must be equal to or greater than the Effective Begin Date.</description>
        <errorConditionFormula>DTE_END_EFFEV__c &lt; DTE_BEGIN_EFFEV__c</errorConditionFormula>
        <errorMessage>Effective End Date must be equal to or greater than the Effective Begin Date.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>IND_MissingInfo_Status__c</fullName>
        <label>Missing Info Letter Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>OPEN</fullName>
                </value>
                <value>
                    <fullName>PROCESSED</fullName>
                </value> 
                <value>
                    <fullName>FAILED</fullName>
                </value>                
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS_WTLST__c</fullName>
        <description>Waitlist/Enrollment Freeze Status</description>
        <label>Waitlist/Enrollment Freeze Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00754</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>CDE_MODE_CASE__c</fullName>
        <description>Case Mode</description>
        <label>Case Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00358</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_WTLST__c.object
<CustomObject>
    <description>Case Waitlist</description>
    <fields>
        <fullName>CDE_STATUS_WTLST__c</fullName>
        <description>Waitlist Status</description>
        <label>Waitlist/Enrollment Freeze Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00754</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_WTLST__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_WTLST__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Waitlist/Enrollment Freezes</relationshipLabel>
        <relationshipName>T_SBSD_CASE114</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Waitlist/Enrollment Freeze</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Waitlist ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlists/County Freezes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00358.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INT</fullName>
        <label>Intake</label>
    </customValue>
    <customValue>
        <fullName>ONG</fullName>
        <label>Ongoing</label>
    </customValue>
    <customValue>
        <fullName>RED</fullName>
        <label>Redetermination</label>
    </customValue>
    <description>R00358</description>
    <masterLabel>R00358</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00754.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>REM</fullName>
        <label>Removed</label>
    </customValue>
    <customValue>
        <fullName>RFS</fullName>
        <label>Ready for Service</label>
    </customValue>
    <customValue>
        <fullName>WLT</fullName>
        <label>Waitlisted</label>
    </customValue>
    <customValue>
        <fullName>ENF</fullName>
        <label>Enrollment Freeze</label>
    </customValue>
    <customValue>
        <fullName>NON</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <description>R00754</description>
    <masterLabel>R00754</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00797.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AWE</fullName>
        <label>Alternative Work Experience (AWEP)</label>
    </customValue>
    <customValue>
        <fullName>CMA</fullName>
        <label>Case Management Activities</label>
    </customValue>
    <customValue>
        <fullName>CS</fullName>
        <label>Community Services</label>
    </customValue>
    <customValue>
        <fullName>CWE</fullName>
        <label>Community Work Experience (CWEP)</label>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
        <label>Education Activities (ABE, GED, ESL, High School)</label>
    </customValue>
    <customValue>
        <fullName>EF</fullName>
        <label>Employment First / Job Search</label>
    </customValue>
    <customValue>
        <fullName>EMP</fullName>
        <label>Employed</label>
    </customValue>
    <customValue>
        <fullName>HSL</fullName>
        <label>High School/Jr High</label>
    </customValue>
    <customValue>
        <fullName>JR</fullName>
        <label>Job Readiness</label>
    </customValue>
    <customValue>
        <fullName>JS</fullName>
        <label>Job Search/Job Finding Club</label>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
        <label>Post Secondary Education includes pre-registration</label>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
        <label>OJT/Subsidized Employment</label>
    </customValue>
    <customValue>
        <fullName>SEM</fullName>
        <label>Self-employed</label>
    </customValue>
    <customValue>
        <fullName>VOC</fullName>
        <label>Vocational/Job Skills Training</label>
    </customValue>
    <description>R00797</description>
    <masterLabel>R00797</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CaseMissingInfoTrackingBatch_Test.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           5/09/2023                                                         
*  @description    Case batch class for tracking missing information letter and creating eligibility run data                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 9-May-2023                                                            
*  * Author: Diya Chaudhary                                                      
*  * Description: Initial version                   
*********************************************************************************************/
@isTest
public class CaseMissingInfoTrackingBatch_Test {
    
    public static testMethod void testMethod1(){
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1');
        insert provider;
        
        T_CHATS_PROVR_STATUS__c provider1= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 3');
        insert provider1;
        
        T_SBSD_CASE__c sbsdcase=TestClassUtility.createCase(false,county.Id);
        T_SBSD_CASE_WTLST__c waitlist= new T_SBSD_CASE_WTLST__c(CDE_STATUS_WTLST__c ='RFS',IDN_CASE__c=sbsdcase.Id,DTE_BEGIN_EFFV_WTLST__c=System.Today(),DTE_END_EFFV_WTLST__c =System.Today());
        insert waitlist;
        
        Date datetoday=System.Today();
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today().addYears(4);
        sbsdcase.IDN_EXTNL__c='12345';
        sbsdcase.IND_MissingInfo_Status__c = 'OPEN';
        insert sbsdcase;
        T_SBSD_CASE_STATUS_MODE__c caseStaMod = TestClassUtility.createCaseStatusMode(true, sbsdcase.Id);
        caseStaMod.CDE_MODE_CASE__c='INT';
        UPDATE caseStaMod;
        List<T_CBMS_ADDNL_INFO__c> tanfDataList = new List<T_CBMS_ADDNL_INFO__c>();
            T_CBMS_ADDNL_INFO__c cs1 = new T_CBMS_ADDNL_INFO__c();
            cs1.IDN_CASE_INTFC__c = 'test1';
            cs1.CDE_CAT_ACTIV__c = 'CMA';
            cs1.IDN_CASE_CHATS__c = sbsdcase.Id;
            cs1.DTE_BEGIN_EFFEV__c = system.today();
            cs1.DTE_END_EFFEV__c = system.today() +10;
            tanfDataList.add(cs1);
        insert tanfDataList;
        //GenericDMLHandler.updateRecords(new List<SObject>{sbsdcase}, null);
        Test.startTest();
        CaseMissingInfoTrackingBatch obj = new CaseMissingInfoTrackingBatch();
        DataBase.executeBatch(obj); 
        Test.stopTest();
    }
}