CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_AGRMT__c</fullName>
        <description>Renewal Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CloseFiscalAgreementsBatchTest.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           07/10/2018                                                          
*  @description    Test Class for Testing closing Fiscal Agreements.                             
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 10-Jul-2018                                                             
*  * Author: Vineet Srivastava                                                     
*  * Description: Initial version 
*********************************************************************************************/
@isTest
public class CloseFiscalAgreementsBatchTest {

    public static testMethod void testCloseFABatch(){
        T_COUNTY__c countyRecord = TestClassUtility.createCounty('countyName', 'CD', 99, true);
        T_CHATS_PROVR_STATUS__c provider = TestClassUtility.createProvider(true, 'Level 3');
        T_PROVR_FISCAL_AGREMENT__c faRecord = TestClassUtility.createFiscaAgreement(false, 'FA-00001', System.today().addDays(-15), countyRecord.Id);
        faRecord.ID_SERVICE__c = provider.Id;
        insert faRecord;
        faRecord.DTE_END_AGRMT__c = system.today().addDays(-1);
        update faRecord;
        Test.startTest();
        Database.executeBatch(new CloseFiscalAgreementsBatch(),200);
        Test.stopTest();
        System.assert([SELECT Id FROM T_PROVR_FISCAL_AGREMENT__c where DTE_END_AGRMT__c < TODAY and CDE_TYPE_STATUS__c!='CLS'].isEmpty(),'Query should return zero rows as all closed');
    }
    
    public static testMethod void testCloseFABatchSchedulable(){
        Test.startTest();
        CLoseFiscalAgreementsBatchSchedulable schObj =  new CLoseFiscalAgreementsBatchSchedulable();
        String sch = '0 0 6 1/1 * ? *';
        String jobId =system.schedule('Test Exception Log Clean Up Batch Check', sch, schObj); 
        // Get the information from the CronTrigger API object 
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
        // Verify the expressions are the same System.assertEquals(CRON_EXP, ct.CronExpression); 
        // Verify the job has not run 
        System.assertEquals(0, ct.TimesTriggered,'Cron trigger should return zero jobs'); 
        Test.stopTest();
    }
}