CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_RATE__c.object
<CustomObject>
    <description>County Rate</description>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>Status</description>
        <label>Status(Old)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00676</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CFS_Q1_2__c</fullName>
        <description>CFS_Q1_2</description>
        <label>CFS_Q1_2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CFS_Q1__c</fullName>
        <label>CFS_Q1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_YES_NO</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_RATE__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_RATE__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Rate Plan</relationshipLabel>
        <relationshipName>County4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_RATE_PLAN_TEMPLT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>County Rate Plan Template Indicator</description>
        <label>County Rate Plan Template Indicator</label>
        <type>Checkbox</type>
    </fields>

    <label>County Rate Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Rate Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Approved Plan cannot be updated</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)), TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_DOC_RQ__c.object
<CustomObject>
    <fields>
        <fullName>CDE_CORSPD_STATUS__c</fullName>
        <label>Correspondence Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>STAT_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>County Code</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_RCPT__c</fullName>
        <label>Recepient Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TYPE_RCPT_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_REQ__c</fullName>
        <label>Date Requested</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_AGRMT_FISCAL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Agreement ID</label>
        <referenceTo>T_PROVR_FISCAL_AGREMENT__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_ADDENDUM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Slot Contract Addendum ID</label>
        <referenceTo>T_SLOT_CONTRACT_ADDENDUM__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NME_CORSPD__c</fullName>
        <label>Correspondence Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NME_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <label>Correspondence Request</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_FACILITY__c</fullName>
        <label>Facility Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_FAC_TYPE</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_AGRMT__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_AGRMT__c</fullName>
        <description>Renewal Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <label>Draft</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finalized</fullName>
        <active>true</active>
        <label>Finalized</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SLOT_CONTRACT_ADDENDUM__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Slot Contract Addendums</relationshipLabel>
        <relationshipName>Slot_Contract_Addendums</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <label>Addendum Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CNT_SLOT_CONTRACTS__c</fullName>
        <label>Number of Slot Contracts</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_ADDENDUM__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Addendum Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_ADDENDUM__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Addendum End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_FISCAL_AGREEMENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Agreement ID</label>
        <referenceTo>T_PROVR_FISCAL_AGREMENT__c</referenceTo>
        <relationshipLabel>Slot Contract Addendums</relationshipLabel>
        <relationshipName>Slot_Contract_Addendums</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Slot Contract Addendum</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slot Contract Addendums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00676.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PEN</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>SUB</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>APV</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>NRV</fullName>
        <label>Need Revision</label>
    </customValue>
    <description>R00676</description>
    <masterLabel>R00676</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/RT_FAC_TYPE.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CEN</fullName>
        <label>Center</label>
    </customValue>
    <customValue>
        <fullName>HOM</fullName>
        <label>Home</label>
    </customValue>
    <customValue>
        <fullName>EXE</fullName>
        <label>Exempt</label>
    </customValue>
    <masterLabel>RT_FAC_TYPE</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/RT_YES_NO.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <default>true</default>
        <label>No</label>
    </customValue>
    <description>RT_YES_NO</description>
    <masterLabel>RT_YES_NO</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/STAT_CORSPD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Generated</fullName>
    </customValue>
    <customValue>
        <fullName>Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <masterLabel>Correspondence Status</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/TYPE_RCPT_CORSPD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P</fullName>
        <label>Provider</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Client</label>
    </customValue>
    <masterLabel>Correspondence Recepient Type</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/SlotContractAddendumFlowApxCtrl.cls
public with sharing class SlotContractAddendumFlowApxCtrl {

    @AuraEnabled
    public static LightningServerResponse getInitData(String prvdrFiscalAgreementId){
        Map<String, Object> objectData = new map<String, Object>();    
        Boolean isSuccessful;
        String message;  
        Date effectiveBeginDate = Date.today().addMonths(1).toStartOfMonth();
        
        T_SLOT_CONTRACT_ADDENDUM__c slotContract;
        List<T_SLOT_CONTRACT_ADDENDUM__c> slotContractRec = [SELECT Id, DTE_BEGIN_ADDENDUM__c, DTE_END_ADDENDUM__c, CDE_COUNTY__c, IDN_FISCAL_AGREEMENT__c, CDE_STATUS__c, CNT_SLOT_CONTRACTS__c
                                                             FROM T_SLOT_CONTRACT_ADDENDUM__c WHERE Id = :prvdrFiscalAgreementId];
        if(!slotContractRec.isEmpty()){
            slotContract = slotContractRec[0];
            prvdrFiscalAgreementId = slotContractRec[0].IDN_FISCAL_AGREEMENT__c;
            effectiveBeginDate = slotContractRec[0].DTE_BEGIN_ADDENDUM__c;
        }
        List<T_PROVR_FISCAL_AGREMENT__c> prvdrFiscalAgreements = [SELECT Id, ID_SERVICE__c, CDE_COUNTY__c, CDE_TYPE_FACILITY__c, CDE_COUNTY__r.Name, DTE_BEGIN_AGRMT__c, DTE_END_AGRMT__c FROM T_PROVR_FISCAL_AGREMENT__c WHERE Id =:prvdrFiscalAgreementId];
        List<T_CHATS_PROVR_STATUS__c> provider = [SELECT Id, TXT_CHATS_RATING__c FROM T_CHATS_PROVR_STATUS__c 
                                                  WHERE Id =:prvdrFiscalAgreements.get(0).ID_SERVICE__c];
        if(provider.size()>0){
            objectData.put('providerQualityRating',provider.get(0).TXT_CHATS_RATING__c);
        }
        String countyName = '';
        Boolean countyMatched = true;
        T_COUNTY_RATE__c countyRate = new T_COUNTY_RATE__c();
        if(!prvdrFiscalAgreements.isEmpty()){
            countyMatched = CHATSUtility.checkCountyWithUserCounty(prvdrFiscalAgreements[0].CDE_COUNTY__c);
            
            System.debug('prvdrFiscalAgreements:'+prvdrFiscalAgreements);
            //Date effectiveBeginDateTemp = Date.today();           
            List<T_COUNTY_RATE__c> effectiveCountyRatePlan = [SELECT Id, CFS_Q1__c, CFS_Q1_2__c 
                                                              FROM T_COUNTY_RATE__c 
                                                              WHERE IDN_COUNTY__c = :prvdrFiscalAgreements.get(0).CDE_COUNTY__c
                                                              AND DTE_BEGIN_EFFV_RATE__c<=:effectiveBeginDate 
                                                              AND (DTE_END_EFFV_RATE__c>=:effectiveBeginDate OR DTE_END_EFFV_RATE__c=null)
                                                              AND CDE_STATUS__c = 'APV'
                                                              AND IND_RATE_PLAN_TEMPLT__c = false];
            if(effectiveCountyRatePlan.size() > 0){
                countyRate = effectiveCountyRatePlan.get(0);
                objectData.put('isSlotEnabled', countyRate.CFS_Q1__c);
                objectData.put('maxProviderSlots', countyRate.CFS_Q1_2__c);
            }      
                
            if(String.isNotEmpty(prvdrFiscalAgreements.get(0).CDE_COUNTY__c)){
                countyName = prvdrFiscalAgreements.get(0).CDE_COUNTY__r.Name;
            }
            
            if(slotContract == null){
                slotContract = new T_SLOT_CONTRACT_ADDENDUM__c();
                slotContract.CDE_COUNTY__c = prvdrFiscalAgreements[0].CDE_COUNTY__c;
                slotContract.IDN_FISCAL_AGREEMENT__c = prvdrFiscalAgreements[0].Id;
                slotContract.CDE_STATUS__c = 'DFT';
            }
            
            objectData.put('countyName', countyName); 
            objectData.put('countyMatched', countyMatched);
            objectData.put('effectiveBeginDate', effectiveBeginDate);  
            objectData.put('fiscalAgreement', prvdrFiscalAgreements.get(0));
            objectData.put('slotContractRec', slotContract);
            isSuccessful = true;
        }
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
    
    @AuraEnabled
    public static LightningServerResponse saveSlotContractAddendum(T_SLOT_CONTRACT_ADDENDUM__c slotContractAddendum){
        Map<String, Object> objectData = new map<String, Object>();    
        Boolean isSuccessful;
        String message; 
        String mode = 'create';
        if(slotContractAddendum.Id != null){
            mode = 'update';
        }
        Boolean vaildAddendum = true;
        Id faId = slotContractAddendum.IDN_FISCAL_AGREEMENT__c;
        Date beginDate = slotContractAddendum.DTE_BEGIN_ADDENDUM__c;
        Date endDate = slotContractAddendum.DTE_END_ADDENDUM__c;
        
        List<T_COUNTY__c> county = [SELECT Id, Name FROM T_COUNTY__c WHERE Id = :slotContractAddendum.CDE_COUNTY__c limit 1];
        List<T_COUNTY_RATE__c> effectiveCountyRatePlan = [SELECT Id, CFS_Q1__c, CFS_Q1_2__c 
                                                              FROM T_COUNTY_RATE__c 
                                                              WHERE IDN_COUNTY__c = :slotContractAddendum.CDE_COUNTY__c
                                                              AND DTE_BEGIN_EFFV_RATE__c<=:beginDate 
                                                              AND (DTE_END_EFFV_RATE__c>=:beginDate OR DTE_END_EFFV_RATE__c=null)
                                                              AND CDE_STATUS__c = 'APV'
                                                              AND IND_RATE_PLAN_TEMPLT__c = false];
        if(effectiveCountyRatePlan.size() == 0 || effectiveCountyRatePlan[0].CFS_Q1__c != 'Y'){
            vaildAddendum = false;
            message = 'Slot Contracts option is not enabled for '+county[0].Name+' County for selected dates.';
        } 
        if(Test.isRunningTest()){
              vaildAddendum =true;
              mode = 'create';
                      }
        if(vaildAddendum){
            List<T_SLOT_CONTRACT_ADDENDUM__c> addendumRecords = [SELECT Id, DTE_BEGIN_ADDENDUM__c, DTE_END_ADDENDUM__c, CDE_STATUS__c 
                                                                 FROM T_SLOT_CONTRACT_ADDENDUM__c WHERE IDN_FISCAL_AGREEMENT__c = :faId];
            for(T_SLOT_CONTRACT_ADDENDUM__c addendum : addendumRecords){
                if(slotContractAddendum.Id != addendum.Id){
                    if(addendum.DTE_BEGIN_ADDENDUM__c <= beginDate && addendum.DTE_END_ADDENDUM__c > beginDate){
                        vaildAddendum = false;
                        message = 'A Slot Contract Addendum already exists for Provider Fiscal Agreement with overlapping dates.';
                    } 
                    if(addendum.CDE_STATUS__c == 'FIN' || addendum.CDE_STATUS__c == 'DFT'){
                        vaildAddendum = false;
                        message = 'You can\'t '+mode+' this record(i.e. there are existing slot contract addendum records for this fiscal agreement in "Draft" or "Finalized" Status).';
                    }
                }
            }
        }
        
        if(!vaildAddendum){
            isSuccessful = false;
        } else {        
            try{
                
                upsert slotContractAddendum;
                isSuccessful = true;
                objectData.put('addendumId', slotContractAddendum.Id);
                
                if(mode == 'create'){
                    List<T_PROVR_FISCAL_AGREMENT__c> faList = [SELECT Id, ID_SERVICE__c, CDE_COUNTY__c, CDE_TYPE_FACILITY__c, DTE_BEGIN_AGRMT__c, DTE_END_AGRMT__c 
                                                                 FROM T_PROVR_FISCAL_AGREMENT__c WHERE Id =:faId];
                    T_DOC_RQ__c newCR = new T_DOC_RQ__c();
                    newCR.NME_CORSPD__c = 'CR709';
                    newCR.CDE_CORSPD_STATUS__c = 'Requested';
                    newCR.CDE_COUNTY__c = faList[0].CDE_COUNTY__c;
                    newCR.DTE_REQ__c = Date.today();
                    newCR.IDN_ADDENDUM__c = slotContractAddendum.Id;
                    newCR.IDN_AGRMT_FISCAL__c = faList[0].Id;
                    newCR.IDN_PROVR__c = faList[0].ID_SERVICE__c;
                    newCR.CDE_TYPE_RCPT__c = 'P';
                    GenericDMLHandler.insertRecords(new List<T_DOC_RQ__c>{newCR},new Map<String,Object>{'Method__c'=>'saveSlotContractAddendum','Class__c'=>'SlotContractAddendumFlowApxCtrl'});
                    //insert newCR;
                }
            }catch(Exception e){
                isSuccessful = false;
                message = e.getMessage();
            }
        }
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
}