CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_TYPE_PROVR__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00691</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <label>License Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CNTY_DEPT_NAME__c</fullName>
        <description>County Department Name</description>
        <label>County Department Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_SCH__c.object
<CustomObject>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_AGRMT_FISCAL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement</description>
        <label>Fiscal Agreement</label>
        <referenceTo>T_PROVR_FISCAL_AGREMENT__c</referenceTo>
        <relationshipLabel>Rate Schedules</relationshipLabel>
        <relationshipName>Rate_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Rate Schedule Quality Rating</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Rate Schedules</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_POS_TRANS_QUEUE_ATS__c/T_POS_TRANS_QUEUE_ATS__c.object-meta.xml
<CustomObject>
    <label>T_POS_TRANS_QUEUE_ATS</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>IDN_QUEUE_TRANS_ATS</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T_POS_TRANS_QUEUE_ATSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_POS_TRANS_QUEUE_ATS__c/fields/CDE_COUNTY__c.field-meta.xml
<CustomField>
    <fullName>CDE_COUNTY__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CDE_COUNTY</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/T_POS_TRANS_QUEUE_ATS__c/fields/IDN_AGRMT_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>IDN_AGRMT_FISCAL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IDN_AGRMT_FISCAL</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_REASON_END_AGRMT__c</fullName>
        <description>Reason for Closure</description>
        <label>Reason for Closure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00712</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_AGRMT__c</fullName>
        <description>Renewal Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_RCV_AGRMT_FISCAL__c</fullName>
        <description>Date Received</description>
        <label>Date Fiscal Agreement Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <label>Draft</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finalized</fullName>
        <active>true</active>
        <label>Finalized</label>
    </recordTypes>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00712.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CPV</fullName>
        <label>County Policy Violation</label>
    </customValue>
    <customValue>
        <fullName>DEC</fullName>
        <label>Deceased</label>
    </customValue>
    <customValue>
        <fullName>MTA</fullName>
        <label>Qualified Exempt Child Care Provider is no longer eligible to provide child care</label>
    </customValue>
    <customValue>
        <fullName>NLO</fullName>
        <label>No longer a slot contract</label>
    </customValue>
    <customValue>
        <fullName>NUE</fullName>
        <label>Non-Use</label>
    </customValue>
    <customValue>
        <fullName>PRT</fullName>
        <label>Provider Request</label>
    </customValue>
    <customValue>
        <fullName>EXP</fullName>
        <label>License Expired/Closed</label>
    </customValue>
    <customValue>
        <fullName>NCH</fullName>
        <label>License Number Changed</label>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
        <label>New Fiscal Agreement has been put in place</label>
    </customValue>
    <customValue>
        <fullName>WAR</fullName>
        <isActive>false</isActive>
        <label>Warning! License is pending</label>
    </customValue>
    <customValue>
        <fullName>RFT</fullName>
        <isActive>false</isActive>
        <label>No Provider Record Found in Trails</label>
    </customValue>
    <customValue>
        <fullName>HAR</fullName>
        <isActive>false</isActive>
        <label>Authorization rates are higher than the Fiscal Agreement rates</label>
    </customValue>
    <customValue>
        <fullName>IPT</fullName>
        <isActive>false</isActive>
        <label>Invalid Provider Type</label>
    </customValue>
    <customValue>
        <fullName>FHP</fullName>
        <isActive>false</isActive>
        <label>Fiscal agreement rates are higher than the private pay rates.</label>
    </customValue>
    <customValue>
        <fullName>NOR</fullName>
        <isActive>false</isActive>
        <label>Fiscal Agreement does not have appropriate rates for child</label>
    </customValue>
    <customValue>
        <fullName>IPV</fullName>
        <isActive>false</isActive>
        <label>Intentional Program Violation</label>
    </customValue>
    <description>R00712</description>
    <masterLabel>R00712</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/FiscalAgreementServices_Test.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           11/16/2017                                                          
*  @description    Test class for Fiscal Agreement Trigger                           
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 16-Nov-2017                                                             
*  * Author: Bharadwaj Gaddam                                                      
*  * Description: Initial version                                                 
*                                                                                 
*********************************************************************************************/
@isTest
private class FiscalAgreementServices_Test {
    public static final String FINALIZED= 'FIN';
    public static final String OPEN = 'OPN';
    public static final String NEWFA = 'NEW';
    public static final String CLOSED = 'CLS';
    public static final String openRecordTypeId = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Open').getRecordTypeId();
    public static final String finalizedRecordTypeId = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Finalized').getRecordTypeId();
    public static final String closedRecordTypeId= Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Closed').getRecordTypeId();
    public static T_PROVR_FISCAL_AGREMENT__c fiscalAgreement;
    public static final string DRAFT='DFT';

    @testSetup static void setup() {
        
        List<T_COUNTY__c> countyList = new List<T_COUNTY__c>();
        List<T_CHATS_PROVR_STATUS__c> providerList = new List<T_CHATS_PROVR_STATUS__c >();
        
        Date datetoday=System.Today();
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today();
        
        for(Integer i=0;i<102;i++) {
            countyList.add((T_COUNTY__c)TestClassUtility.createCounty('County'+i,'Dept1',10,false));
            
        }
        
        insert countyList;
        
        for(Integer i=0;i<102;i++) {
            providerList.add(new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1'));
            
        }
        
        insert providerList;
        
        
    }
    
    static testMethod void testcloseExistingFA() {
        
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1');
        insert provider;
        
        Date datetoday=System.Today();
        //Date begindate = date.newInstance(datetoday.year(),datetoday.month()+1,1);
        //Date enddate = begindate.addDays(20);
        
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today().addYears(4);
        
        Test.startTest();
        
        
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement=TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county.Id);
        fiscalAgreement.RecordtypeId=openRecordTypeId;
        fiscalAgreement.CDE_TYPE_STATUS__c=OPEN;
        fiscalAgreement.ID_SERVICE__c=provider.Id;
        fiscalAgreement.DTE_RCV_AGRMT_FISCAL__c=begindateOpn;
        insert fiscalAgreement;
        
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreementFinalized=TestClassUtility.createFiscaAgreement(false,'FA2',begindateFin,county.Id);
        fiscalAgreementFinalized.RecordtypeId=finalizedRecordTypeId;
        fiscalAgreementFinalized.CDE_TYPE_STATUS__c=FINALIZED;
        fiscalAgreementFinalized.ID_SERVICE__c=provider.Id;   
        
        insert fiscalAgreementFinalized;
        
        fiscalAgreementFinalized.RecordtypeId=openRecordTypeId;
        fiscalAgreementFinalized.CDE_TYPE_STATUS__c=OPEN;
        
        update fiscalAgreementFinalized;
        
        T_PROVR_FISCAL_AGREMENT__c updatedFA =[Select Id,CDE_TYPE_STATUS__c,CDE_REASON_END_AGRMT__c,DTE_END_AGRMT__c,RecordTypeId from T_PROVR_FISCAL_AGREMENT__c where Id=:fiscalAgreement.Id Limit 1];
        
        system.assertEquals(CLOSED,updatedFA.CDE_TYPE_STATUS__c,'Status is not changed to Closed');
        system.assertEquals(NEWFA,updatedFA.CDE_REASON_END_AGRMT__c,'No Closure Reason');
        system.assertEquals(System.today()-1,updatedFA.DTE_END_AGRMT__c,'Date is not updated to day before begin date of new FA');
        system.assertEquals(Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Closed').getRecordTypeId(),updatedFA.RecordTypeId,'Not a Closed RecordType');
        
        Test.stopTest();
    }
    
    static testMethod void testcloseExistingFABulk() {
        
        Date datetoday=System.Today();
        //Date begindate = date.newInstance(datetoday.year(),datetoday.month()+1,1);
        //Date enddate = begindate.addDays(20);
        
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today().addYears(4);
        List<T_PROVR_FISCAL_AGREMENT__c> fiscalAgreementFinalizedList = new List<T_PROVR_FISCAL_AGREMENT__c>();
        List<T_PROVR_FISCAL_AGREMENT__c> fiscalAgreementList = new List<T_PROVR_FISCAL_AGREMENT__c>();
        List<T_FISCAL_SCH__c> ratesheduleList= new List<T_FISCAL_SCH__c>();
        
        List<T_COUNTY__c> countyList=[Select Id from T_COUNTY__c where CNTY_DEPT_NAME__c='Dept1' Limit 210];
        List<T_CHATS_PROVR_STATUS__c> providerList=[Select Id from T_CHATS_PROVR_STATUS__c Limit 210];
        
        List<Task> taskList =new List<Task>();
        
        
        Map<string,string> countyProviderMap = new Map<string,string>();
        
        for(Integer i=0;i<102;i++) {
            fiscalAgreement = new T_PROVR_FISCAL_AGREMENT__c();
            fiscalAgreement = TestClassUtility.createFiscaAgreement(false,'FA'+i,begindateOpn,countyList[i].Id);
            fiscalAgreement.RecordtypeId=openRecordTypeId;
            fiscalAgreement.CDE_TYPE_STATUS__c=OPEN;
            fiscalAgreement.ID_SERVICE__c=providerList[i].Id;     
            fiscalAgreementList.add(fiscalAgreement);
            countyProviderMap.put(countyList[i].Id,providerList[i].Id);
            fiscalAgreement.DTE_RCV_AGRMT_FISCAL__c = begindateOpn;
            
        }
        
        insert fiscalAgreementList;
        
        for(Integer i=0;i<102;i++) {
            
            taskList.add(new Task(Type='Other',Description='testing task'+1,OwnerId=userinfo.getUserId(),WhatId=fiscalAgreementList[i].Id));
        }
        
        insert taskList;
        test.startTest();
        List<Task> notStartedTaskList= [Select Status from Task where WhatId IN:fiscalAgreementList Limit 202];
        
        system.assert(notStartedTaskList.size()>100,'No Task Records');
        
        for(Task t:notStartedTaskList) {
            
            system.assertEquals('Not Started',t.Status,'Task in not in Not Started Staus');
        }
        
        for(Integer i=0;i<1;i++) {
            ratesheduleList.add((T_FISCAL_SCH__c)TestClassUtility.createRateSchedule(false,datetoday+10,null,fiscalAgreementList[i].Id,'1'));
            
        }
        
        insert ratesheduleList;
        Set<Id> rateScheduleIds=new Set<Id>();
        for(T_FISCAL_SCH__c ratesch:ratesheduleList) {
            rateScheduleIds.add(ratesch.Id);
        }
        
        for(Integer i=0;i<102;i++) {
            fiscalAgreement = new T_PROVR_FISCAL_AGREMENT__c();
            fiscalAgreement = TestClassUtility.createFiscaAgreement(false,'FA'+i,begindateFin,countyList[i].Id);
            fiscalAgreement.RecordtypeId=finalizedRecordTypeId;
            fiscalAgreement.CDE_TYPE_STATUS__c=FINALIZED;
            fiscalAgreement.ID_SERVICE__c=countyProviderMap.get(countyList[i].Id);     
            fiscalAgreementFinalizedList.add(fiscalAgreement);
            
            
        }
        
        insert fiscalAgreementFinalizedList;
        
        
        for(T_PROVR_FISCAL_AGREMENT__c fiscalAgreementFinalized:fiscalAgreementFinalizedList) {
            fiscalAgreementFinalized.RecordtypeId=openRecordTypeId;
            fiscalAgreementFinalized.CDE_TYPE_STATUS__c=OPEN;
            
        }
        
        update fiscalAgreementFinalizedList;
        
        /*for(T_PROVR_FISCAL_AGREMENT__c updatedFA:[Select Id,CDE_TYPE_STATUS__c,CDE_REASON_END_AGRMT__c,DTE_END_AGRMT__c,RecordTypeId from T_PROVR_FISCAL_AGREMENT__c where Id IN:fiscalAgreementList Limit 210]) {
            system.assertEquals(CLOSED,updatedFA.CDE_TYPE_STATUS__c,'Status is not changed to Closed');
            system.assertEquals(NEWFA,updatedFA.CDE_REASON_END_AGRMT__c,'No Closure Reason');
            system.assertEquals(System.today()-1,updatedFA.DTE_END_AGRMT__c,'Date is not updated to day before begin date of new FA');
            system.assertEquals(closedRecordTypeId,updatedFA.RecordTypeId,'Not a Closed RecordType');
            
        }*/
        
        //bulk test to end Rate schedules
        for(T_FISCAL_SCH__c ratesch:[Select Id, DTE_END_EFFV__c from T_FISCAL_SCH__c where Id IN:rateScheduleIds]) {
            system.assertEquals(datetoday,ratesch.DTE_END_EFFV__c,'End Date not updated to today');
            
        }
        
        
        List<Task> cancelledTaskList= [Select Status from Task where WhatId IN:fiscalAgreementList Limit 202];
        
        //system.assert(cancelledTaskList.size()>100,'No Task Records');
        
        for(Task t:cancelledTaskList) {
            
            //system.assertEquals('Cancelled',t.Status,'Task in not in Cancelled Staus');
        }
        test.stopTest();
    }
    static testMethod void testEndRateSchedule() {
        
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1');
        insert provider;
        
        Date datetoday=System.Today();
        
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today().addYears(4);
        Test.startTest();
        
        
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement=TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county.Id);
        fiscalAgreement.RecordtypeId=openRecordTypeId;
        fiscalAgreement.CDE_TYPE_STATUS__c=OPEN;
        fiscalAgreement.ID_SERVICE__c=provider.Id;
        fiscalAgreement.DTE_RCV_AGRMT_FISCAL__c= begindateOpn-1;
        
        insert fiscalAgreement;
        
        List<T_FISCAL_SCH__c> ratesheduleList= new List<T_FISCAL_SCH__c>();
        ratesheduleList.add((T_FISCAL_SCH__c)TestClassUtility.createRateSchedule(false,datetoday,null,fiscalAgreement.Id,'1'));
        ratesheduleList.add((T_FISCAL_SCH__c)TestClassUtility.createRateSchedule(false,datetoday+10,null,fiscalAgreement.Id,'1'));
        
        insert ratesheduleList;
        
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreementFinalized=TestClassUtility.createFiscaAgreement(false,'FA2',begindateFin,county.Id);
        fiscalAgreementFinalized.RecordtypeId=finalizedRecordTypeId;
        fiscalAgreementFinalized.CDE_TYPE_STATUS__c=FINALIZED;
        fiscalAgreementFinalized.ID_SERVICE__c=provider.Id;   
        fiscalAgreementFinalized.DTE_RCV_AGRMT_FISCAL__c= begindateFin;
        insert fiscalAgreementFinalized;
        
        fiscalAgreementFinalized.RecordtypeId=openRecordTypeId;
        fiscalAgreementFinalized.CDE_TYPE_STATUS__c=OPEN;
        
        update fiscalAgreementFinalized;
        
        T_PROVR_FISCAL_AGREMENT__c updatedFA =[Select Id,CDE_TYPE_STATUS__c,CDE_REASON_END_AGRMT__c,DTE_END_AGRMT__c,RecordTypeId from T_PROVR_FISCAL_AGREMENT__c where Id=:fiscalAgreement.Id Limit 1];
        T_FISCAL_SCH__c ratesheduleUpdated = [Select Id, DTE_END_EFFV__c, IDN_AGRMT_FISCAL__r.DTE_END_AGRMT__c from T_FISCAL_SCH__c where Id=:ratesheduleList[0].Id limit 1];
        try {
            T_FISCAL_SCH__c ratesheduleUpdated2 = [Select Id, DTE_END_EFFV__c from T_FISCAL_SCH__c where Id=:ratesheduleList[1].Id limit 1];
            
        }
        catch(Exception ex) {
            system.assert((string.valueof(ex.getMessage())).contains('List has no rows for assignment to SObject'),'Rate Schedule is not deleted');
        }

        //system.assertEquals(datetoday,ratesheduleUpdated.DTE_END_EFFV__c,'End Date not updated to today');

        //system.assertEquals(ratesheduleUpdated.IDN_AGRMT_FISCAL__r.DTE_END_AGRMT__c ,ratesheduleUpdated.DTE_END_EFFV__c,'End Date not updated to today');

        
        system.assertEquals(CLOSED,updatedFA.CDE_TYPE_STATUS__c,'Status is not changed to Closed');
        system.assertEquals(NEWFA,updatedFA.CDE_REASON_END_AGRMT__c,'No Closure Reason');
        system.assertEquals(System.today()-1,updatedFA.DTE_END_AGRMT__c,'Date is not updated to day before begin date of new FA');
        system.assertEquals(Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Closed').getRecordTypeId(),updatedFA.RecordTypeId,'Not a Closed RecordType');
        
        Test.stopTest();
    }
    

    /*static testMethod void testUpdateEnddateonFA() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(CDE_TYPE_PROVR__c='EFACH');
        insert provider;
        
        Date datetoday=System.Today();
        
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today().addYears(4);
        Test.startTest();
        
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement=TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county.Id);
        fiscalAgreement.ID_SERVICE__c=provider.Id;
        insert fiscalAgreement;
        
        // Below changes added as part of Change request CHATS-6801
        //system.assertEquals(begindateOpn.addYears(1),[Select DTE_END_AGRMT__c from T_PROVR_FISCAL_AGREMENT__c where Id=:fiscalAgreement.Id].DTE_END_AGRMT__c ,'End Date not updated as expected');
        Date dteBeginDate = begindateOpn.addYears(1).addmonths(-1);
        system.assertEquals(Date.newInstance(dteBeginDate.year(), dteBeginDate.month(), Date.daysInMonth(dteBeginDate.year(), dteBeginDate.month())),[Select DTE_END_AGRMT__c from T_PROVR_FISCAL_AGREMENT__c where Id=:fiscalAgreement.Id].DTE_END_AGRMT__c ,'End Date not updated as expected');
        
        //updting CDE_TYPE_PROVR__c on T_CHATS_PROVR_STATUS__c which should update enddate on FA
        provider.CDE_TYPE_PROVR__c='PRS';
        update provider;
        
        //system.assertEquals(begindateOpn.addYears(3),[Select DTE_END_AGRMT__c from T_PROVR_FISCAL_AGREMENT__c where Id=:fiscalAgreement.Id].DTE_END_AGRMT__c ,'End Date not updated as expected');
        // Below changes added as part of Change request CHATS-7209
        begindateOpn = begindateOpn.addYears(3).addmonths(-1);
        begindateOpn = Date.newInstance(begindateOpn.year(), begindateOpn.month(), Date.daysInMonth(begindateOpn.year(), begindateOpn.month()));
        system.assertEquals(begindateOpn,[Select DTE_END_AGRMT__c from T_PROVR_FISCAL_AGREMENT__c where Id=:fiscalAgreement.Id].DTE_END_AGRMT__c ,'End Date not updated as expected');
        
        
        Test.stopTest();
        
    }*/
    
    static testMethod void validateExistingFiscalAgreementTest() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_COUNTY__c county1=TestClassUtility.createCounty('County2','Dept2',10,true);
        
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(CDE_TYPE_PROVR__c='EFACH');
        insert provider;
        
        Date datetoday=System.Today();
        
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today().addYears(4);
        Test.startTest();
        
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement=TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county.Id);
        fiscalAgreement.ID_SERVICE__c=provider.Id;
        fiscalAgreement.CDE_TYPE_STATUS__c='DFT';
        insert fiscalAgreement;
        
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement1=TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county.Id);
        fiscalAgreement1.ID_SERVICE__c=provider.Id;
        fiscalAgreement1.CDE_TYPE_STATUS__c=FINALIZED;
        try{
            insert fiscalAgreement1;
        }
        catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains(Label.NEW_PROVR_FISCAL_AGREEMENT_ERROR) ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement2=TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county1.Id);
        fiscalAgreement2.ID_SERVICE__c=provider.Id;
        //fiscalAgreement2.CDE_TYPE_STATUS__c=FINALIZED;
        insert fiscalAgreement2;
        try{
            fiscalAgreement2.CDE_COUNTY__c = county.Id;
            update fiscalAgreement2;
        }
        catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains(Label.UPDATE_PROVR_FISCAL_AGREEMENT_ERROR) ? true : false;
            //   System.AssertEquals(expectedExceptionThrown, true);
        }
        
        Test.stopTest();
        
    }
    
    
    static testMethod void beforeDeleteCheckFiscalAgreementTypeTest() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(CDE_TYPE_PROVR__c='EFACH');
        insert provider;
        
        Date datetoday=System.Today();
        
        Date begindateOpn=System.Today()-10;
        Date begindateFin=System.Today().addYears(4);
        Test.startTest();
        
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement=TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county.Id);
        fiscalAgreement.ID_SERVICE__c=provider.Id;
        fiscalAgreement.CDE_TYPE_STATUS__c='DFT';
        insert fiscalAgreement;
        
        try{
            delete fiscalAgreement;
            
        }catch(Exception ex) {
            system.assert(string.valueOf(ex.getMessage()).contains('Fiscal Agreement is not in Draft or Finalized Status so cannot be deleted'));
            
        }
    }
    
    static testMethod void testdeleteFARecord() {
        T_COUNTY__c county = TestClassUtility.createCounty('Test County', 'Test Dept', 1 , true);
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(TXT_CHATS_RATING__c ='Level 1');
        insert provider;
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement = TestClassUtility.createFiscaAgreement(false, 'FA-0001', System.today(), county.Id);
        fiscalAgreement.ID_SERVICE__c = provider.Id;
        insert fiscalAgreement;
        Test.startTest();
        FiscalAgreementServices.deleteFARecord(fiscalAgreement.Id);
        Test.stopTest();
        }
    
    /*
    public static testMethod void testInsertATSRecords(){
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(CDE_TYPE_PROVR__c='EFACH');
        insert provider;
        
        Date begindateOpn=System.Today()-10;
        Test.startTest();
        List<T_PROVR_FISCAL_AGREMENT__c> lstFiscalAgreementRecords =new List<T_PROVR_FISCAL_AGREMENT__c>();
        T_PROVR_FISCAL_AGREMENT__c fiscalAgreement=TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county.Id);
        fiscalAgreement.ID_SERVICE__c=provider.Id;
        fiscalAgreement.CDE_TYPE_STATUS__c='OPN';
        lstFiscalAgreementRecords.add(fiscalAgreement);
        Integer intCount = 0;
        
        for(AggregateResult result :[SELECT COUNT(Id) intVal FROM T_POS_TRANS_QUEUE_ATS__c])
        {
            intCount+=(Integer)result.get('intVal');
        }
        
        System.debug('No of records are: '+intCount);
        FiscalAgreementServices.insertATSRecord(lstFiscalAgreementRecords);
        Integer afterCount = 0;
        
        for(AggregateResult result :[SELECT COUNT(Id) intVal FROM T_POS_TRANS_QUEUE_ATS__c])
        {
            afterCount+=(Integer)result.get('intVal');
        }
        System.debug('No of records after are: '+afterCount);
        system.assertEquals(afterCount, intCount+1);
    } */
}