CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_STATUS_PROVR__c</fullName>
        <label>License Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00692</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_PROVR__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00691</valueSetName>
        </valueSet>
    </fields>
	<fields>
        <fullName>CDE_REQ_BGC_CHK_STATE__c</fullName>
        <inlineHelpText>For Qualified Exempt Provider Only: This indicates the provider's State required background check status</inlineHelpText>
        <label>Required Background Check Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00865</valueSetName>
        </valueSet>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_CBC__c.object
<CustomObject>
    <fields>
        <fullName>CDE_BGC_CHK_STATUS__c</fullName>
        <inlineHelpText>Not Cleared Status: Only select this status if the system should also close all Open Fiscal Agreements for this provider.</inlineHelpText>
        <label>Background Check Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00865</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_CBC_STATUS__c</fullName>
        <label>CBC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00724</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Background Check</relationshipLabel>
        <relationshipName>Providers_CBC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NAM_FIRST__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_LAST__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTE_ProvFinFA_CareEff__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fiscal Agreement/Reimbursement Effective</label>
        <type>Date</type>
    </fields>
    <label>Provider Background Check</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Providers Background Check</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>ProvFinFA_CareEff_noFutureDate</fullName>
        <active>false</active>
        <errorConditionFormula>DTE_ProvFinFA_CareEff__c &gt; TODAY()</errorConditionFormula>
        <errorDisplayField>DTE_ProvFinFA_CareEff__c</errorDisplayField>
        <errorMessage>Date entered should be less than or equal to today.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_AGRMT__c</fullName>
        <description>Renewal Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00692.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>R00692</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00724.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MYT</fullName>
        <label>May Take</label>
    </customValue>
    <customValue>
        <fullName>MST</fullName>
        <label>Must Take</label>
    </customValue>
    <customValue>
        <fullName>WTR</fullName>
        <label>Awaiting Results</label>
    </customValue>
    <customValue>
        <fullName>CLR</fullName>
        <label>Clear</label>
    </customValue>
    <customValue>
        <fullName>NAT</fullName>
        <label>No Action Taken</label>
    </customValue>
    <masterLabel>R00724</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00865.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Not Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <description>Background Check Status Values</description>
    <masterLabel>R00865</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/BatchUpdateProviderBackground_Test.cls
@isTest
public class BatchUpdateProviderBackground_Test {
    public static final String openRecordTypeId = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Open').getRecordTypeId();
    
 public static testMethod void testUpdateProviderBackground(){
        T_COUNTY__c county = TestClassUtility.createCounty('countyName', 'countyDepartmentName',10,true);
        T_CHATS_PROVR_STATUS__c provider = TestClassUtility.createProvider(true, 'Test');
     	provider.CDE_TYPE_PROVR__c = 'EFACH';
     	provider.CDE_REQ_BGC_CHK_STATE__c = 'Cleared';
     	provider.CDE_STATUS_PROVR__c = 'Open';
     	update provider;
   
     	Date begindateOpn=System.Today()-10;
     
     	T_PROVR_FISCAL_AGREMENT__c fiscalAgreement = TestClassUtility.createFiscaAgreement(false,'FA1',begindateOpn,county.Id);
        fiscalAgreement.RecordtypeId = openRecordTypeId;
        fiscalAgreement.CDE_TYPE_STATUS__c = 'OPN';
        fiscalAgreement.ID_SERVICE__c = provider.Id;
     	fiscalAgreement.DTE_END_AGRMT__c = Date.Today()+10;
        insert fiscalAgreement;	
     
     	T_PROVR_CBC__c provrCBC = new T_PROVR_CBC__c (CDE_CBC_STATUS__c = 'MST', NAM_FIRST__c = 'fname', NAM_LAST__c = 'lname',
                                                      IDN_PROVR__c = provider.Id, CDE_BGC_CHK_STATUS__c = 'Cleared',
                                                      DTE_ProvFinFA_CareEff__c = System.today());
        insert provrCBC;
     
        Test.startTest();
		String uuId = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id;
        User u1 = TestClassUtility.createUser(uuId, 'test', 'test', 'test@example.com.invalid', 'test@example.com.'+string.valueof(math.random()*3), 'ttes');
        System.runAs(u1){
            BatchUpdateProviderBackground batch = new BatchUpdateProviderBackground();
            database.executebatch(batch);
        }
        Test.stopTest();

    }
}