CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Provider Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CNTY_DEPT_NAME__c</fullName>
        <description>County Department Name</description>
        <label>County Department Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_DOC_RQ__c.object
<CustomObject>
    <fields>
        <fullName>CDE_CORSPD_STATUS__c</fullName>
        <label>Correspondence Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>STAT_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>County Code</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_RCPT__c</fullName>
        <label>Recepient Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TYPE_RCPT_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Correspondence Request</relationshipLabel>
        <relationshipName>Correspondence_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NME_CORSPD__c</fullName>
        <label>Correspondence Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NME_CORSPD</valueSetName>
        </valueSet>
    </fields>
    <label>Correspondence Request</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Correspondence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_PREF__c.object
<CustomObject>
    <fields>
        <fullName>CDE_PREF_CORR_PROVR__c</fullName>
        <description>Correspondence Preference</description>
        <label>Correspondence Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_COR_PREF</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_PREF_LANG_PROVR__c</fullName>
        <description>Language Preference</description>
        <label>Language Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00057</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipName>Correspondence_and_Lang_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_ACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active?</description>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Correspondence and Language Preferences</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence and Language Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_ASST_HSNG__c</fullName>
        <description>Does the household receive benefits from Housing Voucher or Cash Assistance?</description>
        <label>Household receives Voucher/Cash Asst?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00717</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_LANG_CORR__c</fullName>
        <label>Primary Language Spoken at Home</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00057</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <description>Provider ID</description>
        <label>Provider ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IND_ASSIST_PROVR__c</fullName>
        <description>Did a provider assist you in completing</description>
        <label>Provider assisted with application?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00619</valueSetName>
        </valueSet>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00619.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <description>R00619</description>
    <masterLabel>R00619</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00717.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Unknown</label>
    </customValue>
    <description>R00717</description>
    <masterLabel>R00717</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/RT_COR_PREF.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>MAIL</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>EMAIL</label>
    </customValue>
    <description>RT_COR_PREF</description>
    <masterLabel>RT_COR_PREF</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/STAT_CORSPD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Requested</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Generated</fullName>
    </customValue>
    <customValue>
        <fullName>Deleted</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <masterLabel>Correspondence Status</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/TYPE_RCPT_CORSPD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P</fullName>
        <label>Provider</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Client</label>
    </customValue>
    <masterLabel>Correspondence Recepient Type</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CorrespondenceRequestTriggerTest.cls
@isTest
public class CorrespondenceRequestTriggerTest {
    static testmethod void testCorrespondenceRequestTrigger(){
        test.startTest();
        T_COUNTY__c countyObj = new T_COUNTY__c(CNTY_DEPT_NAME__c = 'Arapahoe County', CDE_COUNTY__c = 3);
        insert countyObj;
        T_SBSD_CASE__c caseObject = new T_SBSD_CASE__c (	CDE_COUNTY__c = countyObj.Id, IND_ASSIST_PROVR__c = 'N', CDE_ASST_HSNG__c = 'N', Name = '123', CDE_LANG_CORR__c = 'SPN');
        insert caseObject;
        T_CHATS_PROVR_STATUS__c providerObj = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'Provider Test');
        insert providerObj;
        T_CHATS_PROVR_STATUS__c providerObj1 = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'Provider Test1');
        insert providerObj1;
        
        T_PROVR_PREF__c provrPref = new T_PROVR_PREF__c (IDN_PROVR__c = providerObj.Id, CDE_PREF_LANG_PROVR__c = 'SPN', CDE_PREF_CORR_PROVR__c = '1', IND_ACTIVE__c = true);
        insert provrPref;
        
        T_DOC_RQ__C corrReq_case = new T_DOC_RQ__C( 	NME_CORSPD__c = 'CR213',
                                             			CDE_CORSPD_STATUS__c='Requested',
                                                   		IDN_CASE__c = caseObject.Id,
                                                   		CDE_TYPE_RCPT__c='C');
        insert corrReq_case;
        
        T_DOC_RQ__C corrReq_provr = new T_DOC_RQ__C( 	NME_CORSPD__c = 'CR213',
                                             			CDE_CORSPD_STATUS__c='Requested',
                                                   		IDN_PROVR__c = providerObj.Id,
                                             			CDE_TYPE_RCPT__c='P');
        insert corrReq_provr;
        
        T_DOC_RQ__C corrReq_provr1 = new T_DOC_RQ__C( 	NME_CORSPD__c = 'CR213',
                                             			CDE_CORSPD_STATUS__c='Requested',
                                                   		IDN_PROVR__c = providerObj1.Id,
                                             			CDE_TYPE_RCPT__c='P');
        insert corrReq_provr1;
        
        
        
        test.stopTest();
    }
}