CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PMT_PLAN__c.object
<CustomObject>
    <description>Information on the arrangements made by a provider or case to repay a debt owed to the county/state</description>
    <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Repayment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00005</valueSetName>
        </valueSet>
    </fields>
    <label>Repayment Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Payment Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>AllfieldsenteredError</fullName>
        <active>false</active>
        <description>Error when all the fields have been entered when creating new record</description>
        <errorConditionFormula>OR(AND(ISNEW(),
OR(ISNULL( NBR_PCTG__c ),NBR_PCTG__c&lt;=0),  
ISNULL( AMT_PLAN_PMT__c ), 
ISNULL(  AMT_PLAN_PMT_PCT_MIN__c)
),
AND(ISNEW(),
OR(NOT(ISNULL( NBR_PCTG__c )),NBR_PCTG__c&lt;=0),  
NOT(ISNULL( AMT_PLAN_PMT__c ))), 
And(
ISNEW(),
NBR_PCTG__c&lt;=0
))</errorConditionFormula>
        <errorMessage>Either of Payment plan amount or Percentage must be entered. Percentage must be greater than 0.</errorMessage>
    </validationRules-->
     <!--validationRules>
        <fullName>Min_Ded_Amt_if_Percentage_NotBlank</fullName>
        <active>false</active>
        <description>Minimum Deduction Amount must be entered when Percentage field is not null.
Minimum Deduction Amount must be greater than Zero.</description>
        <errorConditionFormula>OR(AMT_PLAN_PMT_PCT_MIN__c &lt;= 0,
 AND(NOT( ISBLANK( NBR_PCTG__c ) ),
     ISBLANK(AMT_PLAN_PMT_PCT_MIN__c)
 ) 
)</errorConditionFormula>
        <errorDisplayField>AMT_PLAN_PMT_PCT_MIN__c</errorDisplayField>
        <errorMessage>Minimum Deduction Amount must be entered when the Percentage value is populated. 
Minimum Deduction Amount must be greater than Zero.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
   <!--validationRules>
        <fullName>Percentage_Not_deletable</fullName>
        <active>false</active>
        <description>once the record is created , Percentage cannot be changed
Either of Amount of Percentage must be entered
Percentage cannot be less than Zero</description>
        <errorConditionFormula>OR(
    AND( NOT( ISNEW() ) ,
        ISCHANGED( NBR_PCTG__c )
    ),
    AND(
NOT( ISNEW() ) ,
        ISBLANK( AMT_PLAN_PMT__c ),
        ISBLANK( NBR_PCTG__c ) 
    ),
    AND(
NOT( ISNEW() ) ,
        NOT( ISBLANK( NBR_PCTG__c )),
        NBR_PCTG__c &lt;= 0) ,
    AND(Not(Isnew()),Not(ISBLANK( AMT_PLAN_PMT__c )),
        NOT(ISBLANK( NBR_PCTG__c ) ))
)</errorConditionFormula>
        <errorDisplayField>NBR_PCTG__c</errorDisplayField>
        <errorMessage>once the record is created , Percentage cannot be changed.
Either of Amount or Percentage must be entered.
Percentage cannot be less than Zero.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>NBR_PCTG_If_AMT_PLAN_PMT_PCT_Not_Blank</fullName>
        <active>false</active>
        <errorConditionFormula>AND(NOT(ISBLANK(  AMT_PLAN_PMT_PCT_MIN__c )), ISBLANK( NBR_PCTG__c ))</errorConditionFormula>
        <errorDisplayField>NBR_PCTG__c</errorDisplayField>
        <errorMessage>Percentage must be entered if Minimum Deduction Amount has been entered.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Owner_County__c</fullName>
        <label>Owner County</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00005</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Common_County__c</fullName>
        <label>Other County</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountyWithoutOther</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/repaymentPlanFlowApexController.cls
/*************************************************************
Class Name      - repaymentPlanFlowApexController
Test Class      - repaymentPlanFlowApexController_Test
Description     - Common controller class for all Repayment Plan components
Author          - Rishav Maji
JIRA Id         - CCCAP-5785
**************************************************************/
public class repaymentPlanFlowApexController {
    
    @AuraEnabled
    public static LightningServerResponse getInitData(String recordId){
        Map<String, Object> objectData = new Map<String, Object>();
        Boolean isSuccessful = true;
        String message = '';
        try {
            Id myRecordId = Id.valueOf(recordId);
            User u = [SELECT Id, Owner_County__c, Common_County__c, Profile.Name FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
            String sObjName = myRecordId.getSObjectType().getDescribe().getName();
            objectData.put('sObjName', sObjName);
            if(sObjName == 'T_CHATS_PROVR_STATUS__c'){ // New Record Flow
                T_CHATS_PROVR_STATUS__c provr = [SELECT Id, Name FROM T_CHATS_PROVR_STATUS__c WHERE Id =: recordId Limit 1];
                objectData.put('parentObjId', provr.Id);
                objectData.put('parentObjName', provr.Name);
                objectData.put('assignedCounties', getAssignedCounties('', sObjName, u));
                objectData.put('allowedCounties', getUserCounties(u));
                //CCCAP-14993
                objectData.put('isAdmin', (FeatureManagement.checkPermission('System_Administrator') || FeatureManagement.checkPermission('CCCAP_Program_Internal_Team')) ? true : false);
            } else { // Edit Record Flow
                T_PMT_PLAN__c payPlan = [SELECT Id, IDN_PROVR__c, IDN_PROVR__r.Name, CDE_COUNTY__c FROM T_PMT_PLAN__c WHERE Id =: recordId Limit 1];
                objectData.put('parentObjId', payPlan.IDN_PROVR__c);
                objectData.put('parentObjName', payPlan.IDN_PROVR__r.Name);
                objectData.put('assignedCounties', getAssignedCounties(payPlan.CDE_COUNTY__c, sObjName, u));
                objectData.put('allowedCounties', getUserCounties(u));
                //CCCAP-14993
                objectData.put('isAdmin', (FeatureManagement.checkPermission('System_Administrator') || FeatureManagement.checkPermission('CCCAP_Program_Internal_Team')) ? true : false);
            }
        } catch (Exception e) {
            isSuccessful = false;
            message = e.getMessage();
        }
        return new LightningServerResponse(isSuccessful, message, objectData);
    }
    
    @AuraEnabled
    public static LightningServerResponse saveRepaymentPlan(T_PMT_PLAN__c repaymentPlanObj){
        List<SObject> lstSObject = new List<SObject>();
        lstSObject.add(repaymentPlanObj);
        return GenericDataSaverApxCtrl.upsertRecordsFinal(lstSObject, true);
    }
    
    public static List<String> getUserCounties(User u){
        List<String> countyList = new List<String>();
        Set<String> countyCodeSet = new Set<String>();
        if(!String.isBlank(u.Owner_County__c)){
            countyCodeSet.add(u.Owner_County__c);
        }
        if (!String.isBlank(u.Common_County__c)) {
            countyCodeSet.addAll(u.Common_County__c.split(';'));
        }
        countyList.addAll(countyCodeSet);
        return countyList;
    }
    
    public static List<Map<String, String>> getAssignedCounties(String currentCountyCode, String sObjName, User u){
        List<Map<String, String>> assignedCounties = new List<Map<String, String>>();
        Set<String> countyCodeSet = new Set<String>();
        assignedCounties.add(new Map<String, String> {'value'=>'', 'label'=>'--None--'});
        if(!String.isBlank(u.Owner_County__c)){
            countyCodeSet.add(u.Owner_County__c);
        }
        if (!String.isBlank(u.Common_County__c)) {
            countyCodeSet.addAll(u.Common_County__c.split(';'));
  }
        if(sObjName == 'T_PMT_PLAN__c' && !String.isBlank(currentCountyCode)){ // Edit Flow
            countyCodeSet.add(currentCountyCode);
        }
        System.debug('countyCodeSet-->'+countyCodeSet);
        Map<String, String> pickListValuesMap = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = T_PMT_PLAN__c.CDE_COUNTY__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        //CCCAP-14993
        if(FeatureManagement.checkPermission('System_Administrator') || FeatureManagement.checkPermission('CCCAP_Program_Internal_Team')) {
            for(Schema.PicklistEntry pickListVal : ple){
                if(pickListVal.getValue() != '66'){ // Excluding 'All County (State)' option
                    assignedCounties.add(new Map<String, String> {'value'=>pickListVal.getValue(), 'label'=>pickListVal.getLabel()});
                }
            }
        } else {
            for(Schema.PicklistEntry pickListVal : ple){
                if(pickListVal.getValue() != '66' && countyCodeSet.contains(pickListVal.getValue())){ // Excluding 'All County (State)' option
                    assignedCounties.add(new Map<String, String> {'value'=>pickListVal.getValue(), 'label'=>pickListVal.getLabel()});
                }
            }
        }
        System.debug('assignedCounties-->'+assignedCounties);
        return assignedCounties;
    }
}