CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_STATUS_PROVR__c</fullName>
        <label>License Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00692</valueSetName>
        </valueSet>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_AGRMT__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_AGRMT__c</fullName>
        <description>Renewal Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00692.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>R00692</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/T204TaskCreationBatch.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           11/27/2022                                                          
*  @description    T204 Task Creation Batch.                             
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 27-Nov-2022                                                             
*  * Author: Azharuddin Mohammad                                                     
*  * Description: Initial version 
*
*  * Version: 2.0
*  * Date: 16-Jan-2025
*  * Author: Raina Yeole
*  * Description: Updated trigger logic to 90 days from 60 and task due date to 30 days from task trigger date
*********************************************************************************************/
global with sharing class T204TaskCreationBatch implements Database.Batchable<sObject> {
    
    public String provrStatusOpen = 'Open';
    List<Task> taskstoBeCreated = new List<Task>();
    Map<String,Object> methodInfo = new Map<String,Object>{'Class__c'=>'T204TaskCreationBatch','Method__c'=>'execute'};
        Date NoDaysFromToday;  
    global Database.QueryLocator start(Database.BatchableContext bc) {
        if(!Test.isRunningTest()){
            NoDaysFromToday = System.today().addDays(integer.valueOf(System.Label.t204task_time_period));
        }else {
            NoDaysFromToday = system.today().addDays(90); // Updated logic as part of CCCAP-12518
        }
        String FAStatusOPN = 'OPN';
        String queryStr ='SELECT Id, Name, DTE_BEGIN_AGRMT__c, DTE_END_AGRMT__c, CDE_COUNTY__c, CDE_TYPE_STATUS__c, OwnerId, ID_SERVICE__c, ID_SERVICE__r.Name, ID_SERVICE__r.CDE_STATUS_PROVR__c FROM T_PROVR_FISCAL_AGREMENT__c WHERE CDE_TYPE_STATUS__c =:FAStatusOPN AND DTE_END_AGRMT__c =: NoDaysFromToday';
        return Database.getQueryLocator(queryStr);
    }
    
    global void execute(Database.BatchableContext bc, List<T_PROVR_FISCAL_AGREMENT__c> scope) {
        String FAStatusFIN = 'FIN';
        Set<Id> counties= new Set<Id>();
        Map<Id,T_PROVR_FISCAL_AGREMENT__c> FaMap = new Map<Id,T_PROVR_FISCAL_AGREMENT__c>();
        Set<Id> provIds = new Set<Id>();
        if(null!=scope &&!scope.isEmpty()){
            System.debug('Number of records fetched from start method :'+scope.size());
            for(T_PROVR_FISCAL_AGREMENT__c openFA : scope){
                if(openFA.ID_SERVICE__r.CDE_STATUS_PROVR__c == provrStatusOpen){
                    provIds.add(openFA.ID_SERVICE__c);
                    counties.add(openFA.CDE_COUNTY__c);
                    FaMap.put(openFA.Id,openFA);
                }
            }
        }
        Map<Id,T_CHATS_PROVR_STATUS__c> providers  = new Map<Id,T_CHATS_PROVR_STATUS__c>([select id,(select id,CDE_COUNTY__c,DTE_BEGIN_AGRMT__c from Provider_Fiscal_Agreements__r 
                                                                                                     where CDE_County__c in :counties and DTE_BEGIN_AGRMT__c>TODAY and CDE_TYPE_STATUS__c=:FAStatusFIN  order by DTE_BEGIN_AGRMT__c desc)  
                                                                                          FROM T_CHATS_PROVR_STATUS__c WHERE id in :provIds]);
        for(T_PROVR_FISCAL_AGREMENT__c openFA : FaMap.values()){
            List<T_PROVR_FISCAL_AGREMENT__c> finalizedFAs = providers.get(openFA.ID_Service__c)?.Provider_Fiscal_Agreements__r;
            if(finalizedFAs!=null && !finalizedFAs.isEmpty()){
                for(T_PROVR_FISCAL_AGREMENT__c finFA : finalizedFAs){
                    if(finFA.CDE_COUNTY__c == openFA.CDE_COUNTY__c && finFA.DTE_BEGIN_AGRMT__c > openFA.DTE_END_AGRMT__c){
                        FaMap.remove(openFA.Id);
                        break;
                    }
                }
            }
        }
        for(T_PROVR_FISCAL_AGREMENT__c eachFA : FaMap.values()){
            Task tsk= new Task();
            tsk.Subject = 'T204 - Fiscal Agreement Renewal Date is within 90 days';
            tsk.WhatId = eachFA.Id;
            tsk.OwnerId = eachFA.OwnerId;
            tsk.Status = 'Not Started';
            tsk.Priority = 'Normal';
            //tsk.ActivityDate= eachFA.DTE_END_AGRMT__c; // Updated logic as part of CCCAP-12518
            tsk.ActivityDate= system.today().addDays(30);
            tsk.Description = 'Provider '+ eachFA.ID_SERVICE__r.Name +' has a fiscal agreement with a Renewal Date within 90 days. Please generate a new Fiscal Agreement and obtain Provider signatures.';
            taskstoBeCreated.add(tsk);    
        }
        
        system.debug(taskstoBeCreated.size());
        system.debug('The task Info -> ' +taskstoBeCreated);
        if(null!=taskstoBeCreated&&!taskstoBeCreated.isEmpty()){
            //Database.DMLOptions dm = new Database.DMLOptions();
            //dm.EmailHeader.triggerUserEmail=true;
            //dm.optAllOrNone = false;
            GenericDMLHandler.insertRecords(taskstoBeCreated,false,methodInfo);
        }
    }
    
    global void finish(Database.BatchableContext bc) {}
}