CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Provider Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PMT_PLAN__c.object
<CustomObject>
    <description>Information on the arrangements made by a provider or case to repay a debt owed to the county/state</description>
    <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>IND_ACTIVE__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Payment Plan Active?</description>
        <label>Payment Plan Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Repayment Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Payment Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>AllfieldsenteredError</fullName>
        <active>false</active>
        <description>Error when all the fields have been entered when creating new record</description>
        <errorConditionFormula>OR(AND(ISNEW(),
OR(ISNULL( NBR_PCTG__c ),NBR_PCTG__c&lt;=0),  
ISNULL( AMT_PLAN_PMT__c ), 
ISNULL(  AMT_PLAN_PMT_PCT_MIN__c)
),
AND(ISNEW(),
OR(NOT(ISNULL( NBR_PCTG__c )),NBR_PCTG__c&lt;=0),  
NOT(ISNULL( AMT_PLAN_PMT__c ))), 
And(
ISNEW(),
NBR_PCTG__c&lt;=0
))</errorConditionFormula>
        <errorMessage>Either of Payment plan amount or Percentage must be entered. Percentage must be greater than 0.</errorMessage>
    </validationRules-->
     <!--validationRules>
        <fullName>Min_Ded_Amt_if_Percentage_NotBlank</fullName>
        <active>false</active>
        <description>Minimum Deduction Amount must be entered when Percentage field is not null.
Minimum Deduction Amount must be greater than Zero.</description>
        <errorConditionFormula>OR(AMT_PLAN_PMT_PCT_MIN__c &lt;= 0,
 AND(NOT( ISBLANK( NBR_PCTG__c ) ),
     ISBLANK(AMT_PLAN_PMT_PCT_MIN__c)
 ) 
)</errorConditionFormula>
        <errorDisplayField>AMT_PLAN_PMT_PCT_MIN__c</errorDisplayField>
        <errorMessage>Minimum Deduction Amount must be entered when the Percentage value is populated. 
Minimum Deduction Amount must be greater than Zero.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
   <!--validationRules>
        <fullName>Percentage_Not_deletable</fullName>
        <active>false</active>
        <description>once the record is created , Percentage cannot be changed
Either of Amount of Percentage must be entered
Percentage cannot be less than Zero</description>
        <errorConditionFormula>OR(
    AND( NOT( ISNEW() ) ,
        ISCHANGED( NBR_PCTG__c )
    ),
    AND(
NOT( ISNEW() ) ,
        ISBLANK( AMT_PLAN_PMT__c ),
        ISBLANK( NBR_PCTG__c ) 
    ),
    AND(
NOT( ISNEW() ) ,
        NOT( ISBLANK( NBR_PCTG__c )),
        NBR_PCTG__c &lt;= 0) ,
    AND(Not(Isnew()),Not(ISBLANK( AMT_PLAN_PMT__c )),
        NOT(ISBLANK( NBR_PCTG__c ) ))
)</errorConditionFormula>
        <errorDisplayField>NBR_PCTG__c</errorDisplayField>
        <errorMessage>once the record is created , Percentage cannot be changed.
Either of Amount or Percentage must be entered.
Percentage cannot be less than Zero.</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>NBR_PCTG_If_AMT_PLAN_PMT_PCT_Not_Blank</fullName>
        <active>false</active>
        <errorConditionFormula>AND(NOT(ISBLANK(  AMT_PLAN_PMT_PCT_MIN__c )), ISBLANK( NBR_PCTG__c ))</errorConditionFormula>
        <errorDisplayField>NBR_PCTG__c</errorDisplayField>
        <errorMessage>Percentage must be entered if Minimum Deduction Amount has been entered.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/classes/PaymentPlanServices_Test.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           11/22/2017                                                          
*  @description    Test class for Payment Plan Trigger                           
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 22-Nov-2017                                                             
*  * Author: Bharadwaj Gaddam                                                      
*  * Description: Initial version                                                 
*                                                                                 
*********************************************************************************************/

@isTest
private class PaymentPlanServices_Test {
    @testSetup static void setup() {
        List<T_CHATS_PROVR_STATUS__c> providerList = new List<T_CHATS_PROVR_STATUS__c >();
        List<T_PMT_PLAN__c> paymntList = new List<T_PMT_PLAN__c>();
        
        for(Integer i=0;i<201;i++) {
            providerList.add(new T_CHATS_PROVR_STATUS__c(NAM_FACILITY__c = 'abc'));
        }
    
        insert providerList;
        
        for(Integer i=0;i<201;i++) {
            paymntList.add((T_PMT_PLAN__c)TestClassUtility.createPaymentPlan(false,providerList[i].Id,null,10,10));
        }
    
        insert paymntList;       

    }    
    static testMethod void testEndPreviousStatus() {
        T_CHATS_PROVR_STATUS__c provider= new T_CHATS_PROVR_STATUS__c(NAM_FACILITY__c = 'abc');
        insert provider;
        
        Test.startTest();
        T_PMT_PLAN__c paymentplan1 = TestClassUtility.createPaymentPlan(true,provider.Id,null,10,10);
        T_PMT_PLAN__c paymentplan2 = TestClassUtility.createPaymentPlan(true,provider.Id,null,20,10);
        system.assertEquals(false,[Select IND_ACTIVE__c from T_PMT_PLAN__c where Id=:paymentplan1.Id].IND_ACTIVE__c,'Previous Payment Plan is not deactivated');

        system.assertEquals(true,[Select IND_ACTIVE__c from T_PMT_PLAN__c where Id=:paymentplan2.Id].IND_ACTIVE__c,'New Payment Plan is not activated');

        Test.stopTest();
    }

    static testMethod void testEndPreviousStatusBulk() {
        List<T_PMT_PLAN__c> paymntList = new List<T_PMT_PLAN__c>();
        for(T_CHATS_PROVR_STATUS__c provider:[Select Id from T_CHATS_PROVR_STATUS__c Limit 210]) {
            paymntList.add((T_PMT_PLAN__c)TestClassUtility.createPaymentPlan(false,provider.Id,null,10,10));
            
        }
        Test.startTest();
        insert paymntList; 
        PaymentPlanServices.activePaymentPlanCheck(paymntList);
        PaymentPlanServices.deactivatePreviousPlan(paymntList);
        PaymentPlanServices.countyCheck(paymntList,true);
        
        Test.stopTest();
        for(T_PMT_PLAN__c paymentPl:[Select IND_ACTIVE__c from T_PMT_PLAN__c where Id NOT IN:paymntList Limit 210]) {
            system.assertEquals(false,paymentPl.IND_ACTIVE__c,'Previous Payment Plan is not deactivated');
        } 
        
        for(T_PMT_PLAN__c paymentPl:[Select IND_ACTIVE__c from T_PMT_PLAN__c where Id IN:paymntList Limit 210]) {
            system.assertEquals(true,paymentPl.IND_ACTIVE__c,'New Payment Plan is not activated');
        }
    }
}