CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_RAT_FEES__c.object
<CustomObject>
    <fields>
        <fullName>IDN_FISCAL_SCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Rate Schedule</description>
        <label>Rate Schedule</label>
        <referenceTo>T_FISCAL_SCH__c</referenceTo>
        <relationshipLabel>ART Fees</relationshipLabel>
        <relationshipName>RAT_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ART Fees</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ART Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_SCH__c.object
<CustomObject>
    <fields>
        <fullName>IDN_AGRMT_FISCAL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement</description>
        <label>Fiscal Agreement</label>
        <referenceTo>T_PROVR_FISCAL_AGREMENT__c</referenceTo>
        <relationshipLabel>Rate Schedules</relationshipLabel>
        <relationshipName>Rate_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Schedules</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/classes/RATFeesServices.cls
public with sharing class RATFeesServices {
    public static final String CR707RsnCode = 'CR0016';
    public static void triggerCorspdCR707(List<T_FISCAL_RAT_FEES__c> newRATFeesList){
        set<Id> rateSchedules = new set<Id>();
        Map<string,string> keyParams = new Map<string, string>();
        integer countyCode;
        
        for(T_FISCAL_RAT_FEES__c eachRATFees: newRATFeesList){
            if(eachRATFees.IDN_FISCAL_SCH__c != NULL){
               rateSchedules.add(eachRATFees.IDN_FISCAL_SCH__c );
            }
        }
        
        map<Id, T_FISCAL_SCH__c> ratFeesFiscalAgrmntMap = new map<Id, T_FISCAL_SCH__c>([select Id, IDN_AGRMT_FISCAL__c, IDN_AGRMT_FISCAL__r.Name, IDN_AGRMT_FISCAL__r.CDE_COUNTY__r.CDE_COUNTY__c, IDN_AGRMT_FISCAL__r.ID_SERVICE__r.Name FROM T_FISCAL_SCH__c WHERE Id IN:rateSchedules]);
        
        for(Id eachRateSchedule: ratFeesFiscalAgrmntMap.keySet()){
            if(ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__r.CDE_COUNTY__c != NULL){
                decimal cntyCode = ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__r.CDE_COUNTY__r.CDE_COUNTY__c;
                countyCode = integer.valueOf(cntyCode);
            }
            if(ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__c != NULL){
                keyParams.put('faId', ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__c);
            }
            if(ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__r.ID_SERVICE__c != NULL){
                keyParams.put('providerId', ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__r.ID_SERVICE__r.Name);
            }            
            CorspdTrigger.createCorspdRequest(CR707RsnCode,NULL,NULL,countyCode,keyParams);
        }
    }

}