CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>CDE_STATUS_PROVR__c</fullName>
        <label>License Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00692</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_PROVR__c</fullName>
        <label>Provider Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00691</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NAM_FACILITY__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Provider Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_CBC__c.object
<CustomObject>
    <fields>
        <fullName>CDE_BGC_CHK_STATUS__c</fullName>
        <inlineHelpText>Not Cleared Status: Only select this status if the system should also close all Open Fiscal Agreements for this provider.</inlineHelpText>
        <label>Background Check Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00865</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_CBC_STATUS__c</fullName>
        <label>CBC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00724</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Background Check</relationshipLabel>
        <relationshipName>Providers_CBC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NAM_FIRST__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_LAST__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTE_ProvFinFA_CareEff__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fiscal Agreement/Reimbursement Effective</label>
        <type>Date</type>
    </fields>
    <label>Provider Background Check</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Providers Background Check</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>ProvFinFA_CareEff_noFutureDate</fullName>
        <active>false</active>
        <errorConditionFormula>DTE_ProvFinFA_CareEff__c &gt; TODAY()</errorConditionFormula>
        <errorDisplayField>DTE_ProvFinFA_CareEff__c</errorDisplayField>
        <errorMessage>Date entered should be less than or equal to today.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_AGRMT__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_RCV_AGRMT_FISCAL__c</fullName>
        <description>Date Received</description>
        <label>Date Fiscal Agreement Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <label>Draft</label>
    </recordTypes>
    <recordTypes>
        <fullName>Finalized</fullName>
        <active>true</active>
        <label>Finalized</label>
    </recordTypes>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00692.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>R00692</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00724.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MYT</fullName>
        <label>May Take</label>
    </customValue>
    <customValue>
        <fullName>MST</fullName>
        <label>Must Take</label>
    </customValue>
    <customValue>
        <fullName>WTR</fullName>
        <label>Awaiting Results</label>
    </customValue>
    <customValue>
        <fullName>CLR</fullName>
        <label>Clear</label>
    </customValue>
    <customValue>
        <fullName>NAT</fullName>
        <label>No Action Taken</label>
    </customValue>
    <masterLabel>R00724</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00865.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>Not Cleared</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <description>Background Check Status Values</description>
    <masterLabel>R00865</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/providerCBCTriggerTest.cls
@isTest
public class providerCBCTriggerTest {
    
    static testmethod void testProviderCBCTrigger(){
        T_CHATS_PROVR_STATUS__c provrObj = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'abc', CDE_STATUS_PROVR__c = 'Open', TXT_CHATS_RATING__c = 'abcdef');
        insert provrObj;
        
        T_CHATS_PROVR_STATUS__c provrObj1 = new T_CHATS_PROVR_STATUS__c (NAM_FACILITY__c = 'abcd', CDE_STATUS_PROVR__c = 'Open', TXT_CHATS_RATING__c = 'abcdefg',CDE_TYPE_PROVR__c = 'EFACH');
        insert provrObj1;
        
        T_COUNTY__c countyObj = new T_COUNTY__c (CDE_COUNTY__c = 3);
        insert countyObj;
        T_COUNTY__c countyObj2 = new T_COUNTY__c (CDE_COUNTY__c = 4);
        insert countyObj2;
        
        Id recordTypeId = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Finalized').getRecordTypeId();
        T_PROVR_FISCAL_AGREMENT__c fiscAgrmntObj = new T_PROVR_FISCAL_AGREMENT__c (RecordTypeId = recordTypeId, CDE_TYPE_STATUS__c = 'FIN', 
                                                                                   ID_SERVICE__c = provrObj.Id, CDE_COUNTY__c = countyObj.Id, 
                                                                                   DTE_BEGIN_AGRMT__c = date.today(), DTE_RCV_AGRMT_FISCAL__c = date.today());
        insert fiscAgrmntObj;
        
        Id recordTypeId2 = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Draft').getRecordTypeId();
        T_PROVR_FISCAL_AGREMENT__c fiscAgrmntObj2 = new T_PROVR_FISCAL_AGREMENT__c (RecordTypeId = recordTypeId2, CDE_TYPE_STATUS__c = 'DFT', 
                                                                                   ID_SERVICE__c = provrObj1.Id, CDE_COUNTY__c = countyObj2.Id, 
                                                                                   DTE_BEGIN_AGRMT__c = date.today(), DTE_RCV_AGRMT_FISCAL__c = date.today(),
                                                                                   ownerId = Userinfo.getUserId());
        insert fiscAgrmntObj2;
        
        T_PROVR_CBC__c provrCBC = new T_PROVR_CBC__c (CDE_CBC_STATUS__c = 'MST', NAM_FIRST__c = 'fname', NAM_LAST__c = 'lname',
                                                      IDN_PROVR__c = provrObj.Id, CDE_BGC_CHK_STATUS__c = 'Cleared',
                                                      DTE_ProvFinFA_CareEff__c = System.today());
        
        T_PROVR_CBC__c provrCBC1 = new T_PROVR_CBC__c (CDE_CBC_STATUS__c = 'MST', NAM_FIRST__c = 'fname', NAM_LAST__c = 'lname',
                                                      IDN_PROVR__c = provrObj1.Id, CDE_BGC_CHK_STATUS__c = 'Cleared',
                                                      DTE_ProvFinFA_CareEff__c = System.today());
        
        Test.startTest();
        insert provrCBC;
        insert provrCBC1;
        for(Task taskeach:[Select Id, Subject from Task Limit 10]) {
            system.assertEquals(true, taskeach.subject.contains('T202') || taskeach.subject.contains('T218'), 'Task subject should be matching');
        }
        provrCBC.DTE_ProvFinFA_CareEff__c = null;
        update provrCBC;
        provrCBC.DTE_ProvFinFA_CareEff__c = System.today();
        update provrCBC;
        provrCBC1.DTE_ProvFinFA_CareEff__c = null;
        update provrCBC1;
        provrCBC1.DTE_ProvFinFA_CareEff__c = System.today();
        update provrCBC1;
        Test.stopTest();
    }
}