CHATS_SIT/force-app/main/default/objects/T_COUNTY_RATE__c.object
<CustomObject>
    <description>County Rate</description>
    <fields>
        <fullName>CFS_Q1__c</fullName>
        <label>CFS_Q1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_YES_NO</valueSetName>
        </valueSet>
    </fields>

    <fields>
        <fullName>RATE_TYPE__c</fullName>
        <description>RATE_TYPE</description>
        <label>RATE_TYPE</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00751</valueSetName>
        </valueSet>
    </fields>
    <label>County Rate Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Rate Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Approved Plan cannot be updated</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)), TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/RT_YES_NO.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <default>true</default>
        <label>No</label>
    </customValue>
    <description>RT_YES_NO</description>
    <masterLabel>RT_YES_NO</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/APXInputPicklistCtrl.cls
/**
* This class is a server side controller for LIInputPicklist
* @author Nikunj Nilesh Doshi (ndoshi@deloitte.com)
*/
public class APXInputPicklistCtrl {

/**
*@description This method is responsible for returning the picklist values for the field mentioned.
* @param String which is the Object Api Name
* @param String which is the Picklist Field Api Name
* @return picklistValues
*/

    @AuraEnabled
    public static List<PicklistEntryDefinition> getPicklistValues(String obj, String fld) {
        List<PicklistEntryDefinition> picklistValues = new List<PicklistEntryDefinition>();
        //Removed unused variable on 5/13/2018 BG          
        for(Schema.PicklistEntry p : Schema.getGlobalDescribe().get(obj).getDescribe().fields.getMap().get(fld).getDescribe().getPicklistValues()) {
            //Added as part of HF_CHATS_20_09_2018
            if(obj=='T_COUNTY_RATE__c' && fld=='Rate_Type__c'){
                List<String> lstRestrictedRateTypes = Label.Inactive_Rate_Type.split(';');
                if(!lstRestrictedRateTypes.contains(p.getValue()) ){
                    picklistValues.add(new PicklistEntryDefinition(p));  
                }
            }
            else if(obj=='T_COUNTY_RATE__c' && fld=='CFS_Q1__c'){
                string label = p.getLabel();
                
                if(label == 'No'){
                   label = 'No (If this is a change from Yes to No, Counties must close the active Slot Contract Addendum records to align with effective date of this County Rate Plan. Please confirm in County Rate Plan notes.)';
                }
                picklistValues.add(new PicklistEntryDefinition(label, p.getValue(), p.isDefaultValue()));
            }
            else{
                picklistValues.add(new PicklistEntryDefinition(p));
            }
        }
        return picklistValues;
    }

    public class PicklistEntryDefinition implements Comparable {
        @AuraEnabled
        public String label {get; private set;}

        @AuraEnabled
        public String value {get; private set;}
 
        @AuraEnabled
        public Boolean isDefaultValue {get; private set;}

        public PicklistEntryDefinition(Schema.PicklistEntry p) {
            label = p.getLabel();
            value = p.getValue();
            isDefaultValue = p.isDefaultValue();
        }
        public PicklistEntryDefinition(String labelstr, String valuestr, Boolean isDefault) {
            label = labelstr;
            value = valuestr;
            isDefaultValue = isDefault;
        }

        public Integer compareTo(Object compareTo){
        /**
        *@description This method is responsible for comparing the picklist values for the field mentioned to the ones present in the system
        * @param String which is the Object Api Name
        * @return 0 if values are equal.
        */
            PicklistEntryDefinition compareToPL = (PicklistEntryDefinition)compareTo; 
            if (value == compareToPL.value){
              return 0;   
            } 
            if (value > compareToPL.value){
                return 1; 
            }
                
            return -1; 
        }
    }
}