CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>DTE_RCVD_PACKET_REDET__c</fullName>
        <description>Redetermination Packet Received Date</description>
        <label>Redetermination Packet Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_SENT_PACKET_REDET__c</fullName>
        <description>Redetermination Packet Sent Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Redetermination Packet Sent Date</label>
        <type>Date</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>CDE_MODE_CASE__c</fullName>
        <description>Case Mode</description>
        <label>Case Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00358</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00358.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INT</fullName>
        <label>Intake</label>
    </customValue>
    <customValue>
        <fullName>ONG</fullName>
        <label>Ongoing</label>
    </customValue>
    <customValue>
        <fullName>RED</fullName>
        <label>Redetermination</label>
    </customValue>
    <description>R00358</description>
    <masterLabel>R00358</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/T309TaskCreationBatch_Test.cls
@isTest
public class T309TaskCreationBatch_Test {
    @testSetup static void setup(){
        T_COUNTY__c countyRec = TestClassUtility.createCounty('Denver', 'Denver', 16, true);
        T_SBSD_CASE__c caseRec = TestClassUtility.createCase(false, countyRec.Id);
        caseRec.DTE_RCVD_PACKET_REDET__c =Date.today()-13;
        caseRec.DTE_SENT_PACKET_REDET__c = Date.today()-15;
        insert caseRec;
        
    }
    @isTest
    public static void testMethod1(){
        T_SBSD_CASE__c csRec = [select id from T_SBSD_CASE__c limit 1];
        T_SBSD_CASE_STATUS_MODE__c caseStaMod = TestClassUtility.createCaseStatusMode(false, csRec.Id);
        caseStaMod.DTE_BEGIN_EFFV__c = Date.today()-15;
        caseStaMod.CDE_MODE_CASE__c = 'RED';
        Test.startTest();
        Insert caseStaMod;
        T309TaskCreationBatch sh1 = new T309TaskCreationBatch();     
        String sch = '0  00 1 3 * ?';
        String jobId = system.schedule('Test', sch, sh1);
        Test.stopTest();
    }
    @istest()
    public static void testMethod2(){
        Test.startTest();
        try{
            integer k = 1/0;
        }catch(exception e){
            T309TaskCreationBatch.setException(e);
        }
        
        Test.stopTest();
    }
}