CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_PLAN__c.object
<CustomObject>
    <description>County Plans</description>
    <fields>
        <fullName>CDE_COUNTY_PLAN_TEMPLT__c</fullName>
        <description>County Plan Template</description>
        <label>County Plan Template Chosen</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_COUNTY_PLAN_TEMPLT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Plan</relationshipLabel>
        <relationshipName>County2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFEV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFEV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ELIGIBILITY_Q4__c</fullName>
        <description>ELIGIBILITY_Q4</description>
        <label>ELIGIBILITY_Q4</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Once the plan is in an Approved status, users should not be able to edit</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)),  TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PRIM_ACTV__c.object
<CustomObject>
    <description>Case-Individual Activity</description>
    
    <fields>
        <fullName>DTE_BEGIN_ACTV_PRIM__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_ACTV_PRIM__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Primary Activity</relationshipLabel>
        <relationshipName>T_SBSD_INDIV22</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Primary Activity</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Primary Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Primary Activity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PRIM_ACTV_CNTR__c.object
<CustomObject>
    <description>Individual Activity and training</description>
    <fields>
        <fullName>CNT_WEEKS__c</fullName>
        <label>Weeks Used</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Primary Activity Counter</relationshipLabel>
        <relationshipName>Primary_Activity_Counter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PRIM_ACTV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Activity ID</label>
        <referenceTo>T_PRIM_ACTV__c</referenceTo>
        <relationshipLabel>Primary Activity Counter</relationshipLabel>
        <relationshipName>Primary_Activity_Counter</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Primary Activity Counter</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Primary Activity Counter ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Primary Activity Counter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/RT_COUNTY_PLAN_TEMPLT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>County Specific Template</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <isActive>false</isActive>
        <label>2</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <isActive>false</isActive>
        <label>4</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <isActive>false</isActive>
        <label>5</label>
    </customValue>
    <description>RT_COUNTY_PLAN_TEMPLT</description>
    <masterLabel>RT_COUNTY_PLAN_TEMPLT</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/PrimaryActivityServices_Test.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           12/8/2017                                                          
*  @description    Test class for Primary Activity Trigger                           
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 8-Dec-2017                                                             
*  * Author: Bharadwaj Gaddam                                                      
*  * Description: Initial version                                                 
*                                                                                 
*********************************************************************************************/
@isTest
private class PrimaryActivityServices_Test {
        
    static testMethod void primActBeforeInsertCheckNullEnddateTest() {
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstNameA','1','lastNameA','1','CC');
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_CASE__c sbsdcase =TestClassUtility.createCase(true,county.Id);
        TestClassUtility.createPrimaryActivity(true,sbsdcase.Id,sbsdIndiv.Id,date.newInstance(2017, 1, 15),null,'DSB');
        try{
            TestClassUtility.createPrimaryActivity(true,sbsdcase.Id,sbsdIndiv.Id,date.newInstance(2017, 12, 4),null,'EDU');
        
        }catch(Exception ex) {
            system.assertEquals(true,string.valueOf(ex.getMessage()).contains(Label.Only_have_one_effective_Primary_Activity),'Failing not due validation code in trigger');
        }
        
       }
       
    static testMethod void primActBeforeInsertCheckTypeTest() {
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstNameA','1','lastNameA','1','CC');
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_CASE__c sbsdcase =TestClassUtility.createCase(true,county.Id);
        
        List<T_PRIM_ACTV__c> primActivList = new List<T_PRIM_ACTV__c>();
        primActivList.add((T_PRIM_ACTV__c)TestClassUtility.createPrimaryActivity(false,sbsdcase.Id,sbsdIndiv.Id,date.newInstance(2017, 1, 15),date.newInstance(2017, 1, 20),'GED'));
        primActivList.add((T_PRIM_ACTV__c)TestClassUtility.createPrimaryActivity(false,sbsdcase.Id,sbsdIndiv.Id,date.newInstance(2017, 1, 15),date.newInstance(2017, 1, 20),'POS'));
       
        insert primActivList;
        
        //testing after insert createPrimaryActivityCounter method to check uto created Primary activity counter records
        
        T_PRIM_ACTV_CNTR__c primActCnt1=[Select Id,IDN_CLIENT__c,CNT_WEEKS__c,IDN_PRIM_ACTV__c from T_PRIM_ACTV_CNTR__c where IDN_PRIM_ACTV__c =:primActivList[0].Id];
        system.assertEquals(primActivList[0].Id,primActCnt1.IDN_PRIM_ACTV__c,'Problem in Primary Activity');
        system.assertEquals(primActivList[0].IDN_CLIENT__c,primActCnt1.IDN_CLIENT__c,'Problem in Individual');
        system.assertEquals(0,primActCnt1.CNT_WEEKS__c,'Value is other than Zero');
        
        T_PRIM_ACTV_CNTR__c primActCnt2=[Select Id,IDN_CLIENT__c,CNT_WEEKS__c,IDN_PRIM_ACTV__c from T_PRIM_ACTV_CNTR__c where IDN_PRIM_ACTV__c =:primActivList[1].Id];
        system.assertEquals(primActivList[1].Id,primActCnt2.IDN_PRIM_ACTV__c,'Problem in Primary Activity');
        system.assertEquals(primActivList[1].IDN_CLIENT__c,primActCnt2.IDN_CLIENT__c,'Problem in Individual');
        system.assertEquals(0,primActCnt2.CNT_WEEKS__c,'Value is other than Zero');
        
        
        try{
           TestClassUtility.createPrimaryActivity(true,sbsdcase.Id,sbsdIndiv.Id,date.newInstance(2017, 1, 12),null,'GED'); 
           TestClassUtility.createPrimaryActivity(true,sbsdcase.Id,sbsdIndiv.Id,date.newInstance(2017, 1, 13),date.newInstance(2017, 1, 25),'GED'); 
           TestClassUtility.createPrimaryActivity(true,sbsdcase.Id,sbsdIndiv.Id,date.newInstance(2017, 1, 17),date.newInstance(2017, 1, 25),'GED');
        
        }catch(Exception ex) {
            system.assertEquals(true,string.valueOf(ex.getMessage()).contains(Label.The_Individual_already_has_an_existing_primary_activity_GED_ESL_ABE ),'Failing not due validation code in trigger');
        }
        
        try{
            TestClassUtility.createPrimaryActivity(true,sbsdcase.Id,sbsdIndiv.Id,date.newInstance(2017, 1, 17),date.newInstance(2017, 1, 25),'POS');
        
        }catch(Exception ex) {
            system.assertEquals(true,string.valueOf(ex.getMessage()).contains(Label.The_Individual_already_has_an_existing_primary_activity_POS),'Failing not due validation code in trigger');
        }
        
       }
       
    static testMethod void primActBeforeInsertCheckJobsearchUtilizeTest() {
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstNameA','1','lastNameA','1','CC');
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_CASE__c sbsdcase =TestClassUtility.createCase(true,county.Id);
        T_COUNTY_PLAN__c  countyPlan = TestClassUtility.createCountyPlan('',false);
        countyPlan.CDE_COUNTY__c=county.Id;
        countyPlan.ELIGIBILITY_Q4__c=10;
        countyPlan.DTE_BEGIN_EFFEV__c = system.today()+1;
        countyPlan.DTE_END_EFFEV__c = system.today()+11;
        countyPlan.CDE_COUNTY_PLAN_TEMPLT__c='1';
        insert countyPlan;
        
        T_PRIM_ACTV__c primActExisting=TestClassUtility.createPrimaryActivity(true,sbsdcase.Id,sbsdIndiv.Id,system.today()-350,null,'JS');
        TestClassUtility.createPrimaryActivityCNTR(true,sbsdIndiv.Id,primActExisting.Id,15);
        
        try{
            TestClassUtility.createPrimaryActivity(true,sbsdcase.Id,sbsdIndiv.Id,system.today(),null,'JS');
        
        }catch(Exception ex) {
            //Bharadwaj to fix
            system.assertEquals(false,string.valueOf(ex.getMessage()).contains(Label.The_Individual_has_already_reached_the_time_limit_for_Job_Search_in_the_past_yea),'Failing not due validation code in trigger');
        }
        
       }
       
       static testMethod void primActBeforeUpdateCheckNullEnddateTest() {
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstNameA','1','lastNameA','1','CC');
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_CASE__c sbsdcase =TestClassUtility.createCase(true,county.Id);
        
        List<T_PRIM_ACTV__c> primActivList = new List<T_PRIM_ACTV__c>();
        primActivList.add((T_PRIM_ACTV__c)TestClassUtility.createPrimaryActivity(false,sbsdcase.Id,sbsdIndiv.Id,system.today()-100,system.today()+20,'GED'));
        primActivList.add((T_PRIM_ACTV__c)TestClassUtility.createPrimaryActivity(false,sbsdcase.Id,sbsdIndiv.Id,system.today()+21,null,'POS'));
       
        insert primActivList;  
        
        try{
            primActivList[0].DTE_END_ACTV_PRIM__c=null;
            update primActivList[0];
        }catch(Exception ex) {
            system.assertEquals(true,string.valueOf(ex.getMessage()).contains(Label.Only_have_one_effective_Primary_Activity),'Failing not due validation code in trigger');
        }
        
       }
       
       static testMethod void primActBeforeInsertCheckBeginDateTest() {
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstNameA','1','lastNameA','1','CC');
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_CASE__c sbsdcase =TestClassUtility.createCase(true,county.Id);
        TestClassUtility.createPrimaryActivity(true,sbsdcase.Id,sbsdIndiv.Id,system.today()-100,system.today()+100,'DSB');
        try{
            TestClassUtility.createPrimaryActivity(true,sbsdcase.Id,sbsdIndiv.Id,system.today(),null,'EDU');
        
        }catch(Exception ex) {
            system.assertEquals(true,string.valueOf(ex).contains(Label.Only_have_one_effective_Primary_Activity),'Failing not due to expected validation error'+Label.Only_have_one_effective_Primary_Activity);
        }
        
       }
       
       static testMethod void primActBeforeUpdateCheckBeginDateTest() {
        T_SBSD_INDIV__c sbsdIndiv = TestClassUtility.createIndividual(true,date.newInstance(1983, 7, 15),'firstNameA','1','lastNameA','1','CC');
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_SBSD_CASE__c sbsdcase =TestClassUtility.createCase(true,county.Id);
        List<T_PRIM_ACTV__c> primActivList = new List<T_PRIM_ACTV__c>();
        primActivList.add((T_PRIM_ACTV__c)TestClassUtility.createPrimaryActivity(false,sbsdcase.Id,sbsdIndiv.Id,system.today()-100,system.today()+20,'GED'));
        primActivList.add((T_PRIM_ACTV__c)TestClassUtility.createPrimaryActivity(false,sbsdcase.Id,sbsdIndiv.Id,system.today()+21,system.today()+110,'POS'));
       
        insert primActivList;  
        
        try{
            primActivList[1].DTE_BEGIN_ACTV_PRIM__c=system.today();
            update primActivList[1];
        }catch(Exception ex) {
            system.assertEquals(true,string.valueOf(ex.getMessage()).contains(Label.Only_have_one_effective_Primary_Activity),'Failing not due validation code in trigger');
        }
        
       }
       
}