CHATS_SIT/force-app/main/default/objects/T_COPAY_DELINQC__c.object
<CustomObject>
    <description>Information about households who have been reported as delinquent in paying their parent fee to the provider</description>
   <!--  <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_MONTH_DELINQC__c</fullName>
        <description>Delinquency Month</description>
        <label>Delinquency Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00614</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_RESOLN_DELINQC__c</fullName>
        <description>Delinquency Resolution Date</description>
        <label>Delinquency Resolution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_RPTD_DELINQC__c</fullName>
        <description>Delinquency Reported Date</description>
        <label>Delinquency Reported Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_YEAR_DELINQC__c</fullName>
        <description>Delinquency Year</description>
        <label>Delinquency Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Parent Fee Delinquency</relationshipLabel>
        <relationshipName>T_COPAY_DELINQC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_fee_Reverse_Refer_Track__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Parent fee Reverse Refer Track</label>
        <description>Whenever a new parent fee Delinquency record got created or resolution date updated need to send flag for that case to CBMS.</description>
        <type>Checkbox</type>
    </fields>
    <label>Parent Fee Delinquency</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Parent Fee Delinquency ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parent Fee Delinquencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00373</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Reverse_Refer_Track__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for marked a case that needs to be send in next file to CBMS.</description>
        <label>Case Reverse Refer Track</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHATS_Reverse_Refer_Mode__c</fullName>
    <label>CHATS Reverse Refer Mode</label>
    <description>This field is used for maintaining information about the triggers point for which Case and related information will be shared with CBMS.</description>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case Closure</fullName>
            </value>
            <value>
                <fullName>Pending Case</fullName>
            </value>
            <value>
                <fullName>Parent Fee Creation</fullName>
            </value>
            <value>
                <fullName>Parent Fee Update</fullName>
            </value>
            <value>
                <fullName>Auth Creation</fullName>
            </value>
            <value>
                <fullName>Auth Termination</fullName>
            </value>
            <value>
                <fullName>Auth Schedules Update</fullName>
            </value>
            <value>
                <fullName>Parent Fee Delinquency Creation</fullName>
            </value>
            <value>
                <fullName>Parent Fee Delinquency Resolution Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00373.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CW</fullName>
        <label>Child Welfare Child Care</label>
    </customValue>
    <customValue>
        <fullName>FT</fullName>
        <label>Transitional TANF</label>
    </customValue>
    <customValue>
        <fullName>LI</fullName>
        <label>Low Income Child Care</label>
    </customValue>
    <customValue>
        <fullName>TF</fullName>
        <label>TANF</label>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
        <isActive>false</isActive>
        <label>Employment First</label>
    </customValue>
    <description>R00373</description>
    <masterLabel>R00373</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00614.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>January</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>February</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>March</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>April</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>May</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>June</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>July</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>August</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>September</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>October</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>November</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>December</label>
    </customValue>
    <description>R00614</description>
    <masterLabel>R00614</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/parentFeeDelinquencyServices.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           11/16/2017                                                          
*  @description    Handler class for Parent Fee Delinquency Trigger                             
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 16-Nov-2017                                                             
*  * Author: Azharuddin Mohammad                                                      
*  * Description: Initial version                                                 
*  *CHAT-1044: Can only be Month of Reported Delinquency Date, month before, or 2 months before
*  *CHAT-1048: Can only be Year of DTE_RPTD_DELINQC, year of month before, or year of 2 months before
*********************************************************************************************/
public class parentFeeDelinquencyServices {
    public static void delinqcMonthYear(List<T_COPAY_DELINQC__c> newParentFeeDelinqcList){
        for(T_COPAY_DELINQC__c eachPFDelinqc : newParentFeeDelinqcList){
            if(eachPFDelinqc.DTE_RPTD_DELINQC__c != null){
                date rptdDate = eachPFDelinqc.DTE_RPTD_DELINQC__c;
                integer rptdDelinqcMonth = rptdDate.month();
                String rptdDelinqcMonth_str = string.valueOf(rptdDelinqcMonth);
                integer Year = rptdDate.year();
                integer pYear = Year - 1;
                String rptdDelinqcYear = string.valueOf(Year);
                String prvYear = string.valueOf(pYear);
                integer prev1MonthInteger = rptdDelinqcMonth - 1;
                integer prev2MonthInteger = rptdDelinqcMonth - 2;
                String prev1MonthInteger_str = string.valueOf(prev1MonthInteger);
                String prev2MonthInteger_str = string.valueOf(prev2MonthInteger);
                
                if(rptdDelinqcMonth > 2){
                    if(eachPFDelinqc.DTE_MONTH_DELINQC__c != null){
                        if( (eachPFDelinqc.DTE_MONTH_DELINQC__c != rptdDelinqcMonth_str)  && (eachPFDelinqc.DTE_MONTH_DELINQC__c != prev1MonthInteger_str) && 
                           (eachPFDelinqc.DTE_MONTH_DELINQC__c != prev2MonthInteger_str)){  // IronDome fix
                               eachPFDelinqc.DTE_MONTH_DELINQC__c.addError('Delinquency Month accepts values only for previous two months range');    
                           }
                    }
                    if(eachPFDelinqc.DTE_YEAR_DELINQC__c != null){
                        if(eachPFDelinqc.DTE_YEAR_DELINQC__c != rptdDelinqcYear){
                            eachPFDelinqc.DTE_YEAR_DELINQC__c.addError('Delinquency Year accepts values only for previous two months range');
                        }
                    }
                }
                
                if(rptdDelinqcMonth == 2) {
                    if(eachPFDelinqc.DTE_MONTH_DELINQC__c != null){
                        if( (eachPFDelinqc.DTE_MONTH_DELINQC__c != rptdDelinqcMonth_str)     &&
                           (eachPFDelinqc.DTE_MONTH_DELINQC__c != prev1MonthInteger_str)  && 
                           (eachPFDelinqc.DTE_MONTH_DELINQC__c != '12')){
                               eachPFDelinqc.DTE_MONTH_DELINQC__c.addError('Delinquency Month accepts values only for previous two months range');
                           }
                    }
                    if(eachPFDelinqc.DTE_YEAR_DELINQC__c != null){
                        if(eachPFDelinqc.DTE_MONTH_DELINQC__c != null){
                            if( ((eachPFDelinqc.DTE_MONTH_DELINQC__c != rptdDelinqcMonth_str) || (eachPFDelinqc.DTE_YEAR_DELINQC__c != rptdDelinqcYear))  &&
                               ((eachPFDelinqc.DTE_MONTH_DELINQC__c != prev1MonthInteger_str) || (eachPFDelinqc.DTE_YEAR_DELINQC__c != rptdDelinqcYear)) && 
                               ((eachPFDelinqc.DTE_MONTH_DELINQC__c != '12') || (eachPFDelinqc.DTE_YEAR_DELINQC__c != prvYear)) ){
                                   eachPFDelinqc.addError('Delinquency Month & Year accepts values only for previous two months range');
                               }
                        }else{
                            if((eachPFDelinqc.DTE_YEAR_DELINQC__c != rptdDelinqcYear) && (eachPFDelinqc.DTE_YEAR_DELINQC__c != prvYear)){
                                eachPFDelinqc.DTE_YEAR_DELINQC__c.addError('Delinquency Year accepts values only for previous two months range');
                            }
                        }
                    }
                }
                if(rptdDelinqcMonth == 1){
                    if(eachPFDelinqc.DTE_MONTH_DELINQC__c != null){
                        if( (eachPFDelinqc.DTE_MONTH_DELINQC__c != rptdDelinqcMonth_str)     &&
                           (eachPFDelinqc.DTE_MONTH_DELINQC__c != '12') &&
                           (eachPFDelinqc.DTE_MONTH_DELINQC__c != '11')){
                               eachPFDelinqc.DTE_MONTH_DELINQC__c.addError('Delinquency Month accepts values only for previous two months range');
                           }
                    }
                    if(eachPFDelinqc.DTE_YEAR_DELINQC__c != null){
                        if(eachPFDelinqc.DTE_MONTH_DELINQC__c != null){
                            if( ((eachPFDelinqc.DTE_MONTH_DELINQC__c != rptdDelinqcMonth_str) || (eachPFDelinqc.DTE_YEAR_DELINQC__c != rptdDelinqcYear))     &&
                               ((eachPFDelinqc.DTE_MONTH_DELINQC__c != '12') || (eachPFDelinqc.DTE_YEAR_DELINQC__c != prvYear)) && 
                               ((eachPFDelinqc.DTE_MONTH_DELINQC__c != '11') || (eachPFDelinqc.DTE_YEAR_DELINQC__c != prvYear)) ){
                                   eachPFDelinqc.addError('Delinquency Month & Year accepts values only for previous two months range');
                               }
                        }else{
                            if((eachPFDelinqc.DTE_YEAR_DELINQC__c != rptdDelinqcYear) && (eachPFDelinqc.DTE_YEAR_DELINQC__c != prvYear)){
                                eachPFDelinqc.DTE_YEAR_DELINQC__c.addError('Delinquency Year accepts values only for previous two months range');
                            }
                        }
                    }
                }   //Rptd Date month is January
            }//Rptd Date is not null
        }
    }// end of delinqcMonthYear method
    
    // for CCCAP-10162 by Shashank
    public static void markReverseRefOnCase(Map<Id,T_COPAY_DELINQC__c> newParentFeeDelinqcMap,Map<Id,T_COPAY_DELINQC__c> oldParentFeeDelinqcMap){
        List<T_SBSD_CASE__c> cases = new list<T_SBSD_CASE__c>();
        List<T_COPAY_DELINQC__c> parentFeetoUpdate = new List<T_COPAY_DELINQC__c>();
        String mode = Trigger.isInsert?'Parent Fee Delinquency Creation':'Parent Fee Delinquency Resolution Update';
        Map<Id,Id> copayVsCase = new Map<Id,Id>();
        Map<Id,T_SBSD_CASE__c> caseMap = new Map<Id,T_SBSD_CASE__c>();
        for(T_COPAY_DELINQC__c eachPFDelinqc : newParentFeeDelinqcMap.values()){
            if(Trigger.isInsert 
               || (eachPFDelinqc.DTE_RESOLN_DELINQC__c!=null && eachPFDelinqc.DTE_RESOLN_DELINQC__c !=oldParentFeeDelinqcMap.get(eachPFDelinqc.Id).DTE_RESOLN_DELINQC__c)){
                   copayVsCase.put(eachPFDelinqc.Id,eachPFDelinqc.IDN_CASE__c);
               }
        }
        for(T_SBSD_CASE__c chatsCase : [select id,CHATS_Reverse_Refer_Mode__c,Program_Type__c
                                        from T_SBSD_CASE__c where id in:copayVsCase.values() and CHATS_Reverse_Refer_Mode__c excludes(:mode) and Program_Type__c in ('TF','LI')])
        {
            caseMap.put(chatsCase.Id,chatsCase);
        }
        for(T_COPAY_DELINQC__c eachPFDelinqc : newParentFeeDelinqcMap.values()){
            if(caseMap.containsKey(eachPFDelinqc.IDN_CASE__c)){
                T_SBSD_CASE__c chatsC = caseMap.get(eachPFDelinqc.IDN_CASE__c);
                chatsC.CHATS_Reverse_Refer_Mode__c = chatsC.CHATS_Reverse_Refer_Mode__c!=null?chatsC.CHATS_Reverse_Refer_Mode__c+';'+mode :mode;
                chatsC.Case_Reverse_Refer_Track__c = true;
                cases.add(chatsC);
                parentFeetoUpdate.add(new T_COPAY_DELINQC__c(Id=eachPFDelinqc.Id,Parent_fee_Reverse_Refer_Track__c = true));
            }
        }
        if(!cases.isEmpty()){
            GenericDMLHandler.updateRecords(cases, new Map<String,Object>{'byPassObjects'=>new Set<String>{'T_SBSD_Case__c'},'Class__c'=>'parentFeeDelinquencyServices','Method__c'=>'markReverseRefOnCase'});
        }
        if(!parentFeetoUpdate.isEmpty()){
            update parentFeetoUpdate;
        }
    }
}