CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_PLAN__c.object
<CustomObject>
    <description>County Plans</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Plan</relationshipLabel>
        <relationshipName>County2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>Status</description>
        <label>Status(old)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00676</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ELIGIBILITY_Q2_1__c</fullName>
        <description>ELIGIBILITY_Q2_1</description>
        <label>ELIGIBILITY_Q2_1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ELIGIBILITY_Q3_1__c</fullName>
        <description>ELIGIBILITY_Q3_1</description>
        <label>ELIGIBILITY_Q3_1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ELIGIBILITY_Q4__c</fullName>
        <description>ELIGIBILITY_Q4</description>
        <label>ELIGIBILITY_Q4</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>County Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Once the plan is in an Approved status, users should not be able to edit</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)),  TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PRIM_ACTV__c.object
<CustomObject>
    <description>Case-Individual Activity</description>
    
    <fields>
        <fullName>CDE_TYPE_ACTV__c</fullName>
        <description>Primary Activity</description>
        <label>Primary Activity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00738</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_ACTV_PRIM__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_ACTV_PRIM__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Primary Activity</relationshipLabel>
        <relationshipName>T_SBSD_CASE12</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Primary Activity</relationshipLabel>
        <relationshipName>T_SBSD_INDIV22</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ignore__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ignore</label>
        <type>Checkbox</type>
    </fields>
    <label>Primary Activity</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Primary Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Primary Activity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PRIM_ACTV_CNTR__c.object
<CustomObject>
    <description>Individual Activity and training</description>
    <fields>
        <fullName>CNT_WEEKS__c</fullName>
        <label>Weeks Used</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Primary Activity Counter</relationshipLabel>
        <relationshipName>Primary_Activity_Counter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IDN_PRIM_ACTV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Activity ID</label>
        <referenceTo>T_PRIM_ACTV__c</referenceTo>
        <relationshipLabel>Primary Activity Counter</relationshipLabel>
        <relationshipName>Primary_Activity_Counter</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Primary Activity Counter</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Primary Activity Counter ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Primary Activity Counter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_ASST_HSNG__c</fullName>
        <description>Does the household receive benefits from Housing Voucher or Cash Assistance?</description>
        <label>Household receives Voucher/Cash Asst?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00717</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IND_ASSIST_PROVR__c</fullName>
        <description>Did a provider assist you in completing</description>
        <label>Provider assisted with application?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00619</valueSetName>
        </valueSet>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Date Person Entered Home</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <formula>IDN_CASE__r.CDE_COUNTY__c</formula>
        <label>code county</label>
        <type>Text</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>CDE_MODE_CASE__c</fullName>
        <description>Case Mode</description>
        <label>Case Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00358</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS_CASE__c</fullName>
        <description>Case Status</description>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00357</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00357.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>REO</fullName>
        <label>Reopen</label>
    </customValue>
    <description>R00357</description>
    <masterLabel>R00357</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00358.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INT</fullName>
        <label>Intake</label>
    </customValue>
    <customValue>
        <fullName>ONG</fullName>
        <label>Ongoing</label>
    </customValue>
    <customValue>
        <fullName>RED</fullName>
        <label>Redetermination</label>
    </customValue>
    <description>R00358</description>
    <masterLabel>R00358</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00619.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <description>R00619</description>
    <masterLabel>R00619</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00676.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PEN</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>SUB</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>APV</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>NRV</fullName>
        <label>Need Revision</label>
    </customValue>
    <description>R00676</description>
    <masterLabel>R00676</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00717.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Unknown</label>
    </customValue>
    <description>R00717</description>
    <masterLabel>R00717</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00738.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DSB</fullName>
        <label>Incapacitated</label>
    </customValue>
    <customValue>
        <fullName>EDU</fullName>
        <label>Teen Parent Education</label>
    </customValue>
    <customValue>
        <fullName>EMP</fullName>
        <label>Employment/Self Employment</label>
    </customValue>
    <customValue>
        <fullName>GED</fullName>
        <label>GED/ESL/ABE (max 12 months)</label>
    </customValue>
    <customValue>
        <fullName>JS</fullName>
        <label>Job Search</label>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
        <label>Post Secondary Education / Job Skills (max 48 months)</label>
    </customValue>
    <customValue>
        <fullName>SUD</fullName>
        <label>Substance Use Disorder (max 12 months)</label>
    </customValue>
    <description>R00738</description>
    <masterLabel>R00738</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/primaryActivityCounterTriggerTest.cls
@isTest
public class primaryActivityCounterTriggerTest {
    static testmethod void testPrimaryActivityCounterTrigger() {
        //County object
        test.startTest();
        T_COUNTY__c countyObj = new T_COUNTY__c (  CDE_COUNTY__c = 3 );
        insert countyObj;
        T_COUNTY_PLAN__c countyPlanObj = new T_COUNTY_PLAN__c(	CDE_COUNTY__c = countyObj.Id, CDE_STATUS__c = 'APV', 
                                                              	ELIGIBILITY_Q2_1__c = 105, ELIGIBILITY_Q3_1__c = 50, ELIGIBILITY_Q4__c = 15);
        insert countyPlanObj;
        
        T_SBSD_CASE__c caseObj = new T_SBSD_CASE__c (   CDE_COUNTY__c = countyObj.Id, IND_ASSIST_PROVR__c = 'N', CDE_ASST_HSNG__c = 'N');
        T_SBSD_CASE__c caseObj2 = new T_SBSD_CASE__c (CDE_COUNTY__c = countyObj.Id, IND_ASSIST_PROVR__c = 'N', CDE_ASST_HSNG__c = 'N');
        insert new List<T_SBSD_CASE__c>{caseObj, caseObj2};
            
       T_SBSD_INDIV__c adultIndiv = TestClassUtility.createIndividual(true, Date.today().addYears(-30), 'AdultFirst', '1', 'AdultLast', '123456789', 'CC');
       T_SBSD_CASE_INDIV__c caseIndivPC = TestClassUtility.createCaseIndividual(true,caseObj2.Id, adultIndiv.Id, true);

        
        T_SBSD_CASE_STATUS_MODE__c caseStatModeObj = new T_SBSD_CASE_STATUS_MODE__c(    DTE_BEGIN_EFFV__c = date.today(), IDN_CASE__c = caseObj.Id,
                                                                                        CDE_MODE_CASE__c = 'ONG', CDE_STATUS_CASE__c = 'OPN'
                                                                                   );
        T_SBSD_CASE_STATUS_MODE__c caseStatModeObj2 = new T_SBSD_CASE_STATUS_MODE__c(DTE_BEGIN_EFFV__c = date.today(), IDN_CASE__c = caseObj2.Id,
                                                                                        CDE_MODE_CASE__c = 'ONG', CDE_STATUS_CASE__c = 'OPN'
                                                                                   );
        insert new List<T_SBSD_CASE_STATUS_MODE__c>{caseStatModeObj, caseStatModeObj2};
        
        T_PRIM_ACTV__c prmryActvtyObj = new T_PRIM_ACTV__c(	IDN_CASE__c = caseObj.Id, DTE_BEGIN_ACTV_PRIM__c = system.today(),
                                                          	DTE_END_ACTV_PRIM__c = system.today() + 1, Ignore__c = true,
                                                          	CDE_TYPE_ACTV__c = 'JS'
                                                          );
        T_PRIM_ACTV__c prmryActvtyObj2 = new T_PRIM_ACTV__c(IDN_CASE__c = caseObj2.Id, DTE_BEGIN_ACTV_PRIM__c = system.today(),
                                                          	DTE_END_ACTV_PRIM__c = system.today() + 1, Ignore__c = true,
                                                          	CDE_TYPE_ACTV__c = 'SUD'
                                                          );
        insert new List<T_PRIM_ACTV__c>{prmryActvtyObj, prmryActvtyObj2};
        
        T_PRIM_ACTV_CNTR__c prmryActvtyCntr = new T_PRIM_ACTV_CNTR__c(	IDN_PRIM_ACTV__c = prmryActvtyObj.Id, CNT_WEEKS__c = 13);
        T_PRIM_ACTV_CNTR__c prmryActvtyCntr2 = new T_PRIM_ACTV_CNTR__c(	IDN_PRIM_ACTV__c = prmryActvtyObj2.Id, CNT_WEEKS__c = 50, IDN_CLIENT__c=adultIndiv.Id);
        insert new List<T_PRIM_ACTV_CNTR__c>{prmryActvtyCntr, prmryActvtyCntr2};
        
        system.assertEquals(prmryActvtyObj.Id,[select IDN_EXTNL__c from T_PRIM_ACTV__c where Id=:prmryActvtyObj.Id].IDN_EXTNL__c,'Primary actvity External id should be matching with Record Id');
    	test.stopTest();
    }
}