CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Individual ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    

    <fields>
        <fullName>NBR_SSN__c</fullName>
        <description>SSN</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>SSN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/classes/ATSAsyncCallbackHandlerIndividualTest.cls
@isTest
private class ATSAsyncCallbackHandlerIndividualTest  {
    
    static testMethod void myUnitTest() {
        
        
        T_COUNTY__c countyRec = TestClassUtility.createCounty('Denver','Denver',1,true);
        T_SBSD_CASE__c caseRec = TestClassUtility.createCase(true, countyRec.Id);
        T_SBSD_INDIV__c individual = TestClassUtility.createIndividual(false,system.today().addYears(-15),'firstName','1','lastName','123','CC');
        individual.IDN_EXTNL__c='12345';
        
         T_SBSD_INDIV__c individual1 = TestClassUtility.createIndividual(false,system.today().addYears(-15),'firstName','1','lastName','123','CC');
        individual1.IDN_EXTNL__c='12345';
        individual1.NBR_SSN__c= '1234543212';	
        
        
        Profile prof =[select id from profile where name = 'System Administrator'];
        User us = [select id,profileId from user where profileId =:prof.Id and IsActive = true LIMIT 1];
        
        System.runAs(us){
            
            // Start the Test  
            Test.startTest();
            
            Database.Saveresult res = Database.Insert(individual);
            ATSAsyncCallbackHandlerIndividual obj = new ATSAsyncCallbackHandlerIndividual();
            obj.processSave(res);
			Database.Saveresult res1 = Database.Insert(individual1, false);
            obj.processSave(res1);
            Test.stoptest();
            
        }
        
    }
}