CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_EMPLMT_INCOME__c.object
<CustomObject>
    <description>Income information from employment for individual</description>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Verified</description>
        <label>Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AMT_INCOME_ANNUAL_ESTMD__c</fullName>
        <description>Estimated Annual Income</description>
        <label>Estimated Income</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_FREQ_PAY_ESTMD__c</fullName>
        <description>Estimated Pay Frequency</description>
        <label>Estimated Income Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00341</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CNT_WEEK_PER_HOURS_ESTMD__c</fullName>
        <description>Estimated Hours per Week</description>
        <label>Estimated Hours per Week</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Income Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EMPLMT_INDIV__c</fullName>
        <description>Employment ID</description>
        <label>Employment ID</label>
        <referenceTo>T_SBSD_INDIV_EMPLMT__c</referenceTo>
        <relationshipLabel>Employment Income</relationshipLabel>
        <relationshipName>T_SBSD_INDIV_EMPLMT1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>JIRA CHAT - 2779,2778</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00848</valueSetName>
        </valueSet>
    </fields>
    <label>Employment Income</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Date Person Entered Home</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_EMPLMT__c.object
<CustomObject>
    <description>Employer information</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>ADR_CITY__c</fullName>
        <description>City</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADR_LINE_1__c</fullName>
        <description>Address Line 1</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADR_LINE_2__c</fullName>
        <description>Address Line 2</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Line 2</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADR_STATE__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00002</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADR_ZIP_EXTN__c</fullName>
        <description>Zip Ext.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Zip Ext.</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADR_ZIP_MAIN__c</fullName>
        <description>Zip</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Employment Begin Date</description>
        <label>Employment Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Employment End Date</description>
        <label>Employment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>T_SBSD_INDIV19</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_STUBS_PAY_RCVS__c</fullName> 
        <description>Job started within the last 60 days?</description>
        <label>Job started within the last 60 days?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00619</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NAM_BUSNS__c</fullName>
        <description>Employer/Business Name</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Employer/Business Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Employment</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Employment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_CDE_SOURCE_VRFYD_SE</fullName>
        <active>false</active>
        <description>CDE_SOURCE_VRFYD_SE is required when T_SBSD_INDIV_EMPLMT, CDE_TYPE_VRFYD_SE is &quot;Written Verification&quot; and Self-Employment record type.</description>
        <errorConditionFormula>OR(AND(ISNEW(),NOT(IDN_CLIENT__r.Is_Peak_Data__c),NOT(IDN_CLIENT__r.Is_CBMS_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)),AND(NOT(ISNEW()),NOT( ISCHANGED(CDE_WAGE_MIN__c)), NOT(IDN_CLIENT__r.Is_Peak_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_SE__c</errorDisplayField>
        <errorMessage>How Verified is required if Verified is &apos;Written Verification&apos;</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00341.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2PM</fullName>
        <label>Twice per Month</label>
    </customValue>
    <customValue>
        <fullName>1PY</fullName>
        <label>Once a Year</label>
    </customValue>
    <customValue>
        <fullName>2PY</fullName>
        <label>Twice a Year</label>
    </customValue>
    <customValue>
        <fullName>E2M</fullName>
        <label>Every Other Month</label>
    </customValue>
    <customValue>
        <fullName>E2W</fullName>
        <label>Every Two Weeks</label>
    </customValue>
    <customValue>
        <fullName>HLY</fullName>
        <label>Hourly</label>
    </customValue>
    <customValue>
        <fullName>MON</fullName>
        <label>Monthly</label>
    </customValue>
    <customValue>
        <fullName>ONE</fullName>
        <label>One Time Only</label>
    </customValue>
    <customValue>
        <fullName>QRT</fullName>
        <label>Quarterly</label>
    </customValue>
    <customValue>
        <fullName>WKY</fullName>
        <label>Weekly</label>
    </customValue>
    <description>R00341</description>
    <masterLabel>R00341</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00367.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Available</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <label>Verbal Verification</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Written Verification</label>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
        <isActive>false</isActive>
        <label>CV</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
        <isActive>false</isActive>
        <label>N/A-adult caretaker</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <isActive>false</isActive>
        <label>SV</label>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
        <isActive>false</isActive>
        <label>N/A-not requesting child</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>R00367</description>
    <masterLabel>R00367</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00619.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <description>R00619</description>
    <masterLabel>R00619</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00848.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACT</fullName>
        <default>true</default>
        <label>Active</label>
    </customValue>
    <customValue>
        <fullName>INA</fullName>
        <label>Inactive</label>
    </customValue>
    <masterLabel>R00848</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/IndividualEmploymentTest.cls
@isTest
public class IndividualEmploymentTest {
    
    public static testMethod void testGetEmploymentDetails(){
        T_COUNTY__c countyRec = TestClassUtility.createCounty('Denver', 'Denver', 1, true);
        T_SBSD_CASE__c caseRec = TestClassUtility.createCase(true, countyRec.Id);
        T_SBSD_INDIV__c individual = TestClassUtility.createIndividual(true, system.today(), 'firstName', '1', 'lastName', '123', 'CC');
        T_SBSD_CASE_INDIV__c caseIndiv = TestClassUtility.createCaseIndividual(false, caseRec.Id, individual.Id, true);
        caseIndiv.DTE_END_EFFV__c = null;
        Insert caseIndiv;
        T_SBSD_INDIV_EMPLMT__c emp = new T_SBSD_INDIV_EMPLMT__c();
        emp.IDN_CLIENT__c = individual.Id;
        emp.ADR_CITY__c = 'TestCity';
        emp.ADR_LINE_1__c = 'Line1';
        emp.ADR_LINE_2__c = 'Line2';
        emp.ADR_ZIP_MAIN__c = '12345';
        emp.ADR_ZIP_EXTN__c = '1234';
        emp.ADR_STATE__c = 'CO';
        emp.DTE_BEGIN_EFFV__c = System.today();
        emp.IND_STUBS_PAY_RCVS__c = 'N';
        emp.NAM_BUSNS__c = 'TestBusiness';
        emp.DTE_END_EFFV__c = null;
        emp.IDN_CASE__c = caseRec.Id;
        Insert emp;
        T_EMPLMT_INCOME__c income = new T_EMPLMT_INCOME__c();
        income.IDN_EMPLMT_INDIV__c = emp.Id;
        income.CDE_STATUS__c = 'ACT';
        income.DTE_BEGIN_EFFV__c = System.today();
        income.AMT_INCOME_ANNUAL_ESTMD__c = 50;
        income.CNT_WEEK_PER_HOURS_ESTMD__c = 20;
        income.CDE_FREQ_PAY_ESTMD__c = '1PY';
        income.CDE_TYPE_VERIF__c = 'SD';
        Insert income;
        
        Test.startTest();
        LightningServerResponse response = IndividualEmployment.getEmploymentDetails(caseRec.id);
        System.debug('response:' + response.objectData);
        System.assertEquals(true, response.objectData.get('data') != null);
        List<IndivEmploymeentWrapper> data = (List<IndivEmploymeentWrapper>)response.objectData.get('data');
        Test.stopTest();
    }
}