CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_PLAN__c.object
<CustomObject>
    <description>County Plans</description>
    <fields>
        <fullName>CDE_COUNTY_PLAN_TEMPLT__c</fullName>
        <description>County Plan Template</description>
        <label>County Plan Template Chosen</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_COUNTY_PLAN_TEMPLT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Plan</relationshipLabel>
        <relationshipName>County2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFEV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IND_COUNTY_PLAN_TEMPLT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>County Plan Template Indicator</description>
        <label>County Plan Template Indicator</label>
        <type>Checkbox</type>
    </fields>
    <label>County Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Once the plan is in an Approved status, users should not be able to edit</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)),  TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/RT_COUNTY_PLAN_TEMPLT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>County Specific Template</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <isActive>false</isActive>
        <label>2</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <isActive>false</isActive>
        <label>4</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <isActive>false</isActive>
        <label>5</label>
    </customValue>
    <description>RT_COUNTY_PLAN_TEMPLT</description>
    <masterLabel>RT_COUNTY_PLAN_TEMPLT</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/countyPlanFlowController_Test.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           12/02/2017                                                          
*  @description    Test class for countyPlanFlowController class                           
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 2-Dec-2017                                                             
*  * Author: Bharadwaj Gaddam                                                      
*  * Description: Initial version                                                 
*                                                                                 
*********************************************************************************************/
@isTest
private class countyPlanFlowController_Test {
   
    static testMethod void testgetCountyPlanRecord() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_COUNTY_PLAN__c countyRatePlan=TestClassUtility.createCountyPlan('PEN',false); 
        countyRatePlan.CDE_COUNTY__c = county.Id;
        countyRatePlan.CDE_COUNTY_PLAN_TEMPLT__c = '1';
        countyRatePlan.DTE_BEGIN_EFFEV__c=System.today().addMonths(1).toStartOfMonth();
        insert countyRatePlan;
        LightningServerResponse  lightserresobj= countyPlanFlowController.getCountyPlanRecord(countyRatePlan.Id);
        system.assertEquals(true,lightserresobj.isSuccessful,'It should be successful');
        system.assertEquals('Success',lightserresobj.successMessage ,'It should be success');
        system.debug(lightserresobj.objectData.get('countyRatePlanRecord'));
        system.assert(String.valueOf(lightserresobj.objectData.get('countyPlanRecord')).Contains(countyRatePlan.Id),'It should not return null');
              
        //Exception scenario
        LightningServerResponse  lightserresobj2= countyPlanFlowController.getCountyPlanRecord(county.Id);
        system.assertEquals(false,lightserresobj2.isSuccessful,'It should be successful');
        system.assertEquals(null,lightserresobj2.objectData,'It is not returning NULL where in it supposed to return NULL');    
    }
      
    static testMethod void testgetCountyPlanRecordForTemplate() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_COUNTY_PLAN__c countyRatePlan=TestClassUtility.createCountyPlan('PEN',false); 
        countyRatePlan.CDE_COUNTY__c = county.Id;
        countyRatePlan.CDE_COUNTY_PLAN_TEMPLT__c = '1';
        countyRatePlan.IND_COUNTY_PLAN_TEMPLT__c =true;
        countyRatePlan.DTE_BEGIN_EFFEV__c=System.today().addMonths(1).toStartOfMonth();
        user u =[Select id from User where UserName='newuserchats@testorg.com'];
        system.runAs(u){
            insert countyRatePlan;
        }
        LightningServerResponse  lightserresobj= countyPlanFlowController.getCountyPlanRecordForTemplate(countyRatePlan.CDE_COUNTY_PLAN_TEMPLT__c,countyRatePlan.CDE_COUNTY__c);
        system.assertEquals(true,lightserresobj.isSuccessful,'It should be successful');
        system.assertEquals('Success',lightserresobj.successMessage ,'It should be success');
        system.debug(lightserresobj.objectData.get('countyRatePlanRecord'));
    
        //Exception scenario
        LightningServerResponse  lightserresobj2= countyPlanFlowController.getCountyPlanRecordForTemplate('error',countyRatePlan.Id);
        map<String, Object> respMap = countyPlanFlowController.ownerCountyValidation(county.Id, true);
        Boolean contyMatched = (Boolean)respMap.get('countyMatched');
        system.assertEquals(true,contyMatched);
        respMap = countyPlanFlowController.ownerCountyValidation(countyRatePlan.Id, false);
        Boolean contyMatched2 = (Boolean)respMap.get('countyMatched');
        system.assertEquals(true,contyMatched2);
        //system.assertEquals(false,lightserresobj2.isSuccessful,'It should be successful');
        //system.assertEquals(null,lightserresobj2.objectData,'It is not returning NULL where in it supposed to return NULL');    
    }
    
    static testMethod void tesGetCountyValidatedForNewCountyPlan() {        
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_COUNTY_PLAN__c countyPlan = TestClassUtility.createCountyPlan('PEN',false); 
        T_COUNTY_PLAN__c returnedCountyPlan= countyPlanFlowController.getCountyValidatedForNewCountyPlan(county.Id);
        system.assertEquals(null,returnedCountyPlan.Id,'County plan has no reocrds');
        countyPlan.CDE_COUNTY__c = county.Id;
        insert countyPlan;
        T_COUNTY_PLAN__c returnedCountyPlan1= countyPlanFlowController.getCountyValidatedForNewCountyPlan(county.Id);
        system.assertEquals(countyPlan.Id,returnedCountyPlan1.Id,'County plan has reocrds');
    }
    
    @TestSetup
    public static void testDataSetup(){
        CHATSUtility.createTemplateUser();
    }
}