CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_RATE__c.object
<CustomObject>
    <description>County Rate</description>
    <fields>
        <fullName>CDE_RATE_PLAN_TEMPLT__c</fullName>
        <description>County Rate Plan Template</description>
        <label>County Rate Plan Template</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_COUNTY_RATE_PLAN_TEMPLT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Rate Plan</relationshipLabel>
        <relationshipName>County4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_RATE_PLAN_TEMPLT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>County Rate Plan Template Indicator</description>
        <label>County Rate Plan Template Indicator</label>
        <type>Checkbox</type>
    </fields>

    <label>County Rate Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Rate Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Approved Plan cannot be updated</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)), TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/RT_COUNTY_RATE_PLAN_TEMPLT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>County Specific Template</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <isActive>false</isActive>
        <label>2</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <isActive>false</isActive>
        <label>4</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <isActive>false</isActive>
        <label>5</label>
    </customValue>
    <description>RT_COUNTY_RATE_PLAN_TEMPLT</description>
    <masterLabel>RT_COUNTY_RATE_PLAN_TEMPLT</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/countyRatePlanFlowController_Test.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           12/02/2017                                                          
*  @description    Test class for countyRatePlanFlowController class                           
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 2-Dec-2017                                                             
*  * Author: Bharadwaj Gaddam                                                      
*  * Description: Initial version                                                 
*                                                                                 
*********************************************************************************************/
@isTest
private class countyRatePlanFlowController_Test {
  
    static testMethod void testgetCountyRatePlanRecord() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_COUNTY_RATE__c countyRatePlan=TestClassUtility.createCountyRatePlan('PEN',false); 
        countyRatePlan.IDN_COUNTY__c = county.Id;
        countyRatePlan.CDE_RATE_PLAN_TEMPLT__c = '1';
        insert countyRatePlan;
        LightningServerResponse  lightserresobj= countyRatePlanFlowController.getCountyRatePlanRecord(countyRatePlan.Id);
        system.assertEquals(true,lightserresobj.isSuccessful,'It should be successful');
        system.assertEquals('Success',lightserresobj.successMessage ,'It should be success');
        system.debug(lightserresobj.objectData.get('countyRatePlanRecord'));
        system.assert(String.valueOf(lightserresobj.objectData.get('countyRatePlanRecord')).Contains(countyRatePlan.Id),'It should not return null');
      
        //Exception scenario
        LightningServerResponse  lightserresobj2= countyRatePlanFlowController.getCountyRatePlanRecord(county.Id);
        system.assertEquals(false,lightserresobj2.isSuccessful,'It should be successful');
        system.assertEquals(null,lightserresobj2.objectData,'It is not returning NULL where in it supposed to return NULL');    
    }
    
     static testMethod void testgetCountyRatePlanRecordForTemplate() {
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_COUNTY_RATE__c countyRatePlan=TestClassUtility.createCountyRatePlan('PEN',false); 
        countyRatePlan.IDN_COUNTY__c = county.Id;
        countyRatePlan.CDE_RATE_PLAN_TEMPLT__c = '1';
        countyRatePlan.IND_RATE_PLAN_TEMPLT__c =true;
        user u =[Select id from User where UserName='newuserchats@testorg.com'];
        system.runAs(u){
            insert countyRatePlan;
        }
        LightningServerResponse  lightserresobj = countyRatePlanFlowController.getCountyRatePlanRecordForTemplate(countyRatePlan.CDE_RATE_PLAN_TEMPLT__c,countyRatePlan.IDN_COUNTY__c);
        system.assertEquals(true,lightserresobj.isSuccessful,'It should be successful');
        system.assertEquals('Success',lightserresobj.successMessage ,'It should be success');
        
        map<String, Object> respMap = CountyRatePlanFlowController.ownerCountyValidation(county.Id, true);
        Boolean contyMatched = (Boolean)respMap.get('countyMatched');
        system.assertEquals(true,contyMatched);
        respMap = CountyRatePlanFlowController.ownerCountyValidation(countyRatePlan.Id, false);
        Boolean contyMatched2 = (Boolean)respMap.get('countyMatched');
        system.assertEquals(true,contyMatched2);
         
        //Exception scenario
        LightningServerResponse  lightserresobj2= countyRatePlanFlowController.getCountyRatePlanRecordForTemplate('error',countyRatePlan.Id);
        system.assertEquals(false,lightserresobj2.isSuccessful,'It should be successful');
        system.assertEquals(new T_COUNTY_RATE__c(),lightserresobj2.objectData.get('countyRatePlanRecord'),'It is not returning NULL where in it supposed to return NULL');    
    }
    
    static testMethod void testGetCountyValidatedForNewCountyRatePlan() {        
        T_COUNTY__c county=TestClassUtility.createCounty('County1','Dept1',10,true);
        T_COUNTY_RATE__c countyRatePlan = TestClassUtility.createCountyRatePlan('PEN',false); 
        T_COUNTY_RATE__c returnedCountyRatePlan= CountyRatePlanFlowController.getCountyValidatedForNewRatePlan(county.Id);
        system.assertEquals(null,returnedCountyRatePlan.Id ,'County Rate Plan has no records');
        countyRatePlan.IDN_COUNTY__c = county.Id;
        insert countyRatePlan;
        T_COUNTY_RATE__c returnedCountyRatePlan1= CountyRatePlanFlowController.getCountyValidatedForNewRatePlan(county.Id);
        system.assertEquals(countyRatePlan.Id,returnedCountyRatePlan1.Id ,'County Rate Plan has records');
    }
    
    @TestSetup
    public static void testDataSetup(){
        CHATSUtility.createTemplateUser();
    }
}