CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_INDIV_DSBLTY__c.object
<CustomObject>
    <description>Individual Disability Information</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_LENGTH_DSBLTY__c</fullName>
        <description>Incapacitation Length</description>
        <label>Incapacitation Length</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00328</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_SOURCE_DSBLTY_CHILD__c</fullName>
        <description>How Verified</description>
        <label>How Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00693</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_DSBLTY__c</fullName>
        <description>Incapacitation Type</description>
        <label>Incapacitation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00327</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Incapacitation Reported Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Incapacitation Reported Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Incapacitation End Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Incapacitation End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Disability</relationshipLabel>
        <relationshipName>T_SBSD_INDIV6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_CC_GIVE_ABLE__c</fullName>
        <description>Able to take care of children?</description>
        <label>Able to take care of children?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00619</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IND_REQMT_WORK_MEET_ABLE__c</fullName>
        <description>Individual is able to meet the work requirement</description>
        <label>Individual can meet work requirement?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00619</valueSetName>
        </valueSet>
    </fields>
    <label>Disability</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Incapacitation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_INDIV_REL__c.object
<CustomObject>
    <description>Information on how individuals on the case are related to the primary applicant</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_REL_INDIV__c</fullName>
        <description>Relationship</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00243</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT_RELTD__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Relationship (Client ID)</relationshipLabel>
        <relationshipName>Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Client ID</description>
        <label>Primary Caretaker</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>Primary_Individual_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Date Person Entered Home</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_CRTKR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is the Primary Parent/Caretaker</description>
        <label>Primary Parent/Caretaker</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>CDE_MODE_CASE__c</fullName>
        <description>Case Mode</description>
        <label>Case Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00358</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00327.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BEH</fullName>
        <label>Behavioral</label>
    </customValue>
    <customValue>
        <fullName>DEV</fullName>
        <label>Developmental</label>
    </customValue>
    <customValue>
        <fullName>PHY</fullName>
        <default>true</default>
        <label>Physical</label>
    </customValue>
    <description>R00327</description>
    <masterLabel>R00327</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00328.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PER</fullName>
        <label>Permanent</label>
    </customValue>
    <customValue>
        <fullName>TMP</fullName>
        <label>Temporary</label>
    </customValue>
    <description>R00328</description>
    <masterLabel>R00328</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00358.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INT</fullName>
        <label>Intake</label>
    </customValue>
    <customValue>
        <fullName>ONG</fullName>
        <label>Ongoing</label>
    </customValue>
    <customValue>
        <fullName>RED</fullName>
        <label>Redetermination</label>
    </customValue>
    <description>R00358</description>
    <masterLabel>R00358</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00619.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <description>R00619</description>
    <masterLabel>R00619</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00693.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DST</fullName>
        <label>Doctor&apos;s Statement</label>
    </customValue>
    <customValue>
        <fullName>FSP</fullName>
        <label>Family Service Plan (FSP)</label>
    </customValue>
    <customValue>
        <fullName>IEP</fullName>
        <label>Individual Education Plan (IEP)</label>
    </customValue>
    <customValue>
        <fullName>IHP</fullName>
        <label>Individual Health Care Plan (IHP)</label>
    </customValue>
    <customValue>
        <fullName>TF</fullName>
        <label>TANF File</label>
    </customValue>
    <description>R00693</description>
    <masterLabel>R00693</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/DisabilityServicesTest.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           09/26/2017                                                          
*  @description    Test class for DisabilityServices
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 17-Nov-2017                                                             
*  * Author: Shubham Jain                                                      
*  * Description: Initial version                                                 
*                                                                                 
*  * Version: 2.0                                                                             
*  * Date: 27-Apr-2017                                                             
*  * Author: Shubham Jain                                                      
*  * Description: Added start & stop method to fix 101 SOQL error.

*********************************************************************************************/
@isTest
public class DisabilityServicesTest {
    public static testMethod void testUpdateFieldsForPrimaryCaretaker(){
        List<T_SBSD_INDIV__c> individuals = [SELECT Id FROM T_SBSD_INDIV__c limit 100];
        System.assertEquals(false, individuals.isEmpty(), 'individuals should not be empty');
        T_INDIV_DSBLTY__c indivDisablity = new T_INDIV_DSBLTY__c(IDN_CLIENT__c = individuals.get(0).Id,
                                                                 CDE_TYPE_DSBLTY__c = 'BEH',
                                                                 DTE_BEGIN_EFFV__c = System.today(),
                                                                 IND_CC_GIVE_ABLE__c = 'Y',
                                                                 CDE_SOURCE_DSBLTY_CHILD__c = 'DST'
                                                                );
        insert indivDisablity;
        List<T_INDIV_DSBLTY__c> insertedIndividualDisablity = [SELECT IND_REQMT_WORK_MEET_ABLE__c FROM T_INDIV_DSBLTY__c limit 100];
        System.assertEquals(1, insertedIndividualDisablity.size(), 'insertedIndividualDisablity should not be empty');
        System.assertEquals('N', insertedIndividualDisablity.get(0).IND_REQMT_WORK_MEET_ABLE__c, 'IND_REQMT_WORK_MEET_ABLE__c should be N');
        
        List<T_SBSD_CASE_INDIV__c> caseIndividuals = [SELECT Id,IND_CRTKR__c, IDN_CASE__c FROM T_SBSD_CASE_INDIV__c limit 100];
        System.assertEquals(false, caseIndividuals.isEmpty(), 'caseIndividuals should not be empty');
        insert new T_SBSD_CASE_STATUS_MODE__c(
            IDN_CASE__c = caseIndividuals.get(0).IDN_CASE__c,
            CDE_MODE_CASE__c = 'INT',
            DTE_BEGIN_EFFV__c = System.today()-5,
            DTE_END_EFFV__c = System.today()+5
        );              
        
        caseIndividuals.get(0).IND_CRTKR__c = true;
        update caseIndividuals;
        
        try{
            indivDisablity.IND_CC_GIVE_ABLE__c = 'N';
            update indivDisablity;
            System.assert(true, 'This state should not be executed');
        }catch(Exception ex){
            indivDisablity.CDE_LENGTH_DSBLTY__c = 'PER';
        }
        update indivDisablity;
        insertedIndividualDisablity = [SELECT IND_REQMT_WORK_MEET_ABLE__c FROM T_INDIV_DSBLTY__c WHERE Id = :indivDisablity.Id];
        System.assertEquals(1, insertedIndividualDisablity.size(), 'insertedIndividualDisablity should not be empty');
        //System.assertEquals('Y', insertedIndividualDisablity.get(0).IND_REQMT_WORK_MEET_ABLE__c, 'IND_REQMT_WORK_MEET_ABLE__c should be changed to Y');
    }
    
    public static testMethod void testUpdateFieldsForRelatedPrimaryCaretaker(){
        CaseLastUpdatedServices.isPeakApplicationContext = true;
        List<T_SBSD_INDIV__c> individuals = [SELECT Id FROM T_SBSD_INDIV__c limit 100];
        System.assertEquals(false, individuals.isEmpty(), 'individuals should not be empty');
        
        List<T_SBSD_CASE_INDIV__c> caseIndividuals = [SELECT Id,IND_CRTKR__c, IDN_CASE__c FROM T_SBSD_CASE_INDIV__c limit 100];
        System.assertEquals(false, caseIndividuals.isEmpty(), 'caseIndividuals should not be empty');
        insert new T_SBSD_CASE_STATUS_MODE__c(
            IDN_CASE__c = caseIndividuals.get(0).IDN_CASE__c,
            CDE_MODE_CASE__c = 'INT',
            DTE_BEGIN_EFFV__c = System.today()-5,
            DTE_END_EFFV__c = System.today()+5
        );              
        caseIndividuals.get(0).IND_CRTKR__c = true;
        update caseIndividuals;
        
        List<T_SBSD_CASE__c> caseRecords = [SELECT Id FROM T_SBSD_CASE__c limit 100];
        System.assertEquals(false, caseRecords.isEmpty(), 'caseRecords should not be empty');
        
        Test.startTest();
        CaseLastUpdatedServices.isPeakApplicationContext = true;
        
        T_SBSD_INDIV__c indivRec = TestClassUtility.createIndividual(true,System.today().addYears(-15), 'firstNameB','1', 'lastNameB','123456780','CC');
        insert new T_SBSD_CASE_INDIV__c(IND_CRTKR__c=false, IDN_CASE__c=caseRecords.get(0).Id,IDN_CLIENT__c=indivRec.Id, DTE_BEGIN_EFFV__c = System.today().addDays(-5));
        
        //T_INDIV_REL__c relationship = new T_INDIV_REL__c(IDN_CLIENT_RELTD__c = indivRec.Id, IDN_CLIENT__c = individuals.get(0).Id, CDE_TYPE_REL_INDIV__c = 'M');
        //insert relationship;
        
        //System.assertEquals(true,relationship.Id!=null, 'relationship should be successfully inserted');
        
        T_INDIV_DSBLTY__c indivDisablity = new T_INDIV_DSBLTY__c(IDN_CLIENT__c = indivRec.Id,
                                                                 CDE_TYPE_DSBLTY__c = 'BEH',
                                                                 DTE_BEGIN_EFFV__c = System.today(),
                                                                 IND_CC_GIVE_ABLE__c = 'Y'
                                                                );
        
        try{
            insert indivDisablity;
            System.assert(true, 'This code should not be reachable');
        }catch(Exception ex){
            indivDisablity.CDE_LENGTH_DSBLTY__c = 'PER';
            indivDisablity.CDE_SOURCE_DSBLTY_CHILD__c = 'DST';
            insert indivDisablity;
        }
        List<T_INDIV_DSBLTY__c> insertedIndividualDisablity = [SELECT IND_REQMT_WORK_MEET_ABLE__c FROM T_INDIV_DSBLTY__c WHERE Id = :indivDisablity.Id];
        System.assertEquals(1, insertedIndividualDisablity.size(), 'insertedIndividualDisablity should not be empty');
        Test.stopTest();
        // System.assertEquals('Y', insertedIndividualDisablity.get(0).IND_REQMT_WORK_MEET_ABLE__c, 'IND_REQMT_WORK_MEET_ABLE__c should be Y');
    }
    
    public static testMethod void testUpdateFieldsForAge(){
        List<T_SBSD_CASE__c> caseRecords = [SELECT Id FROM T_SBSD_CASE__c limit 100];
        System.assertEquals(false, caseRecords.isEmpty(), 'caseRecords should not be empty');
        
        T_SBSD_INDIV__c indivRec = TestClassUtility.createIndividual(true,System.today().addYears(-25), 'firstNameB','1', 'lastNameB','123456780','CC');
        T_INDIV_DSBLTY__c indivDisablity = new T_INDIV_DSBLTY__c(IDN_CLIENT__c = indivRec.Id,
                                                                 CDE_TYPE_DSBLTY__c = 'BEH',
                                                                 DTE_BEGIN_EFFV__c = System.today(),
                                                                 IND_CC_GIVE_ABLE__c = 'Y'
                                                                );
        try{
            insert indivDisablity;
            System.assert(true, 'This code should not be reachable');
        }catch(Exception ex){
            indivDisablity.CDE_LENGTH_DSBLTY__c = 'PER';
            indivDisablity.CDE_SOURCE_DSBLTY_CHILD__c = 'DST';
            insert indivDisablity;
        }
        List<T_INDIV_DSBLTY__c> insertedIndividualDisablity = [SELECT IND_REQMT_WORK_MEET_ABLE__c FROM T_INDIV_DSBLTY__c WHERE Id = :indivDisablity.Id];
        System.assertEquals(1, insertedIndividualDisablity.size(), 'insertedIndividualDisablity should not be empty');
        // System.assertEquals('Y', insertedIndividualDisablity.get(0).IND_REQMT_WORK_MEET_ABLE__c, 'IND_REQMT_WORK_MEET_ABLE__c should be Y');
    }
    
    
    @testSetup
    public static void setUpData(){
        User user;
        Profile userProfile=[Select id from Profile where Name ='System Administrator'];
        user = TestClassUtility.createUser(userProfile.Id , 'test','test','test@example.com','test@example.com.uesername','ttes');
        
        if(user!=null){
        	insert user;
        }
             
        System.runAs(user){
            T_COUNTY__c countyRec = TestClassUtility.createCounty('Denver','Denver',1,true);
            T_SBSD_CASE__c caseRec = TestClassUtility.createCase(true,countyRec.Id);
            T_SBSD_INDIV__c indivRec = TestClassUtility.createIndividual(true,System.today().addYears(-15), 'firstNameA','1', 'lastNameA','123456789','CC');
            insert new T_SBSD_CASE_INDIV__c(IND_CRTKR__c=false, IDN_CASE__c=caseRec.Id,IDN_CLIENT__c=indivRec.Id, DTE_BEGIN_EFFV__c = System.today().addDays(-5));
        }
    }
}