CHATS_SIT/force-app/main/default/objects/T_COUNTY_PLAN__c.object
<CustomObject>
    <description>County Plans</description>
    <fields>
        <fullName>CCCAP_Q1__c</fullName>
        <description>CCCAP_Q1</description>
        <label>CCCAP_Q1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_YES_NO</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFEV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <label>County Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Once the plan is in an Approved status, users should not be able to edit</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)),  TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/RT_YES_NO.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <default>true</default>
        <label>No</label>
    </customValue>
    <description>RT_YES_NO</description>
    <masterLabel>RT_YES_NO</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CompareCountyPlanTemplateControllerTest.cls
@isTest
public class CompareCountyPlanTemplateControllerTest {
     static testmethod void testcomparecountyPlanTemplateController(){
        test.startTest(); 
        TestClassUtility.createCounty('countyName', 'countyDepartmentName', 01, true);
        T_COUNTY_PLAN__c countyPlan = TestClassUtility.createCountyPlan('PEN', false);
        //countyPlan.DTE_BEGIN_EFFEV__c = Date.valueOf(Label.CP_JS_Activation_Date);
        //DateTime jsActivationDate = (DateTime)JSON.deserialize('"' + Label.CP_JS_Activation_Date + '"', DateTime.class);
        countyPlan.DTE_BEGIN_EFFEV__c =  System.today().addDays(10) ;
        insert countyPlan;
        
        PageReference pageRef = Page.countyPlanTemplate;
        //Removed unused variable on 5/14/2018 BG  
        ApexPages.currentPage().getParameters().put('countyPlanId', countyPlan.Id);
        system.assertEquals('No',CompareCountyPlanTemplateController.getCountyPlan().CCCAP_Q1__c,'County plan CCCAP_Q1 should be null');
        system.assertEquals(true,CompareCountyPlanTemplateController.getJsActivated(),'JS Activation should be true');
        system.assertEquals(true,CompareCountyPlanTemplateController.getTTANFRemoved(),'TTANF Rmoved should be true');
        test.stopTest();        
    }

}