CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_PLAN__c.object
<CustomObject>
    <description>County Plans</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Plan</relationshipLabel>
        <relationshipName>County2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>Status</description>
        <label>Status(old)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00676</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFEV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFEV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ELIGIBILITY_Q2_1__c</fullName>
        <description>ELIGIBILITY_Q2_1</description>
        <label>ELIGIBILITY_Q2_1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ELIGIBILITY_Q3_1__c</fullName>
        <description>ELIGIBILITY_Q3_1</description>
        <label>ELIGIBILITY_Q3_1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ELIGIBILITY_Q4__c</fullName>
        <description>ELIGIBILITY_Q4</description>
        <label>ELIGIBILITY_Q4</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Once the plan is in an Approved status, users should not be able to edit</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)),  TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PRIM_ACTV__c.object
<CustomObject>
    <description>Case-Individual Activity</description>
    
    <fields>
        <fullName>DTE_END_ACTV_PRIM__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Primary Activity</relationshipLabel>
        <relationshipName>T_SBSD_CASE12</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Primary Activity</relationshipLabel>
        <relationshipName>T_SBSD_INDIV22</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Primary Activity</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Primary Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Primary Activity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PRIM_ACTV_CNTR__c.object
<CustomObject>
    <description>Individual Activity and training</description>
    <fields>
        <fullName>CDE_TYPE__c</fullName>
        <formula>CASE( IDN_PRIM_ACTV__r.CDE_TYPE_ACTV__c, &quot;GED&quot;, &quot;GED/ESL/ABE&quot;, &quot;JS&quot;, &quot;Job Search&quot;, &quot;POS&quot;,&quot;Post-Secondary Education / Job Skills&quot;, &quot;SUD&quot;,&quot;Substance Use Disorder&quot;,&quot;&quot;)</formula>
        <label>Counter Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CNT_WEEKS__c</fullName>
        <label>Weeks Used</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Primary Activity Counter</relationshipLabel>
        <relationshipName>Primary_Activity_Counter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PRIM_ACTV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Activity ID</label>
        <referenceTo>T_PRIM_ACTV__c</referenceTo>
        <relationshipLabel>Primary Activity Counter</relationshipLabel>
        <relationshipName>Primary_Activity_Counter</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Primary Activity Counter</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Primary Activity Counter ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Primary Activity Counter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Case</relationshipLabel>
        <relationshipName>Case_County</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <formula>IDN_CASE__r.CDE_COUNTY__c</formula>
        <label>code county</label>
        <type>Text</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>CDE_MODE_CASE__c</fullName>
        <description>Case Mode</description>
        <label>Case Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00358</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS_CASE__c</fullName>
        <description>Case Status</description>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00357</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00357.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>REO</fullName>
        <label>Reopen</label>
    </customValue>
    <description>R00357</description>
    <masterLabel>R00357</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00358.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INT</fullName>
        <label>Intake</label>
    </customValue>
    <customValue>
        <fullName>ONG</fullName>
        <label>Ongoing</label>
    </customValue>
    <customValue>
        <fullName>RED</fullName>
        <label>Redetermination</label>
    </customValue>
    <description>R00358</description>
    <masterLabel>R00358</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00676.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PEN</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>SUB</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>APV</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>NRV</fullName>
        <label>Need Revision</label>
    </customValue>
    <description>R00676</description>
    <masterLabel>R00676</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/primaryActivityCounterServices.cls
//Removed DML statements from FOR loop on 5/12/18 BG                                                                   
public with sharing class primaryActivityCounterServices {
    public static void createT105task(List<T_PRIM_ACTV_CNTR__c> newPrmryCntrList) {
        Map<Id, T_PRIM_ACTV_CNTR__c> prmryActvtyCntrMap = new Map<Id, T_PRIM_ACTV_CNTR__c>();
        set<Id> caseIdsFromCaseStatus = new set<Id>();
        set<Id> prmryCntrActvty = new set<Id>();
        Map<Id, T_COUNTY_PLAN__c> cntyPlanWeekDtlsMap = new Map<Id,T_COUNTY_PLAN__c>();
        List<Task> taskList = new List<Task>();
        Map<Id, T_SBSD_CASE_INDIV__c> caseToCaseIndivMap = new Map<Id, T_SBSD_CASE_INDIV__c>();    
        
        for(T_PRIM_ACTV_CNTR__c eachPrmryCntr : newPrmryCntrList) {
            if(eachPrmryCntr.IDN_PRIM_ACTV__c != Null) {
                prmryCntrActvty.add(eachPrmryCntr.IDN_PRIM_ACTV__c);
            }
        }
        system.debug('prmrycntractvty 13 '+ prmryCntrActvty);
        for(T_PRIM_ACTV_CNTR__c eachPrmryCntr : [select Id, IDN_PRIM_ACTV__c, IDN_PRIM_ACTV__r.IDN_CASE__c, IDN_PRIM_ACTV__r.DTE_END_ACTV_PRIM__c, IDN_PRIM_ACTV__r.Name, CDE_TYPE__c, CNT_WEEKS__c, IDN_CLIENT__c FROM T_PRIM_ACTV_CNTR__c 
                                                 WHERE IDN_PRIM_ACTV__c IN:prmryCntrActvty
                                                 //AND IDN_PRIM_ACTV__r.IDN_CASE__c IN (select IDN_CASE__c  FROM T_SBSD_CASE_STATUS_MODE__c WHERE CDE_MODE_CASE__c = 'ONG' AND CDE_STATUS_CASE__c = 'OPN')
                                                 ]) {
            prmryActvtyCntrMap.put(eachPrmryCntr.IDN_PRIM_ACTV__r.IDN_CASE__c, eachPrmryCntr);
        }
        system.debug('prmryactvtycntrmap 21 '+prmryActvtyCntrMap);

        //added by Nikita for CCCAP-12153
        for(T_SBSD_CASE_INDIV__c caseIndiv : [SELECT Id, IDN_CASE__c, IDN_CLIENT__c, DTE_END_EFFV__c FROM T_SBSD_CASE_INDIV__c WHERE IDN_CASE__c IN: prmryActvtyCntrMap.keySet()]){
            if(prmryActvtyCntrMap.get(caseIndiv.IDN_CASE__c).IDN_CLIENT__c == caseIndiv.IDN_CLIENT__c){
              caseToCaseIndivMap.put(caseIndiv.IDN_CASE__c, caseIndiv);
            }
        }
        system.debug('casetocaseidivmap 28 '+caseToCaseIndivMap);
        
        for(T_SBSD_CASE_STATUS_MODE__c eachCaseStatusMode : [select Id, IDN_CASE__c, CDE_STATUS_CASE__c, CDE_MODE_CASE__c FROM T_SBSD_CASE_STATUS_MODE__c WHERE IDN_CASE__c IN:prmryActvtyCntrMap.keySet() AND CDE_MODE_CASE__c = 'ONG' AND CDE_STATUS_CASE__c = 'OPN' AND (DTE_END_EFFV__c >=: system.today() OR DTE_END_EFFV__c = Null)]) {
            caseIdsFromCaseStatus.add(eachCaseStatusMode.IDN_CASE__c);
        }
        system.debug('caseidsfromcasestatus 34 '+caseIdsFromCaseStatus);
        
        //List of all active County Plans
        for(T_COUNTY_PLAN__c eachCountyPlan : [select Id, CDE_COUNTY__c, ELIGIBILITY_Q2_1__c, ELIGIBILITY_Q3_1__c, ELIGIBILITY_Q4__c FROM T_COUNTY_PLAN__c WHERE CDE_COUNTY__c IN (select Id FROM T_COUNTY__c) AND CDE_STATUS__c = 'APV' AND DTE_BEGIN_EFFEV__c <=: system.today() AND (DTE_END_EFFEV__c >=: system.today() OR DTE_END_EFFEV__c = Null) ]) {
            cntyPlanWeekDtlsMap.put(eachCountyPlan.CDE_COUNTY__c , eachCountyPlan);
        }
        system.debug('cntyplanweekdtlsmap 40 '+cntyPlanWeekDtlsMap);
        
        //Loop cases
        for(T_SBSD_CASE__c eachCase : [select Id, Name, CDE_COUNTY__c, OwnerId FROM T_SBSD_CASE__c WHERE Id IN:prmryActvtyCntrMap.keySet() ]) {
            if(caseIdsFromCaseStatus.contains(eachCase.Id)) {
                if((prmryActvtyCntrMap.containsKey(eachCase.Id)) && (cntyPlanWeekDtlsMap.ContainsKey(eachCase.CDE_COUNTY__c)) && (caseToCaseIndivMap.ContainsKey(eachCase.Id)) && (caseToCaseIndivMap.get(eachCase.Id).DTE_END_EFFV__c == null)){
                    if( ((prmryActvtyCntrMap.get(eachCase.Id).CDE_TYPE__c == 'GED/ESL/ABE') &&  ( prmryActvtyCntrMap.get(eachCase.Id).CNT_WEEKS__c == cntyPlanWeekDtlsMap.get(eachCase.CDE_COUNTY__c).ELIGIBILITY_Q3_1__c - 2 )) || ((prmryActvtyCntrMap.get(eachCase.Id).CDE_TYPE__c == 'Job Search') &&  ( prmryActvtyCntrMap.get(eachCase.Id).CNT_WEEKS__c == cntyPlanWeekDtlsMap.get(eachCase.CDE_COUNTY__c).ELIGIBILITY_Q4__c - 2 )) || ((prmryActvtyCntrMap.get(eachCase.Id).CDE_TYPE__c == 'Post-Secondary Education / Job Skills') && (prmryActvtyCntrMap.get(eachCase.Id).CNT_WEEKS__c == cntyPlanWeekDtlsMap.get(eachCase.CDE_COUNTY__c).ELIGIBILITY_Q2_1__c - 2 ))) {
                    
                        Task taskRecrd1 = new Task( OwnerId = eachCase.OwnerId, Subject = 'T105 - Time Limited Activity End Date Approaching', Priority = 'Normal', WhatId = eachCase.Id, ActivityDate = prmryActvtyCntrMap.get(eachCase.Id).IDN_PRIM_ACTV__r.DTE_END_ACTV_PRIM__c , Description = 'Case ' + eachCase.Name + ' has 2 weeks left for ( '+prmryActvtyCntrMap.get(eachCase.Id).IDN_PRIM_ACTV__r.Name+ ' , ' +prmryActvtyCntrMap.get(eachCase.Id).CDE_TYPE__c+ ' ). Please update the primary activity.');
                        taskList.add(taskRecrd1);
                    }
                }
            
            
            // SUD task generation at 50 weeks as part of CCCAP-13790
            if(prmryActvtyCntrMap.containsKey(eachCase.Id) && 
               prmryActvtyCntrMap.get(eachCase.Id).CDE_TYPE__c == 'Substance Use Disorder' && 
               prmryActvtyCntrMap.get(eachCase.Id).CNT_WEEKS__c == 50 && 
               caseToCaseIndivMap.get(eachCase.Id).DTE_END_EFFV__c == null){
                
                Task taskRecrd2 = new Task( 
                    OwnerId = eachCase.OwnerId, 
                    Subject = 'T105 - Time Limited Activity End Date Approaching', 
                    Priority = 'Normal', 
                    WhatId = eachCase.Id, 
                    ActivityDate = prmryActvtyCntrMap.get(eachCase.Id).IDN_PRIM_ACTV__r.DTE_END_ACTV_PRIM__c, 
                    Description = 'Case ' + eachCase.Name + ' has 2 weeks left for ( '+prmryActvtyCntrMap.get(eachCase.Id).IDN_PRIM_ACTV__r.Name+ ' , ' +prmryActvtyCntrMap.get(eachCase.Id).CDE_TYPE__c+ ' ). Please update the primary activity.'
                );
                taskList.add(taskRecrd2); 
               }}
        }
        //Start of code quality change BG 5/12/18
        if(!taskList.isEmpty()) {
            try{
            GenericDMLHandler.insertRecords(taskList,null);
            } catch(Exception ex) {
                ExceptionLoggingServices.captureExceptionLog(ex, new Map<String,Object>{'Class__c'=>'primaryActivityCounterServices','Method__c'=>'createT105task'});
            }
        }
        //End of code quality change BG 5/12/18
    }
}