CHATS_SIT/force-app/main/default/objects/T_EMPLMT_INCOME__c.object
<CustomObject>
    <description>Income information from employment for individual</description>
    <fields>
        <fullName>CDE_SOURCE_VRFYD_PAY__c</fullName>
        <label>How Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CCH</fullName>
                    <label>Cancelled checks</label>
                </value>
                <value>
                    <fullName>VER</fullName>
                    <label>Collateral Contact</label>
                </value>
                <value>
                    <fullName>CWR</fullName>
                    <label>Colorado Works Referral</label>
                </value>
                <value>
                    <fullName>ELT</fullName>
                    <label>Employment letter</label>
                </value>
                <value>
                    <fullName>LGR</fullName>
                    <label>Ledger</label>
                </value>
                <value>
                    <fullName>OTH</fullName>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>OD</fullName>
                    <label>Owner&apos;s Draw</label>
                </value>
                <value>
                    <fullName>PST</fullName>
                    <label>Paystub</label>
                </value>
                <value>
                    <fullName>STB</fullName>
                    <label>Paystubs</label>
                </value>
                <value>
                    <fullName>SML</fullName>
                    <label>Self Employment Letter</label>
                </value>
                <value>
                    <fullName>TF</fullName>
                    <label>Tax Form</label>
                </value>
                <value>
                    <fullName>WNW</fullName>
                    <label>Work Number website</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_EMPLMT_INDIV__c</fullName>
        <description>Employment ID</description>
        <label>Employment ID</label>
        <referenceTo>T_SBSD_INDIV_EMPLMT__c</referenceTo>
        <relationshipLabel>Employment Income</relationshipLabel>
        <relationshipName>T_SBSD_INDIV_EMPLMT1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employment Income</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_EMPLMT__c.object
<CustomObject>
    <description>Employer information</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <label>Employment</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Employment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <recordTypes>
        <fullName>Employment</fullName>
        <active>true</active>
        <label>Employment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Self_Employment</fullName>
        <active>true</active>
        <label>Self-Employment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_CDE_SOURCE_VRFYD_SE</fullName>
        <active>false</active>
        <description>CDE_SOURCE_VRFYD_SE is required when T_SBSD_INDIV_EMPLMT, CDE_TYPE_VRFYD_SE is &quot;Written Verification&quot; and Self-Employment record type.</description>
        <errorConditionFormula>OR(AND(ISNEW(),NOT(IDN_CLIENT__r.Is_Peak_Data__c),NOT(IDN_CLIENT__r.Is_CBMS_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)),AND(NOT(ISNEW()),NOT( ISCHANGED(CDE_WAGE_MIN__c)), NOT(IDN_CLIENT__r.Is_Peak_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_SE__c</errorDisplayField>
        <errorMessage>How Verified is required if Verified is &apos;Written Verification&apos;</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/classes/employmentIncomeApexController.cls
/*************************************************************
Class Name	    - employmentIncomeApexController
Test Class	    - employmentIncomeApexController_Test
Description     - Common controller class for all Employment Income components
Author          - Rishav Maji
JIRA Id			- CCCAP-3041
**************************************************************/
public without sharing class employmentIncomeApexController {
    
    @AuraEnabled
    public static LightningServerResponse getInitData(String recordId){
        Map<String, Object> objectData = new Map<String, Object>();
        Boolean isSuccessful = true;
        String message = '';
        String employmentType;
        try {
            Id myRecordId = Id.valueOf(recordId);
            String sObjName = myRecordId.getSObjectType().getDescribe().getName();
            objectData.put('sObjName', sObjName);
            if(sObjName == 'T_EMPLMT_INCOME__c'){
                T_EMPLMT_INCOME__c emp = [SELECT Id, IDN_EMPLMT_INDIV__c, IDN_EMPLMT_INDIV__r.RecordType.DeveloperName FROM T_EMPLMT_INCOME__c WHERE Id =: recordId WITH SECURITY_ENFORCED Limit 1];
                objectData.put('employmentType', emp.IDN_EMPLMT_INDIV__r.RecordType.DeveloperName);
                objectData.put('parentObjId', emp.IDN_EMPLMT_INDIV__c);
                objectData.put('howVerifiedOptions', getHowVerifiedOptions(emp.IDN_EMPLMT_INDIV__r.RecordType.DeveloperName));
            } else {
                T_SBSD_INDIV_EMPLMT__c emp = [SELECT Id, RecordType.DeveloperName FROM T_SBSD_INDIV_EMPLMT__c WHERE Id =: recordId WITH SECURITY_ENFORCED Limit 1];
                objectData.put('employmentType', emp.RecordType.DeveloperName);
                objectData.put('parentObjId', emp.Id);
                objectData.put('howVerifiedOptions', getHowVerifiedOptions(emp.RecordType.DeveloperName));
            }
        } catch (Exception e) {
            isSuccessful = false;
            message = e.getMessage();
        }
        return new LightningServerResponse(isSuccessful, message, objectData);
    }
    
    @AuraEnabled
    public static LightningServerResponse saveEmploymentIncome(T_EMPLMT_INCOME__c empIncomeObj){
        List<SObject> lstSObject = new List<SObject>();
        lstSObject.add(empIncomeObj);
        return GenericDataSaverApxCtrl.upsertRecordsFinal(lstSObject, true);
    }
    
    public static List<Map<String, String>> getHowVerifiedOptions(String employmentType){
        String allowedOptionsLabel = employmentType == 'Self_Employment' ? System.Label.SelfEmploymentIncome_HowVerified_Options : System.Label.EmploymentIncome_HowVerified_Options;
        List<String> allowedOptions = allowedOptionsLabel.deleteWhitespace().split(',');
        List<Map<String, String>> howVerifiedOptions = new List<Map<String, String>>();
        howVerifiedOptions.add(new Map<String, String> {'value'=>'', 'label'=>'--None--'});
        Schema.DescribeFieldResult fieldResult = T_EMPLMT_INCOME__c.CDE_SOURCE_VRFYD_PAY__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry pv : picklistValues){
            if(allowedOptions.contains(pv.getValue()))
                howVerifiedOptions.add(new Map<String, String> {'value'=>pv.getValue(), 'label'=>pv.getLabel()});
        }
        return howVerifiedOptions;
    }
}