CHATS_SIT/force-app/main/default/objects/T_EMPLMT_INCOME__c.object
<CustomObject>
    <description>Income information from employment for individual</description>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Verified</description>
        <label>Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AMT_INCOME_ANNUAL_ESTMD__c</fullName>
        <description>Estimated Annual Income</description>
        <label>Estimated Income</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_FREQ_PAY_ESTMD__c</fullName>
        <description>Estimated Pay Frequency</description>
        <label>Estimated Income Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00341</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CNT_WEEK_PER_HOURS_ESTMD__c</fullName>
        <description>Estimated Hours per Week</description>
        <label>Estimated Hours per Week</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Income Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EMPLMT_INDIV__c</fullName>
        <description>Employment ID</description>
        <label>Employment ID</label>
        <referenceTo>T_SBSD_INDIV_EMPLMT__c</referenceTo>
        <relationshipLabel>Employment Income</relationshipLabel>
        <relationshipName>T_SBSD_INDIV_EMPLMT1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>JIRA CHAT - 2779,2778</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00848</valueSetName>
        </valueSet>
    </fields>
    <label>Employment Income</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_EMPLMT_PAY_STUB__c.object
<CustomObject>
    <description>Information about employment income including individual receiving the income, amount and frequency</description>
  <!--  <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Verified</description>
        <label>Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_EMPLMT_INCOME__c</fullName>
        <label>Employment Income ID</label>
        <referenceTo>T_EMPLMT_INCOME__c</referenceTo>
        <relationshipLabel>Employment Pay Stub</relationshipLabel>
        <relationshipName>Employment_Pay_Stub</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>JIRA CHAT-2779 and 2778
2. added new columns T_EMPLMT_PAY_STUB.CDE_STATUS and T_EMPLMT_INCOME.CDE_STATUS</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00848</valueSetName>
        </valueSet>
    </fields>
    <label>Employment Pay Stub</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Pay Stub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Pay Stub</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>How_Verified_Employment_RecordType</fullName>
        <active>false</active>
        <errorConditionFormula>AND(OR(ISNEW(),ISCHANGED(CDE_SOURCE_VRFYD_PAY__c)),IDN_EMPLMT_INCOME__r.IDN_EMPLMT_INDIV__r.RecordType.DeveloperName  = &apos;Employment&apos;, OR( ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;CCH&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;LGR&apos;), ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;OTH&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;PST&apos;)))</errorConditionFormula>
        <errorMessage>Please select one of these Employment letter, Paystubs, Verbal, Work Number website in How Verified</errorMessage>
    </validationRules-->
    <!--Making modification as part of CCCAP-15586 Issue 2-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>How_Verified_Self_Employment_RecordType</fullName>
        <active>false</active>
        <errorConditionFormula>AND(OR(ISNEW(),ISCHANGED(CDE_SOURCE_VRFYD_PAY__c)),
IDN_EMPLMT_INCOME__r.IDN_EMPLMT_INDIV__r.RecordType.DeveloperName  = &apos;Self_Employment&apos;,OR(ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;ELT&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;STB&apos;), ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;VER&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;WNW&apos;)) )</errorConditionFormula>
        <errorMessage>Please select one of these Cancelled checks, Ledger, Other, Paystub in How Verified</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>CNT_SIZE_FAMILY__c</fullName>
        <description>Family Size</description>
        <label>Family Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTE_RCVD_PACKET_REDET__c</fullName>
        <description>Redetermination Packet Received Date</description>
        <label>Redetermination Packet Received Date</label>
        <type>Date</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    

    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_EMPLMT__c.object
<CustomObject>
    <description>Employer information</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>ADR_CITY__c</fullName>
        <description>City</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Employment Begin Date</description>
        <label>Employment Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>T_SBSD_INDIV19</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employment</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Employment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_CDE_SOURCE_VRFYD_SE</fullName>
        <active>false</active>
        <description>CDE_SOURCE_VRFYD_SE is required when T_SBSD_INDIV_EMPLMT, CDE_TYPE_VRFYD_SE is &quot;Written Verification&quot; and Self-Employment record type.</description>
        <errorConditionFormula>OR(AND(ISNEW(),NOT(IDN_CLIENT__r.Is_Peak_Data__c),NOT(IDN_CLIENT__r.Is_CBMS_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)),AND(NOT(ISNEW()),NOT( ISCHANGED(CDE_WAGE_MIN__c)), NOT(IDN_CLIENT__r.Is_Peak_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_SE__c</errorDisplayField>
        <errorMessage>How Verified is required if Verified is &apos;Written Verification&apos;</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00341.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2PM</fullName>
        <label>Twice per Month</label>
    </customValue>
    <customValue>
        <fullName>1PY</fullName>
        <label>Once a Year</label>
    </customValue>
    <customValue>
        <fullName>2PY</fullName>
        <label>Twice a Year</label>
    </customValue>
    <customValue>
        <fullName>E2M</fullName>
        <label>Every Other Month</label>
    </customValue>
    <customValue>
        <fullName>E2W</fullName>
        <label>Every Two Weeks</label>
    </customValue>
    <customValue>
        <fullName>HLY</fullName>
        <label>Hourly</label>
    </customValue>
    <customValue>
        <fullName>MON</fullName>
        <label>Monthly</label>
    </customValue>
    <customValue>
        <fullName>ONE</fullName>
        <label>One Time Only</label>
    </customValue>
    <customValue>
        <fullName>QRT</fullName>
        <label>Quarterly</label>
    </customValue>
    <customValue>
        <fullName>WKY</fullName>
        <label>Weekly</label>
    </customValue>
    <description>R00341</description>
    <masterLabel>R00341</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00367.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Available</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <label>Verbal Verification</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Written Verification</label>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
        <isActive>false</isActive>
        <label>CV</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
        <isActive>false</isActive>
        <label>N/A-adult caretaker</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <isActive>false</isActive>
        <label>SV</label>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
        <isActive>false</isActive>
        <label>N/A-not requesting child</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>R00367</description>
    <masterLabel>R00367</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00848.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACT</fullName>
        <default>true</default>
        <label>Active</label>
    </customValue>
    <customValue>
        <fullName>INA</fullName>
        <label>Inactive</label>
    </customValue>
    <masterLabel>R00848</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/RedeterminationFlowCtrlTest.cls
@isTest
public class RedeterminationFlowCtrlTest {
    public static testMethod void testUpdateCase(){
        test.startTest();
        T_SBSD_CASE__c caseRecord = new T_SBSD_CASE__c();
        insert caseRecord;
        T_SBSD_CASE_STATUS_MODE__c caseStatusModeChild = new T_SBSD_CASE_STATUS_MODE__c();
        caseStatusModeChild.IDN_CASE__c = caseRecord.Id; 
        caseStatusModeChild.DTE_BEGIN_EFFV__c = date.today()-2;
        insert caseStatusModeChild;
        LightningServerResponse lsr=RedeterminationFlowCtrl.updateCase(new List<SObject>{caseRecord});
        system.assertEquals(true,lsr.isSuccessful,'isSuccessful should be true');
        test.stopTest();
    }
    
    public static testMethod void testUpdateCaseError(){
        test.startTest();
        T_SBSD_CASE__c caseRecord = new T_SBSD_CASE__c();
        insert caseRecord;
        T_SBSD_CASE_STATUS_MODE__c caseStatusModeChild = new T_SBSD_CASE_STATUS_MODE__c();
        caseStatusModeChild.IDN_CASE__c = caseRecord.Id; 
        caseStatusModeChild.DTE_BEGIN_EFFV__c = date.today()-2;
        insert caseStatusModeChild;
        caseRecord.CNT_SIZE_FAMILY__c = 12345678;
        LightningServerResponse lsr=RedeterminationFlowCtrl.updateCase(new List<SObject>{caseRecord});
        system.assertEquals(false,lsr.isSuccessful,'isSuccessful should be false');
        test.stopTest();
    }
    
    public static testMethod void testCaseServices(){
        Test.startTest();
        Map<String, SObject> data= CaseLastUpdatedTestFactory.createCaseData();
        T_SBSD_CASE__c caseRec= (T_SBSD_CASE__c)data.get('caseRec');
        T_SBSD_INDIV__c indiv= (T_SBSD_INDIV__c)data.get('individual');
        T_SBSD_INDIV_EMPLMT__c  emp= new T_SBSD_INDIV_EMPLMT__c(idn_client__c=indiv.Id, ADR_CITY__c = 'test', DTE_BEGIN_EFFV__c = System.today().addDays(-5));
        insert emp;
        T_EMPLMT_INCOME__c empInc= new T_EMPLMT_INCOME__c(idn_emplmt_indiv__c= emp.Id, CDE_STATUS__c='ACT' , 
                                                          DTE_BEGIN_EFFV__c=System.today(), 
                                                          CNT_WEEK_PER_HOURS_ESTMD__c = 20.00, 
                                                          AMT_INCOME_ANNUAL_ESTMD__c = 10000.00, 
                                                          CDE_FREQ_PAY_ESTMD__c = 'MON',
                                                          CDE_TYPE_VERIF__c = 'SD');
        insert empInc;
        T_EMPLMT_PAY_STUB__c empPayStub= new T_EMPLMT_PAY_STUB__c(idn_emplmt_income__c=empInc.Id, CDE_STATUS__c='ACT');
        insert empPayStub;
        caseRec.DTE_RCVD_PACKET_REDET__c = System.today().addDays(-1);
        LightningServerResponse lsr=RedeterminationFlowCtrl.updateCase(new List<SObject>{caseRec});
        system.assertEquals(System.today().addDays(-1),[Select DTE_RCVD_PACKET_REDET__c from T_SBSD_CASE__c where Id=:caseRec.Id].DTE_RCVD_PACKET_REDET__c,'Packet recieved date should be yesterday');
        Test.stopTest();
    }
    
    public static testMethod void testRedeterminationFlowAgain(){
        test.startTest();
        T_SBSD_CASE__c caseRecord = new T_SBSD_CASE__c();
        insert caseRecord;
        T_SBSD_CASE_STATUS_MODE__c caseStatusModeChild = new T_SBSD_CASE_STATUS_MODE__c();
        caseStatusModeChild.IDN_CASE__c = caseRecord.Id; 
        caseStatusModeChild.DTE_BEGIN_EFFV__c = date.today()-2;
        insert caseStatusModeChild;
        LightningServerResponse lsr=RedeterminationFlowCtrl.updateCase(new List<SObject>{caseRecord});
        system.assertEquals(true,lsr.isSuccessful,'isSuccessful should be true');
        LightningServerResponse lsr2=RedeterminationFlowCtrl.updateCase(new List<SObject>{caseRecord});
        system.assertEquals(false,lsr2.isSuccessful,'isSuccessful should be false');
        test.stopTest();
    }
    
}