CHATS_SIT/force-app/main/default/objects/T_EMPLMT_INCOME__c.object
<CustomObject>
    <description>Income information from employment for individual</description>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Verified</description>
        <label>Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AMT_INCOME_ANNUAL_ESTMD__c</fullName>
        <description>Estimated Annual Income</description>
        <label>Estimated Income</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CDE_FREQ_PAY_ESTMD__c</fullName>
        <description>Estimated Pay Frequency</description>
        <label>Estimated Income Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00341</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CNT_WEEK_PER_HOURS_ESTMD__c</fullName>
        <description>Estimated Hours per Week</description>
        <label>Estimated Hours per Week</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Income Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EMPLMT_INDIV__c</fullName>
        <description>Employment ID</description>
        <label>Employment ID</label>
        <referenceTo>T_SBSD_INDIV_EMPLMT__c</referenceTo>
        <relationshipLabel>Employment Income</relationshipLabel>
        <relationshipName>T_SBSD_INDIV_EMPLMT1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employment Income</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_EMPLMT_PAY_STUB__c.object
<CustomObject>
    <description>Information about employment income including individual receiving the income, amount and frequency</description>
  <!--  <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Verified</description>
        <label>Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_EMPLMT_INCOME__c</fullName>
        <label>Employment Income ID</label>
        <referenceTo>T_EMPLMT_INCOME__c</referenceTo>
        <relationshipLabel>Employment Pay Stub</relationshipLabel>
        <relationshipName>Employment_Pay_Stub</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employment Pay Stub</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Pay Stub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Pay Stub</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>How_Verified_Employment_RecordType</fullName>
        <active>false</active>
        <errorConditionFormula>AND(OR(ISNEW(),ISCHANGED(CDE_SOURCE_VRFYD_PAY__c)),IDN_EMPLMT_INCOME__r.IDN_EMPLMT_INDIV__r.RecordType.DeveloperName  = &apos;Employment&apos;, OR( ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;CCH&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;LGR&apos;), ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;OTH&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;PST&apos;)))</errorConditionFormula>
        <errorMessage>Please select one of these Employment letter, Paystubs, Verbal, Work Number website in How Verified</errorMessage>
    </validationRules-->
    <!--Making modification as part of CCCAP-15586 Issue 2-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>How_Verified_Self_Employment_RecordType</fullName>
        <active>false</active>
        <errorConditionFormula>AND(OR(ISNEW(),ISCHANGED(CDE_SOURCE_VRFYD_PAY__c)),
IDN_EMPLMT_INCOME__r.IDN_EMPLMT_INDIV__r.RecordType.DeveloperName  = &apos;Self_Employment&apos;,OR(ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;ELT&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;STB&apos;), ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;VER&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;WNW&apos;)) )</errorConditionFormula>
        <errorMessage>Please select one of these Cancelled checks, Ledger, Other, Paystub in How Verified</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_EMPLMT__c.object
<CustomObject>
    <description>Employer information</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>ADR_CITY__c</fullName>
        <description>City</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Employment Begin Date</description>
        <label>Employment Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>T_SBSD_INDIV19</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ignore__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ignore</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NAM_BUSNS__c</fullName>
        <description>Employer/Business Name</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Employer/Business Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Employment</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Employment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <recordTypes>
        <fullName>Employment</fullName>
        <active>true</active>
        <label>Employment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_CDE_SOURCE_VRFYD_SE</fullName>
        <active>false</active>
        <description>CDE_SOURCE_VRFYD_SE is required when T_SBSD_INDIV_EMPLMT, CDE_TYPE_VRFYD_SE is &quot;Written Verification&quot; and Self-Employment record type.</description>
        <errorConditionFormula>OR(AND(ISNEW(),NOT(IDN_CLIENT__r.Is_Peak_Data__c),NOT(IDN_CLIENT__r.Is_CBMS_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)),AND(NOT(ISNEW()),NOT( ISCHANGED(CDE_WAGE_MIN__c)), NOT(IDN_CLIENT__r.Is_Peak_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_SE__c</errorDisplayField>
        <errorMessage>How Verified is required if Verified is &apos;Written Verification&apos;</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00341.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2PM</fullName>
        <label>Twice per Month</label>
    </customValue>
    <customValue>
        <fullName>1PY</fullName>
        <label>Once a Year</label>
    </customValue>
    <customValue>
        <fullName>2PY</fullName>
        <label>Twice a Year</label>
    </customValue>
    <customValue>
        <fullName>E2M</fullName>
        <label>Every Other Month</label>
    </customValue>
    <customValue>
        <fullName>E2W</fullName>
        <label>Every Two Weeks</label>
    </customValue>
    <customValue>
        <fullName>HLY</fullName>
        <label>Hourly</label>
    </customValue>
    <customValue>
        <fullName>MON</fullName>
        <label>Monthly</label>
    </customValue>
    <customValue>
        <fullName>ONE</fullName>
        <label>One Time Only</label>
    </customValue>
    <customValue>
        <fullName>QRT</fullName>
        <label>Quarterly</label>
    </customValue>
    <customValue>
        <fullName>WKY</fullName>
        <label>Weekly</label>
    </customValue>
    <description>R00341</description>
    <masterLabel>R00341</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00367.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Available</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <label>Verbal Verification</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Written Verification</label>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
        <isActive>false</isActive>
        <label>CV</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
        <isActive>false</isActive>
        <label>N/A-adult caretaker</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <isActive>false</isActive>
        <label>SV</label>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
        <isActive>false</isActive>
        <label>N/A-not requesting child</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>R00367</description>
    <masterLabel>R00367</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/EmploymentPayStubApxCtrlTest.cls
@isTest
public class EmploymentPayStubApxCtrlTest {
 public static testMethod void testCaseLastUpdatedFields(){
        Map<String, SObject> caseData = CaseLastUpdatedTestFactory.createCaseData();
        
        T_SBSD_INDIV_EMPLMT__c employment = new T_SBSD_INDIV_EMPLMT__c(ADR_CITY__c='NY',IDN_CLIENT__c=caseData.get('individual').Id,
                                                                        NAM_BUSNS__c='test',
                                                                        DTE_BEGIN_EFFV__c=system.today(),
                                                                        Ignore__c=true);
                                
        
        insert employment;
        
        T_EMPLMT_INCOME__c empIncome = new T_EMPLMT_INCOME__c(IDN_EMPLMT_INDIV__c=employment.Id,
                                                              DTE_BEGIN_EFFV__c=system.today(),
                                                              CNT_WEEK_PER_HOURS_ESTMD__c = 20.00,
                                                              AMT_INCOME_ANNUAL_ESTMD__c = 10000.00,
                                                              CDE_FREQ_PAY_ESTMD__c = 'MON',
                                                              CDE_TYPE_VERIF__c = 'SD');
        insert empIncome;
        T_EMPLMT_PAY_STUB__c payStub = new T_EMPLMT_PAY_STUB__c(IDN_EMPLMT_INCOME__c=empIncome.Id, CDE_TYPE_VERIF__c ='NA');
        insert payStub;
        
        
        Test.startTest();
        EmploymentPayStubApxCtrl.getDoInit(empIncome.id);
        EmploymentPayStubApxCtrl.getDoInit(payStub.id);
        EmploymentPayStubApxCtrl.getDoInit('');
        Test.stopTest();
    }
}