CHATS_SIT/force-app/main/default/objects/T_EMPLMT_INCOME__c.object
<CustomObject>
    <description>Income information from employment for individual</description>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Income Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EMPLMT_INDIV__c</fullName>
        <description>Employment ID</description>
        <label>Employment ID</label>
        <referenceTo>T_SBSD_INDIV_EMPLMT__c</referenceTo>
        <relationshipLabel>Employment Income</relationshipLabel>
        <relationshipName>T_SBSD_INDIV_EMPLMT1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>JIRA CHAT - 2779,2778</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00848</valueSetName>
        </valueSet>
    </fields>
    <label>Employment Income</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_EMPLMT_PAY_STUB__c.object
<CustomObject>
    <description>Information about employment income including individual receiving the income, amount and frequency</description>
  <!--  <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>IDN_EMPLMT_INCOME__c</fullName>
        <label>Employment Income ID</label>
        <referenceTo>T_EMPLMT_INCOME__c</referenceTo>
        <relationshipLabel>Employment Pay Stub</relationshipLabel>
        <relationshipName>Employment_Pay_Stub</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>bypassValidations__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <description>To be able to update status from backend. CCCAP-15586</description>
        <label>bypassValidation</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>JIRA CHAT-2779 and 2778
2. added new columns T_EMPLMT_PAY_STUB.CDE_STATUS and T_EMPLMT_INCOME.CDE_STATUS</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00848</valueSetName>
        </valueSet>
    </fields>
    <label>Employment Pay Stub</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Pay Stub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Pay Stub</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>How_Verified_Employment_RecordType</fullName>
        <active>false</active>
        <errorConditionFormula>AND(OR(ISNEW(),ISCHANGED(CDE_SOURCE_VRFYD_PAY__c)),IDN_EMPLMT_INCOME__r.IDN_EMPLMT_INDIV__r.RecordType.DeveloperName  = &apos;Employment&apos;, OR( ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;CCH&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;LGR&apos;), ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;OTH&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;PST&apos;)))</errorConditionFormula>
        <errorMessage>Please select one of these Employment letter, Paystubs, Verbal, Work Number website in How Verified</errorMessage>
    </validationRules-->
    <!--Making modification as part of CCCAP-15586 Issue 2-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>How_Verified_Self_Employment_RecordType</fullName>
        <active>false</active>
        <errorConditionFormula>AND(OR(ISNEW(),ISCHANGED(CDE_SOURCE_VRFYD_PAY__c)),
IDN_EMPLMT_INCOME__r.IDN_EMPLMT_INDIV__r.RecordType.DeveloperName  = &apos;Self_Employment&apos;,OR(ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;ELT&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;STB&apos;), ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;VER&apos;),ISPICKVAL(CDE_SOURCE_VRFYD_PAY__c , &apos;WNW&apos;)) )</errorConditionFormula>
        <errorMessage>Please select one of these Cancelled checks, Ledger, Other, Paystub in How Verified</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>DTE_RCVD_PACKET_REDET__c</fullName>
        <description>Redetermination Packet Received Date</description>
        <label>Redetermination Packet Received Date</label>
        <type>Date</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Date Person Entered Home</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_STATUS_MODE__c.object
<CustomObject>
    <description>Has the case status(opn,close,pen)</description>
    <fields>
        <fullName>CDE_ELIGTY_CONTNUS__c</fullName>
        <label>Maintain Eligibility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00387</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_MODE_CASE__c</fullName>
        <description>Case Mode</description>
        <label>Case Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00358</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_STATUS_CASE__c</fullName>
        <description>Case Status</description>
        <label>Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00357</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Status Mode</relationshipLabel>
        <relationshipName>T_SBSD_CASE10</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Status Mode</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Status Mode ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Status Mode</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Effective_End_Date_Greater_than_Begin</fullName>
        <active>false</active>
        <description>Effective End Date cannot be before Effective Start Date</description>
        <errorConditionFormula>AND (
DTE_END_EFFV__c &lt; DTE_BEGIN_EFFV__c,
 $Label.Batch_User_Id  &lt;&gt;  $User.Id 
)</errorConditionFormula>
        <errorDisplayField>DTE_END_EFFV__c</errorDisplayField>
        <errorMessage>Case cannot be reopened on the same day it was closed, please try again tomorrow.</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_EMPLMT__c.object
<CustomObject>
    <description>Employer information</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Employment Begin Date</description>
        <label>Employment Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Employment End Date</description>
        <label>Employment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>T_SBSD_INDIV19</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employment</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Employment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <recordTypes>
        <fullName>Employment</fullName>
        <active>true</active>
        <label>Employment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_CDE_SOURCE_VRFYD_SE</fullName>
        <active>false</active>
        <description>CDE_SOURCE_VRFYD_SE is required when T_SBSD_INDIV_EMPLMT, CDE_TYPE_VRFYD_SE is &quot;Written Verification&quot; and Self-Employment record type.</description>
        <errorConditionFormula>OR(AND(ISNEW(),NOT(IDN_CLIENT__r.Is_Peak_Data__c),NOT(IDN_CLIENT__r.Is_CBMS_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)),AND(NOT(ISNEW()),NOT( ISCHANGED(CDE_WAGE_MIN__c)), NOT(IDN_CLIENT__r.Is_Peak_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_SE__c</errorDisplayField>
        <errorMessage>How Verified is required if Verified is &apos;Written Verification&apos;</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00357.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>REO</fullName>
        <label>Reopen</label>
    </customValue>
    <description>R00357</description>
    <masterLabel>R00357</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00358.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INT</fullName>
        <label>Intake</label>
    </customValue>
    <customValue>
        <fullName>ONG</fullName>
        <label>Ongoing</label>
    </customValue>
    <customValue>
        <fullName>RED</fullName>
        <label>Redetermination</label>
    </customValue>
    <description>R00358</description>
    <masterLabel>R00358</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00387.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N</fullName>
        <label>Break in Eligibility</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Continuous</label>
    </customValue>
    <description>R00387</description>
    <masterLabel>R00387</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00848.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACT</fullName>
        <default>true</default>
        <label>Active</label>
    </customValue>
    <customValue>
        <fullName>INA</fullName>
        <label>Inactive</label>
    </customValue>
    <masterLabel>R00848</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/RedeterminationFlowCtrl.cls
public with sharing class RedeterminationFlowCtrl {
    final static String INACTIVE = 'INA';
    
    @AuraEnabled
    public static LightningServerResponse updateCase(List<SObject> caseRecs){
        System.debug('caseRecs:'+caseRecs);
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful = true;
        String message;
        List<APXFieldValidationError> lstAPXFieldValidationError; 
        Savepoint sp = Database.setSavepoint();
        List<SObject> lstRecordsToBeUpdated = new List<SObject>();
        List<SObject> lstEmplmtIncomeRecordsToBeUpdated = new List<SObject>();
        List<SObject> lstRecordsToBeInserted = new List<SObject>();
        List<Database.SaveResult> lstSaveResult = new List<Database.SaveResult>();
        Map<Id,Id> individualIds = new Map<Id,Id>();
        //Set<Id> individualIds = new Set<Id>();
        Set<Id> employmentIncomeIds = new Set<Id>();
        Map<Id,T_SBSD_CASE__c> mapIdToCaseRecords = new Map<Id,T_SBSD_CASE__c>();
        
        lstRecordsToBeUpdated.addAll(caseRecs);
        Set<Id> caseIds = new Set<Id>();
        for(SObject sOb:caseRecs){
            if(sOb.get('Id')!=null){
                caseIds.add((Id)sOb.get('Id'));
                mapIdToCaseRecords.put((Id)sOb.get('Id'),(T_SBSD_CASE__c)sOb);
            }
        }
        System.debug('caseIds:'+caseIds);
        for(T_SBSD_CASE__c cas:[Select Id,Name,DTE_RCVD_PACKET_REDET__c,(SELECT CDE_MODE_CASE__c,CDE_STATUS_CASE__c,DTE_BEGIN_EFFV__c,DTE_END_EFFV__c,Id,
                                                                         IDN_CASE__c, CreatedDate FROM T_SBSD_CASE10__r WHERE (DTE_END_EFFV__c=null OR DTE_END_EFFV__c>TODAY) ORDER BY DTE_BEGIN_EFFV__c DESC NULLS FIRST),
                                (SELECT IDN_CLIENT__c FROM CaseIndividuals__r WHERE DTE_BEGIN_EFFV__c<=TODAY AND (DTE_END_EFFV__c=null OR DTE_END_EFFV__c>TODAY))
                                 from T_SBSD_CASE__c where Id IN :caseIds]){
                                    
            System.debug('cas:'+cas);
            if(!cas.T_SBSD_CASE10__r.isEmpty()){
                System.debug('cas.T_SBSD_CASE10__r:'+cas.T_SBSD_CASE10__r);
                if(cas.DTE_RCVD_PACKET_REDET__c==mapIdToCaseRecords.get(cas.Id).DTE_RCVD_PACKET_REDET__c 
                   && cas.T_SBSD_CASE10__r.get(0).CDE_MODE_CASE__c=='RED' 
                   && date.newinstance(cas.T_SBSD_CASE10__r.get(0).CreatedDate.year(), cas.T_SBSD_CASE10__r.get(0).CreatedDate.month(), cas.T_SBSD_CASE10__r.get(0).CreatedDate.day())==System.today()){
                       isSuccessful = false;
                   }else{
                       T_SBSD_CASE_STATUS_MODE__c sbsdCaseStaMod =  new T_SBSD_CASE_STATUS_MODE__c();
                       sbsdCaseStaMod.CDE_MODE_CASE__c= 'RED';
                       sbsdCaseStaMod.DTE_BEGIN_EFFV__c= date.today();
                       sbsdCaseStaMod.CDE_STATUS_CASE__c = cas.T_SBSD_CASE10__r.get(0).CDE_STATUS_CASE__c;
                       sbsdCaseStaMod.IDN_CASE__c = cas.id;
                       sbsdCaseStaMod.CDE_ELIGTY_CONTNUS__c = cas.T_SBSD_CASE10__r.get(0).CDE_STATUS_CASE__c=='REO'?'Y':'';//CCCAP-13725 To enable eligibility to use SMI during reopen redetermination and income result to pass
                       lstRecordsToBeInserted.add(sbsdCaseStaMod);  
                       //SJ: CHATS-6763 - Added logic to populate end date for all effective case status mode]
                       for(T_SBSD_CASE_STATUS_MODE__c eachEffectiveCaseStatusMode:cas.T_SBSD_CASE10__r){
                           if(eachEffectiveCaseStatusMode.DTE_END_EFFV__c == null){
                               eachEffectiveCaseStatusMode.DTE_END_EFFV__c = date.today()-1; 
                           }
                           lstRecordsToBeUpdated.add(eachEffectiveCaseStatusMode);    
                       }
                   }
            }
            for(T_SBSD_CASE_INDIV__c caseIndiv:cas.CaseIndividuals__r){
                individualIds.put(caseIndiv.IDN_CLIENT__c,cas.Id);
            }
        }
        if(isSuccessful){
            Map<Id, T_EMPLMT_PAY_STUB__c> payStubMap = new Map<Id, T_EMPLMT_PAY_STUB__c>();
            for(T_SBSD_INDIV_EMPLMT__c employment:[SELECT Id, Name, IDN_CLIENT__c, DTE_END_EFFV__c, (SELECT Id, Name, CDE_STATUS__c FROM T_SBSD_INDIV_EMPLMT1__r) FROM T_SBSD_INDIV_EMPLMT__c WHERE IDN_CLIENT__c IN: individualIds.keyset() and IDN_CASE__c IN: caseIds
                                                  								AND (DTE_END_EFFV__c = null OR DTE_END_EFFV__c > TODAY)]){
                for(T_EMPLMT_INCOME__c employmentIncome : employment.T_SBSD_INDIV_EMPLMT1__r){
                    employmentIncomeIds.add(employmentIncome.Id);
                    if(employmentIncome.CDE_STATUS__c != INACTIVE){
                        employmentIncome.CDE_STATUS__c = INACTIVE;
                        lstEmplmtIncomeRecordsToBeUpdated.add(employmentIncome);
                    }
                }
            }
            for(T_EMPLMT_PAY_STUB__c payStub : [SELECT Id, Name, CDE_STATUS__c, IDN_EMPLMT_INCOME__r.IDN_EMPLMT_INDIV__r.IDN_CLIENT__c, IDN_EMPLMT_INCOME__r.Name FROM T_EMPLMT_PAY_STUB__c WHERE IDN_EMPLMT_INCOME__c IN:employmentIncomeIds AND CDE_STATUS__c!=:INACTIVE]){
                payStub.CDE_STATUS__c = INACTIVE;
                payStub.bypassValidations__c = System.now(); // Setting timestamp to bypass validation rule CCCAP-15586
                lstEmplmtIncomeRecordsToBeUpdated.add(payStub);
                payStubMap.put(payStub.Id, payStub);
            }
            
            System.debug('lstRecordsToBeUpdated:'+lstRecordsToBeUpdated);
            System.debug('lstRecordsToBeInserted:'+lstRecordsToBeInserted);
            System.debug('lstEmplmtIncomeRecordsToBeUpdated:'+lstEmplmtIncomeRecordsToBeUpdated);
            
            List<Database.SaveResult> saveResults = Database.update(lstEmplmtIncomeRecordsToBeUpdated, false);
            List<String> dmlErrorMessages = new List<String>();
            for(Integer i = 0; i < saveResults.size(); i++){
                if(!saveResults[i].isSuccess()){
                    sObject obj = lstEmplmtIncomeRecordsToBeUpdated[i];
                    String objName = obj.getSObjectType().getDescribe().getName();                    
                    List<Database.Error> saveResultErrors = saveResults[i].getErrors();
                    for(Database.Error err : saveResultErrors){
                        String msg = err.getMessage();
                        if(objName == 'T_EMPLMT_INCOME__c'){
                            msg = 'Employment Income '+obj.get('Name')+ ': '+msg;
                        }
                        if(objName == 'T_EMPLMT_PAY_STUB__c'){
                            msg = 'Employment Income '+payStubMap.get(obj.Id).IDN_EMPLMT_INCOME__r.Name+ ', Pay Stub '+ obj.get('Name') +': '+msg;
                        }
                        dmlErrorMessages.add(msg);
                    }
                }
            }
            lstSaveResult.addAll(Database.update(lstRecordsToBeUpdated, false));
            lstSaveResult.addAll(Database.insert(lstRecordsToBeInserted, false));
            System.debug('lstSaveResult:'+lstSaveResult);
            
            lstRecordsToBeUpdated.addAll(lstRecordsToBeInserted);
            
            lstAPXFieldValidationError = CrudResponseApxCtrl.getCrudResponseFromSaveResults(lstRecordsToBeUpdated, lstSaveResult);
            if(lstAPXFieldValidationError.isEmpty() && dmlErrorMessages.isEmpty()){
                objectData.put('upsertedRecords',lstRecordsToBeUpdated);
                message = Label.Record_has_been_successfully_updated;
                isSuccessful = true;
            }else{
                objectData.put('upsertedRecords',lstRecordsToBeUpdated);
                objectData.put('dmlErrorMessages', dmlErrorMessages);
                message = Label.ERRORS_ON_THIS_PAGE;
                isSuccessful = false;
                // Rollback to the savepoint
                Database.rollback(sp);
                ExceptionLoggingServices.captureExceptionLog(lstSaveResult, lstRecordsToBeUpdated, new Map<String,Object>{'Class__c'=>'RedeterminationFlowCtrl','Method__c'=>'updateCase'});
            }
        }else{
            message = System.Label.CANNOT_ACCESS_REDETERMINATION_FLOW;
        }
        return new LightningServerResponse(isSuccessful,message,objectData,lstAPXFieldValidationError);
  }
}