CHATS_SIT/force-app/main/default/objects/T_INDIV_VERIF__c.object
<CustomObject>
    <description>Individual verification tracking</description>
    <fields>
        <fullName>CDE_TYPE_INFO_INDIV__c</fullName>
        <description>Type of Individual Information</description>
        <label>Type of Individual Information</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00366</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Verified</description>
        <label>Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual Information ID</label>
        <referenceTo>T_SBSD_INDIV_INFO__c</referenceTo>
        <relationshipLabel>Individual Verification</relationshipLabel>
        <relationshipName>Individual_Verification</relationshipName>
        <type>Lookup</type> 
    </fields>
    <label>Individual Verification</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Individual Verification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>CDE_SOURCE_VRFYD_CITIZEN__c</fullName>
        <description>How Verified (Citizenship)</description>
        <label>How Verified (Citizenship)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00708</valueSetName>
        </valueSet>
    </fields>
    

    <fields>
        <fullName>Is_Peak_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Peak Data</label>
        <type>Checkbox</type>
    </fields>
    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_INFO__c.object
<CustomObject>
    <description>Information codes about individual</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_INFO_INDIV__c</fullName>
        <description>Type of Individual Information</description>
        <label>Individual Information Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00366</valueSetName>
        </valueSet>
    </fields> 
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Individual Information (Individual)</relationshipLabel>
        <relationshipName>Individual_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Individual Information</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Individual Information ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00366.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CS</fullName>
        <label>citizenship status</label>
    </customValue>
    <customValue>
        <fullName>HDS</fullName>
        <label>head start</label>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
        <label>marital status</label>
    </customValue>
    <customValue>
        <fullName>FST</fullName>
        <label>foster care</label>
    </customValue>
    <customValue>
        <fullName>IMM</fullName>
        <isActive>false</isActive>
        <label>age appropriate immunization</label>
    </customValue>
    <description>R00366</description>
    <masterLabel>R00366</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00367.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Available</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <label>Verbal Verification</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Written Verification</label>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
        <isActive>false</isActive>
        <label>CV</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
        <isActive>false</isActive>
        <label>N/A-adult caretaker</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <isActive>false</isActive>
        <label>SV</label>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
        <isActive>false</isActive>
        <label>N/A-not requesting child</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>R00367</description>
    <masterLabel>R00367</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/IndividualVerificationFlowApxCtrlTest.cls
/*
*/
@isTest
public class IndividualVerificationFlowApxCtrlTest {
	
    public static testMethod void testGetInitData(){
        LightningServerResponse lsr = null;
        List<T_SBSD_INDIV__c> indivRecs = [SELECT id FROM T_SBSD_INDIV__c];
        System.assertNotEquals(true, indivRecs.isEmpty(), 'indivRecs should not be empty');
        List<T_SBSD_INDIV_INFO__c> indivInfos = [SELECT id FROM T_SBSD_INDIV_INFO__c WHERE IDN_CLIENT__c = :indivRecs.get(0).Id];
		System.assertEquals(false, indivInfos.isEmpty(), 'indivInfos should not be empty');
        lsr = IndividualVerificationFlowApxCtrl.getInitData(indivRecs.get(0).Id);
        System.assertEquals(true, lsr.objectData.containsKey('indVerif'), 'objectData should contain not indVerif as key');
        T_INDIV_VERIF__c expectedRecord = (T_INDIV_VERIF__c)lsr.objectData.get('indVerif');
		System.assertEquals(null, expectedRecord.Id, 'Id should be null');
        insert new T_INDIV_VERIF__c(IDN_CLIENT__c = indivInfos.get(0).Id, CDE_TYPE_INFO_INDIV__c = 'CS', CDE_TYPE_VERIF__c = 'V');
        lsr = IndividualVerificationFlowApxCtrl.getInitData(indivRecs.get(0).Id);
        System.assertEquals(true, lsr.objectData.containsKey('indVerif'), 'objectData should contain indVerif as key');
        List<T_INDIV_VERIF__c> actualResults = [SELECT CDE_TYPE_VERIF__c FROM T_INDIV_VERIF__c WHERE IDN_CLIENT__r.IDN_CLIENT__c = :indivRecs.get(0).Id AND CDE_TYPE_INFO_INDIV__c = 'CS' LIMIT 1];
        System.assertNotEquals(true, actualResults.isEmpty(), 'actualResults should not be empty');
        expectedRecord = (T_INDIV_VERIF__c)lsr.objectData.get('indVerif');
        System.assertEquals(actualResults.get(0).Id, expectedRecord.Id, 'Id should match for both the records');
        IndividualVerificationFlowApxCtrl.isReadOnlyProfile();
        CitizenshipDatafixBatch obj = new CitizenshipDatafixBatch();
        DataBase.executeBatch(obj);
    }
    
    @testSetup
    public static void testSetup(){
        T_SBSD_INDIV__c indivRec = TestClassUtility.createIndividual(false,System.today().addYears(-15), 'firstName','1', 'lastName','123456789','CC');
		indivRec.CDE_SOURCE_VRFYD_CITIZEN__c = 'AC';
        insert indivRec;
        indivRec.Is_Peak_Data__c = true;
        update indivRec;
        T_SBSD_INDIV_INFO__c indivInfo =  new T_SBSD_INDIV_INFO__c(IDN_CLIENT__c = indivRec.Id, DTE_BEGIN_EFFV__c = System.today().addDays(-15), DTE_END_EFFV__c = System.today().addDays(15), CDE_TYPE_INFO_INDIV__c= 'CS');
        insert indivInfo;
    }
}