CHATS_SIT/force-app/main/default/objects/T_INDIV_CUST__c.object
<CustomObject>
    <description>Information about children on multiple cases</description>
    <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Custody</relationshipLabel>
        <relationshipName>T_SBSD_INDIV24</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Custody</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Joint Custody ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custody</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>INDIV_AGE_GRTR_OR_EQ_19</fullName>
        <active>false</active>
        <description>CHAT-1175: This record may not be appropriate for this individual based on their age</description>
        <errorConditionFormula>NOT( IDN_CLIENT__r.Is_Peak_Data__c ) &amp;&amp; NOT( IDN_CLIENT__r.Is_CBMS_Data__c ) &amp;&amp; IDN_CLIENT__r.Age__c &gt;= VALUE( $Label.Teen_Parent_Age_Limit )</errorConditionFormula>
        <errorMessage>This record may not be appropriate for this individual based on their age</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_INDIV_REL__c.object
<CustomObject>
    <description>Information on how individuals on the case are related to the primary applicant</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_REL_INDIV__c</fullName>
        <description>Relationship</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00243</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CLIENT_RELTD__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Relationship (Client ID)</relationshipLabel>
        <relationshipName>Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Client ID</description>
        <label>Primary Caretaker</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>Primary_Individual_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_CRTKR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is the Primary Parent/Caretaker</description>
        <label>Primary Parent/Caretaker</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/classes/custodyServices.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           11/30/2017                                                          
*  @description    Handler class for Custody Trigger                             
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 30-Nov-2017                                                             
*  * Author: Azharuddin Mohammad                                                      
*  * Description: Initial version                                                 
*  *CHAT-1175: When Save is clicked, show a warning message (""This record may not be appropriate for this individual
*  *		   based on their age and/or relationship to the primary caretaker of this case"") 
*  *		   on the screen only for individuals who:
*  *           -are 19 and older (Validation Rule )
*  *           -are younger than 19 but have a relationship of mother, father, spouse, common law husband, 
*  *            common law wife, husband, wife, live-in companion
*  *		   -are the primary caretaker
*********************************************************************************************/
public class custodyServices {
    /*
    public static void primaryCareTaker(List<T_INDIV_CUST__c> newCustodyList){
        Map<Id,T_INDIV_CUST__c> custody_caseIndiv_Map = new Map<Id,T_INDIV_CUST__c>();
        List<string> relationship = new List<string>();
        relationship.add('M');
        relationship.add('F');
        relationship.add('CLH');
        relationship.add('CLW');
        relationship.add('H');
        relationship.add('W');
        relationship.add('LIC');
        
        for(T_INDIV_CUST__c eachCustody : newCustodyList){
            if(eachCustody.IDN_CLIENT__c != NULL){
                custody_caseIndiv_Map.put(eachCustody.IDN_CLIENT__c, eachCustody);
            }
        }
        if(custody_caseIndiv_Map != NULL){
            for(T_SBSD_CASE_INDIV__c caseIndiv : [select Id, IDN_CLIENT__c, IND_CRTKR__c FROM T_SBSD_CASE_INDIV__c WHERE IDN_CLIENT__c IN:custody_caseIndiv_Map.keySet() AND IND_CRTKR__c = TRUE] ){
                T_INDIV_CUST__c custodyRec = custody_caseIndiv_Map.get(caseIndiv.IDN_CLIENT__c);
                custodyRec.addError('This record may not be appropriate because individual is the primary caretaker');
            }
            for(T_INDIV_REL__c caseRelationship : [select Id, IDN_CLIENT_RELTD__c, IDN_CLIENT__c, CDE_TYPE_REL_INDIV__c FROM T_INDIV_REL__c WHERE IDN_CLIENT_RELTD__c IN:custody_caseIndiv_Map.keySet() AND IDN_CLIENT__c != NULL AND CDE_TYPE_REL_INDIV__c IN:relationship]){
                T_INDIV_CUST__c custodyRec1 = custody_caseIndiv_Map.get(caseRelationship.IDN_CLIENT_RELTD__c);
                custodyRec1.addError('This record may not be appropriate for this individual based on their age and/or relationship to the primary caretaker of this case');
            }
        }
    }*/
}