CHATS_SIT/force-app/main/default/objects/T_INDIV_REL__c.object
<CustomObject>
    <description>Information on how individuals on the case are related to the primary applicant</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_SOURCE_VRFYD_REL__c</fullName>
        <description>How Verified</description>
        <label>How Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00698</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_REL_INDIV__c</fullName>
        <description>Relationship</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00243</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Verified</description>
        <label>Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT_RELTD__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Relationship (Client ID)</relationshipLabel>
        <relationshipName>Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Client ID</description>
        <label>Primary Caretaker</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Relationship</relationshipLabel>
        <relationshipName>Primary_Individual_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00367.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Available</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <label>Verbal Verification</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Written Verification</label>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
        <isActive>false</isActive>
        <label>CV</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
        <isActive>false</isActive>
        <label>N/A-adult caretaker</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <isActive>false</isActive>
        <label>SV</label>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
        <isActive>false</isActive>
        <label>N/A-not requesting child</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>R00367</description>
    <masterLabel>R00367</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00698.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AFD</fullName>
        <label>Affidavit</label>
    </customValue>
    <customValue>
        <fullName>COD</fullName>
        <label>Court Order</label>
    </customValue>
    <customValue>
        <fullName>NPA</fullName>
        <label>Notarized Power of Attorney</label>
    </customValue>
    <customValue>
        <fullName>TF</fullName>
        <label>TANF File</label>
    </customValue>
    <description>R00698</description>
    <masterLabel>R00698</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/NewRelationshipController.cls
public with sharing class NewRelationshipController {
    @AuraEnabled
    public static LightningServerResponse getDoInit(String recordId){
        
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful;
        String message;
        String sObjectName;
        if(String.isNotBlank(recordId)){
            sObjectName = CHATSAuraUtility.getSobjectName(recordId);
        }
        
        if(sObjectName =='T_INDIV_REL__c'){
            List<T_INDIV_REL__c> inidvRelLst = [Select id, Name,CDE_SOURCE_VRFYD_REL__c,CDE_TYPE_REL_INDIV__c, CDE_TYPE_VERIF__c,IDN_CLIENT__c,IDN_CLIENT_RELTD__c,
                                                DTE_BEGIN_EFFV__c, DTE_END_EFFV__c from T_INDIV_REL__c where id=:recordId];
            if(inidvRelLst != null && inidvRelLst.size()>0){
                objectData.put('relRec',inidvRelLst[0]);
            }
        }

        objectData.put('getSobjectName',sObjectName);
        return new LightningServerResponse(true,message,objectData);
    }
}