CHATS_SIT/force-app/main/default/objects/T_INDIV_EMPLMT_INFO__c.object
<CustomObject>
    <description>Employment type information</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_INFO_EMPLMT__c</fullName>
        <description>Employment Information Type</description>
        <label>Temporary Break Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00337</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EMPLMT_INDIV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employment ID</description>
        <label>Employment ID</label>
        <referenceTo>T_SBSD_INDIV_EMPLMT__c</referenceTo>
        <relationshipLabel>Employment Temporary Break Information</relationshipLabel>
        <relationshipName>Employment_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employment Temporary Break</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Employment Temporary Break ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Temporary Break Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
   <!--Commented as part of CCCAP-10798-->
       <!--validationRules>
        <fullName>MaternityMedicalLeaveNotGreaterThanToday</fullName>
        <active>false</active>
        <errorConditionFormula>AND(NOT(IDN_EMPLMT_INDIV__r.IDN_CLIENT__r.Is_Peak_Data__c),NOT(IDN_EMPLMT_INDIV__r.IDN_CLIENT__r.Is_CBMS_Data__c), TEXT(CDE_TYPE_INFO_EMPLMT__c) = &apos;ML&apos; , DTE_BEGIN_EFFV__c &gt; Today())</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV__c</errorDisplayField>
        <errorMessage>Effective Begin Date must be a past date for maternity/medical leave.</errorMessage>
    </validationRules-->
    
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>DTE_CHGD_LAST_DATA_ELIGTY__c</fullName>
        <description>Eligibility Data Last Changed Date</description>
        <label>Eligibility Data Last Changed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IND_CHGD_DATA_ELIGTY__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Eligibility Data Changed</description>
        <label>Eligibility Data Changed</label>
        <type>Checkbox</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_EMPLMT__c.object
<CustomObject>
    <description>Employer information</description>
   <!-- <enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>ADR_CITY__c</fullName>
        <description>City</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_INFO_EMPLMT__c</fullName>
        <label>Temporary Break Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00337</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Employment Begin Date</description>
        <label>Employment Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>T_SBSD_INDIV19</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_STUBS_PAY_RCVS__c</fullName> 
        <description>Job started within the last 60 days?</description>
        <label>Job started within the last 60 days?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00619</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>NAM_BUSNS__c</fullName>
        <description>Employer/Business Name</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Employer/Business Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Employment</label>
   <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Employment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <recordTypes>
        <fullName>Employment</fullName>
        <active>true</active>
        <label>Employment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Req_CDE_SOURCE_VRFYD_SE</fullName>
        <active>false</active>
        <description>CDE_SOURCE_VRFYD_SE is required when T_SBSD_INDIV_EMPLMT, CDE_TYPE_VRFYD_SE is &quot;Written Verification&quot; and Self-Employment record type.</description>
        <errorConditionFormula>OR(AND(ISNEW(),NOT(IDN_CLIENT__r.Is_Peak_Data__c),NOT(IDN_CLIENT__r.Is_CBMS_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)),AND(NOT(ISNEW()),NOT( ISCHANGED(CDE_WAGE_MIN__c)), NOT(IDN_CLIENT__r.Is_Peak_Data__c), ISPICKVAL( CDE_SOURCE_VRFYD_SE__c , &apos;&apos;) , RecordType.DeveloperName = &apos;Self_Employment&apos;, ISPICKVAL(CDE_TYPE_VRFYD_SE__c, &apos;V&apos;)))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_SE__c</errorDisplayField>
        <errorMessage>How Verified is required if Verified is &apos;Written Verification&apos;</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00337.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MPL</fullName>
        <label>Maternity/Paternity</label>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
        <label>Medical leave</label>
    </customValue>
    <customValue>
        <fullName>EIW</fullName>
        <label>Seasonal break</label>
    </customValue>
    <description>R00337</description>
    <masterLabel>R00337</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00619.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <description>R00619</description>
    <masterLabel>R00619</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/EmploymentInformationTriggerTest.cls
@isTest
public class EmploymentInformationTriggerTest {
    public static testMethod void testCaseLastUpdatedFields(){
        Map<String, SObject> caseData = CaseLastUpdatedTestFactory.createCaseData();
        
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.T_SBSD_INDIV_EMPLMT__c; 
		Map<String,Schema.RecordTypeInfo> employmentRecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
		
        T_SBSD_INDIV_EMPLMT__c employment =  new T_SBSD_INDIV_EMPLMT__c(	IDN_CLIENT__c=caseData.get('individual').Id,
                                  		 									ADR_CITY__c = 'Denver',
                                 		  									IND_STUBS_PAY_RCVS__c = 'Y',
                                  		 									DTE_BEGIN_EFFV__c = date.today(),
                                         									NAM_BUSNS__c = 'DellCorp' );
        insert employment;
        insert new T_INDIV_EMPLMT_INFO__c (	IDN_EMPLMT_INDIV__c = employment.Id,
                                        	CDE_TYPE_INFO_EMPLMT__c = 'EIW',
                                          DTE_BEGIN_EFFV__c = system.today());
        
        Test.startTest();
		CaseLastUpdatedTestFactory.testCaseDataUpdate();
        EmploymentTempBreakBatch obj = new EmploymentTempBreakBatch();
        DataBase.executeBatch(obj);
        //05.16.2018 - Assert added for Code Review changes - Shubham K
        
        List<T_SBSD_CASE__c> caseRecords = [SELECT IND_CHGD_DATA_ELIGTY__c, DTE_CHGD_LAST_DATA_ELIGTY__c FROM T_SBSD_CASE__c limit 100];
        System.assertEquals(false,caseRecords.isEmpty(),'caseRecords should not be empty');
        System.assertEquals(System.today(), caseRecords.get(0).DTE_CHGD_LAST_DATA_ELIGTY__c, 'DTE_CHGD_LAST_DATA_ELIGTY__c should be equal to today');
        
        Test.stopTest();
    }


}