CHATS_SIT/force-app/main/default/objects/T_INDIV_EDUC__c.object
<CustomObject>
    <description>Individual Education information</description>
    <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_INFO_EDUC__c</fullName>
        <label>Temporary Break Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00854_BreakType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Verified</description>
        <label>Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Teen Parent Education</relationshipLabel>
        <relationshipName>T_SBSD_INDIV7</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teen Parent Education</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Training or Education ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teen Parent Education</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_INDIV_EDUC_INFO__c.object
<CustomObject>
   <!--  <enableLicensing>false</enableLicensing>-->
    <fields>
        <fullName>CDE_TYPE_INFO_EDUC__c</fullName>
        <label>Temporary Break Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00854_BreakType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_VERIF__c</fullName>
        <description>Verified</description>
        <label>Verified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00367</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_EDUC_INDIV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teen Parent Education ID</label>
        <referenceTo>T_INDIV_EDUC__c</referenceTo>
        <relationshipLabel>Teen Parent Education Temporary Break</relationshipLabel>
        <relationshipName>Teen_Parent_Education_Temporary_Break</relationshipName>
        <type>Lookup</type> 
    </fields>
    <label>Teen Parent Education Temporary Break</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Teen Parent Education Temporary Break ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teen Parent Education Temporary Break</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Future_validation</fullName>
        <active>false</active>
        <description>Begin Date can not be more than 31 days in future.</description>
        <errorConditionFormula>DTE_BEGIN_EFFV__c &gt; Today()+31</errorConditionFormula>
        <errorMessage>Begin Date can not be more than 31 days in future</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>DTE_CHGD_LAST_DATA_ELIGTY__c</fullName>
        <description>Eligibility Data Last Changed Date</description>
        <label>Eligibility Data Last Changed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IND_CHGD_DATA_ELIGTY__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Eligibility Data Changed</description>
        <label>Eligibility Data Changed</label>
        <type>Checkbox</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00367.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Available</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <label>Verbal Verification</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Written Verification</label>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
        <isActive>false</isActive>
        <label>CV</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
        <isActive>false</isActive>
        <label>N/A-adult caretaker</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <isActive>false</isActive>
        <label>SV</label>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
        <isActive>false</isActive>
        <label>N/A-not requesting child</label>
    </customValue>
    <customValue>
        <fullName>PEN</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>R00367</description>
    <masterLabel>R00367</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00854_BreakType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ESB</fullName>
        <label>Education Session Break</label>
    </customValue>
    <customValue>
        <fullName>MPL</fullName>
        <label>Maternity/Paternity</label>
    </customValue>
    <customValue>
        <fullName>ML</fullName>
        <label>Medical leave</label>
    </customValue>
    <description>R00854_BreakType</description>
    <masterLabel>R00854_BreakType</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/EducationTriggerTest.cls
@isTest
public class EducationTriggerTest {
    public static testMethod void testCaseLastUpdatedFields(){
        Map<String, SObject> caseData = CaseLastUpdatedTestFactory.createCaseData();
        T_INDIV_EDUC__c indivEduc = new T_INDIV_EDUC__c(	IDN_CLIENT__c=caseData.get('individual').Id,
                                   	CDE_TYPE_VERIF__c = 'NA',
                                   	DTE_BEGIN_EFFV__c = date.today() );
        insert indivEduc;
        Test.startTest();
        T_INDIV_EDUC_INFO__c indivEduc1 = new T_INDIV_EDUC_INFO__c(	IDN_EDUC_INDIV__c=indivEduc.Id,
                                   	CDE_TYPE_INFO_EDUC__c = 'MPL',
                                       CDE_TYPE_VERIF__c = 'NA',
                                   	DTE_BEGIN_EFFV__c = date.today() );
        insert indivEduc1;
		CaseLastUpdatedTestFactory.testCaseDataUpdate();
        TeenEduBreakBatch obj = new TeenEduBreakBatch();
        DataBase.executeBatch(obj);
        // 5/16/2018 - Assert statement added for Code Review Changes : Shubham K.
        List<T_SBSD_CASE__c> caseRecords = [SELECT IND_CHGD_DATA_ELIGTY__c, DTE_CHGD_LAST_DATA_ELIGTY__c FROM T_SBSD_CASE__c limit 100];
        System.assertEquals(false,caseRecords.isEmpty(),'caseRecords should not be empty');
        System.assertEquals(System.today(), caseRecords.get(0).DTE_CHGD_LAST_DATA_ELIGTY__c, 'DTE_CHGD_LAST_DATA_ELIGTY__c should be equal to today');
        Test.stopTest();
    }

}