CHATS_SIT/force-app/main/default/objects/T_INDIV_VERIF__c.object
<CustomObject>
    <description>Individual verification tracking</description>
    <fields>
        <fullName>CDE_TYPE_INFO_INDIV__c</fullName>
        <description>Type of Individual Information</description>
        <label>Type of Individual Information</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00366</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual Information ID</label>
        <referenceTo>T_SBSD_INDIV_INFO__c</referenceTo>
        <relationshipLabel>Individual Verification</relationshipLabel>
        <relationshipName>Individual_Verification</relationshipName>
        <type>Lookup</type> 
    </fields>
    <label>Individual Verification</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Individual Verification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Individual_Status__c</fullName>
        <description>CCCAP-13633</description>
        <label>Individual Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
            <value>
                <fullName>PC</fullName>
                <label>Primary Caretaker</label>
            </value>
            <value>
                <fullName>AC</fullName>
                <label>Additional Caretaker</label>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>CDE_ATTENDING_SCHOOL1__c</fullName>
        <label>Child attending kindergarten or above?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_ETNCTY__c</fullName>
        <description>Ethnicity</description>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00114</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_GENDER__c</fullName>
        <description>Gender</description>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00080</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_RACE__c</fullName>
        <description>Race</description>
        <label>Race</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00130</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_SOURCE_VRFYD_CITIZEN__c</fullName>
        <description>How Verified (Citizenship)</description>
        <label>How Verified (Citizenship)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00708</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_SOURCE_VRFYD_DOB__c</fullName>
        <description>How Verified (DOB)</description>
        <label>How Verified (DOB)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00706</valueSetName>
        </valueSet>
    </fields>
    
    <fields>
        <fullName>IND_CDE_TYPE_VERIF_DOB__c</fullName>
        <description>This is new field for DOB verification for removing global picklist Set R000367 reference.</description>
        <label>DOB verified?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A-adult caretaker</fullName>
                </value>
                <value>
                    <fullName>N/A-not requesting child</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <label>Not Available</label>
                </value>
                <value>
                    <fullName>SD</fullName>
                    <label>Verbal Verification</label>
                </value>
                <value>
                    <fullName>V</fullName>
                    <label>Written Verification</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IND_CHILD_IDEA__c</fullName>
        <description>Have you referred this child to Part B or C of the Individuals with Disabilities Education Act (IDEA)?*</description>
        <label>Child referred to IDEA Part B or C?*</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00619</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IND_CHILD_SCREEN__c</fullName>
        <description>Have you referred this child to Early and Periodic Screening Diagnosis and Treatment?*</description>
        <label>Referred to Early &amp; Periodic Screening?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00619</valueSetName>
        </valueSet>
    </fields>

    <fields>
        <fullName>Bypass_On__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Bypass On</label>
        <type>DateTime</type>
    </fields>
    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_INFO__c.object
<CustomObject>
    <description>Information codes about individual</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_INFO_INDIV__c</fullName>
        <description>Type of Individual Information</description>
        <label>Individual Information Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00366</valueSetName>
        </valueSet>
    </fields> 
    <fields>
        <fullName>CDE_VALUE_INFO_INDIV__c</fullName>
        <label>Individual Information Value</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CDE_TYPE_INFO_INDIV__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>R00847</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Individual Information (Individual)</relationshipLabel>
        <relationshipName>Individual_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Individual Information</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Individual Information ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00080.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Male</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Female</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>X</label>
    </customValue>
    <description>R00080</description>
    <masterLabel>R00080</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00114.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>H</fullName>
        <label>Hispanic</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Non-Hispanic</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Unknown</label>
    </customValue>
    <description>R00114</description>
    <masterLabel>R00114</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00130.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Black/African American</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>American Indian/Alaskan Native</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Asian</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>White</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Native Hawaiian/Other Pacific Islander</label>
    </customValue>
    <description>R00130</description>
    <masterLabel>R00130</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00366.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CS</fullName>
        <label>citizenship status</label>
    </customValue>
    <customValue>
        <fullName>HDS</fullName>
        <label>head start</label>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
        <label>marital status</label>
    </customValue>
    <customValue>
        <fullName>FST</fullName>
        <label>foster care</label>
    </customValue>
    <customValue>
        <fullName>IMM</fullName>
        <isActive>false</isActive>
        <label>age appropriate immunization</label>
    </customValue>
    <description>R00366</description>
    <masterLabel>R00366</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00619.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <description>R00619</description>
    <masterLabel>R00619</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00847.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3</fullName>
        <label>Common Law Relationship</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Divorced</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Married - Living w/ Spouse</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Married - Not living with Spouse (Involuntarily)</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Married - Not living with Spouse (Voluntarily)</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Significant Other</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Single - Never Married</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Widow/Widower</label>
    </customValue>
    <customValue>
        <fullName>CZN</fullName>
        <label>Citizen</label>
    </customValue>
    <customValue>
        <fullName>NCZ</fullName>
        <label>Non-Citizen</label>
    </customValue>
    <customValue>
        <fullName>LFR</fullName>
        <label>Qualified Alien</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>N/A-adult caretaker</fullName>
    </customValue>
    <customValue>
        <fullName>N/A-not requesting child</fullName>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <masterLabel>R00847</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/AdultIndividualUpdate.cls
//Commenting out as the batch is no longer in use
global with sharing class AdultIndividualUpdate{
    /*global List<Exception> batchErrors = new List<Exception>();
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id FROM T_SBSD_INDIV__c where id not in (select idn_client__c from t_sbsd_case_indiv__c where Individual_Status__c ='Child' and (DTE_END_EFFV__c=null or DTE_END_EFFV__c >today)) and id in (select IDN_CLIENT__c from t_sbsd_case_indiv__c where (Individual_Status__c ='PC' or Individual_Status__c ='AC') and (DTE_END_EFFV__c=null or DTE_END_EFFV__c >today))]);
    }

    global void execute(Database.BatchableContext BC, List<T_SBSD_INDIV__c> scope){
		Set<Id> indAdult = new Set<Id>();
        List<T_INDIV_VERIF__c> indivVerifToDelete = new List<T_INDIV_VERIF__c>();
        List<T_SBSD_INDIV_INFO__c> indivInfoToUpdate = new List<T_SBSD_INDIV_INFO__c>();
        List<T_SBSD_INDIV__c> indivToUpdate = new List<T_SBSD_INDIV__c>();
        List<String> indivFieldsToUpdate = new List<String>{'CDE_GENDER__c','CDE_ATTENDING_SCHOOL1__c','IND_CHILD_IDEA__c','IND_CHILD_SCREEN__c','CDE_RACE__c','CDE_ETNCTY__c','IND_CDE_TYPE_VERIF_DOB__c','CDE_SOURCE_VRFYD_DOB__c','CDE_SOURCE_VRFYD_CITIZEN__c'};
        for(T_SBSD_INDIV__c indiv : scope){
            indAdult.add(indiv.Id);
        }
       	for(T_SBSD_INDIV_INFO__c indivInfo : [SELECT Id,IDN_CLIENT__c,CDE_VALUE_INFO_INDIV__c, (SELECT Id FROM Individual_Verification__r WHERE CDE_TYPE_INFO_INDIV__c = 'CS') 
                                                FROM T_SBSD_INDIV_INFO__c WHERE IDN_CLIENT__c IN :indAdult AND CDE_TYPE_INFO_INDIV__c = 'CS']){
            if(indivInfo.CDE_VALUE_INFO_INDIV__c != 'N/A-adult caretaker'){
                indivInfo.CDE_VALUE_INFO_INDIV__c = 'N/A-adult caretaker';
                indivInfoToUpdate.add(indivInfo);
            }
            if(indivInfo.Individual_Verification__r!=null && indivInfo.Individual_Verification__r.size()>0){
                indivVerifToDelete.addAll(indivInfo.Individual_Verification__r);
            }
        }
        
        List<T_SBSD_INDIV__c> indivList = [SELECT Id, CDE_GENDER__c,CDE_ATTENDING_SCHOOL1__c, IND_CHILD_IDEA__c, IND_CHILD_SCREEN__c, CDE_RACE__c, CDE_ETNCTY__c, IND_CDE_TYPE_VERIF_DOB__c, CDE_SOURCE_VRFYD_DOB__c, CDE_SOURCE_VRFYD_CITIZEN__c FROM T_SBSD_INDIV__c WHERE Id IN :indAdult];
        for(T_SBSD_INDIV__c indiv : indivList){
            indiv.CDE_GENDER__c = (indiv.CDE_GENDER__c != '3') ? '3' : indiv.CDE_GENDER__c;
            indiv.CDE_ATTENDING_SCHOOL1__c = (indiv.CDE_ATTENDING_SCHOOL1__c != 'Unknown') ? 'Unknown' : indiv.CDE_ATTENDING_SCHOOL1__c;
            indiv.IND_CHILD_IDEA__c = (indiv.IND_CHILD_IDEA__c != 'N') ? 'N' : indiv.IND_CHILD_IDEA__c;
            indiv.IND_CHILD_SCREEN__c = (indiv.IND_CHILD_SCREEN__c != 'N') ? 'N' : indiv.IND_CHILD_SCREEN__c;
            indiv.CDE_RACE__c = (indiv.CDE_RACE__c != '6') ? '6' : indiv.CDE_RACE__c; 
            indiv.CDE_ETNCTY__c = (indiv.CDE_ETNCTY__c != 'U') ? 'U' : indiv.CDE_ETNCTY__c;
            indiv.IND_CDE_TYPE_VERIF_DOB__c = (indiv.IND_CDE_TYPE_VERIF_DOB__c != 'N/A-adult caretaker') ? 'N/A-adult caretaker' : indiv.IND_CDE_TYPE_VERIF_DOB__c;
            indiv.CDE_SOURCE_VRFYD_DOB__c = (indiv.CDE_SOURCE_VRFYD_DOB__c != '' || indiv.CDE_SOURCE_VRFYD_DOB__c != null) ? '' : indiv.CDE_SOURCE_VRFYD_DOB__c;
            indiv.CDE_SOURCE_VRFYD_CITIZEN__c = (indiv.CDE_SOURCE_VRFYD_CITIZEN__c != '' || indiv.CDE_SOURCE_VRFYD_CITIZEN__c != null) ? '' : indiv.CDE_SOURCE_VRFYD_CITIZEN__c; 
            indiv.Bypass_On__c = System.now();
            indivToUpdate.add(indiv);
        }
        try {
            if(!indivVerifToDelete.isEmpty()){
                GenericDMLHandler.deleteRecords(indivVerifToDelete, new Map<String,Object>{'Method__c'=>'execute','Class__c'=>'AdultIndividualUpdate'});
            }
            if(!indivInfoToUpdate.isEmpty()){
                GenericDMLHandler.updateRecords(indivInfoToUpdate, false, new Map<String,Object>{'Method__c'=>'execute','Class__c'=>'AdultIndividualUpdate'});
            }
            if(!indivToUpdate.isEmpty()){
                IndividualServices.disableTrigger = true;
                GenericDMLHandler.updateRecords(indivToUpdate, false, new Map<String,Object>{'Method__c'=>'execute','Class__c'=>'AdultIndividualUpdate'});
                IndividualServices.disableTrigger = false;
            }
        } catch(DMLException ex) {
            IndividualServices.disableTrigger = false;
            batchErrors.add(ex);
        } catch(Exception e) {
            IndividualServices.disableTrigger = false;
            batchErrors.add(e);
        }
    }

    global void finish(Database.BatchableContext BC){
        if(!batchErrors.isEmpty()){
            Map<String,Object> methodInfo = new Map<String,Object>{'Method__c' => 'execute','Class__c' => 'AdultIndividualUpdate'};
            for(Exception e : batchErrors){
                ExceptionLoggingServices.captureExceptionLog(e, methodInfo);
            }
        }
    }*/
}