CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_TYPE_STATUS__c</fullName>
        <description>Fiscal Agreement Status</description>
        <label>Fiscal Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00703</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_AGRMT__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <recordTypes>
        <fullName>Finalized</fullName>
        <active>true</active>
        <label>Finalized</label>
    </recordTypes>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00703.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CLS</fullName>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>OPN</fullName>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>FIN</fullName>
        <label>Finalized</label>
    </customValue>
    <customValue>
        <fullName>DFT</fullName>
        <label>Draft</label>
    </customValue>
    <description>R00703</description>
    <masterLabel>R00703</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/OpenFiscalAgreementsBatch.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           08/26/2020                                                          
*  @description    Batch class for opening Fiscal Agreements which have begin date today and 
				   status finalized
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 08/26/2020
*  * Author: Balamurugan Chinnaiah
*  * Description: Initial version 
*********************************************************************************************/
global with sharing class OpenFiscalAgreementsBatch implements Database.Batchable<sObject>{
    Public Final Id OPEN_RECORD_TYPE_ID = Schema.SObjectType.T_PROVR_FISCAL_AGREMENT__c.getRecordTypeInfosByName().get('Open').getRecordTypeId();
    Public Final String FINALIZED_STATUS = 'FIN';
	Public Final String OPEN_STATUS = 'OPN';
    global Database.QueryLocator start(Database.BatchableContext BC){
        Date dateToday =  System.today() ;
        return Database.getQueryLocator('SELECT Id, CDE_TYPE_STATUS__c, DTE_BEGIN_AGRMT__c FROM T_PROVR_FISCAL_AGREMENT__c where CDE_TYPE_STATUS__c =:FINALIZED_STATUS and DTE_BEGIN_AGRMT__c =:dateToday');   
    }
    
    global void execute(Database.BatchableContext BC, List<T_PROVR_FISCAL_AGREMENT__c> scope){
        List<T_PROVR_FISCAL_AGREMENT__c> lstFARecords = new List<T_PROVR_FISCAL_AGREMENT__c>();
        for(T_PROVR_FISCAL_AGREMENT__c faRecord: scope){
			faRecord.CDE_TYPE_STATUS__c = OPEN_STATUS;
			faRecord.RecordtypeId =  OPEN_RECORD_TYPE_ID;
            lstFARecords.add(faRecord); 
        }
        if(!lstFARecords.isEmpty()){
        	GenericDMLHandler.updateRecords(lstFARecords, false, new Map<String,Object>{'Method__c'=>'execute','Class__c'=>'OpenFiscalAgreementsBatch'});
        }   
    }
    
    global void finish(Database.BatchableContext BC){
        
        
    }
}