CHATS_SIT/force-app/main/default/objects/T_PROVR_PREF__c.object
<CustomObject>
    <fields>
        <fullName>CDE_PREF_CORR_PROVR__c</fullName>
        <description>Correspondence Preference</description>
        <label>Correspondence Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_COR_PREF</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_PREF_LANG_PROVR__c</fullName>
        <description>Language Preference</description>
        <label>Language Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00057</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IND_ACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active?</description>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Correspondence and Language Preferences</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Correspondence and Language Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/RT_COR_PREF.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>MAIL</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>EMAIL</label>
    </customValue>
    <description>RT_COR_PREF</description>
    <masterLabel>RT_COR_PREF</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CorrespondanceAndLangPrefService_Test.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           11/08/2017                                                          
*  @description   Test class for Correspondance and Language Preference  Handler                           
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 09-Nov-2017                                                             
*  * Author: Shubham Khandelwal                                                      
*  * Description: Initial version                                                 
*                                                                                 
*********************************************************************************************/

@isTest()
public class CorrespondanceAndLangPrefService_Test {
    
    private static String EMAIL = '2';
    private static String MAIL = '1';
    private static String ENGLISH = 'ENG';
    private static String POLISH = 'POL';
    private static String OTHER = 'OTH';
    
    
    static T_PROVR_PREF__c corresAndlangfPref;
    
    static void createTestData(){
        
        List<T_PROVR_PREF__c> lstCorresAndlangfPref = new List<T_PROVR_PREF__c>();
        T_PROVR_PREF__c activeCorresAndlangfPref1 = TestClassUtility.createCorrespondanceAndLanguagePref(true,EMAIL,ENGLISH);
        T_PROVR_PREF__c activeCorresAndlangfPref2 = TestClassUtility.createCorrespondanceAndLanguagePref(true,MAIL,POLISH);
        T_PROVR_PREF__c inactiveCorresAndlangfPref3 = TestClassUtility.createCorrespondanceAndLanguagePref(false,MAIL,POLISH);
        corresAndlangfPref = TestClassUtility.createCorrespondanceAndLanguagePref(true,MAIL,POLISH);
        
        lstCorresAndlangfPref.add(activeCorresAndlangfPref1);
        lstCorresAndlangfPref.add(activeCorresAndlangfPref2);
        lstCorresAndlangfPref.add(inactiveCorresAndlangfPref3);
        
        if(lstCorresAndlangfPref.size() > 0){
        	insert lstCorresAndlangfPref;
        }
            
        
    }
    
    static testmethod  void testBeforeTriggerCorresAndLanPref(){
        
        createTestData();
        
        Test.startTest();
        
        List<T_PROVR_PREF__c> lstActiveCorresAndlangfPref = [Select Id,IND_ACTIVE__c,CDE_PREF_CORR_PROVR__c,CDE_PREF_LANG_PROVR__c 
                                                             from T_PROVR_PREF__c where IND_ACTIVE__c = true ];
        
        System.assert(lstActiveCorresAndlangfPref.size() > 0,'Correspondence and Language Preferences cannot be empty');
        
        if(corresAndlangfPref != null){
           insert corresAndlangfPref;	
        }
         
        
        List<T_PROVR_PREF__c> lstAfterInsert = [Select Id,IND_ACTIVE__c,CDE_PREF_CORR_PROVR__c,CDE_PREF_LANG_PROVR__c 
                                                from T_PROVR_PREF__c where IND_ACTIVE__c = true and id =:corresAndlangfPref.id];
        
        System.assertEquals(1, lstAfterInsert.size(),'Should have one Correspondence and Language Preferences record');
        
        List<T_PROVR_PREF__c> lstInactiveCorresAndlangfPref = [Select Id,IND_ACTIVE__c,CDE_PREF_CORR_PROVR__c,CDE_PREF_LANG_PROVR__c 
                                                               from T_PROVR_PREF__c where IND_ACTIVE__c = false ];
        
        System.assert(lstInactiveCorresAndlangfPref.size() > 0,'Correspondence and Language Preferences cannot be empty');
        
        test.stopTest();
   
    }
    
    public static testMethod void testProcessSaveResult(){
        T_PROVR_PREF__c corresAndlangfPref = TestClassUtility.createCorrespondanceAndLanguagePref(true,MAIL,POLISH);
        corresAndlangfPref.CDE_PREF_LANG_PROVR__c = 'SOME_RANDOM_PICKLIST_VALUE';
        CorrespondanceAndLangPrefService.processSaveResult(new List<SObject>{corresAndlangfPref});     
        system.assertEquals('SOME_RANDOM_PICKLIST_VALUE',corresAndlangfPref.CDE_PREF_LANG_PROVR__c ,'Should match the value');         
    }
    
}