CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>DTE_CHGD_LAST_DATA_ELIGTY__c</fullName>
        <description>Eligibility Data Last Changed Date</description>
        <label>Eligibility Data Last Changed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Case ID External</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IND_CHGD_DATA_ELIGTY__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Eligibility Data Changed</description>
        <label>Eligibility Data Changed</label>
        <type>Checkbox</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV_INFO__c.object
<CustomObject>
    <description>Information codes about individual</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_INFO_INDIV__c</fullName>
        <description>Type of Individual Information</description>
        <label>Individual Information Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00366</valueSetName>
        </valueSet>
    </fields> 
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Individual Information (Individual)</relationshipLabel>
        <relationshipName>Individual_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_EXTNL__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Individual Information</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Individual Information ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00366.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CS</fullName>
        <label>citizenship status</label>
    </customValue>
    <customValue>
        <fullName>HDS</fullName>
        <label>head start</label>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
        <label>marital status</label>
    </customValue>
    <customValue>
        <fullName>FST</fullName>
        <label>foster care</label>
    </customValue>
    <customValue>
        <fullName>IMM</fullName>
        <isActive>false</isActive>
        <label>age appropriate immunization</label>
    </customValue>
    <description>R00366</description>
    <masterLabel>R00366</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/IndividualInformationTriggerTest.cls
@isTest
public class IndividualInformationTriggerTest {
    public static testMethod void testCaseLastUpdatedFields(){
        Map<String, SObject> caseData = CaseLastUpdatedTestFactory.createCaseData();
        insert new T_SBSD_INDIV_INFO__c(	IDN_CLIENT__c = caseData.get('individual').Id,
                                        CDE_TYPE_INFO_INDIV__c = 'HDS',
                                        IDN_EXTNL__c = '12345',
                                        DTE_BEGIN_EFFV__c = date.today() );
        Test.startTest();
        CaseLastUpdatedTestFactory.testCaseDataUpdate();
        
        // 5.16.2018 - Added assert statement as part of code review changes :Shubham K
        List<T_SBSD_CASE__c> caseRecords = [SELECT IND_CHGD_DATA_ELIGTY__c, DTE_CHGD_LAST_DATA_ELIGTY__c FROM T_SBSD_CASE__c limit 100];
        System.assertEquals(false,caseRecords.isEmpty(),'caseRecords should not be empty');
        System.assertEquals(System.today(), caseRecords.get(0).DTE_CHGD_LAST_DATA_ELIGTY__c, 'DTE_CHGD_LAST_DATA_ELIGTY__c should be equal to today');
        
        Test.stopTest();
    }

}