CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>DTE_CHGD_LAST_DATA_ELIGTY__c</fullName>
        <description>Eligibility Data Last Changed Date</description>
        <label>Eligibility Data Last Changed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IND_CHGD_DATA_ELIGTY__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Eligibility Data Changed</description>
        <label>Eligibility Data Changed</label>
        <type>Checkbox</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_PHONE__c.object
<CustomObject>
    <description>Information about the phone numbers collected for a household</description>
    <fields>
        <fullName>CDE_TYPE_PHONE__c</fullName>
        <description>Phone Number Type</description>
        <label>Phone Number Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00159</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Phone</relationshipLabel>
        <relationshipName>T_SBSD_CASE14</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NBR_PHONE_EXTN__c</fullName>
        <description>Phone Number Ext.</description>
        <label>Phone Number Ext.</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NBR_PHONE__c</fullName>
        <description>Phone Number</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Case Phone</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Phone Number ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Phone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00159.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EMR</fullName>
        <label>Emergency</label>
    </customValue>
    <customValue>
        <fullName>HOM</fullName>
        <label>Home</label>
    </customValue>
    <customValue>
        <fullName>MOB</fullName>
        <label>Mobile</label>
    </customValue>
    <customValue>
        <fullName>WOR</fullName>
        <label>Work</label>
    </customValue>
    <description>R00159</description>
    <masterLabel>R00159</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CasePhoneTriggerTest.cls
@isTest
public class CasePhoneTriggerTest {
    public static testMethod void testCaseLastUpdatedFields(){
        Map<String, SObject> caseData = CaseLastUpdatedTestFactory.createCaseData();
        insert new T_SBSD_CASE_PHONE__c(IDN_CASE__c=caseData.get('caseRec').Id,NBR_PHONE__c='123456',
                                        NBR_PHONE_EXTN__c=3244,
                                        CDE_TYPE_PHONE__c='HOM');
        
        Test.startTest();
        CaseLastUpdatedTestFactory.testCaseDataUpdate();
         // 5/16/2018 - Assert statement added for Code Review Changes : Shubham K.
        List<T_SBSD_CASE__c> caseRecords = [SELECT IND_CHGD_DATA_ELIGTY__c, DTE_CHGD_LAST_DATA_ELIGTY__c FROM T_SBSD_CASE__c limit 100];
        System.assertEquals(false,caseRecords.isEmpty(),'caseRecords should not be empty');
        System.assertEquals(System.today(), caseRecords.get(0).DTE_CHGD_LAST_DATA_ELIGTY__c, 'DTE_CHGD_LAST_DATA_ELIGTY__c should be equal to today');
        Test.stopTest();
    }
}