CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_STATE__c</fullName>
        <formula>IDN_CLIENT__r.IDN_STATE__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IND_CRTKR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is the Primary Parent/Caretaker</description>
        <label>Primary Parent/Caretaker</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV_ROLE__c.object
<CustomObject>
    <description>Identifies the primary applicant/head of household for a case</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_ROLE_CASE__c</fullName>
        <description>Role</description>
        <label>Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00355</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE_INDIV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Individual ID</label>
        <referenceTo>T_SBSD_CASE_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual Role</relationshipLabel>
        <relationshipName>Case_Individual_Role</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Individual Role</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00355.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>HOH</fullName>
        <default>true</default>
        <label>Head of Household</label>
    </customValue>
    <customValue>
        <fullName>LIC</fullName>
        <label>Live-In-Companion (of Head of Household)</label>
    </customValue>
    <customValue>
        <fullName>SPS</fullName>
        <label>Spouse (of Head of Household)</label>
    </customValue>
    <description>R00355</description>
    <masterLabel>R00355</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CR109DataLoader.cls
public with sharing class CR109DataLoader extends AbstractCorspdDataLoader{
    
    public CR109DataLoader(string corspdName, string caseId, integer providerId, string corrId ){
        this.corspdName = corspdName;
        this.caseId = caseId;
        this.providerId = providerId;
        this.corrId = corrId;
    }
    public override string getxmldata(){
        XmlStreamWriter xmlWrtr = new XmlStreamWriter();
	    xmlWrtr.writeStartDocument(null, '1.0" encoding="US-ASCII');
        xmlWrtr.writeStartElement(null, 'Correspondence', null); 

        //setCorspdInfo(xmlWrtr);
        
        setClientHeaderInfo(xmlWrtr);
        setKeyParameters(xmlWrtr);
        setSignatureInfo(xmlWrtr, 'C',this.caseId, null, null);
        
        xmlWrtr.writeEndElement(); 
        xmlWrtr.writeEndDocument();
		xmldata = xmlWrtr.getXmlString();
		xmlWrtr.close();
        return xmldata;
    }
    public override void setCorspdInfo(XmlStreamWriter xmlWrtr){
        createElement(xmlWrtr, 'Template_Name', this.corspdName);
        createElement(xmlWrtr, 'Reason_Code', 'CR0005');
        createElement(xmlWrtr, 'CORSPD_Effective_Date', '2017-10-18');
        createElement(xmlWrtr, 'REPRINT_SW', 'N');
        createElement(xmlWrtr, 'lang_cd', 'EN');
    }    
    public override void setKeyParameters(XmlStreamWriter xmlWrtr){
        List<T_SBSD_CASE_INDIV_ROLE__c> caseStateId = new List<T_SBSD_CASE_INDIV_ROLE__c>();
        xmlWrtr.writeStartElement(null, 'KeyParameter', null);
        createElement(xmlWrtr, 'CorrespondenceId', this.corrId);
        createElement(xmlWrtr, 'CaseNumber', this.caseId);
        Date dt = system.today();
        String dateRequested = dt.month() + '/' + dt.day() + '/' + dt.year();
        createElement(xmlWrtr, 'CreationDate', dateRequested);
        //Added order by to fetch latest active PC CCCAP-15253
        caseStateId = [	Select IDN_CASE_INDIV__r.IDN_CASE__c, IDN_CASE_INDIV__r.IDN_STATE__c, IDN_CASE_INDIV__r.IND_CRTKR__c 
                       	from T_SBSD_CASE_INDIV_ROLE__c 
                       	where IDN_CASE_INDIV__r.IDN_CASE__r.Name = :this.caseId
                       	and IDN_CASE_INDIV__r.IND_CRTKR__c = true
                        and CDE_ROLE_CASE__c = 'HOH' order by IDN_CASE_INDIV__r.DTE_END_EFFV__c Desc
                        limit 1];
        if(caseStateId.size() == 1) {
            createElement(xmlWrtr, 'StateId', caseStateId[0].IDN_CASE_INDIV__r.IDN_STATE__c );
        } else {
            createElement(xmlWrtr, 'StateId', '');
        }
        xmlWrtr.writeEndElement();
    }
}