CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>DTE_CHGD_LAST_DATA_ELIGTY__c</fullName>
        <description>Eligibility Data Last Changed Date</description>
        <label>Eligibility Data Last Changed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IND_CHGD_DATA_ELIGTY__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Eligibility Data Changed</description>
        <label>Eligibility Data Changed</label>
        <type>Checkbox</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV_ROLE__c.object
<CustomObject>
    <description>Identifies the primary applicant/head of household for a case</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_ROLE_CASE__c</fullName>
        <description>Role</description>
        <label>Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00355</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_CASE_INDIV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Individual ID</label>
        <referenceTo>T_SBSD_CASE_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual Role</relationshipLabel>
        <relationshipName>Case_Individual_Role</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Individual Role</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual Role</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00355.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>HOH</fullName>
        <default>true</default>
        <label>Head of Household</label>
    </customValue>
    <customValue>
        <fullName>LIC</fullName>
        <label>Live-In-Companion (of Head of Household)</label>
    </customValue>
    <customValue>
        <fullName>SPS</fullName>
        <label>Spouse (of Head of Household)</label>
    </customValue>
    <description>R00355</description>
    <masterLabel>R00355</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CaseIndivRoleTriggerTest.cls
@isTest
public class CaseIndivRoleTriggerTest {
 public static testMethod void testCaseLastUpdatedFields(){
        Map<String, SObject> caseData = CaseLastUpdatedTestFactory.createCaseData();
        insert new T_SBSD_CASE_INDIV_ROLE__c(IDN_CASE_INDIV__c=caseData.get('caseIndiv').Id,DTE_BEGIN_EFFV__c= System.today(),
                                        DTE_END_EFFV__c=System.today(),
                                        CDE_ROLE_CASE__c='HOH');
        
        Test.startTest();
        CaseLastUpdatedTestFactory.testCaseDataUpdate();
     	 // 5/16/2018 - Assert statement added for Code Review Changes : Shubham K.
        List<T_SBSD_CASE__c> caseRecords = [SELECT IND_CHGD_DATA_ELIGTY__c, DTE_CHGD_LAST_DATA_ELIGTY__c FROM T_SBSD_CASE__c limit 100];
        System.assertEquals(false,caseRecords.isEmpty(),'caseRecords should not be empty');
        System.assertEquals(System.today(), caseRecords.get(0).DTE_CHGD_LAST_DATA_ELIGTY__c, 'DTE_CHGD_LAST_DATA_ELIGTY__c should be equal to today');
        Test.stopTest();
    }
}