CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/batchsit_t_fiscal_rate__x.object-meta.xml
<CustomObject>
    <description>batchsit$t_fiscal_rate</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_fiscal_rate</externalName>
    <label>batchsit$t_fiscal_rate</label>
    <pluralLabel>batchsit$t_fiscal_rate</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/fields/amt_fa__c.field-meta.xml
<CustomField>
    <fullName>amt_fa__c</fullName>
    <description>amt_fa</description>
    <externalDeveloperName>amt_fa</externalDeveloperName>
    <label>Fiscal Agreement Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/fields/cde_age_group__c.field-meta.xml
<CustomField>
    <fullName>cde_age_group__c</fullName>
    <description>cde_age_group</description>
    <externalDeveloperName>cde_age_group</externalDeveloperName>
    <label>Age Group</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/fields/cde_care_unit__c.field-meta.xml
<CustomField>
    <fullName>cde_care_unit__c</fullName>
    <description>cde_care_unit</description>
    <externalDeveloperName>cde_care_unit</externalDeveloperName>
    <label>Care Unit</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_fiscal_rate__x/fields/idn_fiscal_sch__c.field-meta.xml
<CustomField>
    <fullName>idn_fiscal_sch__c</fullName>
    <description>idn_fiscal_sch</description>
    <externalDeveloperName>idn_fiscal_sch</externalDeveloperName>
    <label>idn_fiscal_sch</label>
    <length>18</length>
    <referenceTargetField>T_FISCAL_SCH__c.IDN_EXTNL__c</referenceTargetField>
    <referenceTo>T_FISCAL_SCH__c</referenceTo>
    <relationshipLabel>batchsit$t_fiscal_rate</relationshipLabel>
    <relationshipName>batchsit_t_fiscal_rate</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <label>License Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Quality Rating</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_RATE__c.object
<CustomObject>
    <description>County Rate</description>
    <fields>
        <fullName>CDE_STATUS__c</fullName>
        <description>Status</description>
        <label>Status(Old)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00676</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_EFFV_RATE__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_EFFV_RATE__c</fullName>
        <description>Effective End Date</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_COUNTY__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>County Rate Plan</relationshipLabel>
        <relationshipName>County4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_RATE_PLAN_TEMPLT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>County Rate Plan Template Indicator</description>
        <label>County Rate Plan Template Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAYMENT_Q10_1__c</fullName>
        <description>PAYMENT_Q10_1</description>
        <label>PAYMENT_Q10_1</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PAYMENT_Q11_1__c</fullName>
        <description>PAYMENT_Q11_1</description>
        <label>PAYMENT_Q11_1</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PAYMENT_Q17__c</fullName>
        <label>PAYMENT_Q17</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00619</valueSetName>
        </valueSet>
    </fields>

    <fields>
        <fullName>PAYMENT_Q9_1__c</fullName>
        <description>PAYMENT_Q9_1</description>
        <label>PAYMENT_Q9_1</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RATE_TYPE__c</fullName>
        <description>RATE_TYPE</description>
        <label>RATE_TYPE</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00751</valueSetName>
        </valueSet>
    </fields>
    <label>County Rate Plan</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Rate Plan</pluralLabel>
    <sharingModel>Read</sharingModel>
    <!--Commented
    as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Approved_Plan_cannot_be_updated</fullName>
        <active>false</active>
        <description>Approved Plan cannot be updated</description>
        <errorConditionFormula>OR(AND( NOT(ISCHANGED(CDE_STATUS__c)) ,NOT(ISNEW()),ISPICKVAL(CDE_STATUS__c,
    &apos;APV&apos;)), TEXT(PRIORVALUE(CDE_STATUS__c)) = &apos;APV&apos; )</errorConditionFormula>
        <errorMessage>Approved Plan cannot be updated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY_RATE_AMT__c.object
<CustomObject>
    <description>County Rate Amount</description>
    <fields>
        <fullName>CDE_AGE_GROUP__c</fullName>
        <description>Age Group</description>
        <label>Age Group</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00710</valueSetName>
        </valueSet>
    </fields>
    <label>County Rate</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County Rate</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_RAT_FEES__c.object
<CustomObject>
    <fields>
        <fullName>IDN_FISCAL_SCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Rate Schedule</description>
        <label>Rate Schedule</label>
        <referenceTo>T_FISCAL_SCH__c</referenceTo>
        <relationshipLabel>ART Fees</relationshipLabel>
        <relationshipName>RAT_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ART Fees</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ART Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_RATE__c/T_FISCAL_RATE__c.object-meta.xml
<CustomObject>
    <label>Rate</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_RATE__c/fields/AMT_FA__c.field-meta.xml
<CustomField>
    <fullName>AMT_FA__c</fullName>
    <label>Fiscal Rate Amount</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_RATE__c/fields/CDE_AGE_GROUP__c.field-meta.xml
<CustomField>
    <fullName>CDE_AGE_GROUP__c</fullName>
    <description>Age Group</description>
    <label>Age Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>R00710</valueSetName>
    </valueSet>
</CustomField>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_RATE__c/fields/CDE_CARE_UNIT__c.field-meta.xml
<CustomField>
    <fullName>CDE_CARE_UNIT__c</fullName>
    <description>Care Unit</description>
    <label>Care Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>R00715</valueSetName>
    </valueSet>
</CustomField>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_RATE__c/fields/IDN_FISCAL_SCH__c.field-meta.xml
<CustomField>
    <fullName>IDN_FISCAL_SCH__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fiscal Rate Schedule</label>
    <referenceTo>T_FISCAL_SCH__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/T_FISCAL_SCH__c.object
<CustomObject>
    <fields>
        <fullName>DTE_BEGIN_EFFV__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_AGRMT_FISCAL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement</description>
        <label>Fiscal Agreement</label>
        <referenceTo>T_PROVR_FISCAL_AGREMENT__c</referenceTo>
        <relationshipLabel>Rate Schedules</relationshipLabel>
        <relationshipName>Rate_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TXT_CHATS_RATING__c</fullName>
        <label>Rate Schedule Quality Rating</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Rate Schedules</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_PROVR_FISCAL_AGREMENT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fiscal Agreement County</description>
        <label>Fiscal Agreement County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreement</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_TYPE_FACILITY__c</fullName>
        <label>Facility Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RT_FAC_TYPE</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_AGRMT__c</fullName>
        <description>Effective Begin Date</description>
        <label>Effective Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_SERVICE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Provider Fiscal Agreements</relationshipLabel>
        <relationshipName>Provider_Fiscal_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Provider Fiscal Agreement</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Fiscal Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Date_Received_Required_for_Open_FA</fullName>
        <active>false</active>
        <description>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</description>
        <errorConditionFormula>AND (ISBLANK(DTE_RCV_AGRMT_FISCAL__c ) ,OR(ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;OPN&apos;) ,ISPICKVAL(CDE_TYPE_STATUS__c  , &apos;FIN&apos;)) )</errorConditionFormula>
        <errorDisplayField>DTE_RCV_AGRMT_FISCAL__c</errorDisplayField>
        <errorMessage>Date Fiscal Agreement Received is Required to Finalize Fiscal Agreement</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00619.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Y</fullName>
        <label>Yes</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>No</label>
    </customValue>
    <description>R00619</description>
    <masterLabel>R00619</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00676.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PEN</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>SUB</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>APV</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>NRV</fullName>
        <label>Need Revision</label>
    </customValue>
    <description>R00676</description>
    <masterLabel>R00676</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00710.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>0-6 Months</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>06-12 Months</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>12-18 Months</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>18-24 Months</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>24-30 Months</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>30-36 Months</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>36 - School Age</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>School Age</label>
    </customValue>
    <description>R00710</description>
    <masterLabel>R00710</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/R00715.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>NP</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>PT</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>FT</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>FTPT</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>FTFT</label>
    </customValue>
    <description>R00715</description>
    <masterLabel>R00715</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/RT_FAC_TYPE.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CEN</fullName>
        <label>Center</label>
    </customValue>
    <customValue>
        <fullName>HOM</fullName>
        <label>Home</label>
    </customValue>
    <customValue>
        <fullName>EXE</fullName>
        <label>Exempt</label>
    </customValue>
    <masterLabel>RT_FAC_TYPE</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/RateScheduleFlowApxCtrl.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.                                            
*  @date           12/14/2017                                                          
*  @description    APEX CLASS for Rate Schedule Flow                             
*  Modification Log:                                                                             
*                                                                                      
*  * Version: 1.0                                                                             
*  * Date: 14-Dec-2017                                                             
*  * Author: Vineet Srivastava, Gaurav Dharra                                                     
*  * Description: Initial version 
*  
*  * Version: 1.1                                                                            
*  * Date: 06-08-2018                                                             
*  * Author: Gaurav Trivedi
*  * Description: Added error handeling for updateCaseParentFeeRecords as a part of CHATS-5173 bug fix                                                    
*********************************************************************************************/

public with sharing class RateScheduleFlowApxCtrl {
    /**
* @description get Provider, Fiscal Agreement, RAT Fees Information
* @author Vineet Srivasatava
* @date 12/14/2017   
* @param prvdrFiscalAgreementId
* @return LightningServerResponse
*/

    public static final String CR707RsnCode = 'CR0016'; 
	
    @AuraEnabled
    public static LightningServerResponse getInitData(String prvdrFiscalAgreementId, String effectiveBeginDateInput){
    Map<String, Object> objectData = new map<String, Object>();
	Map<String, Object> mapRateDescription = new map<String, Object>();    
        Boolean isSuccessful;
        String message;
        system.debug('EffectiveBeginDate--->'+effectiveBeginDateInput);
        List<T_PROVR_FISCAL_AGREMENT__c> prvdrFiscalAgreements = [SELECT Id, ID_SERVICE__c, CDE_COUNTY__c, CDE_TYPE_FACILITY__c, CDE_COUNTY__r.Name, DTE_BEGIN_AGRMT__c, (SELECT Id, DTE_BEGIN_EFFV__c FROM Rate_Schedules__r ORDER BY CreatedDate DESC NULLS FIRST) FROM T_PROVR_FISCAL_AGREMENT__c WHERE Id =:prvdrFiscalAgreementId];
        //objectData.put('prvdrFiscalAgreement',prvdrFiscalAgreements.isEmpty()?null:prvdrFiscalAgreements.get(0)); 
        List<T_CHATS_PROVR_STATUS__c> provider = [SELECT Id, TXT_CHATS_RATING__c FROM T_CHATS_PROVR_STATUS__c 
                                                  WHERE Id =: prvdrFiscalAgreements.get(0).ID_SERVICE__c];
        objectData.put('CDE_TYPE_FACILITY__c',prvdrFiscalAgreements.get(0).CDE_TYPE_FACILITY__c);
        if(provider.size()>0){
            objectData.put('providerQualityRating',provider.get(0).TXT_CHATS_RATING__c);
        }
        List<String> rateTypeOptions = new List<String>();
        String countyName = '';
        Boolean countyMatched = true;
        Date effectiveBeginDate;
        T_COUNTY_RATE__c countyRate = new T_COUNTY_RATE__c();
        if(!prvdrFiscalAgreements.isEmpty()){
            countyMatched = CHATSUtility.checkCountyWithUserCounty(prvdrFiscalAgreements[0].CDE_COUNTY__c);
            
            System.debug('prvdrFiscalAgreements:'+prvdrFiscalAgreements);
            if(effectiveBeginDateInput!=null && effectiveBeginDateInput!=''){
            List<T_COUNTY_RATE__c> effectiveCountyRatePlan = [SELECT RATE_TYPE__c, PAYMENT_Q9_1__c, PAYMENT_Q10_1__c, PAYMENT_Q11_1__c, PAYMENT_Q17__c 
                                                              FROM T_COUNTY_RATE__c 
                                                              WHERE IDN_COUNTY__c = :prvdrFiscalAgreements.get(0).CDE_COUNTY__c
                                                              AND DTE_BEGIN_EFFV_RATE__c<=:Date.valueOf(effectiveBeginDateInput) 
                                                              AND (DTE_END_EFFV_RATE__c>=:Date.valueOf(effectiveBeginDateInput) OR DTE_END_EFFV_RATE__c=null)
                                                              AND CDE_STATUS__c = 'APV'
                                                              AND IND_RATE_PLAN_TEMPLT__c = false];
            System.debug('effectiveCountyRatePlan:'+effectiveCountyRatePlan);
            if(effectiveCountyRatePlan.size() > 0){
                countyRate = effectiveCountyRatePlan.get(0);
            }
            if(!effectiveCountyRatePlan.isEmpty() && String.isNotEmpty(effectiveCountyRatePlan.get(0).RATE_TYPE__c)){
                //Added as part of HF_CHATS_20_09_2018
                List<String> lstRateTypeOptions=effectiveCountyRatePlan.get(0).RATE_TYPE__c.split(';');
                List<String> lstRestrictedTypeOptions = Label.Inactive_Rate_Type.split(';');
                for(integer i=0;i<lstRateTypeOptions.size();i++){
                    if(!lstRestrictedTypeOptions.contains(lstRateTypeOptions.get(i))){
                      rateTypeOptions.add(lstRateTypeOptions.get(i));  
                    }   
                }
            }
            }    
            if(String.isNotEmpty(prvdrFiscalAgreements.get(0).CDE_COUNTY__c)){
                countyName = prvdrFiscalAgreements.get(0).CDE_COUNTY__r.Name;
            }
            if(prvdrFiscalAgreements.get(0).Rate_Schedules__r.isEmpty()){
                effectiveBeginDate = prvdrFiscalAgreements.get(0).DTE_BEGIN_AGRMT__c;
            }
            if(!prvdrFiscalAgreements.get(0).Rate_Schedules__r.isEmpty()){
                
                /*List<T_FISCAL_RATE__c> lstExistingFiscalRateAmount = [SELECT CDE_AGE_GROUP__c, CDE_CARE_UNIT__c, AMT_FA__c,
                                                                      IDN_FISCAL_SCH__c, AMT_PROVR__c, CDE_RATE_TYPE__c FROM T_FISCAL_RATE__c 
                                                                      WHERE IDN_FISCAL_SCH__c =:prvdrFiscalAgreements.get(0).Rate_Schedules__r.get(0).Id ];*/
                List<batchsit_t_fiscal_rate__x> lstExistingFiscalRateAmount = getLstFiscalRateAmount(prvdrFiscalAgreements.get(0).Rate_Schedules__r.get(0).Id);
                objectData.put('lstExistingFiscalRateAmount', lstExistingFiscalRateAmount);
            }
        }
        List<T_FISCAL_RAT_FEES__c> associatedRATFees = getAssocRATFees(prvdrFiscalAgreementId);
        
        List<T_FISCAL_SCH__c> latestRateSchedule = [Select Id, DTE_BEGIN_EFFV__c, DTE_END_EFFV__c, IDN_AGRMT_FISCAL__c, CDE_RATE_TYPE__c From T_FISCAL_SCH__c Where IDN_AGRMT_FISCAL__r.CDE_COUNTY__c=:prvdrFiscalAgreements.get(0).CDE_COUNTY__c AND IDN_AGRMT_FISCAL__r.ID_SERVICE__c=:prvdrFiscalAgreements.get(0).ID_SERVICE__c ORDER BY DTE_END_EFFV__c  DESC NULLS FIRST LIMIT 1];
        objectData.put('latestRateSchedule', latestRateSchedule);
        
        objectData.put('rateTypeOptions', rateTypeOptions);        
        objectData.put('countyName', countyName);   
        objectData.put('countyMatched', countyMatched); 
        objectData.put('effectiveBeginDate', effectiveBeginDate);    
        objectData.put('effectiveCountyRatePlan', countyRate);
        
        
        if(associatedRATFees.size()>0) {
            objectData.put('ratFeesRec', associatedRATFees.get(0));
        }
        
        List<AgeGroupWrapper> lstTierGroupValuetoLabel = CHATSUtility.getPicklistValuesToLabelList(T_COUNTY_RATE_AMT__c.CDE_AGE_GROUP__c.getDescribe());        
        if(lstTierGroupValuetoLabel!= null)
        {
            objectData.put('lstTierGroupValuetoLabel',JSON.serialize(lstTierGroupValuetoLabel));
        }
        Map<String, String> mapRateTypeValuetoLabel = CHATSUtility.getPicklistValuesToLabelMap(T_COUNTY_RATE_AMT__c.CDE_RATE_TYPE__c.getDescribe());
        if(mapRateTypeValuetoLabel!= null)
        {
            objectData.put('mapRateTypeValuetoLabel',JSON.serialize(mapRateTypeValuetoLabel));
        }
	for(Rate_Type_Description__mdt rateDescription :[Select id, MasterLabel, Rate_Type_Code__c, Description__c from Rate_Type_Description__mdt ]){
            mapRateDescription.put(rateDescription.Rate_Type_Code__c,rateDescription);
        }
        if(mapRateDescription != null){
           objectData.put('mapRateDescription',mapRateDescription); 
        }    
        isSuccessful = true;
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
    @auraEnabled
    public static LightningServerResponse getCeilingAmount(String countyRatePlanId, String providerType, String tierValue){
        system.debug('providerType--->'+providerType);
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful;
        String message;
        List<T_COUNTY_RATE_AMT__c> lstCountyRateAmt = getCountyRateAmountAssocToCountyRatePlan(countyRatePlanId, providerType, tierValue);
        if (lstCountyRateAmt.size()>0){
            isSuccessful = true;
            objectData.put('lstCountyRateAmt' , lstCountyRateAmt);
        }
        else{
            isSuccessful = false;
            message = Label.No_County_Rate_Amount_Data_Found;
        }
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
    
    @auraEnabled
    public static LightningServerResponse getCeilingAmountForExe(String countyRatePlanId, String providerType, String tierValue, List<String> selectedRateLst){
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful;
        String message;
        List<T_COUNTY_RATE_AMT__c> lstCountyRateAmt = getCountyRateAmountAssocToCountyRatePlanForExe(countyRatePlanId, providerType, tierValue, selectedRateLst);
        if (lstCountyRateAmt.size()>0){
            isSuccessful = true;
            objectData.put('lstCountyRateAmt' , lstCountyRateAmt);
        }
        else{
            isSuccessful = false;
            message = Label.No_County_Rate_Amount_Data_Found;
        }
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
    
    /**
* @description get RAT Fees Information associated to a Rate Schedule
* @author Gaurav Dharra
* @date 12/14/2017   
* @param String fiscal Agreement Id
* @return List<T_FISCAL_RAT_FEES__c>
*/   
    @AuraEnabled
    public static List<T_FISCAL_RAT_FEES__c> getAssocRATFees(Id fiscalAgreementId) {
        List<T_FISCAL_RAT_FEES__c> assocRATFeesRec = new List<T_FISCAL_RAT_FEES__c>();
        //Removed unused variable on 5/14/2018 BG  
        List<T_FISCAL_SCH__c> latestRateSchedulerRec = getRateSchedulerAssocToFiscalAggrement(fiscalAgreementId);
        if(latestRateSchedulerRec.size()>0) {
            assocRATFeesRec.addAll(getRATFeesAssocToRateScheduler(latestRateSchedulerRec.get(0).Id));
        }
        return assocRATFeesRec;
    }
    /**
* @description get Rate Scheduler Information associated to a Fiscal Agreement
* @author Gaurav Dharra
* @date 12/14/2017   
* @param String fiscal Agreement Id
* @return List<T_FISCAL_SCH__c>
*/   
    public static List<T_FISCAL_SCH__c> getRateSchedulerAssocToFiscalAggrement(Id fiscalAgreementId) {
        return [SELECT Id from T_FISCAL_SCH__c where IDN_AGRMT_FISCAL__c =: fiscalAgreementId ORDER By DTE_END_EFFV__c DESC];
    }
    /**
* @description get RAT Fees associated to a Rate Scheduler
* @author Gaurav Dharra
* @date 12/14/2017   
* @param String fiscal Agreement Id
* @return List<T_FISCAL_RAT_FEES__c>
*/   
    public static List<T_FISCAL_RAT_FEES__c> getRATFeesAssocToRateScheduler(Id rateScheduleId) {
        // Added 3 TXT MONTH fields by Rishav for CCCAP-2616
        return [SELECT AMT_TRANS_FA__c, CDE_TRANS_FREQ__c, AMT_ACT_FA__c, CDE_ACT_FREQ__c, AMT_REG_FA__c, CDE_REG_FREQ__c, AMT_TRANS_PROVR__c, AMT_ACT_PROVR__c, AMT_REG_PROVR__c,TXT_ACT_MONTH__c,TXT_REG_MONTH__c,TXT_TRANS_MONTH__c
                FROM T_FISCAL_RAT_FEES__c 
                WHERE IDN_FISCAL_SCH__c =: rateScheduleId 
                ORDER By CreatedDate DESC];
    }
    public static List<T_COUNTY_RATE_AMT__c> getCountyRateAmountAssocToCountyRatePlan(Id countyRatePlanId, String facilityType, String tierValue ) {
        system.debug('Rate Plan Id----> '+countyRatePlanId);
        system.debug('facility Type---->'+ facilityType);
        return [SELECT CDE_AGE_GROUP__c, NBR_AMOUNT__c, CDE_UNIT__c, IDN_COUNTY_RATE__c, CDE_RATE_TYPE__c, CDE_TIER__c
                FROM T_COUNTY_RATE_AMT__c 
                WHERE IDN_COUNTY_RATE__c =: countyRatePlanId and CDE_PROVR_TYPE__c=: facilityType and CDE_TIER__c =:facilityType!='EXE'?tierValue : '1'
                ORDER By CreatedDate DESC];
    }
    
    public static List<T_COUNTY_RATE_AMT__c> getCountyRateAmountAssocToCountyRatePlanForExe(Id countyRatePlanId, String facilityType, String tierValue, List<String> selectedRateLst ) {
        List<T_COUNTY_RATE_AMT__c> countyRateAmtList = [SELECT CDE_AGE_GROUP__c, NBR_AMOUNT__c, CDE_UNIT__c, IDN_COUNTY_RATE__c, CDE_RATE_TYPE__c, CDE_TIER__c
                                                        FROM T_COUNTY_RATE_AMT__c 
                                                        WHERE IDN_COUNTY_RATE__c =: countyRatePlanId and CDE_PROVR_TYPE__c=: facilityType and CDE_RATE_TYPE__c IN :selectedRateLst  and CDE_TIER__c =:facilityType!='EXE'?tierValue : '1'
                                                        ORDER By CreatedDate DESC];
        return countyRateAmtList;
    }
    
    @AuraEnabled
    public static LightningServerResponse getInitDataView(String rateScheduleId){
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful;
        String message;
        Map<String, Object> mapRateDescription = new map<String, Object>();
        
        /*List<T_FISCAL_RATE__c> lstExistingFiscalRateAmount = [SELECT Id,CDE_AGE_GROUP__c, CDE_CARE_UNIT__c, AMT_FA__c,
                                                              IDN_FISCAL_SCH__c, AMT_PROVR__c, CDE_RATE_TYPE__c
                                                              FROM T_FISCAL_RATE__c 
                                                              WHERE IDN_FISCAL_SCH__c =:rateScheduleId ];*/
        
        T_FISCAL_SCH__c fiscalSchedule = [SELECT IDN_AGRMT_FISCAL__r.CDE_COUNTY__c,
                                          IDN_AGRMT_FISCAL__r.CDE_COUNTY__r.name,  
                                          DTE_BEGIN_EFFV__c, IDN_AGRMT_FISCAL__c,
                                          IDN_AGRMT_FISCAL__r.ID_SERVICE__c,
                                          CDE_RATE_TYPE__c,
                                          TXT_CHATS_RATING__c
                                          FROM T_FISCAL_SCH__c 
                                          WHERE Id =:rateScheduleId ];
        List<batchsit_t_fiscal_rate__x> lstExistingFiscalRateAmount = getLstFiscalRateAmount(rateScheduleId);                                  
        List<String> selectedRateTypeOptions = new List<String>();
        if(fiscalSchedule.CDE_RATE_TYPE__c!=null){
            selectedRateTypeOptions = fiscalSchedule.CDE_RATE_TYPE__c.split(';');
        }
	for(Rate_Type_Description__mdt rateDescription :[Select id, MasterLabel, Rate_Type_Code__c, Description__c from Rate_Type_Description__mdt ]){
            mapRateDescription.put(rateDescription.Rate_Type_Code__c,rateDescription);
        }
        if(mapRateDescription != null){
           objectData.put('mapRateDescription',mapRateDescription); 
        }    
        if (lstExistingFiscalRateAmount.size()>0){
            objectData.put('lstExistingFiscalRateAmount', lstExistingFiscalRateAmount);
            isSuccessful= true;
           // Id providerId= fiscalSchedule.IDN_AGRMT_FISCAL__r.ID_SERVICE__c;   
            //Id countyId = fiscalSchedule.IDN_AGRMT_FISCAL__r.CDE_COUNTY__c;    
            String countyName = fiscalSchedule.IDN_AGRMT_FISCAL__r.CDE_COUNTY__r.name;
            Date effectiveBeginDate = fiscalSchedule.DTE_BEGIN_EFFV__c;
            
            
            objectData.put('providerQualityRating',fiscalSchedule.TXT_CHATS_RATING__c);
            objectData.put('rateTypeOptions', selectedRateTypeOptions);
            objectData.put('selectedRateTypeOptions', selectedRateTypeOptions);
            objectData.put('countyName', countyName);    
            objectData.put('effectiveBeginDate', effectiveBeginDate);    
            List<AgeGroupWrapper> lstTierGroupValuetoLabel = CHATSUtility.getPicklistValuesToLabelList(T_COUNTY_RATE_AMT__c.CDE_AGE_GROUP__c.getDescribe());        
            if(lstTierGroupValuetoLabel!= null)
            {
                objectData.put('lstTierGroupValuetoLabel',JSON.serialize(lstTierGroupValuetoLabel));
            }
            Map<String, String> mapRateTypeValuetoLabel = CHATSUtility.getPicklistValuesToLabelMap(T_COUNTY_RATE_AMT__c.CDE_RATE_TYPE__c.getDescribe());
            if(mapRateTypeValuetoLabel!= null)
            {
                objectData.put('mapRateTypeValuetoLabel',JSON.serialize(mapRateTypeValuetoLabel));
            }
            
            List<T_FISCAL_RAT_FEES__c> associatedRATFees = getRATFeesAssocToRateScheduler(rateScheduleId);
            
            if(associatedRATFees.size()>0) {
                objectData.put('ratFeesRec', associatedRATFees.get(0));
            }
        }else
        {
            isSuccessful= false;
            message= Label.No_Data_Found;  
        }
        
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
    @AuraEnabled
    public static LightningServerResponse finishRateSchedule(String providerId, T_FISCAL_SCH__c rateSchedule){
        
    	List<T_FISCAL_SCH__c> rateScheduleList = new List<T_FISCAL_SCH__c>();
        rateScheduleList.add(rateSchedule);
        LightningServerResponse lsr = updateCaseParentFeeRecords(providerId);
        RateScheduleServices.insertATSRecord(rateScheduleList);
        return lsr;
    }
    public static LightningServerResponse updateCaseParentFeeRecords(String providerId){
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful;
        String message;
        try{
            WebserviceResponse wsr = HerokuService.updateCaseParentFee(providerId);
            isSuccessful = wsr.isSuccess;
            message = wsr.statusCode+Label.SEPARATOR_COMMA+wsr.message;
        }catch(Exception e) {
            message  = Label.HEROKU_ERROR+e.getMessage();
            isSuccessful = false;
            ExceptionLoggingServices.captureExceptionLog(e, new Map<String,Object>{'Class__c'=>'RateScheduleFlowApxCtrl','Method__c'=>'updateCaseParentFeeRecords'});
        }
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
    public static List<batchsit_t_fiscal_rate__x> getLstFiscalRateAmount(Id rateScheduleId){
        List<Id>lstRateScheduleId = new List<Id>();
        lstRateScheduleId.add(rateScheduleId);
        List<batchsit_t_fiscal_rate__x> lstExistingFiscalRateAmount = new List<batchsit_t_fiscal_rate__x>(); 
        List<FiscalRateWrapper> lstFiscalRateWrapper = HerokuService.fiscalRatefetch(lstRateScheduleId);
        for(FiscalRateWrapper fiscalWrap : lstFiscalRateWrapper){
            batchsit_t_fiscal_rate__x fiscalRate = new batchsit_t_fiscal_rate__x();
            fiscalRate.cde_age_group__c =  fiscalWrap.ageGroup;
            fiscalRate.cde_care_unit__c = fiscalWrap.careUnit;
            fiscalRate.amt_fa__c = fiscalWrap.fiscalRateAmount;
            fiscalRate.idn_fiscal_sch__c = fiscalWrap.idnFiscalSchedule;
            fiscalRate.amt_provr__c = fiscalWrap.providerRateAmount;
            fiscalRate.cde_rate_type__c = fiscalWrap.rateType;
            lstExistingFiscalRateAmount.add(fiscalRate);
        }
        return lstExistingFiscalRateAmount;
    }
    @auraEnabled
    public static LightningServerResponse insertFiscalRateRecords(List<batchsit_t_fiscal_rate__x>lstFiscalRateAmount){
        Map<String, Object> objectData = new map<String, Object>();
        Boolean isSuccessful;
        String message;
        WebserviceResponse wsr = HerokuService.createFiscalRateRecords(lstFiscalRateAmount);
        isSuccessful = wsr.isSuccess;
        if(isSuccessful == true && !(wsr.message == 'Retry')){
            objectData.put('upsertedRecords',wsr.lstSObject);
            message= 'Success';    
        }else{
            if(wsr.message == 'Retry'){
                objectData.put('Retry',true);
                message = 'Retry';
                isSuccessful = true;
            }else{
                message = wsr.message;  
            }  
        }
        return new LightningServerResponse(isSuccessful,message,objectData);
    }
    
    @auraEnabled
    public static LightningServerResponse triggerCorspdCR707(Id rateScheduleId){
    	String message;
        set<Id> rateSchedules = new set<Id>();
        Map<string,string> keyParams = new Map<string, string>();
        integer countyCode;

        try{
        map<Id, T_FISCAL_SCH__c> ratFeesFiscalAgrmntMap = new map<Id, T_FISCAL_SCH__c>([select Id, IDN_AGRMT_FISCAL__c, IDN_AGRMT_FISCAL__r.Name, IDN_AGRMT_FISCAL__r.CDE_COUNTY__r.CDE_COUNTY__c, IDN_AGRMT_FISCAL__r.ID_SERVICE__r.Name FROM T_FISCAL_SCH__c WHERE Id =:rateScheduleId]);
        
        for(Id eachRateSchedule: ratFeesFiscalAgrmntMap.keySet()){
            if(ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__r.CDE_COUNTY__c != NULL){
                decimal cntyCode = ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__r.CDE_COUNTY__r.CDE_COUNTY__c;
                countyCode = integer.valueOf(cntyCode);
            }
            if(ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__c != NULL){
                keyParams.put('faId', ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__c);
            }
            if(ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__r.ID_SERVICE__c != NULL){
                keyParams.put('providerId', ratFeesFiscalAgrmntMap.get(eachRateSchedule).IDN_AGRMT_FISCAL__r.ID_SERVICE__r.Name);
            }
            CorspdTrigger.createCorspdRequest(CR707RsnCode,NULL,NULL,countyCode,keyParams);
        }
        return new LightningServerResponse(true,message,null); 
        }
        catch(Exception e) {
            return new LightningServerResponse(false,message,null);
        }

    }
}