CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/batchsit_t_pos_trans_queue_ats__x.object-meta.xml
<CustomObject>
    <description>batchsit$t_pos_trans_queue_ats</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_pos_trans_queue_ats</externalName>
    <label>batchsit$t_pos_trans_queue_ats</label>
    <pluralLabel>batchsit$t_pos_trans_queue_ats</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/cde_county__c.field-meta.xml
<CustomField>
    <fullName>cde_county__c</fullName>
    <description>cde_county</description>
    <externalDeveloperName>cde_county</externalDeveloperName>
    <label>cde_county</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/cde_status_trans__c.field-meta.xml
<CustomField>
    <fullName>cde_status_trans__c</fullName>
    <description>cde_status_trans</description>
    <externalDeveloperName>cde_status_trans</externalDeveloperName>
    <label>cde_status_trans</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/cde_type_trans__c.field-meta.xml
<CustomField>
    <fullName>cde_type_trans__c</fullName>
    <description>cde_type_trans</description>
    <externalDeveloperName>cde_type_trans</externalDeveloperName>
    <label>cde_type_trans</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/dte_change_last__c.field-meta.xml
<CustomField>
    <fullName>dte_change_last__c</fullName>
    <description>dte_change_last</description>
    <externalDeveloperName>dte_change_last</externalDeveloperName>
    <label>dte_change_last</label>
    <type>Date</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/idn_auth__c.field-meta.xml
<CustomField>
    <fullName>idn_auth__c</fullName>
    <description>idn_auth</description>
    <externalDeveloperName>idn_auth</externalDeveloperName>
    <label>idn_auth</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/idn_provr__c.field-meta.xml
<CustomField>
    <fullName>idn_provr__c</fullName>
    <description>idn_provr</description>
    <externalDeveloperName>idn_provr</externalDeveloperName>
    <label>idn_provr</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/idn_slot_contract__c.field-meta.xml
<CustomField>
    <fullName>idn_slot_contract__c</fullName>
    <externalDeveloperName>idn_slot_contract</externalDeveloperName>
    <label>idn_slot_contract</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/slot_contract_description__c.field-meta.xml
<CustomField>
    <fullName>slot_contract_description__c</fullName>
    <externalDeveloperName>slot_contract_description</externalDeveloperName>
    <label>slot_contract_description</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/T_AUTH__c.object
<CustomObject>
    <description>Authorization</description>
    <!--enableChangeDataCapture>false</enableChangeDataCapture-->
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>County</description>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>T_AUTH</relationshipLabel>
        <relationshipName>T_AUTH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_SLOT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Authorization Slot Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_SLOT_CONTRACT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Slot Contract ID</label>
        <referenceTo>T_SLOT_CONTRACT__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!-- Added as part of HF_CHATS_20_09_2018_1 -->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Begin_Date_Prior_Case_Redeterimnation</fullName>
        <active>false</active>
        <description>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</description>
        <errorConditionFormula>AND(ISNEW(),DTE_BEGIN_EFFV_AUTH__c &gt; Case_Redertimination_Date__c)</errorConditionFormula>
        <errorDisplayField>DTE_BEGIN_EFFV_AUTH__c</errorDisplayField>
        <errorMessage>Authorization Begin Date cannot be greater than the Case Redetermination Due Date on the case</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_CHATS_PROVR_STATUS__c.object
<CustomObject>
    <label>Provider</label>
    <nameField>
        <label>Provider ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_COUNTY__c.object
<CustomObject>
    <description>County</description>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <description>County Code</description>
        <externalId>true</externalId>
        <label>County Code</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>County</label>
  <nameField>
        <displayFormat>{0}</displayFormat>
        <label>County Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SLOT_CONTRACT__c.object
<CustomObject>
    <fields>
        <fullName>CDE_CARE_LEVEL__c</fullName>
        <label>Care Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_CARE_UNIT__c</fullName>
        <label>Care Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_COUNTY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>T_COUNTY__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CDE_PRG_TYPE__c</fullName>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDE_RATE_TYPE__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Rate_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CNT_DAYS_OF_MONTH__c</fullName>
        <label># of days per month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTE_BEGIN_SLOT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Slot Contract Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DTE_END_SLOT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Slot Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDN_AUTH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Authorization ID</label>
        <referenceTo>T_AUTH__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_PROVIDER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider ID</label>
        <referenceTo>T_CHATS_PROVR_STATUS__c</referenceTo>
        <relationshipLabel>Slot Contracts</relationshipLabel>
        <relationshipName>Slot_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_AVAILABLE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available for Use</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLOT_CONTRACT_DESCRIPTION__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Slot Contract Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Slot Contract</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slot Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/Care_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>0-6 Months</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>06-12 Months</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>12-18 Months</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>18-24 Months</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>24-30 Months</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>30-36 Months</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>36 - School Age</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>School Age</label>
    </customValue>
    <masterLabel>Care Level</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/Care_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>PT</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>FT</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>FTPT</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>FTFT</label>
    </customValue>
    <masterLabel>Care Unit</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/Program_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>LI</fullName>
        <label>Low Income Child Care</label>
    </customValue>
    <customValue>
        <fullName>TF</fullName>
        <label>TANF</label>
    </customValue>
    <customValue>
        <fullName>CW</fullName>
        <label>Child Welfare Child Care</label>
    </customValue>
    <masterLabel>Program Type</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/globalValueSets/Rate_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Regular</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Before School</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>After School</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>B and A School</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>Overnight</label>
    </customValue>
    <customValue>
        <fullName>37</fullName>
        <label>Weekend</label>
    </customValue>
    <customValue>
        <fullName>43</fullName>
        <label>Evening</label>
    </customValue>
    <customValue>
        <fullName>55</fullName>
        <label>Disability</label>
    </customValue>
    <customValue>
        <fullName>91</fullName>
        <label>Out-of-County</label>
    </customValue>
    <masterLabel>Rate Type</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/SlotContractUtility.cls
public with sharing class SlotContractUtility {
    public static boolean ALLOW_DELETE=false;
    
    @AuraEnabled
    public static LightningServerResponse getSlotContractHistory(String recordId){
        T_SLOT_CONTRACT__c slotContract = [SELECT SLOT_CONTRACT_DESCRIPTION__c FROM T_SLOT_CONTRACT__c WHERE Id = :recordId];
            
        List<T_SLOT_CONTRACT__c> data = [SELECT Id, Name, IDN_AUTH__c, IDN_AUTH__r.Name, IND_AVAILABLE__c, toLabel(CDE_CARE_LEVEL__c), toLabel(CDE_CARE_UNIT__c),
                                         	SLOT_CONTRACT_DESCRIPTION__c, CNT_DAYS_OF_MONTH__c, toLabel(CDE_PRG_TYPE__c), toLabel(CDE_RATE_TYPE__c), DTE_BEGIN_SLOT__c, DTE_END_SLOT__c
                                          FROM T_SLOT_CONTRACT__c 
                                          WHERE SLOT_CONTRACT_DESCRIPTION__c = :slotContract.SLOT_CONTRACT_DESCRIPTION__c ORDER BY DTE_BEGIN_SLOT__c DESC];
        
        Map<String,Object> objectData = new Map<String,Object>();
        objectData.put('isSuccessful',true);
        objectData.put('data',data);
        return new LightningServerResponse(true,'Success',objectData);
    }
    public static void checkIfDeleteAllowed(List<T_SLOT_CONTRACT__c> slotContractList)
    {
        List<T_SLOT_CONTRACT__c> toDelete=new List<T_SLOT_CONTRACT__c>();
        for(T_SLOT_CONTRACT__c slotRec : slotContractList) {
            if(ALLOW_DELETE==false) {
                slotRec.adderror('You do not have permission to delete this record.');
            }else{
                toDelete.add(slotRec);
            }
        }
        if(toDelete.size()>0)
        {
            insertATSRecord(toDelete);
        }
    }
    public static void insertATSRecord(List<T_SLOT_CONTRACT__c> slotContractList) {
        List<batchsit_t_pos_trans_queue_ats__x> lstATSRecords = new List<batchsit_t_pos_trans_queue_ats__x>();
        Set<Id> providerIdset = new Set<Id>();
        Set<Id> countyIdset = new Set<Id>();
        Set<Id> authIdSet = new Set<Id>();
        Map<Id, String> providerIdtoNameMap = new Map<Id, String>();
        Map<Id, T_COUNTY__c> countyIdtoCountyMap = new Map<Id, T_COUNTY__c>();
        Map<Id, String> authIdtoNameMap = new Map<Id, String>();
        
        for(T_SLOT_CONTRACT__c sc : slotContractList) {
            providerIdset.add(sc.IDN_PROVIDER__c);
            countyIdset.add(sc.CDE_COUNTY__c);
            authIdSet.add(sc.IDN_AUTH__c);
        }
        for(T_CHATS_PROVR_STATUS__c provider : [Select Id, Name from T_CHATS_PROVR_STATUS__c where Id IN :providerIdset]){
            providerIdtoNameMap.put(provider.Id, provider.Name);
        }
        for(T_COUNTY__c county: [Select Id, Name, CDE_COUNTY__c from T_COUNTY__c where Id IN :countyIdset]){
            countyIdtoCountyMap.put(county.Id, county);
        }
        for(T_AUTH__c auth : [Select Id, Name from T_AUTH__c where Id IN :authIdSet]){
            authIdtoNameMap.put(auth.Id, auth.Name);
        }
        batchsit_t_pos_trans_queue_ats__x atsRecord;
        for(T_SLOT_CONTRACT__c sc : slotContractList) {
            atsRecord = new batchsit_t_pos_trans_queue_ats__x();
            atsRecord.CDE_STATUS_TRANS__c = '1';
            atsRecord.CDE_TYPE_TRANS__c = '9';
            if(sc.Name != null) {
                atsRecord.idn_slot_contract__c = sc.Name;  
                atsRecord.slot_contract_description__c = sc.SLOT_CONTRACT_DESCRIPTION__c; 
            }
            if(providerIdtoNameMap.containsKey(sc.IDN_PROVIDER__c)){
                atsRecord.IDN_PROVR__c = providerIdtoNameMap.get(sc.IDN_PROVIDER__c);
            }
            if(countyIdtoCountyMap.containsKey(sc.CDE_COUNTY__c)){
                atsRecord.CDE_COUNTY__c = String.valueOf(countyIdtoCountyMap.get(sc.CDE_COUNTY__c).CDE_COUNTY__c); 
            }
            if(sc.IDN_AUTH__c != null && authIdtoNameMap.containsKey(sc.IDN_AUTH__c)){
                atsRecord.IDN_AUTH__c = authIdtoNameMap.get(sc.IDN_AUTH__c);
            }
            atsRecord.DTE_CHANGE_LAST__c = system.today();
            lstATSRecords.add(atsRecord);            
        }
        if(!lstATSRecords.isEmpty()){
            ATSHandler.insertATSRecord(true, lstATSRecords);
        }
    }
    
    //method to update authorization begin date if slot is deleted
    public static void updateAuthSlotBegin(List<T_SLOT_CONTRACT__c> slotContractList){
        Map<id,id> authKeyVsSlot=new Map<id,id>();        
        for(T_SLOT_CONTRACT__c sc : slotContractList){            
            if(string.isNotBlank(sc.IDN_AUTH__c)){
                authKeyVsSlot.put(sc.IDN_AUTH__c, sc.id);
            }
        }
        
        List<T_AUTH__c> authListToUpdate = new List<T_AUTH__c>([SELECT id, IDN_SLOT_CONTRACT__c, DTE_BEGIN_SLOT__c 
                                                                FROM T_AUTH__c WHERE id in :authKeyVsSlot.keySet()]);
        
        if(authListToUpdate!=null && !authListToUpdate.isEmpty()){
            for(T_AUTH__c indAuth : authListToUpdate){ 
                if(indAuth.IDN_SLOT_CONTRACT__c == authKeyVsSlot.get(indAuth.id)){
                    indAuth.DTE_BEGIN_SLOT__c = null;
 
                }
            }
            GenericDMLHandler.updateRecords(authListToUpdate,new Map<String,Object>{'Method__c'=>'updateAuthSlotBegin','Class__c'=>'SlotContractUtility'});
        }
    }

}