CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/batchsit_t_pos_trans_queue_ats__x.object-meta.xml
<CustomObject>
    <description>batchsit$t_pos_trans_queue_ats</description>
    <externalDataSource>Heroku_Connect_datasource</externalDataSource>
    <externalName>batchsit$t_pos_trans_queue_ats</externalName>
    <label>batchsit$t_pos_trans_queue_ats</label>
    <pluralLabel>batchsit$t_pos_trans_queue_ats</pluralLabel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/cde_status_trans__c.field-meta.xml
<CustomField>
    <fullName>cde_status_trans__c</fullName>
    <description>cde_status_trans</description>
    <externalDeveloperName>cde_status_trans</externalDeveloperName>
    <label>cde_status_trans</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/cde_type_trans__c.field-meta.xml
<CustomField>
    <fullName>cde_type_trans__c</fullName>
    <description>cde_type_trans</description>
    <externalDeveloperName>cde_type_trans</externalDeveloperName>
    <label>cde_type_trans</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/dte_change_last__c.field-meta.xml
<CustomField>
    <fullName>dte_change_last__c</fullName>
    <description>dte_change_last</description>
    <externalDeveloperName>dte_change_last</externalDeveloperName>
    <label>dte_change_last</label>
    <type>Date</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/idn_case__c.field-meta.xml
<CustomField>
    <fullName>idn_case__c</fullName>
    <description>idn_case</description>
    <externalDeveloperName>idn_case</externalDeveloperName>
    <label>idn_case</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/batchsit_t_pos_trans_queue_ats__x/fields/idn_client__c.field-meta.xml
<CustomField>
    <fullName>idn_client__c</fullName>
    <description>idn_client</description>
    <externalDeveloperName>idn_client</externalDeveloperName>
    <label>idn_client</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE__c.object
<CustomObject>
    <description>Chats cases</description>
    <fields>
        <fullName>Is_CBMS_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is CBMS Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Peak_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Peak Data</label>
        <type>Checkbox</type>
    </fields>
    <label>Case</label>
    <nameField>
        <label>Case ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Cannot_upd_Redet_Pckge_Rcvd_Date</fullName>
        <active>false</active>
        <description>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</description>
        <errorConditionFormula>AND( NOT( ISNEW() ) ,
    ISCHANGED( DTE_RCVD_PACKET_REDET__c ),
    CLOSED_CASES_STATUS__c &gt; 0
)</errorConditionFormula>
        <errorMessage>Cannot Update Redetermination Package Receive Date if the Case Status is Closed</errorMessage>
    </validationRules-->
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>county_affltd_to_usrProfile_ownercounty</fullName>
        <active>false</active>
        <description>CHAT-1150: User cannot enter a County that&apos;s not affiliated with the User&apos;s profile</description>
        <errorConditionFormula>VALUE(TEXT( Owner:User.Owner_County__c )) &lt;&gt;  CDE_COUNTY__r.CDE_COUNTY__c</errorConditionFormula>
        <errorDisplayField>CDE_COUNTY__c</errorDisplayField>
        <errorMessage>Cannot enter a County that&apos;s not affiliated with the User&apos;s profile</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INDIV__c.object
<CustomObject>
   <!---->
    <description>Associator of cases and clients</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>CaseIndividuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDN_CLIENT__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client ID</description>
        <label>Client ID</label>
        <referenceTo>T_SBSD_INDIV__c</referenceTo>
        <relationshipLabel>Case Individual</relationshipLabel>
        <relationshipName>Case_Individual</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IND_CRTKR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is the Primary Parent/Caretaker</description>
        <label>Primary Parent/Caretaker</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Individual</label>
     <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Individual ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_CASE_INFO__c.object
<CustomObject>
    <description>Method of contact like email</description>
     <!--<enableChangeDataCapture>false</enableChangeDataCapture>-->
    <fields>
        <fullName>CDE_TYPE_INFO_CASE__c</fullName>
        <description>Case Information Type</description>
        <label>Case Information Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R00833</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IDN_CASE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Case ID</description>
        <label>Case ID</label>
        <referenceTo>T_SBSD_CASE__c</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>T_SBSD_CASE13</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TXT_VALUE_INFO_CASE__c</fullName>
        <description>Case Information</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Case Information</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Case Information</label>
  	<nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Information ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CHATS_SIT/force-app/main/default/objects/T_SBSD_INDIV__c.object
<CustomObject>
    
    <description>Additional demographic information about an individual on a case including name, date of birth, maritial status, race</description>
    <fields>
        <fullName>Is_CBMS_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is CBMS Data</label>
        <type>Checkbox</type>
    </fields>
    

    <fields>
        <fullName>Is_Peak_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Peak Data</label>
        <type>Checkbox</type>
    </fields>
    <label>Individual</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <!--Commented as part of CCCAP-10798-->
    <!--validationRules>
        <fullName>Require_How_Verified_if_SSN_populated</fullName>
        <active>false</active>
        <description>How verified(Identity) is required if SSN is populated</description>
        <errorConditionFormula>NOT(Is_Peak_Data__c) &amp;&amp; NOT(Is_CBMS_Data__c) &amp;&amp;
NOT(ISBLANK(NBR_SSN__c)) &amp;&amp; ISBLANK(TEXT(CDE_SOURCE_VRFYD_IDNTY__c))</errorConditionFormula>
        <errorDisplayField>CDE_SOURCE_VRFYD_IDNTY__c</errorDisplayField>
        <errorMessage>How verified(Identity) is required if SSN is populated</errorMessage>
    </validationRules-->
</CustomObject>

CHATS_SIT/force-app/main/default/globalValueSets/R00833.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EM</fullName>
        <label>Email</label>
    </customValue>
    <customValue>
        <fullName>PMC</fullName>
        <label>Primary Method of Contact</label>
    </customValue>
    <description>R00833</description>
    <masterLabel>R00833</masterLabel>
</GlobalValueSet>

CHATS_SIT/force-app/main/default/classes/CaseInformationServices.cls
/*********************************************************************************************
*  @author         Deloitte Consulting LLP.
*  @date           05/28/2018
*  @description    Handler class for Case Information
*  Modification Log:
*
*  * Version: 1.0
*  * Date: 28-May-2018
*  * Author: Bharadwaj Gaddam
*  * Description: Initial version 
*********************************************************************************************/
/**
* @description Restricting user from creating not more than one Email Type
* @author Bharadwaj Gaddam 
* @date 05/28/2018  
* @param List<T_SBSD_CASE_INFO__c> trigger.new Case Information list
* @return void
*/
public with sharing class CaseInformationServices {

    public static final string EMAIL=Label.EM;

    public static void allowOnlyOneEmailType(List<T_SBSD_CASE_INFO__c> caseInfoNewList) {
        Set<Id> caseIdSet = new Set<Id>();
        for(T_SBSD_CASE_INFO__c caseInfoEach: caseInfoNewList) {
            if(caseInfoEach.CDE_TYPE_INFO_CASE__c==EMAIL && caseInfoEach.IDN_CASE__c!=null) {
                caseIdSet.add(caseInfoEach.IDN_CASE__c);
            }
        }
        Map<Id,T_SBSD_CASE__c> caseMap = new  Map<Id,T_SBSD_CASE__c>([Select Id,Is_Peak_Data__c,Is_CBMS_Data__c, (select Id,CDE_TYPE_INFO_CASE__c from T_SBSD_CASE13__r where CDE_TYPE_INFO_CASE__c=:EMAIL and Id NOT IN:caseInfoNewList Limit 1) from T_SBSD_CASE__c where Id IN:caseIdSet]);
        for(T_SBSD_CASE_INFO__c caseInfoEach: caseInfoNewList) {
            if(caseInfoEach.CDE_TYPE_INFO_CASE__c==EMAIL && caseInfoEach.IDN_CASE__c!=null) {
                if(caseMap.get(caseInfoEach.IDN_CASE__c)!=null) {
                    if(caseMap.get(caseInfoEach.IDN_CASE__c).T_SBSD_CASE13__r.size()>0 && caseMap.get(caseInfoEach.IDN_CASE__c).Is_Peak_Data__c && caseMap.get(caseInfoEach.IDN_CASE__c).Is_CBMS_Data__c) {
                        caseInfoEach.addError(Label.Please_update_the_existing_Email_record_for_that_case);                        
                    }
                }
            }
        }
    }
    
    public static void insertCaseIndivToATSOnEmailUpdate(list<T_SBSD_CASE_INFO__c> newCaseInfoList, Map<Id, T_SBSD_CASE_INFO__c> oldCaseInfoMap) {
        Set<Id> caseIdSet = new Set<Id>();
        Map<Id, T_SBSD_CASE_INDIV__c> casePrimaryTakerMap = new Map<Id, T_SBSD_CASE_INDIV__c>();
        List<batchsit_t_pos_trans_queue_ats__x> lstATSRecords = new List<batchsit_t_pos_trans_queue_ats__x>();
        for(T_SBSD_CASE_INFO__c eachCaseinfo : newCaseInfoList) {
            if(eachCaseinfo.IDN_CASE__c != null){
                caseIdSet.add(eachCaseinfo.IDN_CASE__c);
            }
        }
        if(!caseIdSet.isEmpty()){
            for(T_SBSD_CASE_INDIV__c eachCaseIndiv : [SELECT IDN_CASE__c, IDN_CASE__r.Name, Name, IDN_CLIENT__r.Name FROM T_SBSD_CASE_INDIV__c WHERE IDN_CASE__c IN: caseIdSet AND IND_CRTKR__c = true]){
                casePrimaryTakerMap.put(eachCaseIndiv.IDN_CASE__c, eachCaseIndiv);
            }
        }
        for(T_SBSD_CASE_INFO__c eachCaseInfo1 : newCaseInfoList){
            if(trigger.isUpdate){
                system.debug('in Update');
                if(eachCaseInfo1.CDE_TYPE_INFO_CASE__c == 'EM' && eachCaseInfo1.TXT_VALUE_INFO_CASE__c != oldCaseInfoMap.get(eachCaseInfo1.Id).TXT_VALUE_INFO_CASE__c  && casePrimaryTakerMap.get(eachCaseInfo1.IDN_CASE__c) != null){
                    batchsit_t_pos_trans_queue_ats__x atsRecord1 = new batchsit_t_pos_trans_queue_ats__x();
                    atsRecord1.CDE_STATUS_TRANS__c= '1';
                    atsRecord1.CDE_TYPE_TRANS__c ='3';
                    atsRecord1.IDN_CASE__c = casePrimaryTakerMap.get(eachCaseInfo1.IDN_CASE__c).IDN_CASE__r.Name;
                    atsRecord1.IDN_CLIENT__c = casePrimaryTakerMap.get(eachCaseInfo1.IDN_CASE__c).IDN_CLIENT__r.Name;
                    atsRecord1.DTE_CHANGE_LAST__c = System.today();
                    lstATSRecords.add(atsRecord1);
                }
            } else if(trigger.isInsert){
                system.debug('In insert');
                if(eachCaseInfo1.CDE_TYPE_INFO_CASE__c == 'EM' && casePrimaryTakerMap.get(eachCaseInfo1.IDN_CASE__c) != null){
                    batchsit_t_pos_trans_queue_ats__x atsRecord2 = new batchsit_t_pos_trans_queue_ats__x();
                    atsRecord2.CDE_STATUS_TRANS__c= '1';
                    atsRecord2.CDE_TYPE_TRANS__c ='3';
                    atsRecord2.IDN_CASE__c = casePrimaryTakerMap.get(eachCaseInfo1.IDN_CASE__c).IDN_CASE__r.Name;
                    atsRecord2.IDN_CLIENT__c = casePrimaryTakerMap.get(eachCaseInfo1.IDN_CASE__c).IDN_CLIENT__r.Name;
                    atsRecord2.DTE_CHANGE_LAST__c = System.today();
                    lstATSRecords.add(atsRecord2);
                }
            }
        }
        ATSHandler.insertATSRecord(true, lstATSRecords);
    }
}